### ISSUE TITLE
Disable exit sequence override when ALiVE isn't active in mission

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#10]
The delayed exit sequence is a common grievance which discourages a lot of people using ALiVE especially when mission editing in MP. Can it only be enabled if ALiVE (Required) is in the mission?

**Comment by tupolov** [comment]
Can we clarify what players expect here? There are a few ways to exit from MP game:

1. Abort button
2. Player Exit

Assuming the expectation is that if you hit Abort, you should not be shown an exit screen.

Will see if we can remove it completely, but pretty sure for everything outside of Abort, we need a "complete" exit.

**Comment by friznit** [comment]
Correct assumption.

1.  ALiVE Player Exit  - a custom button with which we can run our own script to force a complete exit and do db magic.

2.  Abort button - revert to default, so there is no ALiVE exit sequence.  Changing this will also resolve ACE having to workaround because they want to disable Abort in some instances to prevent players "combat logging" (though obviously users with ALiVE installed will still see "ALiVE Player Exit" though....)
