### ISSUE TITLE
ORBAT created vehicles do not patrol

### ISSUE THREAD

**Issue by EasyEB** [ALiVEOS/ALiVE.OS#100]
Hello!

When using ORBAT creted factions the vehicles won't patrol. There are dudes in ot and they act when fired upon, but when spawned by Alive as part of a task (destroy vehicles) they sit immobile.

The only difference I can tell from a "regular" (non ORBAT) faction vehicle is that in a BMP for example the gunner is the group leader when created with ORBAT.

**Comment by HeroesandvillainsOS** [comment]
Are they patrolling under normal conditions for you? It seems you're talking about the C2ISTAR destroy vehicles task. I'm personally seeing them patrol just fine when spawned by the mil/civ/cust obj modules.

**Comment by EasyEB** [comment]
Yes sir, that is correct. Sorry I didn't specify. 

They patrol just fine under normal placement conditions, it's only during the destroy vehicles tasks that they are parked.

**Comment by SpyderBlack723** [comment]
Is it possible that this is more likely a bug with the task itself and not the units? Units created via ORBAT Creator should be no different than those that weren't.

**Comment by EasyEB** [comment]
Update: I've now seen them patrol both when they are part of a task (destroy vehicles), and when they are just going about their business.

However, when they are part of a task they are more prone to stay put.

I feel this issue can go to the bottom of the pile, it's not severe.

**Comment by SpyderBlack723** [comment]
Probably an issue with the task itself then.
