### ISSUE TITLE
Request: An option to spawn less groups than Platoon 30

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#102]
I'm finding it difficult to balance smaller scale insurgency missions with the default drop down unit numbers. The best part about ALiVE to me, especially as a mission maker, is how well ALiVE "randomly" places units, especially when filtering is left low or completely off. You never know what's around the corner, even when you make the mission yourself.

However, on 5x5 - 10x10 maps, I still feel like the default options spawn too many units. Some ways I try to work around this is filtering out objectives (this is not ideal because that can eliminate lots of smaller towns from having objectives at all so the mission maker would always know for sure that certain towns are "safe"), and then manually placing the units and some custom objectives to flesh things out, but doing that sort of eliminates that element of surprise for the mission maker IMO. You'll always remember where you placed everything and that can take the fun out of things.

What I'd love to see is an option to spawn about half of what's currently available. A Platoon 15, if you will. I think this would help insurgency missions stay fresh and smaller scale, so there isn't guaranteed to be a fight around every corner but most importantly, there COULD BE because even the mission maker would never be certain.

**Comment by marceldev89** [comment]
Isn't that exactly what the `Override X` options are for in the placement modules?

**Comment by SpyderBlack723** [comment]
Overrides (^) or manual placement are your best option.

**Comment by HeroesandvillainsOS** [comment]
Yes but it doesn't function the way I'd hope.

Its been a while since I tested this, but here's an example. Put 30 infantry and 0 in everything else in the overrides of a civ/mil obj module, press play and watch the amount of spawns. Then, go back into the module and put it to Platoon 30 instead, while putting 0 in everything other than infantry and notice how doing it the first way spawns way way more units.

**Comment by HeroesandvillainsOS** [comment]
But Spyder, overrides and manual placement are defeat the purpose of my request. I'd always know what areas got filtered out from having objectives and where the manually placed units would spawn. The best part about ALiVE is the element of surprise but you lose that when you micro-manage where all the units are. It kills the first hour or so of a mission because you'd know which towns are empty and which have resistance.

**Comment by marceldev89** [comment]
@HeroesandvillainsOS that's just random chance that the weighted option spawns more than the overrides. Review the last bit of this post: http://alivemod.com/forum/conversation/post/12524. :smile:

**Comment by HeroesandvillainsOS** [comment]
Thanks. I see the post but am having a tough time interpreting the relevant part of the scale. If we divide the way you have it there in the 800 and 400 examples, assuming it's equal the lower you go, my math says a Platoon 30 would spawn 0-3 infantry and 0-1 of everything else. So at most that would be 8 groups if we add 1 for every non-infantry category so that definitely can't be right, can it?

The last time I tested the overrides, I went in and manually entered 10 infantry groups and 2 motorized groups into the fields (with 0 in everything else) and still had more total groups spawn than the default Platoon 30 option. I didn't spend too much time with it because it was counter-productive to my overall goal but assuming it still can have similar results, I still feel like it defeates the purpose of overriding in general if it's intentionally designed to be even more random.

That is unless I'm misunderstand which I admit is very likely.

**Comment by marceldev89** [comment]
The occupying units of objectives at start are not taking in to account with both the weighted and overridden counts. You'll have to keep that in mind when counting the spawned groups.

So if you start with 20 objectives it will (at least) spawn 20 groups to occupy those objectives and then spawn the counts set in the placement modules.

**Comment by coachwn** [comment]
So if I set in a mission to spawn a Battalion for example is it going to be per TAOR and covering those objectives within the TAOR or is that going to be spread out over the entire map with small groups covering objectives within the TAOR? The reason I am asking is we are currently running an ALiVE mission and we are getting stupid numbers of spawns by the AI OPCOM. The mission builder has 2 TAOR's set on Sahrani and its getting ridiculous trying to fight our way off the southern island area.

Just curious.

**Comment by HeroesandvillainsOS** [comment]
Okay. That's good info. But let's put that into an example. I'd like to clarify my request in this thread and I think seeing it put plainly would would help. Staying with your 20 objectives model, using infantry only, whats the approximate number of total groups with:

Platoon 30 set to infantry only = ? # of groups

15 infantry override = ? # of groups

Based on what you're saying the answer would be 50(ish) and 35(ish) but that's not at all what I'm seeing. Not on the 15 override portion, at least.

**Comment by SpyderBlack723** [comment]
Placement modules spread their placed units over their entire set of objectives. It is not done 1 Battalion per TAOR, unless you have two placement modules, each set to one Battalion and each covering a separate TAOR.

**Comment by coachwn** [comment]
Ok that is what I thought but was curious if this was something different.

**Comment by marceldev89** [comment]
@HeroesandvillainsOS the actual math for the weighted infantry only option is `floor((_size / 10) * 0.8))` => `30 / 10 = 3 * 0.8 = 2.4 floored = 2 groups` so you'd end up with:
```
Platoon 30 infantry only  = 20 +  2 = 22 groups
Override 15 infantry only = 20 + 15 = 35 groups
```

**Comment by HeroesandvillainsOS** [comment]
Yeah that's very consistent with what I'm seeing. I think that makes my Platoon 15 request a good one. :)

Thanks for the breakdown marceldev89.

**Comment by HeroesandvillainsOS** [comment]
Or wait, I think in that example platoon 15 would essentially not change the total numbers of groups at all...

**Comment by HeroesandvillainsOS** [comment]
Ok. So this all brings us back to the beginning where Spyder said limiting the objectives was the best way to do it. The numbers don't lie and I don't doubt your knowledge on this so he is definitely right. 

I didn't realize group numbers were tied so hard to the objectives. Honestly thanks sucks. Back to manually placing units I guess.

We can probably close this since essentially my request would require a re-write to the ALiVE spawning system and I definitely don't want or expect that.

Thanks for the help guys.

**Comment by SpyderBlack723** [comment]
Just set a possibility modifier on each manually placed group.

**Comment by friznit** [comment]
Define a number of small TAORs.  Have one Mil Placement place units in only one of them and a second Mil Placement set to objectives only covering the rest.  You'll get fewer groups spawned at start to cover the objectives and can limit it further with the manual override.  AI Commander in insurgency works spawns fewer to begin with anyway, as it relies on recruiting civilians from objectives.

**Comment by HeroesandvillainsOS** [comment]
Sorry I'm not sure what that means. Is there a setting I'm missing when double clicking on a group icon?

**Comment by friznit** [comment]
Every object or unit in ArmA can have a probability of presence.  Set it to 33% and they'll only appear 1 in 3 times you run the mission.

**Comment by HeroesandvillainsOS** [comment]
^^^ That question was to Spyder. Friznit popping in like a Ninja. 

@Friznit, that's a good idea. I've tried doing that before and didn't really see the units migrating out of the main TAOR too much (so the objectives only TAOR pretty empty for a decent amount of time), but I have some ideas now that I understand the way it works a bit better so all in all I feel like this topic was worth it.

Thanks guys. I'll bump the initial platoon/company size thread with some follow-up questions as they come to me. I appreciate the help everyone.
