### ISSUE TITLE
ORBAT Creator Feature Requests

### ISSUE THREAD

**Issue by DavisBrown723** [ALiVEOS/ALiVE.OS#103]
Any and all feature requests related to the ORBAT Creator

_**Please post bug reports as separate issues**_

-----------------------

**Must-Do**   _Features that the ORBAT Creator would feel incomplete without_
 - Investigate erroneous export under certain circumstances (Missing base classes) - Very rare/circumstantial? <--- Fixed under certain circumstances
-----------------------

**To Do**   _General tasks needing completion_
- Sorting custom unit list in unit editor by editor category type needs completing.

-----------------------

**Wishlist**   _Features that would be nice to have, but not vital to the experience_
- When editing vehicle crew, actual unit objects are added to the vehicle for previewing
- Interface for defining markers (tied to faction, needs own export option)
- Interface for defining faction-specific static data elements
    Logistics vehicles,  Ambient ammo boxes, Ambient Vehicles, Player Log options, Compositions

- Define a set of a certain gear type that will be randomly selected from and equipped during runtime
- Additional export options
  - Required Addons <---- partially done
  - Optional wrapping of groups/units inside CfgGroups/CfgVehicles
- Implement OutputManager class
- Bring vehicle edit screen up-to-par with the virtual garage
- Vehicle inventory management
-----------------------
**Utilities**
- Tool to simplify the mod packaging process
-----------------------
Items will be removed as they are added internally.

**Comment by HeroesandvillainsOS** [comment]
How about automated Zeus compatibility or is that already in?

**Comment by SpyderBlack723** [comment]
That would fall under additional export options

**Comment by friznit** [comment]
ALiVE Support Units Configurable Kickass System (SUCKS) that generates a Logistics static data override so that I can define which vehicles in my custom faction are used for convoys and air transport.

**Comment by EasyEB** [comment]
ALiVE Customizable Unit Nationality Trait System (CUNTS) that allows selection of unit ethnicity, language and naming convention (Altian/Greek, Western, Middle Eastern and so on).

**Comment by friznit** [comment]
Configurable ACE Kit Enhancements (CAKE) that allow you to include ACE config settings on units (Engineer, Medic, FRIES etc) and vehicles (medical, repair) if using ACE (obviously).

**Comment by HeroesandvillainsOS** [comment]
^^^ So glad I was bored and hopped on the Github today. This was worth it. :)

**Comment by VCB-Spartan** [comment]
Hey Spyder. Love the Orbatron. Makes it a lot easier to put together classes and ensuring the correct classnames are used.
I would like to add some randomness in the units (uniform, headgear, vehicle textures, etc...). Obviously at the moment not even the Arsenal had that feature but I was wondering if you could do one of your magic tricks and enhance the Orbatron to create multiple units of the same (it can already do that) and offer to merge them into a single randomiisable unit?

**Comment by SpyderBlack723** [comment]
Hey @VCB-Spartan, thanks for the significant testing you and the VCB'ers have done and continue to do. Randomized gear is a feature that I would love to add. The main issue was adding an interface for it (not possible within arsenal as you stated) while maintaining a self-explanatory UI, your idea with the unit merging is excellent and something I'll definitely give some thought.

Thanks again!

**Comment by VCB-Spartan** [comment]
Good job adding the RHS turrets to the Orbatron. That was a really quick turn around if I may say so...! 👍

**Comment by SpyderBlack723** [comment]
Unfortunately not so quick as the forward declaration of the base class needs to be changed in order to allow sub-class inheritance.

**Comment by 1ncontinentia** [comment]
Well that goes without saying

**Comment by VCB-Spartan** [comment]
Guess that explains why some RHS vehicles still show RHS men on some turrets. Can't work out how to fix that atm...

**Comment by VCB-Spartan** [comment]
Hi SpyderBlack723,
I have created 4 new factions and they appear fine in 3Den.
However in Zeus, despite populating the units []={...} field for all
factions, only one of the appears on Zeus and can be interacted with.
Is it because the CfgPatches.hpp always uses     class testMod_test and
therefore multiple Orbatron created faction cannot all be seen by Zeus?

**Comment by SpyderBlack723** [comment]
@VCB-Spartan Yes, you need to change `testMod_test` to something that reflects the component for the mod.

For example, if you mod is named MyMod and you make a faction with the classname BLU_RND
you could change it to `myMod_BLU_RND`

And if you haven't already, change the addons\test folder to addons\mod_factionclassname or something that is unique to each mod.

**Comment by VCB-Spartan** [comment]
Excellent. Will the new version create this automatically in the future so
manual input is not necessary?

**Comment by SpyderBlack723** [comment]
I'd love to automate or provide the option of automation for as many things as possible, problem mainly just lies with having time to work on the project. For now the CfgPatches generation should significantly help many people who've never done this process before, leaving the folder renaming to be the most complicated task outside of the game hopefully.

**Comment by mast3rbates** [comment]
any plans for an option to have vehicle based groups' units spawn inside the vehicle?

**Comment by SpyderBlack723** [comment]
That's a feature request for BIS

**Comment by SpyderBlack723** [comment]
> also an ammobox option that compiled all of their ammo types into it would be cool.
Could you elaborate on what you mean by this?

**Comment by mast3rbates** [comment]
the ability to create a generic ammobox that automatically compiled all the ammo types from the units in a faction and added them to it. maybe have drop downs for the amounts.

**Comment by marceldev89** [comment]
An option to import incompatible groups would be neat. RHS is a good test case for that. ^^

**Comment by SpyderBlack723** [comment]
@marceldev89 Done

https://gyazo.com/803438a7c4f7324c26e1fcbeac311cb9
https://gyazo.com/8641d698c3216df67992cf560d53d147

**Comment by mast3rbates** [comment]
an import config function so you dont have to pack it and add it as an addon to continue editing an incomplete faction.

**Comment by coachwn** [comment]
I wish there was that option for drop downs or text entry to add amounts in the editor for sure...if this was available in the Orbat creator I would love it.

**Comment by SpyderBlack723** [comment]
Drop downs or text entry for what?

**Comment by coachwn** [comment]
To add amounts of weapons, ammo, medical,  etc...

**Comment by SpyderBlack723** [comment]
Not possible via config

**Comment by AUTigerGrad** [comment]
I would like the ability to DISABLE randomized sunglasses, etc. on units which do have randomization built into it.   I'm not a fan of seeing a bunch of troops wearing hot pink beach sunglasses, etc.

**Comment by SpyderBlack723** [comment]
> an import config function so you dont have to pack it and add it as an addon to continue editing an incomplete faction.
Would be fairly suicidal to attempt in SQF, an alternative export option that can be re-imported is more feasible.

**Comment by coachwn** [comment]
Spyder...I wanted to say that after using the newest version last night I would like to see an option to clean up the transition from unit editor to group editor and back be a little easier to transition back and forth.

**Comment by SpyderBlack723** [comment]
Probably not going to happen unless BIS change the way ctrlmenustrips work. The previous method of individual buttons would never hold up with future additions.

**Comment by coachwn** [comment]
Yeah I did the same thing yesterday/last night and it was just the repetition that was giving me the idea.

**Comment by SpyderBlack723** [comment]
> ALiVE Customizable Unit Nationality Trait System (CUNTS) that allows selection of unit ethnicity, language and naming convention (Altian/Greek, Western, Middle Eastern and so on).

Done.

**Comment by VCB-Spartan** [comment]
A feature that allows you to add custom markers/flags to represent your faction on the map

**Comment by SpyderBlack723** [comment]
> A feature that allows you to add custom markers/flags to represent your faction on the map

Is there documentation on how to do that? Is this something possible via config?

**Comment by VCB-Spartan** [comment]
Hi SpyderBlack723,
This is the BIS documentation on how to create a custom flag. Admittedly, I have not had much time to get it to work:
https://community.bistudio.com/wiki/cfgMarkers
Apparently the cfgmarkers part goes in the config.cpp:

https://forums.bistudio.com/topic/171328-custom-map-marker-config/

**Comment by SpyderBlack723** [comment]
I've actually created custom markers before so shouldn't be a problem.

Will add it to the list!

**Comment by VCB-Spartan** [comment]
Do you eve sleep?!? 😉
Guessing you could only provide the framework for custom markers and people would need to manually enter the paa path in Notepad ++

**Comment by VCB-Spartan** [comment]
Thank you again for this great tool SpyderBlack723.
Your genius and efforts have brought a new lease of life in Arma for me.
Keep up the good work!

**Comment by SpyderBlack723** [comment]
Will most likely include a screen where you can name the marker and then enter the path to your image (or select from predefined flags like when creating a faction).

Will need to update the mod template to allow for easy adding / removing of markers as well.

**Comment by coachwn** [comment]
You sorta touched on this earlier in the thread but the ability to edit the vehicle crews the same way as the unit (soldiers) would be good.

**Comment by friznit** [comment]
You already can.  Vehicle crews are simply assigned from one of your existing edited units.

**Comment by coachwn** [comment]
Ok maybe I am not doing it correctly. With every faction and unit I have exported I have to manually assign troops from the edited faction as the crew of the vehicle after I edit and export. When I am editing the faction I do not get an option to edit assigned troops. So of someone can explain how and where to see it I would appreciate it.

**Comment by friznit** [comment]
Create a unit class called crew, then select a vehicle and edit the vehicle loadout.  In the arsenal view, select the top icon for crew, then pick your crew class.

**Comment by VCB-Spartan** [comment]
As Friznit said...
RHS vehicles are a bit different and require a bit more coding work as only some of the crew is assigned with the new crew (the commander and gunner positions are usually the same as the original crew)

**Comment by coachwn** [comment]
Does it have to be just crew or can it be specific? Such as "Armor Crew" or "Heli Crew"; that is how I see them and determine at a glance in the ORBAT creator without actually clicking on each unit to see how they appear when I am determining what the units look like.

**Comment by EasyEB** [comment]
You can name the unit class Timmy-Bob as far as the Orb is concerned.

**Comment by VCB-Spartan** [comment]
Hi SpyderBlack,

Still loving the Orbatron. Think Friz is getting a bit worried about me creating too many factions with custom textures and bumping up our repo by a noticeable amount!

Is there any chance we could have the option to load Arsenal saved vehicle loadouts when in the Orbatron? I usually create my units in the Arsenal before going to the Orbatron and really think the same with vehicles would be really cool.

Also, I seem to remember you used to include a vehicle texture file path in the past. I like to change textures with the faction emblem and use obj setObjectTextureGlobal [selection, texture].
At the moment, it is a bit hit and miss finding with selection number to use short of delving into an existing faction (RHS, LOP...) config file.

Any thoughts?

Cheers!

**Comment by SpyderBlack723** [comment]
Never had a field for vehicle texture path. Just the current way it works with selecting it from the menu. To be honest I spent more time working on that than I would like to admit and it's still black magic to me. Any improvements to the texture system is probably far off since I have zero clue what I'm doing and there doesn't really seem to be any documentation on it.

Are vehicle loadouts in the arsenal used to change the weapons/ammunition the vehicles uses, miscellaneous components (like littlebird side benches, or the inventory of a vehicle?

**Comment by VCB-Spartan** [comment]
Hi,

No you can only save the paint job and also accessories (typically RHS vehicles).
You cannot associate crew, ammo or anything else unfortunately.

**Comment by mast3rbates** [comment]
any plans on jip support? everytime someone jips it reloads the init and resets the player's gear.

**Comment by SpyderBlack723** [comment]
As far as I'm aware, the code only executes on the server. If not, then it will in the next release. Though, setUnitLoadout is broken and doesn't add items globally.

**Comment by Ookreson** [comment]
I was wondering if it would be possible to add two features-

-Garage/Virtual Arsenal of vehicles when modifying them, and not just "skins and crew"
-Vehicle inventory management

I know that when creating/copying vehicles into a faction it creates new classes.
I'm working on a CTRG revision and for the life of me, I can't seem to find the correct Prowlers in the CTRG faction to inherit and be used in the revised faction, hence the wishlist addition above.

**Comment by coachwn** [comment]
The prowler is listed in NATO.

**Comment by SpyderBlack723** [comment]
I specifically dodged implementing the virtual garage itself, trying to tie the virtual arsenal into the ORBAT Creator resulted in a massive list of issues.

To be honest, it's unlikely that any/many major features will be added to the ORBAT Creator at this point due to lack of time.. I've updated the above set of features with your ideas though, thanks.

**Comment by Ookreson** [comment]
coachwn, that's actually partially incorrect.

Nato has their own prowler, but CTRG actually has 3.

The light variant, and the other two whose scopes are listed at 0 which won't show up in the editor, only the squad compositions.

I've figured out a rough workaround, but I still need to fix it some more, as the CTRG Variants of the armed prowler's turret are glitched, due to the fact that the turret classnames are probably wrong.
