### ISSUE TITLE
Indexing fails

### ISSUE THREAD

**Issue by SpiderOfDeath** [ALiVEOS/ALiVE.OS#104]
- ArmA Version 1.64.138497

- Alive Version 1.2.0.1608121

I am trying to index [F.A.T.A](http://www.armaholic.com/page.php?id=22057)  because a mission maker would like to create a mission there. I tried to index the map but ArmA keeps crashing on me after i hit Map Indexing in the Alive Menu.

[ArmA RPT](http://pastebin.com/R2nEaFip)

[Indexing Log](http://pastebin.com/YafJjKy8)

**Comment by SpiderOfDeath** [comment]
Huh sorry seems like i uploaded the wrong logs. Sorry for that. Here are the right ones.

[Alive Log](http://pastebin.com/r37eqmDd)
[ArmA RPT](http://pastebin.com/FWjD5siS)

**Comment by SpyderBlack723** [comment]
Fairly certain F.A.T.A. should work off the bat unless there has been an update recently.

**Comment by SpiderOfDeath** [comment]
Not really. Í got it from [Armaholic](http://www.armaholic.com/page.php?id=22057)

**Comment by SpiderOfDeath** [comment]
´This can be closed. FATA is compatible with Aliive. The error is caused by the mission maker.
