### ISSUE TITLE
CS on Dedi Servers: Combat Spt does not work unless synced to Virtual AI Module

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#108]
Combat Support does not show in the ALiVE menu when placed standalone with ALiVE (Required).

It either needs C2ISTAR placed or to be synced to the Virtual AI module

This happens on dedi only.

Need repro steps.

**Comment by friznit** [comment]
CS doesn't appear to enjoy playing solo since the C2ISTAR update a while ago.  Not sure why syncing the virtual ai module would "fix" it, but the correct approach is to place the C2ISTAR module down (not synced).

**Comment by Ligthert** [comment]
I had this issues somewhere back in 2014 where the CS didn't spawn fast enough or got profiled somehow and I had to sync them to AI Caching module and the module to not cache those. This was later resolved during an update somehow. Maybe it got overwritten?

Requirement for this at the time was that there were a lot of profiles that made the server take its sweet time messing with the order of the init.
