### ISSUE TITLE
Logistics choppers land and take off without unloading

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#109]
As discussed in the following thread, there are reports of resupply helicopters touching down and taking off without dropping off the intended supplies: 

http://alivemod.com/forum/2440-logistics-broken

The good news is, here's an excellent video from Furcas using CBA and ALiVE only which demonstrates the issue:

https://m.youtube.com/watch?v=MThLFXD6py8&ebc=ANyPxKqldZ4lRotDuag_4pH8MDSnSJvgQk5pmuePR1t0jxjBvxGot2v5C9v5Wtq5hqKTzEsG-Nki097kww8oW8VjYkgghefgfw&time_continue=430

(Link embedded within the thread above incase you can't open the link here).

**Comment by marceldev89** [comment]
Also see https://github.com/ALiVEOS/ALiVE.OS/issues/107 😃

**Comment by HeroesandvillainsOS** [comment]
I read 107 but didn't see this specifically mentioned. But all those big words confuse me so you probably did address it there. :(

**Comment by marceldev89** [comment]
My bad, #107 is mostly about slingloading. :)

**Comment by tupolov** [comment]
Believe this is fixed with https://github.com/ALiVEOS/ALiVE.OS/commit/8c653727b945e28d96ebe58601e267857dcc490e

**Comment by HeroesandvillainsOS** [comment]
Nice. Thanks Tupolov.
