### ISSUE TITLE
Ability to delete SITREP/SPOTREP markers off the map

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#11]
Requesting the ability to delete SITREPS/SPOTREPS in a similar way to how we can CTRL+Right Click to delete Advanced Markers.

These tend to pile up on long persistence missions as players place them down quite often. In keeping with a milsim mentality, it would make sense that these could be deleted/cleaned up as needed. As of right now, maps can get extremely cluttered making it hard to track progress accurately.

In addition, we have discovered a bug when a high number of these have been placed down. It essentially stops putting the new SITREPS at the top of the list and starts putting them randomly in the middle/bottom of the list making it very difficult to find and read new ones that are being reported. I have to look at the ID on the marker, then scroll through every SITREP and find the matching ID to read it.

http://i.imgur.com/VZTgkIP.jpg -- If your map doesn't look like this... you are not operator enough!

Thanks for reading!

Vegas

**Comment by Vegas** [comment]
BUMP

**Comment by tupolov** [comment]
Request also will consider not persisting marker for SITREP and PATROLREP.

SPOTREPS can be deleted.
