### ISSUE TITLE
Saving/Loading in ORBAT Arsenal

### ISSUE THREAD

**Issue by abramsba** [ALiVEOS/ALiVE.OS#110]
When editing units the options save, load, export and import buttons are disabled. 

![Screenshot](http://i.imgur.com/4fgqWKk.jpg)

I think the inclusion of these features would also help cut down the amount of time it takes to create and manage the load outs of large factions as it's very time consuming to have to pick each loadout individually. 

I just browsed through the source and tracked it down to here, I assume:

https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/sys_orbatcreator/fnc_orbatCreator.sqf#L3243

                _ctrlButtonSave = findDisplay -1 displayctrl 44146;
                _ctrlButtonSave ctrlEnable false;

                _ctrlButtonLoad = findDisplay -1 displayctrl 44147;
                _ctrlButtonLoad ctrlEnable false;

                _ctrlButtonExport = findDisplay -1 displayctrl 44148;
                _ctrlButtonExport ctrlEnable false;

                _ctrlButtonImport = findDisplay -1 displayctrl 44149;
                _ctrlButtonImport ctrlEnable false;

Could these be enabled or is there a reason they're disabled?

**Comment by SpyderBlack723** [comment]
They are disabled to keep the interface very simple so users do not get confused with what exactly is being exported and imported.

You do not need to create each loadout individually unless they are drastically different from one another, this is what inheritance is used for. You can create a base unit that has a common set of gear, and then create additional units that inherit from this base unit (thus automatically having this gear). Are these buttons still necessary for you?

**Comment by abramsba** [comment]
I wouldn't call it a requirement but a nice to have, and I understand the confusion the buttons could have to people using it. Though, I don't agree that it should be disabled to protect the user from misunderstanding their function. I also think enough people are familiar with the Arsenal at this point to know they wouldn't influence any orbat functions. 


I have a lot of different custom loadouts that I have already gone through, filtered, and saved as a template should I need to use or export later. The load out of my units are also not always the same as others or able to be represented in a way that an item should be carried down a hierarchy and I often find myself forgetting to include items. (EG Creating copies of OPFOR units and switching up their gear to use TRYK's). 

Is there a way to change the text of those buttons via `ctrlSetText` to change the displayed name as to not cause confusion?

**Comment by SpyderBlack723** [comment]
I can change it for the next release

**Comment by abramsba** [comment]
Thanks, much appreciated!

**Comment by SpyderBlack723** [comment]
7136b1c35538877bd41841a6a7e6cbd5182515e0
