### ISSUE TITLE
Request: Transport/Gunship support option.

### ISSUE THREAD

**Issue by EasyEB** [ALiVEOS/ALiVE.OS#111]
So, CAS and Transport helicopters work great the way they are. But I miss an option for helicopters that can dual function.

The Hind is the perfect example as it is a little bit of both. I'd like to be able to call it in for CAS just like regular, but also be able to tell it to pickup, land and insert like the Transport option does.

Would this be possiburu?

**Comment by SpyderBlack723** [comment]
Perhaps try manually placing it and giving it the transport and cas tags

http://alivemod.com/wiki/index.php/Combat_Support

**Comment by EasyEB** [comment]
Good idea, I'll give it a shot and report back.

**Comment by EasyEB** [comment]
No dice.

**Comment by SpyderBlack723** [comment]
derp, forgot you cannot set each variable separately.

**Comment by EasyEB** [comment]
It really felt like this setvariable ["CS_TYPE","CAS","TRANSPORT"]; would work :)

**Comment by SpyderBlack723** [comment]
Will be
`this setvariable ["CS_TYPE","HYBRID"];`
