### ISSUE TITLE
sys_perfmon spams .rpt

### ISSUE THREAD

**Issue by Ligthert** [ALiVEOS/ALiVE.OS#114]
After the last ArmA 3 update, playing scenarios spams the .rpt-log filling it with ~40 errors per second.

It starts off with:

> 2016/10/21, 19:02:39 Error in expression <stomCode;
> 
> ALiVE_sys_perf_fsmHandle = [_customCode] execFSM "\x\alive\addons\sy>
> 2016/10/21, 19:02:39   Error position: <_customCode] execFSM "\x\alive\addons\sy>
> 2016/10/21, 19:02:39   Error Undefined variable in expression: _customcode

and

> 2016/10/21, 19:02:47 "perfMonitor.fsm started"
> 2016/10/21, 19:02:47 "perfMonitor.fsm init completed"
> 2016/10/21, 19:02:47 Error in expression <180;
> 
> _Next = diag_TickTime;
> 
> if (count _customCode > 0) then {
> _customNext = di>
> 2016/10/21, 19:02:47   Error position: <_customCode > 0) then {
> _customNext = di>
> 2016/10/21, 19:02:47   Error Undefined variable in expression: _customcode

Then this gets spammed over and over again:

> 2016/10/21, 19:15:35 Error in expression <(count _customCode > 0) && (diag_tickTime >= _c>
> 2016/10/21, 19:15:35   Error position: <_customCode > 0) && (diag_tickTime >= _c>
> 2016/10/21, 19:15:35   Error Undefined variable in expression: _customcode

This went on for the duration of the scenario and I traced it back to this snippet:
https://github.com/ALiVEOS/ALiVE.OS/search?utf8=%E2%9C%93&q=%28count+_customCode+%3E+0%29

I have no proposal on how to fix this, other than disabling the performance tracking as a workaround.

**Comment by marceldev89** [comment]
Check the `Custom Perf Monitors` array in the data module, it should be `[['entities',150],['vehicles',300],['agents',450],['allDead',600],['objects',750],['triggers',900], ['activeScripts',1050]]` by default.

**Comment by tupolov** [comment]
Please test again using above

**Comment by tupolov** [comment]
Couldn't repro.
