### ISSUE TITLE
ACE3 specific eventHandlers spawns an error

### ISSUE THREAD

**Issue by Ligthert** [ALiVEOS/ALiVE.OS#115]
After the recent ACE3 update ArmA 3 issues an error when ALiVE tries to work its magic with the ACE3 event handlers.

From the logs:

> 2016/10/21, 19:02:39 Adding ACE Stats EHs to player <NULL-object>
> 2016/10/21, 19:02:39 Error in expression <s_statistics_fnc_unitKilledEH;
> }
> ] call ace_common_fnc_addEventHandler;
> };
> 
> 
> 
> 
> 
> >
> 2016/10/21, 19:02:39   Error position: <ace_common_fnc_addEventHandler;
> };
> 
> 
> 
> 
> 
> >
> 2016/10/21, 19:02:39   Error Undefined variable in expression: ace_common_fnc_addeventhandler
> 2016/10/21, 19:02:39 File x\alive\addons\sys_statistics\fnc_statisticsInit.sqf, line 264

**Comment by marceldev89** [comment]
`ace_common_fnc_addeventhandler` was moved to CBA as `CBA_fnc_addEventHandler`.
