### ISSUE TITLE
Stuck loading using warroom

### ISSUE THREAD

**Issue by arv187** [ALiVEOS/ALiVE.OS#116]
This topic is few large, then I do not want to repeat all over again. I link here all my tests with images and rpt files.

http://alivemod.com/forum/2484-aliveserver-load-screen

I can't find a definitive solution. I tried with spyder insurgency kunduz template too, and editing alive modules options crash too.

**Comment by marceldev89** [comment]
It's probably best to create a simple mission from scratch on Stratis and/or Altis with *only* `@cba_a3`, `@alive` and (on the server) `@aliveserver` loaded to verify that there's nothing wrong with your setup.

**Comment by arv187** [comment]
That was did with spyder template mission, nothing wrong with setup. But when I want edit that template mission or other different mission... its like buy a lottery ticket.

**Comment by marceldev89** [comment]
Hmm I see that you already tested the demo insurgency mission.

Judging by the RPTs, Kunduz isn't working properly.
```
2016/10/20, 22:41:46 Performance warning: Very large search for 12416 (>400 m)
2016/10/20, 22:41:46 Performance warning: Search for 4aafc100# 12416: jbad_house_3_old.p3d was very large (1600 m)
```
It's probably not finding any locations.

**Comment by arv187** [comment]
I think that issue its related with virtual ai module. Read my last post from forum.

**Comment by marceldev89** [comment]
I don't think so. It seems like it's not finding locations/objectives. Post the RPTs with debug turned on in the placement modules.

**Comment by marceldev89** [comment]
Actually, I'm probably talking nonsense but please do it anyway just to be sure. :)

**Comment by arv187** [comment]
That dont have sense, sometimes find locations/objetives and others not? if I disable warroom (for example changing to false ip in server setup) all work good, there are objetives and locations, ai spawn, etc.
Even when waroom is enabled and setup right I can hear ai spawn and runing in loading screen, or when I shut down server I can see connection lost message and map with AI going to objectives. I did much tests, there are all in forum topic.
It's much information to see someone who knows, I dont know about this, but there are rpt, images, etc.

**Comment by marceldev89** [comment]
Alright, a couple of options.
- Test without ACE3
- Disable persistence in the "Military AI Commander" module
- Disable persistence in the "ALiVE Virtual AI System" module

I feel like one of those would fix the loading screen issue.

**Comment by marceldev89** [comment]
Alternatively to testing without ACE3, replace `sys_statistics.pbo` with https://dl.dropboxusercontent.com/u/38551057/sys_statistics.pbo.

**Comment by HeroesandvillainsOS** [comment]
Well Kunduz needs to be reindexed. That much is true. Could that be the problem? Can you try a different map please?

**Comment by arv187** [comment]
@marceldev89 @HeroesandvillainsOS I try that tips other day and report here I promes, Im tired after 4 days with this xD

**Comment by HeroesandvillainsOS** [comment]
The wiki needs an update. The Autumn Chernarus is fine (I use it). I hear Summer is ok but Winter I'm pretty sure has problems so I'd avoid that.

**Comment by arv187** [comment]
You have edited a missions with alive and spyderaddons? I think that. If its yes, what is to play it?

**Comment by HeroesandvillainsOS** [comment]
I'm not sure I exactly understand what you're asking. Yes I use Spyder Addons all the time. I'd say try making a mission on a map proven to work with ALiVE and see if the issue goes away (if you like Chernarus, go for it. It works). That will help narrow down what the problem could be.

**Comment by arv187** [comment]
I was asking for this to play https://forums.bistudio.com/topic/195429-alive-spcoop-1-8-the-beginning-of-the-end/
Thanks to both, I will tests with my mission next week.

**Comment by HeroesandvillainsOS** [comment]
Oh ok. Yeah I have four missions over on BIS forums. Feel free to give them a try and see if the work for you. They work for me. :)

If so, go ahead and unpack them and see how I have everything set up incase that's the issue here (doubtful, but you never know).

**Comment by arv187** [comment]
My mission is working, you can see it in warroom, but if I edit in most cases I get infinite loading screen if I setup warroom.
Seems as when I edit a mission, in kunduz at least, editor crash alive modules.

Sometimes after edit works, as now, 100% times working in warroom, not save status, but that is other history.

https://www.dropbox.com/s/mvf6po7hg2r4ypk/alivewarroom.JPG?dl=0
http://images.akamai.steamusercontent.com/ugc/250340463217141143/0D975503001A5BB10EA57BA487487F2A3EB25CC4/

**Comment by HeroesandvillainsOS** [comment]
Have you tried a different map or one of my missions (which all use a different map) just to see if those are working? We need to rule out whether the issue is Kunduz itself, or something with the way you're setting your mission up.

Honestly, not much can be done if you don't at least try a map with a proper index.

**Comment by marceldev89** [comment]
I'd rather see @arv187 trying out my suggestions to isolate the module that's causing it and go from there. He did mention (on the forums I think) that Kunduz worked fine without @aliveserver.

**Comment by HeroesandvillainsOS** [comment]
Oh ok if that's the case then yeah, good call marceldev89

**Comment by aoakeley** [comment]
I also have the same issue (stuck on loading screen but can hear vehicles etc) with loads of spam in the error logs.

http://alivemod.com/forum/2565-error-spam-error-undefined-variable-in-expression-tempindex
