### ISSUE TITLE
Get error at fnc_statisticsInit.sqf, line 264

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#117]
And for the question... YES... Ace3 is correct loaded...

` 0:10:25 Error in expression <s_statistics_fnc_unitKilledEH;
}
] call ace_common_fnc_addEventHandler;
};

>
 0:10:25   Error position: <ace_common_fnc_addEventHandler;
};

>
 0:10:25   Error Nicht definierte Variable in Ausdruck: ace_common_fnc_addeventhandler
 0:10:25 File x\alive\addons\sys_statistics\fnc_statisticsInit.sqf, line 264`

**Comment by shukari** [comment]
ist need to be -> CBA_fnc_addEventHandler

**Comment by SpyderBlack723** [comment]
9d7121ab23bbcb788c4680cbda752fb7c2f64d22
