### ISSUE TITLE
Alive Mod - Quick Reply - Auto Call

### ISSUE THREAD

**Issue by SASCarter** [ALiVEOS/ALiVE.OS#118]
Hi All,

I'm looking for a mod that will allow the user to easily reply to AI Pilots and or Call in support without opening the command menu/tablet etc.

For example, confirming smoke colour with AI pilot during CAS Transport Evac.... 1 yes 2 no... or call in Transport/Gunships to your approximate location at the push of a button in the event that your squad is overrun? 

Any help appreciated.

**Comment by friznit** [comment]
Not in scope for ALiVE - would require a new/different approach to Combat Support.
