### ISSUE TITLE
CAS Jet RTB Crash Landing

### ISSUE THREAD

**Issue by SASCarter** [ALiVEOS/ALiVE.OS#119]
Created a simple map with a number of support helicopters and a fighter jet. 

As expected, Helicopters provide support and RTB if ordered, land, refuel/arm and are set as ready to be called out again.

The Jet however, Taxis from hanger, takes off, provides support as instructed but when ordered to RTB attempts to land just off the runway and inevitably crashes. Even if it lines up with the runway (not often) it still crashes upon touching the tarmac??

Any ideas?

**Comment by friznit** [comment]
Which map?  Some maps don't have runways defined properly and the AI craps out when trying to land.

**Comment by SASCarter** [comment]
So far .. Bornholm and Tanoa

**Comment by marceldev89** [comment]
Noticed the same on Bornholm as well a while ago. It didn't happen every single time though.

**Comment by SASCarter** [comment]
Is there any way to set the Jets RTB flight path??

**Comment by SpyderBlack723** [comment]
No

**Comment by tupolov** [comment]
We don't touch aircraft AI, so either is the AI or the way the terrain/map has been configured for taxi etc.
