### ISSUE TITLE
Vanilla units spawning periodically

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#12]
Over the last few weeks I've been dealing with vanilla units (CSAT and OPFIA) spawning occasionally instead of the OPFOR modded faction. I've tested this with multiple factions and can duplicate the issue on a regular basis. Bare in mind most of the time the correct faction spawns so to spot the issue can take a bit of teleporting around. 

Here is a test mission on Stratis which duplicates the issue with CSAT spawning. I found a CSAT guy randomly trying to shoot me from a tower in a compound.

https://www.dropbox.com/s/57jzs0uzvffpvi4/Oh_Canada.Stratis.pbo?dl=0 

Requirements
CBA
ALiVE
CUP Weapons
CUP Vehicles
CUP Units

To try and accelerate the issue, I set roadblocks and random camps to high, but just note vanilla units can spawn anywhere (though OPFIA seems especially to like the roadblocks. CSAT can spawn anywhere) 

The second group I spawned to in this instance had CSAT but sometimes it can take longer to see this occur. 

I figured CUP Takistani's was a decent choice here considering even the ALiVE official MSO remake uses that faction (I think). Anyway, I figured CUP_O_TK_MILITIA was about as safe a bet of a "clean" mod as any I could have used though note I can duplicate this with multiple factions.

**Comment by HeroesandvillainsOS** [comment]
Here's a revised version of the mission on Stratis which uses much less modules. Only ALiVE Required, Virtual AI, OPCOM, Mil obj and Civ obj are present.

www.dropbox.com/s/hsvm5vkh1gl1hm4/test.Stratis.pbo?dl=0

Requires CBA, ALiVE, CUP Weapons, CUP Units, CUP Vehicles

**Comment by tupolov** [comment]
Thanks for the repro mission, investigating

**Comment by tupolov** [comment]
Ok, sorry but you spelt MILITIA incorrectly in the military objectives module. You had CUP_O_TK_MILITA when it should be CUP_O_TK_MILITIA. @HeroesandvillainsOS
