### ISSUE TITLE
Custom variables not saving / loading correctly

### ISSUE THREAD

**Issue by 1ncontinentia** [ALiVEOS/ALiVE.OS#120]
Custom variables saved using the script snippets below, do not load correctly. 

```
["CustomVariableTest", "test"] call ALiVE_fnc_setData;
CustomVariableTest = ["CustomVariableTest"] call ALiVE_fnc_getData; 
```
## Repro:

In any ALiVE mission which has persistence enabled, save a custom value using ["CustomVariableTest", "test"] call ALiVE_fnc_setData;, then save and exit the server. Start the server again, connect the client and check all other persistence has loaded correctly. Then use CustomVariableTest = ["CustomVariableTest"] call ALiVE_fnc_getData;  to restore your custom variable data. CustomVariableTest will have no value. 

Interestingly, the server RPT (I will post one soon) shows the value of the saved data on both save and exit and load, but getting it back into the mission does not currently work.

**Comment by SpyderBlack723** [comment]
Are you retrieving the data serverside?

ex.
init.sqf
if (isServer) then {
    // get data
    hint "we got the data";
};

**Comment by 1ncontinentia** [comment]
Yes, tried both client side and server side.

**Comment by tupolov** [comment]
Just tested this and works fine for me.

["AnyKeyName","Yo Momma"] call ALiVE_fnc_setData (exec server side)

Server Save and Exit

test = ["AnyKeyName"] call ALiVE_fnc_getData; diag_log test;

Should see "Yo Momma" in the RPT

**Comment by 1ncontinentia** [comment]
Could you then load it next time you started the server? The issue isn't that you can't save or that it doesn't show up in the rpt, it's that the data isn't accessible once you load the server again (for me at least).

**Comment by SpyderBlack723** [comment]
> **Server Save and Exit**
> 
> test = ["AnyKeyName"] call ALiVE_fnc_getData; diag_log test; (exec server side)
> 
> Should see "Yo Momma" in the RPT

**Comment by ostinelli** [comment]
Same issue here.
