### ISSUE TITLE
Multispawn insertion heli change class (/code field)

### ISSUE THREAD

**Issue by mchgbh** [ALiVEOS/ALiVE.OS#121]
Hi,

the helicopter insertion after respawn uses the Vanilla helicopter, which breaks immersion quite a lot in a few scenarios. It would be great to have a class field and a code field for the init. The code field would important to prevent unrealistic items in inventory of helicopter or add needed items for example. 

Btw: Thank you guys for a great mod!

**Comment by marceldev89** [comment]
You can synchronize a vehicle to the multispawn module and it will use that vehicle.
