### ISSUE TITLE
Task target description incorrect

### ISSUE THREAD

**Issue by EasyEB** [ALiVEOS/ALiVE.OS#122]
Greetings!

I'm using an ORBAT created faction as Opfor and when Alive generates Destroy Vehicles task the target description is the same as the first target vehicle for the rest of the targets.

It goes like this: 
First target is T-72, target description is T-72.

Second target is BMP-1, target description is T-72.

Third target is GRAD, target description is T-72.

And so on.

I only started seeing this after I forced the placement module to use certain ammount of Armored/Mechanized/Motorized groups.

Love you. Bye!

**Comment by tupolov** [comment]
Weird is this 3 separate destroy vehicle tasks? Or one main task with 3 child tasks?

**Comment by EasyEB** [comment]
Three different tasks.

**Comment by tupolov** [comment]
Repro'd and is a wider issue with other tasks too.

**Comment by tupolov** [comment]
Fixed with https://github.com/ALiVEOS/ALiVE.OS/commit/f436f2852aa83124314c9973ff4fa2c781bdfa5a
