### ISSUE TITLE
[REQUEST] More informations on OPCOM warning

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#124]
`16:43:10 There are 89 objectives for this OPCOM instance! Please lower the objective count for performance reasons, suggested is below 80!`
`
Please add informations about the type of the module... i have 6 modules and dont know which one is the right one.

**Comment by tupolov** [comment]
Post the full RPT please

**Comment by shukari** [comment]
http://pastebin.com/AB0MmPS8
You can also see #123 ^^
