### ISSUE TITLE
sys_data module ignores module settings

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#125]
it seams that the sys_data module ingore my settings in the eden module... for example i set "Disable AAR" to No and in rpt -> "CONNECTED TO DATABASE, BUT AAR HAS BEEN TURNED OFF"

Example mission: https://workupload.com/file/BNE9mAe
Server rpt: http://pastebin.com/mNFjxZG2

I digging through the code and it seams to get the infos from the warroom... but i see no settings in warroom for ARR or something.

**Comment by tupolov** [comment]
We turned AAR off on War Room as it is currently under new development.
