### ISSUE TITLE
Enhancement Request: ALiVE IED module/functionality

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#126]
I'd second a inclusion of ace compatibilty with IEDs. As a very large group of the ALiVE community also use ACE, it would be a welcome addition.

My dream scenario would be to see ALiVE incorporate some features that E.O.D. suite uses in that mod (trigger men, different types of IEDs, etc.)

One last thing on IEDs I think would be useful would be to add one line to the Assymetric commander where if you chose to already have some installations enabled (which we can) you also had a sub-line under that which said "Existing IEDs already placed? (none, low, med, high, extreme)."

Finally...adding Spyder's civilian interaction and ambience modules as actual ALiVE built in components would be pretty awesome as well.

**Comment by tupolov** [comment]
Need more detail here.

Today for IEDs, we place an vanilla IED and setup triggers to handle detection, detonation and disarming. Its my understanding that for ACE IEDs we would only place the IED and not use the ALiVE mechanisms for detect, detonate and disarm.

Today in the IED module you can specify the classes used for IEDs, so you should be able to specify ACE IEDs. So, the next enhancement is basically to ONLY place ACE IEDs if its an ACE IED class.

I need to check how Asymmetric does IED classes too.

**Comment by tupolov** [comment]
Work needed

1. Add check for ACE IED on placement
2. Remove ACE IED from ALiVE IED store if it is destroyed
3. Remove ACE IED from ALiVE IED store if it is disarmed

Not inscope VB-IED, Suicide Bomber

**Comment by tupolov** [comment]
So ACE has pressure plate based IEDs and command/trigger IEDs. For ALiVE using pressure plate IEDs by AI is probably most suitable

**Comment by AUTigerGrad** [comment]
Yup, that sounds great Tup.

Would Triggermen be in scope for ALiVE?  i.e. Create certain IEDs that would not be pressure plated but rather activated by a triggerman who detonates the device by cellphone when enemy are within range?

**Comment by 1ncontinentia** [comment]
I suspect using enemy units as triggermen would probably involve messing with low-level ai a bit too much for ALiVE's tastes but perhaps using rogue civilians could work as triggermen?

**Comment by marceldev89** [comment]
@tupolov here's some ACE material in case you haven't seen it yet: http://ace3mod.com/wiki/framework/explosives-framework.html

**Comment by tupolov** [comment]
Yeah seen. I'm thinking not just ACE but any 3rd party IED system. So ALiVE will place the IEDs, but the expectation is that the 3rd party system provides detection, defusal/disarm and detonation. So basically select 3rd party IEDs, enter your class names and we should be good to go. Will get a WIP in this weekend

**Comment by AUTigerGrad** [comment]
TUP...if that is able to be incorporated..does that mean that a mod such as E.O.D. suite could be used in conjunction with ALiVE...ALiVE would spawn the IEDs designated (E.O.D. suite IEDs)....then the players would use the E.O.D.s suite defusal/detection, etc. functionality? Essentially giving the player the ability to use whatever format needed while still getting the benefit of keeping the IEDs inside of the "Asymmetric Commander" framework?

That. Would. Be. Awesome.

**Comment by tupolov** [comment]
In a word. Yes.

**Comment by AUTigerGrad** [comment]
You sir are the man.  You deserve a Heineken.
