### ISSUE TITLE
Enhancement Request:  Ability to select specific factions for Logistics/reinforcements

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#127]
Currently we only have the ability to get logistics from "Side" (i.e. every single faction is available in Blufor, etc.) or "Faction".

But for example...if my player is an RHS Socom Operator....I'd like the ability to be able to call in RHS US Marines or US Army for reinforcements instead of just RHS US SOCOM units  WITHOUT having to have every other Blufor faction (NATO, etc.) also in the list. 

So essentially...the ability to cherry pick which factions are available to players for reinforcements would be a big addition.

**Comment by HeroesandvillainsOS** [comment]
This is a good request. On top of that, I'd like to be able to request individual units from the faction my player and OPCOM is, without having to necessitate a helicopter from the same faction.

For instance, rhs_faction_usmc_ d and rhs_faction_usmc_wd. Both of these factions are completely ALiVE compatible but neither have any helicopters by design. This means you can't request any individual units from LOGCOM. The player faction and compatible OPCOM faction should be enough.

**Comment by HeroesandvillainsOS** [comment]
Copy/paste from ALiVE forums: I'd personally love to see it tap into the factions used in the obj modules/controlled by that side's OPCOM. So if I have ANA at civ objs and special forces at mil objs, no matter who I play as, I can call in ANA and special forces groups on the field.

**Comment by AUTigerGrad** [comment]
Incentive note: I will be the best friend of whoever gets this implemented in a future ALiVE release.  So...you know...that's the golden ticket you have if you can get this done.  I know you're psyched!!

**Comment by friznit** [comment]
Player Logistics was designed to be an interface into the existing logistics setup, so intuitively it should by default list stuff belonging to faction(s) from the synced Mil AI Comd only, regardless of the Player's faction.

Options in the Player Log module should be "Faction = whatever faction is listed in Mil AI Comd module" or "Side = side of factions listed in Mil AI Comd Module".

Enhancement as per autriggerguard's note above: add blacklist/whitelist by faction.

**Comment by AUTigerGrad** [comment]
@friznit If that is how the module is intended to work, it does not appear to be working that way.  When setting the Player Combat Logistics module to "Faction" it is only pulling from the faction that the player belongs to...not the factions listed in the Military Command module.  For example...current campaign players are playing as RHS Socom special forces.  The Military Commander module is only Iraqi Army from the Iraq/Syria conflict mod.  When I go to player logistics and attempt to bring in groups, supplies, etc. it will only pull from RHS Socom and not from the Iraqi Army.  Also..because I only have players as RHS Socom and not the AI commander..the logistics module says "Current Force Pool 0" even though the Iraqi Army Military Logistics module is set to 10000.  

I tested with Vanilla units and got the same result.
