### ISSUE TITLE
ORBAT faction request

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#128]
Some factions I would like to see organized for ALiVE use.

The rest of the RHS factions (Russian VDV and MSV, US Marines and US Army are the only ones currently with ALiVE compatible groups.  Still need Russian Naval troops, US MARSOC/SOCOM units, etc. grouped)

RHS GREF Factions

UNSUNG factions

**Comment by friznit** [comment]
This is really a request to the RHS team, as it's out of our power to fix other mods to work with ALiVE (see also Pull Request #16 ) However, you might be able to do something workable with those factions using the ORBAT Creator tool.

**Comment by AUTigerGrad** [comment]
Yeah, I absolutely can get these factions grouped properly.  I just didn't know if someone else was already working on that.  I could have sworn I saw something on here with someone working on the GREF factions.

**Comment by friznit** [comment]
It's that PR I linked above.

**Comment by coachwn** [comment]
Hey AU...if you can let's try to get together later. I am looking at creating a faction entirely and might need a little help with it

**Comment by AUTigerGrad** [comment]
I can do that.  Hit me up on Steam (AuburnAlumni)

**Comment by coachwn** [comment]
Got my PLA Faction setup...not entirely fleshed out the way I would like to due to limited vehicles in VME but they work.
