### ISSUE TITLE
Enhancement request:  ALiVE "QRF" functions

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#129]
I'd like to see the ability for both the friendly and enemy OPCOMs to utilize a Quick Reaction Force "QRF" when high priority objectives are attacked.  

Essentially....I would think it would simply be calling the Logistics function for reinforcements but not waiting until reinforcements are needed.  

This would especially be useful when attacking major OPCOM targets to add an extra challenge to it.  I.E. you fight your way through an Enemy city, then have to quickly prepare for an enemy counterattack as the OPCOM sends a rapid deployment force to try to retake it ASAP.

**Comment by friznit** [comment]
OPCOM only reacts when an objective has been lost.  It's not clever enough to know if an objective is merely threatened by an enemy force.  Currently, if an objective has been lost and it is a high priority objective, OPCOM will put it at the top of the list in the next analysis cycle anyway, essentially achieving the effect of a counter attack.

See also #6 for AI Comd Enhancements ideas.

**Comment by AUTigerGrad** [comment]
That whole list is outstanding Friznit.

I'd add to that a wish that the OPCOMs spawn static artillery, machine gun nests, and mortar crews at objectives when they are available in the faction.

If OPCOM has a defensive stance...have a higher chance at coming into contact with enemy artillery batteries, MG nests, and fixed defenses. (i.e. spawn ALiVE compositions like bunkers, trenches, etc.)

**Comment by friznit** [comment]
Superseded by #6 and #233
