### ISSUE TITLE
[Demo_Mission] ALiVE_Sabotage caused script error

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#136]
The MP Alive_Sabotage mission caused this error:
```
12:14:38 52 : No control
12:14:38 Error in expression <commanding];
_unit setSkill ["general", _general];

if (_debug) then {["ALiVE Sk>
12:14:38   Error position: <_general];

if (_debug) then {["ALiVE Sk>
12:14:38   Error Nicht definierte Variable in Ausdruck: _general
12:14:38 File x\alive\addons\sys_aiskill\fnc_AISkillSetter.sqf, line 75
12:14:38 52 : No control
```

Also this missions are not updated to Eden aka. 3D editor!

**Comment by shukari** [comment]
you have the repo allready... it is the default Alive_Sabotage mission ^^
https://github.com/ALiVEOS/ALiVE.OS/tree/master/demo/MP/ALiVE_Sabotage.Altis

**Comment by SpyderBlack723** [comment]
Outdated mission may be the issue here.

**Comment by shukari** [comment]
Convert was not possible!

**Comment by SpyderBlack723** [comment]
Yes it will have to be done via developer environment, wasn't suggesting you had to do the conversion ;)

**Comment by shukari** [comment]
Normally you can convert any preEden sqm (2d) to eden sqm... without "developer environment".. or im totally wrong ^^

**Comment by SpyderBlack723** [comment]
Well yes you could download the unpbo'ed version from github, either or.

**Comment by shukari** [comment]
Yes, i used the github version... also i converted the mission successfully to 3d eden.... and then the error appeared.
I also suppose they all are outdated... so is it good to keep outdated missions?

**Comment by friznit** [comment]
Demo missions are going to be rebuilt - or more likely we'll create new ones and the old ones will be scrapped.

See #216
