### ISSUE TITLE
Problem exporting Group config to clipboard

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#137]
This is showing up on various groups that I am trying to build within the ORBAT and when I go to Export > Groups > Selected Groups the following linked error message shows up in the middle of my screen.

The text for the message is as follows:

'...= _result + _newline;
_result = _result |#|+ _output;
};
};
;
File x\alive\addons\sys_orbatcreator\fnc_orbatCreator.sqf, line 6229 
if (!isnil "_resu..."
Error Generic error in expression

http://images.akamai.steamusercontent.com/ugc/396708663053299299/9860624F8DF3C295435ED974DF03593DAB8C0E8B/

**Comment by SpyderBlack723** [comment]
Please use this build

https://www.dropbox.com/s/wx3ipku5qtui78y/ALIVE_ORBAT_CREATOR_TESTBUILD.RAR?dl=0

**Comment by coachwn** [comment]
Is there a way to save and import all my work that I did so I can export it correctly or do I have to start all over? I have pushed all the units out to a text file and didn't know if that was possible yet.

**Comment by SpyderBlack723** [comment]
Temporary method you can try (Will not un-corrupt data SQF data though):

copyToClipboard str ([ALIVE_ORBATCREATOR,"state"] call ALiVE_fnc_orbatCreator)

Save that to file
Then to reload

[ALIVE_ORBATCREATOR,"state", (data from clipboard)] call ALiVE_fnc_hashSet

**Comment by coachwn** [comment]
Tried to load the different mods to load and getting the following error. It does not make a copy of the mod so that I can edit it.

http://images.akamai.steamusercontent.com/ugc/396708663053409284/8A893DF2718002C70F52595A76C7BAB55F5944BC/

**Comment by coachwn** [comment]
Per my comment on the ALiVE forums here is the error message when trying to use the latest version today for copying to make a new faction. Will not even show me a copy of the unit.

Tried copying Massi's PLA
http://images.akamai.steamusercontent.com/ugc/396708796890197079/CC4791CC4E3E9ACE461ADC26F90AEB2E5719BB1B/

Tried copying BLU_F stock as well
http://images.akamai.steamusercontent.com/ugc/396708796890195935/AF992DB660DAEDBDBF41691C8B665A84C206E2AD/

**Comment by SpyderBlack723** [comment]
Thanks, forgot to test a certain change. Have corrected the issue.

9d4503139fbd7f690df2d31600ceb992ac365fcf

**Comment by coachwn** [comment]
Redownload and try it again?

**Comment by SpyderBlack723** [comment]
I'm not going to do another build. I'll wait for the next official build we have and then link that.

If you have a developer environment setup you can pull the latest changes and run those.

**Comment by coachwn** [comment]
Unfortunately I am not...guess I will have to wait for the next build and then finish up my units. Glad I could help get some things worked out.

**Comment by SpyderBlack723** [comment]
@coachwn Found time for one more
https://www.dropbox.com/s/6u3sqrsdyub85mj/ALIVE_ORBAT_CREATOR_TESTBUILD.RAR?dl=0
