### ISSUE TITLE
Request: Slowing down insurgency

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#138]
I'm wondering if it would be possible to take a look at the insurgency model over long persistent sessions. I feel like they grow too much, and much too quickly.

As an example, I have a mission on a 20x20 map. The main AO is most of it. To keep the initial objectives and force sizes small, the Occupation Commander has troops spawning with 200 company mil obj (with low filtering) and 100 company civ obj (limiting them to small obj's and above). The Assymetric Commander gets a 100 company civ obj module only (filtered to tiny obj's and above). They also get 5 cust objectives set to spawn a total of 10 profiles. To give you an idea what this looks like on mission start: 

74 vs 74 profiles for each side
There are no pre-placed installations 
Pre-placed roadblocks are set to low
Civ density high (unfiltered)
Civ hostility low for each side
Occupation Commander gets reinforced in packets (and always controls a suitable mil obj for BCR's)

After 6 persistent hours, the total profiles between both sides jumps up from 148 to 205. If we assume the Occupation Commander is at full strength, this means the Assymetric Commander sees a net of 57 profiles on top of his initial strength, even after taking heavy losses throughout the 6 hours of fighting. At this stage so early on, I would say the mission would be too lop-sided for the Occupation Commander overcome. Or will be soon enough as the insurgency continues to grow and grow.

I feel like installations are too effective at generating Assymetric profiles. They seem to produce not only too many, but too many in such a small amount of time.

I realize there are a few ways to counter-balance this (making the AO smaller, having less civs, increasing the civ hostility towards the insurgents, increasing the initial strength of the Occupation Commander), but all of these options seem less interesting and engaging to me, especially considering my initial settings are relatively conservative all things considered.

In a perfect world, I'd love to see it slowed down tremendously, with more things to do other than shooting to pass the time (delivering supplies to civs, etc). But considering the shooty-shooty nature of the game, some fine tuning for how effective installations or perhaps capping how large the insurgency can get based on Irish strength and objectives would be an excellent first step IMO. Anyway, I would love it if someone that understands the system would take a look at how a typical insurgency develops after 10-20+ persistent hours and see if there's any room for refinement or not.

**Comment by 1ncontinentia** [comment]
I agree on this. Could be a good idea to have a settings for insurgent proliferation speed (but better worded of course).

**Comment by HeroesandvillainsOS** [comment]
I'm wondering if maybe that isn't perhaps exactly what the civ hostility is designed for. I'll be taking a look-see here soon hoping that's the case. I have my doubts though but we'll see. It would need to make a very very noticeable impact to slow things down to a manageable level.

Played another different mission yesterday, similar settings to the above. 41 BLUFOR vs 39 insurgents. After 1:06, the insurgents netted 8 profiles. It's just too much.

**Comment by HeroesandvillainsOS** [comment]
Hmm. I'm wondering if there might be some kind of bug causing new installations to insta-spawn when loading a persistent save. I just set up a vanilla mission to test this on so we'll see. Investigating.

**Comment by HeroesandvillainsOS** [comment]
My vanilla testing has disproven my theory about this being a bug upon loading a persistent save. That would have been too easy! :)

Hopefully a dev has the time to look at this mode and gives us the option to slow it down.

**Comment by HeroesandvillainsOS** [comment]
@Tupolov I know you guys are busy with more pressing stuff but if you get a sec, I just wanted to ask if anyone on the Dev team spends a lot of time with long-term persistent insurgency campaigns (10+ persistent hours) and whether or not you'd have an opinion on it?

I'm avoiding the mode right now due to the proliferation speed with what I feel like are pretty conservative settings (on a map like Takistan, I give the insurgents around 35 total profiles against upwards of 50 friendlies. 25% speed. No pre-placed installations, and FWIW no roadblocks or camps. High density of civs to because I enjoy interrogating those guys though. Medium insurgent hostility, low BLUFOR, etc).

I'm open to suggestions if the consensus is everything is playing out as desired though. It's just regardless of the settings I've tried, somewhere between the 6-12 or so persistent hour mark, the mode goes from very enjoyable to totally insurmountable. The only things left I can think of on my end would be decreasing the total civs and insurgents but then there would be nothing to do.

**Comment by highhead** [comment]
ok will look into

**Comment by HeroesandvillainsOS** [comment]
@highhead Thanks so much man.

**Comment by highhead** [comment]
Hi mate!

The speed of an insurgency taking over an island is dependend on many factors:
- Amount of strategic objectives
- Amount of initial troops
- Small vs. large area
- Amount of civilian system objectives
- Amount of civilians per objective
- Ofc opposing presence, eg. blowing up installations clearing towns
- and some minor more that I may have missed...

All of those can be "configured" to match a certain scenario. But 2 are missing:

- Amount of simultan objectives captured (atm. static 3)
- Amount of newly recruited troops (e.g. dim recruitment centers).

I believe making those 2 configurable too, would help speeding down an Insurgency quite a bit! Esp. in combination with profiles speed setting!

Would that help or am I missing something?

**Comment by friznit** [comment]
An option to reduce the rate at which recruitment centres are generated seems the most balanced approach.

As a mission maker I want to set the recruitment centre ratio (very low, low, medium, high) so that I can control how quickly insurgency spreads.

**Comment by HeroesandvillainsOS** [comment]
Thanks for taking interest in refining the mode @Friznit and @Highhead. :) I agree with Friznit regarding the overall goal of being able to tailor the speed at which the insurgency can grow, and I think having an option to configure the ratio of recruitment centers certainly would accomplish that. It's a really good idea because it would keep the integrity and spirit of insurgency intact, while also addressing the recruitment speed directly as well as giving the mission maker choices (so a win-win-win, really).

If you guys could get that in I think that would do it.

**Comment by highhead** [comment]
its in dev, should hit your missions soon(tm)

**Comment by friznit** [comment]
For info, OPCOM decides whether there should be a recruitment centre based on the number of civ pop present at an objective, which obviously differs greatly depending on the map and module settings.  HH has added an option in the module for mission makers to choose the number of civ pop needed in an area before recruitment centres are built.  The more civs required, the fewer centres will be built, hence slowing down the overall rate at which insurgency spreads.  Neat :)

**Comment by HeroesandvillainsOS** [comment]
Wow! Awesome! And a real incentive to detain some civs in my make-shift detention centers too! That's really really great. Thanks a million @Friznit and @Highhead. It really means a lot because this is basically the only thing I play. 

I can't wait to try it out!
