### ISSUE TITLE
fnc_SeaPatrol.sqf script error

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#139]
```
11:15:57 Error in expression <if (surfaceIsWater _gpos) then {
 
 
if (!terrainIntersectASL [_lastpos,_gpos] || >
11:15:57   Error position: <terrainIntersectASL [_lastpos,_gpos] || >
11:15:57   Error 2 elements provided, 3 expected
11:15:57 File x\alive\addons\mil_command\fnc_SeaPatrol.sqf, line 130
```

http://pastebin.com/yT9xRzRu

**Comment by tupolov** [comment]
Keep these coming Shukari! Really appreciate the testing and bug reports. Please where possible include basic repro steps on vanilla mission. Cheers!

**Comment by shukari** [comment]
I dont really test something... i create only missions for my group ^^
I try my best to make repos.... but all this bugs happen with my framework and mods... so its hard ^^

**Comment by shukari** [comment]
cant reproduce this atm... i try it now for hours but i dont get the error again...
here is the mission where it happend: https://workupload.com/file/jZr89EL

_lastPos was a 2d pos arry or something... because `terrainIntersectASL` need two elements so the error means the first parameter the position.

I could be because i changed the mission between persistent and normal sometimes.

**Comment by marceldev89** [comment]
I've checked the code and I think I've identified the problem.

The position arrays in the `fnc_analysis` data files are 2 elements. `ALIVE_fnc_getClosestSea` uses that data but never adds the third element to the array.
https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/fnc_analysis/fnc_getClosestSea.sqf#L55-L66
https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/fnc_analysis/fnc_getClosestSea.sqf#L92-L104

**Comment by marceldev89** [comment]
Should be fixed in the next release. :)
