### ISSUE TITLE
fnc_taskHandler.sqf caused script error

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#140]
```
11:16:59 Error in expression <dom (_taskPlayers select 0);
_player = [_player] call ALIVE_fnc_getPlayerByUID;
>
11:16:59   Error position: <_player] call ALIVE_fnc_getPlayerByUID;
>
11:16:59   Error Undefined variable in expression: _player
11:16:59 File x\alive\addons\mil_C2ISTAR\fnc_taskHandler.sqf, line 480
```

http://pastebin.com/zVqEVWTp

The server has no player on and i suppose this is because of -autoInit

**Comment by shukari** [comment]
Repo for dedicated server...
Here the mission: https://workupload.com/file/jZr89EL
Automatic tasks and -autoInit trigger this error!

**Comment by tupolov** [comment]
Thanks again for the repro. Looks like Auto tasks needs to be paused if no players on server.

**Comment by tupolov** [comment]
Pushed a fix, if you get a chance to test what's in dev that would be great. Thanks Shukari!

**Comment by tupolov** [comment]
Expiring
