### ISSUE TITLE
[Feature] plans for using "createSimpleObject"

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#141]
Are there plans for using createSimpleObject for constructions and other stuff?

**Comment by SpyderBlack723** [comment]
@marceldev89 mentioned that many objects _may_ already automatically be created using simpleObject via config methods. Needs confirmation.

**Comment by shukari** [comment]
I can only confirm that some objects are simple objects if you set something in eden editor... for example walls...

**Comment by marceldev89** [comment]
@SpyderBlack723 I thought I read somewhere that they did do something through the configs but the changelog says:
> Tweaked: Several non-interactive and non-destructible object types are now Simple Objects by default when placed in the Eden Editor
I'm not sure if that's done through the Eden Editor or the configs. :/

**Comment by shukari** [comment]
Worked only in eden... tested with "Land_BagFence_Long_F"... placed two of them one as simple the other as NON-simple...
- simple object hast no cursorTarget and only `1779911: bagfence_long_f.p3d` as cursorObject
- NON simple has cursortarget and `7d21b900# 1779910: bagfence_long_f.p3d` as cursorObject

The wall created with `"Land_BagFence_Long_F" createVehicle (getPos player)` is NON simple... the changelog is right... only the eden editor transforms objects automatically in simple objects.
