### ISSUE TITLE
[mil_c2istar] Failed tasks do not fail all children tasks

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#142]
Repo Mission: https://workupload.com/file/jZr89EL (same as #140 and #139 )
Picture: https://s11.workupload.com/image/yxaPdXp

Problem:
1. enable auto tasking
2. enable persistence (not sure if this is important)
3. join server
4. make tasks
5. fail tasks

If tasks failed not all children of this tasks get also failed!
Also it seams for persistent task the order is wrong... secure the guys before locate them like on the picture... but i suppose only on the task briefing page...

**Comment by GunnyDev** [comment]
Child Tasks now mirror parent state, also implemented if Parent Task is
deleted so is child task.
