### ISSUE TITLE
[sup_player_resupply] logistic gui problems

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#144]
Repo Mission: https://workupload.com/file/6XxUjGw
RPT: http://pastebin.com/7QtB8jAG
On: EdenEditor-Multiplayer
Steps:
1. open Alive menu->commander->logistics
2. its empty
3. press "show status"
4. press "back to requests"
5. first error
6. close GUI
7. make 1. again
8. get second error
Caused by: i suppose because i deactivated everything in the logistic module ^^
Errors:
```
12:19:24 Error in expression <
_selectedOption = _deliveryListOptions select _selectedIndex;
_selectedValue = >
12:19:24   Error position: <select _selectedIndex;
_selectedValue = >
12:19:24   Error Nullteiler
12:19:24 File x\alive\addons\sup_player_resupply\fnc_PR.sqf, line 1384
```
```
12:19:57 Error in expression <all ALIVE_fnc_PR;
};
};
 
_countWeight = _counts select 0;
_countGroups = _counts>
12:19:57   Error position: <_counts select 0;
_countGroups = _counts>
12:19:57   Error Nicht definierte Variable in Ausdruck: _counts
12:19:57 File x\alive\addons\sup_player_resupply\fnc_PR.sqf, line 2750
```
also again error from #143

**Comment by tupolov** [comment]
12:18:54 There are no delivery methods allowed, enable one or more delivery methods on the Player Combat Logistics module!

This isn't supported, but will ensure we don't initialise if everything is disabled
