### ISSUE TITLE
[civ_placement] rare error

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#145]
I tried to reproduce the #143 error than i get this rare error message.
Please dont ask for a repo i have atm no steps for reproduce this, i try my best to find one... but i hope the rpt can help atm!
On: EdenEditor-Multiplayer
RPT: http://pastebin.com/G1Q2Frk5
Error:
```
11:49:07 Error in expression <ition","_size","_spawn"];
 
if (typeName _x == "ARRAY") then {
_position  = _x se>
11:49:07   Error position: <_x == "ARRAY") then {
_position  = _x se>
11:49:07   Error Nicht definierte Variable in Ausdruck: _x
11:49:07 File x\alive\addons\civ_placement\fnc_CP.sqf, line 1053
```

**Comment by marceldev89** [comment]
I'll take a look while working on #139 since it's the same module. 😃

**Comment by marceldev89** [comment]
This might be fixed with https://github.com/ALiVEOS/ALiVE.OS/commit/2ffdbd2352f8531f360f70b02061503f27c3d1a8 but just missed the boat for release. 🙁

I'll close this for now. Feel free to reopen this one if it happens again with the next release (1.2.1+).
