### ISSUE TITLE
Millitary Objective -> Place Supplies get destroyed on missionstart because spawned in ground

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#146]
Rep mission: https://workupload.com/file/CRDGEwp
Info: in this mission you spawn on a millitary base in a "Land_Research_house_V1_F" 'house' somethimes there spawn a crate
Steps:
1. join and look at the ground
2. if there is nothing restart the mission until you see the crate in the ground
3. you saw the crate in the ground and you are now a passiv smoker because it smokes and disappears
4. all crates are destroyed at this base where you are

**Comment by marceldev89** [comment]
Can confirm, noticed this as well. I _think_ it's the garbage collector doing this but haven't investigated it yet. Will take a look soon-ish.

**Comment by shukari** [comment]
In this case the crate spawned not on the ground of the Land_Research_house_V1_F instead on the normal earth ground... the result was that it "explodes" aka. smoke and sink in the ground ^^

**Comment by marceldev89** [comment]
Well, it's not the garbage collector. It's just improper placement causing the ammo box to collide with the building it's supposed to spawn in. Will come back to this later. 🙂

**Comment by marceldev89** [comment]
Should be fixed with the next release. 😄
