### ISSUE TITLE
[logistic] frezze on transport plane insertion

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#147]
Repo mission: https://workupload.com/file/6XxUjGw
RPT: nothing important in it
Steps:
1. open logistic menu
2. choose transport plane insertion
3. choose car -> hunter
4. request this
5. results:
5.1. on singleplayer and hosted multiplayer (eden) the game frezzes for 5 seconds complete
5.1.1. Tip: walk around after request.. so you see the frezze ^^
5.2. on dedicated server the fps and cps near 0
Picture from marmacp:
overview: http://imgur.com/cLgMJfm
the drop aka logistic requested zone: http://imgur.com/PBCa7U2

**Comment by tupolov** [comment]
Pics are not showing

**Comment by shukari** [comment]
What do you mean?
You can see on the second picture that the cps and fps are at near 0 for some seconds

**Comment by tupolov** [comment]
When I click on the pic links, I only get a 404 image

**Comment by tupolov** [comment]
Please use imgur instead

**Comment by tupolov** [comment]
Does this repro in SP?

**Comment by shukari** [comment]
Sorry i was eating...
1. pictures now on imgur
2. repo is for singleplayer, hosted eden multiplayer and dedicated multiplayer

**Comment by shukari** [comment]
Execute if mission is running in dedicated server and you had requested the hunter this on server an local per debug console:
```
null = [] spawn {
	if (!isDedicated) exitWith {}; // Server
	testFrezze = false;
	uiSleep 2;
	testFrezze = true;
	server_fps_act = 0;
	server_fps_list = [];
	publicVariable "server_fps_list";
	
	while {testFrezze} do
	{
		private _fps = diag_fps;
		server_fps_act = _fps;
		server_fps_list pushBack _fps;
		publicVariable "server_fps_act";
		
		uiSleep 1;
	};
	
	publicVariable "server_fps_list";
	diag_log format ["server_fps_list: %1", server_fps_list];
};

null = [] spawn {
	if (isDedicated) exitWith {}; // Client
	testFrezze = false;
	uiSleep 2;
	testFrezze = true;
	
	while {testFrezze} do
	{
		hintSilent format ["ServerFPS: %1", server_fps_act];
		uiSleep 1;
	};
	
	waitUntil {!(server_fps_list isEqualTo [])};
	diag_log format ["server_fps_list: %1", server_fps_list];
};
```
You can see the on client that the server do nothing for some seconds (no new fps per sec in hint)
also here the fps array:
14:36:48 "server_fps_list: [46.2428,45.7143,[...],45.7143,**2.25098**,45.584,[...],45.584]"

**Comment by tupolov** [comment]
ok repro'd, appears to happen shortly before the vehicle is spawned

**Comment by tupolov** [comment]
Believe code is around here

https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/mil_logistics/fnc_ML.sqf#L4115

**Comment by tupolov** [comment]
Looks like it happens on Altis but not on Stratis. Believe it is related to ALiVE_fnc_getPositionDistancePlayers

**Comment by shukari** [comment]
Yes, i debugged it and it needs 6sec
`10:39:02 "[PERFORMANCE] ([[20995.3,19273],1600]) -> 6.57397 [1 von 1]"`

**Comment by tupolov** [comment]
Great thanks for the update. We are looking into it.

**Comment by shukari** [comment]
Problem is ALIVE_fnc_sectorSortDistance!

11:11:27 "[PERFORMANCE] ([[20995.3,19273],1600]) -> 0 [after ALIVE_fnc_sectorGrid]"
11:11:34 "[PERFORMANCE] ([[20995.3,19273],1600]) -> 6.60898 [after ALIVE_fnc_sectorSortDistance]"
11:11:34 "[PERFORMANCE] ([[20995.3,19273],1600]) -> 6.61398 [after loop]"
11:11:34 "[PERFORMANCE] ([[20995.3,19273],1600]) -> 6.61398 [end]"

**Comment by tupolov** [comment]
You the man.

**Comment by shukari** [comment]
Fork the github, than rewrite the makepbo bat and than build a own alive build...

So... in my repo mission ALIVE_fnc_sectorSortDistance has following times:
```
14:08:09 "[PERFORMANCE2] (961) -> 0 [before ASSERT_TRUE checks]"
14:08:14 "[PERFORMANCE2] (961) -> 5.049 [after ASSERT_TRUE checks]"
14:08:14 "[PERFORMANCE2] (961) -> 5.049 [before ALIVE_fnc_shellSort]"
14:08:16 "[PERFORMANCE2] (961) -> 6.72699 [after ALIVE_fnc_shellSort]"
14:08:16 "[PERFORMANCE2] (961) -> 6.72699 [before own_fnc]"
14:08:16 "[PERFORMANCE2] (961) -> 6.787 [after own_fnc]"
```

You see that alone that ASSERT_TRUE checks need 5sec and the shellsort again 1.7sec... my own function need for 961 sectors only 0,06001sec also for short sector arrays like here with 8:
```
14:07:24 "[PERFORMANCE2] (8) -> 0 [before ASSERT_TRUE checks]"
14:07:24 "[PERFORMANCE2] (8) -> 0.0240021 [after ASSERT_TRUE checks]"
14:07:24 "[PERFORMANCE2] (8) -> 0.0240021 [before ALIVE_fnc_shellSort]"
14:07:24 "[PERFORMANCE2] (8) -> 0.0300064 [after ALIVE_fnc_shellSort]"
14:07:24 "[PERFORMANCE2] (8) -> 0.0300064 [before own_fnc]"
14:07:24 "[PERFORMANCE2] (8) -> 0.0300064 [after own_fnc]"
14:07:25 "########"
14:07:25 "Original distance : 772.068"
14:07:25 "own distance      : 772.068"
```

I will do an Pullrequest with my changes...

**Comment by tupolov** [comment]
wow! Thank you

**Comment by tupolov** [comment]
What is up with ASSERT_TRUE, that's a CBA macro...

**Comment by shukari** [comment]
i dont know ^^ its need 5secs time for something ^^

**Comment by tupolov** [comment]
https://github.com/CBATeam/CBA_A3/blob/70336ffd3788acb38fec917e064a819fa6e25c23/addons/main/script_macros_common.hpp#L1331

Does it really take 5 seconds to check to see if the type is ARRAY? Man that is crazy.

**Comment by tupolov** [comment]
I could understand it if it was an issue with getDistance or shellsort.
