### ISSUE TITLE
[logistic] "Airlift: Air insertion via helicopter or vtol" is broken for certain vehicles (i.e. heavy cars)

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#150]
Repo Mission: https://workupload.com/file/3SQNXhW
RPT: https://workupload.com/file/KGZ7hFN
On: Singleplayer
Steps:
1. player addItem "Alive_Tablet"
2. alive menu -> commander -> logistic
3. choose the second option "Airlift: Air insertion via helicopter or vtol"
4. choose a hunter as supply
5. a helicopter comes WITHOUT the hunter, the hunter still stand on the startposition of the heli
6. the heli hovers
7. the heli land, but why he has no troops to unload..
8. after that he get that he has nothing for unload he flies away

**Attention only some vehicles are not working. The Ghosthawk transports everything but the ghosthawk CANT slingload all hunter variants!**

**Comment by tupolov** [comment]
If the helo can't lift the items requested, it should be delivered by road. :(

**Comment by shukari** [comment]
No, the vehicle stand alone on the startpoint.
The NATO or BLU_F hast the Huron... and that heli can lift hunters!

**Comment by tupolov** [comment]
Yah expectation is the Huron should lift that to resupply.

**Comment by tupolov** [comment]
looks like hunter gets delivered by parachute... but helo still shows up. Weird.

**Comment by tupolov** [comment]
Ok, so looks like there's a mismatch with our getObjectWeight calculation and the Hunter/Ifrit :( This is because we cannot get mass from config.. only from an already spawned object...
