### ISSUE TITLE
[logistic] some entries are multiple times in the selection

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#151]
Its useless to have multiply entries because you dont know if this is the NATO or CTRG vehicle and at the end it is the same.

Alive menu -> commander -> logistic -> airlift 2nd -> vehicles -> car
hunter variants -> 2x in the list
offroad -> 3x
quad -> 4x

Alive menu -> commander -> logistic -> airlift 2nd -> vehicles -> air
Speedboat with minigun -> 2x
rescueboat -> 3x
normal boat -> 3x

Alive menu -> commander -> logistic -> convoy -> vehicles -> armored
everything -> 2x

**Comment by marceldev89** [comment]
I don't think it's a good idea to hide vehicles with duplicate names. Perhaps adding a faction suffix to the names (e.g. `offroad [BLU_F]`)?

**Comment by shukari** [comment]
But these vehicles are all the same... so why 100 variants... then you also need all colors for every vehicle ^^
I request this vehicles for a fight not for a dinner party :P

**Comment by SpyderBlack723** [comment]
Because it's possible that while they all have the same display name, they have individualistic qualities such as camo etc.

**Comment by shukari** [comment]
Only the camo on some rare vehicles... and for example Hunter NATO and CTRG had no differences... nothing...

**Comment by marceldev89** [comment]
We also have to think about all the mods in existence, they might have the same fancy names for different vehicles. Filtering based on names isn't the way to go.

**Comment by shukari** [comment]
Hmm ok...

**Comment by marceldev89** [comment]
Went with a tooltip showing the classname, don't think there is a reliable/easy way to associate things from `CfgVehicles` with factions. https://i.imgur.com/3Z2kFKM.png

**Comment by HeroesandvillainsOS** [comment]
Good call Marceldev89! Lol at the dinner party comment :)
