### ISSUE TITLE
ORBAT Creator errors out when inheriting classes that do not contain Eventhandlers.CBA_Extended_EventHandlers_base

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#153]
So I have a custom faction created and when trying to launch Arma 3 it will not let me past the following  error. I have tried going through the config.cpp myself and adding in the correct codes in the area it was missing to define the class but it still isn't working. If someone can give me a boost that sure would help.

File shg_pla\confg.cpp, line 2282:
/CfgVehicles/O_SHGPLA_SHG_PLA_Truck_Refuel.Turrets: Undefined base class 'Turrets'

Here is the faction file to download. It uses ACE, Massi PLA, VME PLA
https://www.dropbox.com/s/ol7qaxv4iya8ikg/%40shgPLA.zip?dl=0

**Comment by SpyderBlack723** [comment]
Thanks for the report.

Think it might be relating to vehicles that have no turrets. Looking into it.

**Comment by SpyderBlack723** [comment]
Sorry to keep tossing build after build to you, but this should fix your issue

https://www.dropbox.com/s/9ht94eopjuk8b4z/ALIVE_ORBAT_CREATOR_TESTBUILD.RAR?dl=0

To manually fix the code you've already generated, remove all instances of
```
class Turrets : Turrets {
};
```
Where there is nothing between those curly braces

**Comment by coachwn** [comment]
No problem. I am going to give that a shot when I get home from work.

**Comment by SpyderBlack723** [comment]
Actually, I just went ahead and did it already
Here is the revised config.cpp

https://gist.github.com/SpyderBlack723/5af133cfe3d9d8ca4ded896aa4ad5aa9

**Comment by coachwn** [comment]
Now getting error as follows:

File shg_pla\config.cpp, line 2283:
/CfgVehicles/O_SHGPLA_SHG_PLA_Truck_Refuel/EventHandlers.CBA_Extended_EventHandlers: Undefined base class
'CBA_Extended_EventHandlers_base'

**Comment by coachwn** [comment]
We have a code guy here in Spearhead Gaming that is working on this to help out as well.

**Comment by SpyderBlack723** [comment]
Pretty sure my method of providing CBA event handlers compatibility is wrong anyway, will need to take a look at their documentation. Assuming your code guy knows how, he can just remove any of the CBA_Extended_EventHandlers from the classes that error out.

**Comment by coachwn** [comment]
OK removing them from the class that has the problem works. However none of my AI groups are wearing helments now and the helmets are being called for in the class name of the individual units...any ideas?

**Comment by SpyderBlack723** [comment]
Unfortunately, headgear in A3 is restricted to certain factions....

Nothing I can do about it other than add a completely new headgear class for each unit wearing a restricted headgear piece (Which adds a whole lot of clutter and extra complexity)

**Comment by SpyderBlack723** [comment]
Fixed with 5d139404c6627d2a4cca32970be6a5f8c798f6a4
