### ISSUE TITLE
Server hang/crash on IED creation

### ISSUE THREAD

**Issue by ShizCalev** [ALiVEOS/ALiVE.OS#156]
**Repo mission:** [OOP_ICARUS_PART_5.pja310.pbo.zip](https://github.com/ALiVEOS/ALiVE.OS/files/582292/OOP_ICARUS_PART_5.pja310.pbo.zip)
**Enviroment:** Multiplayer w/ HC
**RPT:** http://pastebin.com/M7X8y70e

**Steps:**  

Was pushing into Nahlaya in technicals from the road out of Armanaz.

**Errors:** 

23:34:31 Error in expression < !(!_insideOnly && _in)) then {
_result pushback _x;

};
} forEach _obj_array;
}>
23:34:31   Error position: <pushback _x;

};
} forEach _obj_array;
}>
23:34:31   Error Max array size would be reached. Current size: 9999999, wanted size: 10000000.
23:34:31 File x\alive\addons\x_lib\functions\markers\fnc_validateLocations.sqf, line 49
23:34:31 Error in expression < !(!_insideOnly && _in)) then {
_result pushback _x;

};
} forEach _obj_array;
}>
23:34:31   Error position: <pushback _x;

};
} forEach _obj_array;
}>
23:34:31   Error Max array size would be reached. Current size: 9999999, wanted size: 10000000.
23:34:31 File x\alive\addons\x_lib\functions\markers\fnc_validateLocations.sqf, line 49
23:34:31 Error in expression < !(!_insideOnly && _in)) then {
_result pushback _x;

};
} forEach _obj_array;
}>
23:34:31   Error position: <pushback _x;

};
} forEach _obj_array;
}>
23:34:31   Error Max array size would be reached. Current size: 9999999, wanted size: 10000000.
23:34:31 File x\alive\addons\x_lib\functions\markers\fnc_validateLocations.sqf, line 49

______________________
**&** 

0:38:02 "ALIVE-5347.11 IED: creating 5 IEDs at Nahlaya (107163) - size 250"

was the last error that triggered when the server died.

**Comment by SpyderBlack723** [comment]
```
23:34:31 Error Max array size would be reached. Current size: 9999999, wanted size: 10000000.
23:34:31 File x\alive\addons\x_lib\functions\markers\fnc_validateLocations.sqf, line 49
23:34:31 Error in expression < !(!_insideOnly && _in)) then {
_result pushback _x;

};
} forEach _obj_array;
}>
23:34:31 Error position: <pushback _x;

};
} forEach _obj_array;
}>
23:34:31 Error Max array size would be reached. Current size: 9999999, wanted size: 10000000.
23:34:31 File x\alive\addons\x_lib\functions\markers\fnc_validateLocations.sqf, line 49
```

Seems to be the more likely culprit

**Comment by tupolov** [comment]
Looks like IED module calls validateLocations

https://github.com/ALiVEOS/ALiVE.OS/blob/07b352a5b67184ebe6775f56ba10018bb935a4be/addons/mil_ied/fnc_IED.sqf#L266

Need to check to see why this leads to excessive size of array. Were any TAOR or BLACKLIST markers set?

**Comment by tupolov** [comment]
Can we get a non-pbo, non-binarized repro mission?

**Comment by coachwn** [comment]
Going to keep an eye on this one as well. We might be having similar issues with our server.

**Comment by ShizCalev** [comment]
[OOP_ICARUS_PART_5.pja310.zip](https://github.com/ALiVEOS/ALiVE.OS/files/652595/OOP_ICARUS_PART_5.pja310.zip)

**Comment by ShizCalev** [comment]
[OOP_ICARUS_PART_5.pja310.zip](https://github.com/ALiVEOS/ALiVE.OS/files/652615/OOP_ICARUS_PART_5.pja310.zip)

**Comment by tupolov** [comment]
I don't see the mil_ied module placed in your mission?

**Comment by DarrellJMartin** [comment]
ShizCalev, Tyour provided mission has not got the ALiVE mil_ied module placed, the opcom module 'control type' is set to 'occupation' so there is no way IED's can spawn. Please post a mission without addons other than cba_a3 and ALiVE in future. Thank you.

Cannot reproduce at this time.
