### ISSUE TITLE
ALiVE 1.2.1.1611081 and ACE 3.8.1 and AECX 3.1.1 Do not Update WarRoom Stats

### ISSUE THREAD

**Issue by obsv** [ALiVEOS/ALiVE.OS#157]
Issues:
1.  Stats are not updating to ALiVE WarRoom while using ACE.  It appears as though the ace_medical_lastDamageSource EH is not being picked up by ALiVE WarRoom.  ACEX used with special description.ext to track killed events.  Profile KIA showing on map after unit bleedout.
2.  Shots fired is not updating in ALiVE WarRoom while using ACE.
3.  User exit not logged to ALiVE WarRoom on server save and exit when using ACE.  Works as expected without ACE in repro mission below.  Mission data saved as expected for the ACE mission and reloaded in follow on mission.

Mods:
ALiVE 1.2.1.1611081.
ACE 3.8.1
ACEX 3.1.1
CBA 3.1.2
ASRAI 0.9.34

Tested on local dedicated server with and without ACE.  Kill tracking worked as expected without ACE.  Mission exit worked as expected without ACE.  Shots fired updated without ACE.  I did not look at any other stats.

Testing performed in VR.  I did receive a StaticData.sqf script error running the test mission.  I did have 3D Eden Enhanced on the client during the NO ACE test.

Local and server RPT files included for reference.

[Repro_Test_Missions.zip](https://github.com/ALiVEOS/ALiVE.OS/files/582422/Repro_Test_Missions.zip)
[arma3_client_rpt.zip](https://github.com/ALiVEOS/ALiVE.OS/files/582470/arma3_client_rpt.zip)
[arma3server_rpt.zip](https://github.com/ALiVEOS/ALiVE.OS/files/582471/arma3server_rpt.zip)

**Comment by tupolov** [comment]
Thanks for the report

**Comment by tupolov** [comment]
Tested and working.
