### ISSUE TITLE
BCR Logistics (faction only) use vanilla vehicle and driver

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#162]
Unsure if this is a bug or a necessity for BCR replacements. Setting the option to faction only, BCR transport vehicles default to side and use a vanilla driver.

The modded faction I'm using doesn't have a large transport vehicle. I'm assuming this is why it defaults to side? If that's the case, I feel like the driver of the transport vehicle should belong to the faction.

If that's not the case, and the system is supposed to pull any non-combat vehicle from the faction, then it currently isn't working as intended (the faction I'm using has plenty of non-combat trucks).

**Comment by tupolov** [comment]
Which faction are you using?

**Comment by HeroesandvillainsOS** [comment]
LOP_ISTS the independent version from the new test release

**Comment by HeroesandvillainsOS** [comment]
Sorry. Not enough info there. Project OPFOR. ISIS faction.

**Comment by tupolov** [comment]
LOP_ISTS isn't defined as a custom faction, so it will revert to vanilla vehicles and drivers.

You need to do the following:

```
if(isServer) then {
 
	// -------------------------------------------------------------------------------------------------------------
	// override default data 
	// see script/staticData.sqf
	["MISSION INIT - Waiting"] call ALIVE_fnc_dump;
 
	waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};
 
	["MISSION INIT - Continue"] call ALIVE_fnc_dump;
 
	// override static data settings
       [ALIVE_factionDefaultTransport, "LOP_ISTS", ["my_faction_truck_classname1","my_faction_truck_classname2", etc]] call ALIVE_fnc_hashSet;
 
	["MISSION INIT - Static data override loaded"] call ALIVE_fnc_dump;
	// -------------------------------------------------------------------------------------------------------------
 
};
```

**Comment by HeroesandvillainsOS** [comment]
Awesome! Thanks!

Keeway is looking to get this mod updated, seeing as the version is a test for the community and ALiVE compatibility seems to be important to him and Leight.

Is there anything on their end they can do to organically make it compatible or would these need to be done on your end?

**Comment by HeroesandvillainsOS** [comment]
Oh. Are there any prerequisites for vehicle passenger capacity for BCR replacements or can I just plug in any vehicle of my choosing?

They have some covered landrover type vehicles and stuff which only would hold 4-5 passengers or so. Can I use those or should they be in the spirit of the vanilla Zamak?

**Comment by SpyderBlack723** [comment]
Yes, they can add support on their end, I'll add the details in the morning as long as I remember (if not, ping me).

They need to be big enough to hold a standard infantry group. I would recommend opening the faction in the ORBATerer and checking out the Support category of that faction and noting the peak group size.

**Comment by HeroesandvillainsOS** [comment]
Thanks @Spyderblack723 

Ping! :)

When you say large enough to hold a standard infantry group, I'm assuming you mean I need to include a vehicle large enough to hold the largest group (assuming I want the largest group to keep spawning), correct?

They range from 2-8. So I take it to get the 8 man guys I'd need a vehicle that holds 9. Not sure if they have one. I'll check ORBAT and the available vehicles in the editor later. And thanks for the reply.

**Comment by SpyderBlack723** [comment]
This is what mod authors need to add to have automatic compatibility with mil logistics

**config.cpp**
```
class Extended_PreInit_EventHandlers {
    class modname_componentname_ALiVE_staticData {
        init = "execVM 'staticData.sqf'";
    };
};
```

**staticData.sqf**
```
if(isServer) then {
    if (isclass (configFile >> "CfgVehicles" >> "ALiVE_require")) then {
        if (["ALiVE_require"] call ALiVE_fnc_isModuleAvailable) then {

            waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};

            private _yourFactionClassname = "";

            // Mil logistics convoy transport vehicles per faction

           [ALIVE_factionDefaultTransport, _yourFactionClassname, ["O_Truck_02_transport_F","O_Truck_02_covered_F"]] call ALIVE_fnc_hashSet;

           // Mil logistics air transport vehicles per faction

           [ALIVE_factionDefaultAirTransport, _yourFactionClassname, ["O_Heli_Transport_04_F","O_Heli_Transport_04_box_F"]] call ALIVE_fnc_hashSet;

           // Mil logistics airdrop containers per faction

           [ALIVE_factionDefaultContainers, _yourFactionClassname, ["ALIVE_O_supplyCrate_F","O_CargoNet_01_ammo_F"]] call ALIVE_fnc_hashSet;

        };
    };
};
```

**Comment by HeroesandvillainsOS** [comment]
Awesome. I've sent a link to this thread to someone that will get it to Keeway from Project OPFOR. Thanks Spyder.

**Comment by HeroesandvillainsOS** [comment]
@Tupolov that file works perfectly as a temporary solution. Thanks.

To either of you. Generally speaking, should these vehicles be non-combat? What do most of the factions you guys see, vanilla or otherwise, use for resupply? Should it be transport vehicles only or do they ever have mounted weapons or use APC's or any of that?

**Comment by SpyderBlack723** [comment]
Doesn't really matter, they'll perform their job as transport and any weapons they carry with just help with self-defense if needed.
