### ISSUE TITLE
Sabotage mission on a undestroyable house

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#166]
I get the mission to destroy the "Land_dp_smallFactory_F" house... i tried in zeus everything... satchel charge normal charge... 155mm artillery... every zeus jet cas attack... every mine... nothing... everything around was dead... but this house had no scratch ^^

**Comment by HeroesandvillainsOS** [comment]
If you want to continue adding to the list, feel free to merge with #45

**Comment by highhead** [comment]
fixed in dev
