### ISSUE TITLE
Possible bug with ORBAT Creator exporter function

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#167]
Guys we just found what was wrong with my faction not showing up in the editor. It was brought to my attention that the ORBAT creator did not spit out a }; in the CfgPatches portion. It was exported as this:

class CfgPatches {
    class SHG_PLA {
        units[] = {
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
         "A3_Characters_F",
         "A3_VME_PLA_Men"
        };
        author = "Nichols";
        authors[] = { "Nichols" };

But now it works because I have it as this thanks to a member of our community over at Spearhead Gaming...Jmaster:

class CfgPatches {
    class SHG_PLA {
        units[] = {};
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
         "A3_Characters_F",
         "A3_VME_PLA_Men"
        };
        author = "Nichols";
        authors[] = { "Nichols" };

**Comment by SpyderBlack723** [comment]
I cannot reproducr, it exports just fine. Are you sure it didn't get chopped off by accident when copy&pasting? If you could send your Rpt from a session where this occurs it would help.

**Comment by coachwn** [comment]
I can look for that but I think that rpt was from last week. I am working on a revamp of that mission and will try to reproduce again.

**Comment by coachwn** [comment]
Export was good but still getting the same issue again. No idea why...closing till I can get some more concrete information.
