### ISSUE TITLE
Vehicle(s) disappear from the CS tablet

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#170]
Sometimes, vehicles disappear from the CS tablet under the transport list.

Reference: http://alivemod.com/forum/2523-combat-support-on-local-vs-dedicated

**Comment by marceldev89** [comment]
Should probably also take a look at #108.

**Comment by friznit** [comment]
Unable to repro this.  If you can get a reliable repro please post steps and we can look into it.

**Comment by HeroesandvillainsOS** [comment]
I'm encountering some problems here and am having a hell of a time with a repro. I'll get it though. I hope.

I can definitely provide a mission with this problem, but yeah, mods. I've been slowly working my way up from ALiVE/CBA, one by one with other mods and haven't quite found the culprit or cause. I'm plugging away though.
