### ISSUE TITLE
Optional Folder

### ISSUE THREAD

**Issue by 00specter00** [ALiVEOS/ALiVE.OS#171]
Hi guys!

I would like to know, what are the pbo of the optional folder?

Thank you

**Comment by marceldev89** [comment]
#### Client & server
composition_apex.pbo => Compositions that require the A3: Apex dlc
composition_cup.pbo => Compositions that require the CUP terrains core/maps mods

#### Server
sys_data_auto.pbo => Automatically enables persistence
sys_data_auto_perfmon => Automatically enables performance monitoring
