### ISSUE TITLE
Integrate R3 AAR into War Room

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#172]

**Comment by friznit** [comment]
Static MG icons are not showing
Kill events seem to be quite sporadic or not showing in the feed on the right.

**Comment by friznit** [comment]
Combat Support transport helis continue to show all the mounted player names after players have dismounted

The data appears to "freeze" for 2 - 3 minutes in every 10, making the playback very spikey.

**Comment by friznit** [comment]
Light green colour for GREENFOR troops is very hard to make out against the green background of trees.  Need to use a darker colour.

**Comment by friznit** [comment]
@tupolov are there some changes still outstanding on this?

**Comment by tupolov** [comment]
Complete I believe!

@marceldev89 anymore updates from Titan?

**Comment by marceldev89** [comment]
I don't think there have been any major updates on Titan's side of things. As far as I'm concerned the "integration" is done but obviously there's still stuff that could use work.
