### ISSUE TITLE
Error in fnc_restore

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#173]
```
19:11:02 Error in expression <call ALIVE_fnc_restore];
_i = _i + 1;
} forEach _value;

;
};
default {
_data = >
19:11:02   Error position: <forEach _value;

;
};
default {
_data = >
19:11:02   Error foreach: Type String, expected Array
19:11:02 File x\alive\addons\sys_data_couchdb\fnc_restoreData.sqf, line 106
```

Full Rpt https://alivemod.slack.com/files/friznit/F35ECTD38/arma3server_2016-11-16_18-55-08.rpt

Plugin https://gist.github.com/friznit/912bea5d7bb840798a70c8279a84a245

**Comment by tupolov** [comment]
This is because you use [ ] in player names and sys_data incorrectly parses it as an ARRAY rather than a STRING

**Comment by tupolov** [comment]
The incorrect type is set the 2nd time a mission is saved :(

**Comment by tupolov** [comment]
parseJSON function currently uses [ to identify an ARRAY within a JSON formatted string. We currently do not support the following special chars [ ] { } , : in any names, mission names, text etc.

**Comment by friznit** [comment]
"Feature"

Closed.
