### ISSUE TITLE
Add a line to blacklist unit classnames for CQB module

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#175]
I don't know if this is possible..but adding a line in the CQB module to paste in the different classnames of units that we don't want to spawn in CQB (Pilots, Tank Crew, etc.) would be a nice addition.

**Comment by coachwn** [comment]
Yes this would be a great addition

**Comment by tupolov** [comment]
http://alivemod.com/wiki/index.php/Custom_Blacklists

?

**Comment by AUTigerGrad** [comment]
Thanks Tup.  Yeah I saw that, I just didn't know if it could be built directly into the module instead of having to create a staticdata file.

**Comment by AUTigerGrad** [comment]
FYI Tup, I used that custom blacklist code and placed it in the CQB module but I'm still seeing pilots and tank drivers spawning in CQB.  I tried using the code in the ALiVE Required module init, then I tried the CQB Init module.  Didn't work in either.

**Comment by marceldev89** [comment]
Is this still something that's wanted or are the custom blacklists good enough?
