### ISSUE TITLE
Map indexer crashes

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#177]
This issue is for tracking people having crashes when indexing terrains.

## Required info
**Version info:**
Windows version: `Windows 10 Pro`
.NET version(s): `4.6.2` (check with http://www.asoft.be/prod_netver.html)
Arma 3 version: `1.64`
ALiVE version: `1.2.2`
CBA_A3 version:  `3.1.2`
DeWrp version: `1.71.5.24` (right click `DeWrp.exe` -> Properties -> Details -> File version)

**Paths:**
Path to arma: `D:\Games\steamapps\common\Arma 3`
Path to terrain pbo: `D:\Games\steamapps\common\Arma 3\@mbg_celle2\addons\mbg_celle2.pbo`
Path to `@alive`: `D:\Games\steamapps\common\Arma 3\@alive`
Path to scripts: `C:\Users\marcel\Documents\Arma 3\scripts`

**Misc:**
Arma profile name: `marceldev89`
Arma display mode: `window`
Source of terrain mod: `withSix`

**Data:**
zip of indexing folder (`@alive\indexing\pja312`):
link to RPT:

**Comment by Opendome** [comment]
Version info:
Windows version: Windows 10 Pro
.NET version(s): 4.6.2 (check with http://www.asoft.be/prod_netver.html) The link didnt work but acccording to this my version is 4.6.2
Arma 3 version: 1.64
ALiVE version: 1.2.2
CBA_A3 version: 3.1.2
DeWrp version: 1.71.5.24 (right click DeWrp.exe -> Properties -> Details -> File version)

Paths:
Path to arma: D:\SteamLibrary\steamapps\common\Arma 3
Path to map pbo: D:\SteamLibrary\steamapps\common\Arma 3\@SongBinTahnV06\Addons\projeta3012.pbo
Path to @alive: D:\SteamLibrary\steamapps\common\Arma 3\@ALiVE
Path to scripts: C:\Users\J\Documents\Arma 3\scripts as well as C:\Users\J\Documents\Arma 3 - Other Profiles\Foxhound\scripts

Misc:
Arma profile name: Foxhound
Source of terrain mod: Armaholic

**Comment by marceldev89** [comment]
@Opendome I've added 2 items to the list (zip of indexing folder and rpt), can you do that as well? :)

**Comment by Opendome** [comment]
for sure Ill edit my post to include em

**Comment by tupolov** [comment]
check those paths too

**Comment by Opendome** [comment]
Links updated! Paths double checked and directly copied from explorer location too

**Comment by Opendome** [comment]
does anything jump out at ya?

**Comment by marceldev89** [comment]
Nope, object files are empty and nothing obvious so far. Waiting for more people to report in, maybe we can spot some pattern as to why this is happening.

**Comment by Opendome** [comment]
I hope so :( I reeeeally want to get this map indexed soon.

Thanks for doing this!

**Comment by marceldev89** [comment]
Hmm it seems that the piping the output of DeWrp.exe to the objects file isn't working.

Can you try running the bit below in cmd.exe and check the contents of `@ALiVE\indexing\pja312\x\alive\addons\fnc_strategic\indexes\objects.pja312.sqf`?
```
cmd.exe /c DeWrp.exe -O "D:\SteamLibrary\steamapps\common\Arma 3\@SongBinTahnV06\Addons\projeta3012.pbo" > "D:\SteamLibrary\steamapps\common\Arma 3\@ALiVE\indexing\pja312\x\alive\addons\fnc_strategic\indexes\objects.pja312.sqf"
```

**Comment by Opendome** [comment]
For sure! I have it running now and its doing its thing, how do I check the contents?

**Comment by marceldev89** [comment]
Notepad will do. :)

**Comment by Opendome** [comment]
ohhhh ok I think I got it, itll export it to objects.pja312.sqf right?

**Comment by Opendome** [comment]
lol if we got it working I would seriously cry lol

**Comment by tupolov** [comment]
you can manually create that file and the indexer should just carry on

**Comment by Opendome** [comment]
So Ive had it running for the last 25 minutes and its still going, should I just leave it? Initially it only took like 5 minutes

**Comment by Opendome** [comment]
it also appears its just doing the same thing over and over again

**Comment by Opendome** [comment]
Nm it just finished and says //No Error(s) press any key

**Comment by Opendome** [comment]
Should I upload the output to you now?

**Comment by tupolov** [comment]
yes, also try rerunning the indexer

**Comment by Opendome** [comment]
hmmm its empty?

**Comment by tupolov** [comment]
So dewrp isn't working?

**Comment by Opendome** [comment]
like it seems to work, I see it doing stuff and it says their arent any errors, but when I go and look at the file it says its empty

**Comment by Opendome** [comment]
dewrps being run as admin and this is what the permissions look like for it http://i.imgur.com/rrsqhmW.png

**Comment by marceldev89** [comment]
@Opendome just to confirm, when you run the command I posted above, does it show a bunch of positions and p3d names in the cmd.exe window? If so, that's the reason it's failing. You shouldn't be seeing the output. The only thing that you should see in the cmd.exe window is:
```
DeWrp x64UnicodeVersion 1.71, Dll 5.24 "beketov_wrp.pbo"
No Error(s)

Press the ANY key
````
Try the following instead:
```
cmd.exe /c DeWrp.exe -O "D:\SteamLibrary\steamapps\common\Arma 3\@SongBinTahnV06\Addons\projeta3012.pbo > D:\SteamLibrary\steamapps\common\Arma 3\@ALiVE\indexing\pja312\x\alive\addons\fnc_strategic\indexes\objects.pja312.sqf"
```
I've also cleaned up some of the chatty posts, try to keep the chatter somewhat to a minimum. 👍

**Comment by marceldev89** [comment]
Alright, replace ALiVEClient.dll with https://dl.dropboxusercontent.com/u/38551057/ALiVEClient.dll and try to do an index. It _should_ fix the piping issue.

**Comment by marceldev89** [comment]
Awesome, I guess it's fixed now. 😄

The cycling through objects is intended, it basically loops through all the placed objects of that class. The attributes will stick until you click next.

**Comment by Opendome** [comment]
Ahhh ok thanks! The only thing is Im not sure what that hut looks like so Im not sure if I should allow it to be used as an HQ or not. Also any beginner tips for indexing? :P

**Comment by marceldev89** [comment]
http://alivemod.com/wiki/index.php/Map_Indexing should explain everything.

**Comment by marceldev89** [comment]
Closing this as it's seemingly fixed. :-)

**Comment by Opendome** [comment]
After trying to index (after assignign object attributes) I get a big red square that says

(fnc_strategic) Assertion Failed!
Assertion (count_master >0) failed
count_master:0
0:0
objects provided not valid
