### ISSUE TITLE
error on loading ORBAT creator in fn_arsenal.sqf

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#178]
When starting ORBAT creator I get the following text box that shows up on my screen. It does not stop me from working within the factions but it might create an issue. I am using the latest release version on the current stable build for A3.

Thanks

http://images.akamai.steamusercontent.com/ugc/197426156170433436/2DC56920693919464E682D7C7E292C45A8317E62/

**Comment by SpyderBlack723** [comment]
BIS error can't fix
