### ISSUE TITLE
AI Spawned by Military Defense Tasks don't Engage

### ISSUE THREAD

**Issue by ColonelCarston** [ALiVEOS/ALiVE.OS#179]
Enemies spawned by Military Defense Tasks won't engage targets, they won't react to being shot at, or even members of their squads dying. Their behavior seems in line with the default "Careless" AI Behavior.

From my testing, enemies spawned by the defense objective will act normally until they get the move order to the defense objective.

I've personally had this issue with the Syndikat and CSAT forces, across multiple maps (Lingor, Tanoa, and Stratis) , and different Commander types.

Steps to replicate:
1. Place down a player unit (Optionally disable damage)
2. Setup the basic modules (I followed the [quickstart](http://alivemod.com/wiki/index.php/Quickstart) for my testing scenario)
3. Place down a C2ISTAR module (I changed the item from LaserDesignator to ItemRadio)
4. Start the mission
5. Enable admin teleport and profile debugging (profile locations marked)
6. Generate a defense mission, preferably against a faction hostile to yours.
7. Teleport to the defense area to initiate the mission and have hostile forces spawn.
8. Teleport to the newly spawned hostiles, if you're quick enough, they might shoot at you for a few moments, otherwise they will jog to the objective and pay you no mind.
9. Feel free to shoot around or at the enemies, they won't mind. It's a nice day out!
10. If you wait long enough, you can watch friendly forces engage the enemies with the same results.

Overall, this makes the defense missions **really** boring, as its a bunch of waiting for a running shooting gallery to appear. And you better hope there aren't multiple waves, because it'll just be the same thing.

I didn't attach my .rpt as there weren't any errors related to ALiVE, but I can attach it at request. Additionally, I ran my tests with the most recent versions of CBA and ALiVE and no other mods.

Hope this all helps!

**Comment by coachwn** [comment]
Is the "enemy faction" set at any hostility level towards the "friendly" faction you are playing as? If not that would be part of the issue.

**Comment by ColonelCarston** [comment]
Yes. I've tested it with BLUFOR vs. GREENFOR and BLUFOR vs OPFOR and it's the same result either way. In addition, as I stated above, you can watch friendly forces engage the enemy forces moving to the objective, meaning that the AI definitely consider each other hostile.

To me, it looks like somewhere along the line the AI behavior is being set to careless.

**Comment by tupolov** [comment]
'''profileWaypoint = [_position, 100, "MOVE", "FULL", 100, [], "LINE", "NO CHANGE", "CARELESS"] call ALIVE_fnc_createProfileWaypoint;'''

**Comment by ColonelCarston** [comment]
That seems to confirm my theory.

Is this behavior intentional then? Is it going to be fixed?

**Comment by SpyderBlack723** [comment]
I don't see any benefit of careless over safe mode just needs to be switched.

**Comment by highhead** [comment]
switched and done
