### ISSUE TITLE
Mod Won't load on dedicated server

### ISSUE THREAD

**Issue by cuatristapr** [ALiVEOS/ALiVE.OS#181]
Whenever I try loading the new version, it doesn't work. If I try version 1.2, it works. RPT log below:

RPT Log using only ALiVE and CBA3.2

=====================================================================
== C:\TCAFiles\Users\ChristopherA\21960\arma3server.exe
== "C:\TCAFiles\Users\ChristopherA\21960\arma3server.exe" -ip=63.143.38.134 -port=2327 -noPause -noSound "-cfg=A3DS\basic.cfg" -ranking="" -par="" "-config=A3DS\server.cfg" "-profiles=A3DS" "-servermod=" "-mod=@CBA3.2;@ALiVEnuevo;" -world=empty -maxMem=6144

Original output filename: Arma3Retail_Server
Exe timestamp: 2016/10/07 16:49:20
Current time: 2016/11/29 07:53:55

Type: Public
Build: Stable
Version: 1.64.138732

Allocator: C:\TCAFiles\Users\ChristopherA\21960\dll\tbb4malloc_bi.dll

7:53:55 SteamAPI initialization failed. Steam features wont's be accessible!
7:53:55 String STR_MOD_LAUNCHER_ACTION not found
7:53:55 Initializing stats manager.
7:53:55 Stats config disabled.
7:53:55 sessionID: c207594986d68679feb029a327f7dc1e5bcb4ac0
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 LZW overflow
7:54:18 Error decoding stringtable.xml from x\alive\addons\main\
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 Unsupported language English in stringtable
7:54:18 LZW overflow
7:54:18 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:18 LZW overflow
7:54:18 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:18 LZW overflow
7:54:18 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:18 LZW overflow
7:54:18 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:18 LZW overflow
7:54:18 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding script_mod.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding script_component.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding mod.cpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding Eventhandlers.hpp from x\alive\addons\main\
7:54:19 LZW overflow
7:54:19 Error decoding data\ui\main.hpp from x\alive\addons\main\
7:54:19 Error context author = MODULE_AUTHOR;
ErrorMessage: File x\alive\addons\main\CfgPatches.hpp, line 9: '/CfgPatches/ADDON.VERSION_CONFIG': ';' encountered instead of '='

**Comment by tupolov** [comment]
Tested on my dedi and cannot repro. I suspect Arma is not finding CBA.
