### ISSUE TITLE
Scripterror fnc_getCompositions.sqf

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#186]
```
16:25:26 C2ISTAR - No enterable buildings found for sabotage task! Defaulting to random house within 500m
16:25:26 C2ISTAR - Task SabotageBuilding - There are no buildings to attack at the target area!
16:25:40 Error in expression <elect _i; 

if (isClass _item && (count _cat == 0 || ({tolower(configName _item)>
16:25:40   Error position: <_cat == 0 || ({tolower(configName _item)>
16:25:40   Error Nicht definierte Variable in Ausdruck: _cat
16:25:40 File x\alive\addons\x_lib\functions\composition\fnc_getCompositions.sqf, line 126
```

FullRPT: https://gist.github.com/shukari/70cfdf84323c30a8bccb28be3857860e

Second time, again  suppose auto tasking...
Again in around 5min more than 100mb log. This is a havy bug... something can trash servers!

**Comment by tupolov** [comment]
https://github.com/ALiVEOS/ALiVE.OS/issues/180

**Comment by shukari** [comment]
Really fixed? It is an sabotage task...

**Comment by marceldev89** [comment]
It's the same error as in #180.  Seems like it falls back to compositions when it can't find any enterable buildings.

**Comment by tupolov** [comment]
Negative, sabotage doesn't use compositions.
