### ISSUE TITLE
ALiVE causes ArmA 3 to crash upon mission or editor loading.

### ISSUE THREAD

**Issue by alasdhairm** [ALiVEOS/ALiVE.OS#187]
After ArmA's 1.66 update, ALiVE is causing ArmA 3 to crash upon mission or editor loading, with or without any other mods. The error message is "The instruction at 0x1b3e0f4 referenced memory at 0xd0080000. The memory could not be written. Click on OK to terminate the program."

I'm running Windows 8.1 on an Asus G55VW with 24GB of ram, an Nvidia 660M, and an I7-3630QM. All of my drivers are up to date, and everything works perfectly without ALiVE.

The crash occurs on any and all missions, and when launching from Swifty, Steam, or the ArmA 3 Launcher.
Loading the editor also causes the crash, and about 1/5 of the time it crashes on menu loading. All of this results in the same error message listed above.

[basic.txt](https://github.com/ALiVEOS/ALiVE.OS/files/629828/basic.txt)
[arma3_2016-12-04_16-07-13.txt](https://github.com/ALiVEOS/ALiVE.OS/files/629829/arma3_2016-12-04_16-07-13.txt)
[arma3_2016-12-04_16-15-13.txt](https://github.com/ALiVEOS/ALiVE.OS/files/629830/arma3_2016-12-04_16-15-13.txt)
[arma3_2016-12-04_16-15-43.TXT](https://github.com/ALiVEOS/ALiVE.OS/files/629831/arma3_2016-12-04_16-15-43.TXT)

**Comment by tupolov** [comment]
Needs a repro. We're using ALiVE and not having any issues with CTD

**Comment by alasdhairm** [comment]
I know someone with the same rig and modpack that I have that is having the same problem

**Comment by alasdhairm** [comment]
And if I could upload a .zip, I'd give you the error log

**Comment by tupolov** [comment]
Please provide repro steps or example mission that is crashing.

**Comment by alasdhairm** [comment]
Any and all. Loading the editor causes a crash, and about 1/5 of the time it crashes on menu loading. All of this is with the same error message.

**Comment by SchwererKonigstiger** [comment]
**Reproduction Steps & Information**
With CBA (Current Release on Github) + ALiVE OS (Current Release on Github)
Launching into the game with ALiVE _enabled_ causes CTD with the following error:
`The instruction at 0x1b3e0f4 referenced memory at 0xd0080000`
Logs are provided with his original post.

This occurs at various times, whether instantly at boot, or upon launching into Eden or a MP server.
Seems to be related to the user's computer setup.
Both users having the issue have very similar computer builds.
Launching the game _without_ ALiVE enabled allows a normal boot and access to all regular features.

This error was not an issue with A3 v1.64. 

Repro missions can be [found here if required,](https://github.com/DeathDeliveryCorps/Operations/tree/master/Zeus%20Missions/AltisZeus.Altis) but they are just a blank mission with some ACRE/Zeus modules dropped down.

**Comment by tupolov** [comment]
Is there a repro mission with just CBA and ALiVE? no ACE or ACRE.

**Comment by tupolov** [comment]
Can you try removing the ALiVE_Client.dll and retesting.

**Comment by SchwererKonigstiger** [comment]
Then it would be a blank mission with a single soldier on it. There are no ALiVE modules on those templates.

**Comment by alasdhairm** [comment]
@tupolov Tried that, didn't work. I got the same error message on game loading.

**Comment by tupolov** [comment]
Looks like XEH_preInit doesn't finish. Hmmm

**Comment by alasdhairm** [comment]
What does that mean?

**Comment by coachwn** [comment]
Going to watch this one since I was having some crashes related to a mission as well.

**Comment by tupolov** [comment]
https://twitter.com/Arma3official/status/805761018014134273

**Comment by alasdhairm** [comment]
Just FYI, the ALiVE update hasn't fixed the issue. Hopefully the BI hotfix on wednesday will

**Comment by SchwererKonigstiger** [comment]
Apparently today's hotfix has not fixed the issue yet @tupolov

**Comment by nateberkopec** [comment]
Has everyone in this experiencing this issue [tried the steps on the BIS wiki for fixing access violations?](https://community.bistudio.com/wiki/Arma_3_Unusual_process_exit#0xC0000005_-_ACCESS_VIOLATION) I would also remove all launcher parameters.

**Comment by SchwererKonigstiger** [comment]
The basic steps have already been tried, and launcher Params were set to vanilla.

**Comment by coachwn** [comment]
Yep followed all aspects of the troubleshooting. I haven't played yet today with the hotfix but I am hearing the same rumbles about the problem not being fixed.

**Comment by alasdhairm** [comment]
If anyone's still paying attention, neither the 1.66 hotfix nor the 2.7mb patch solved the problem

**Comment by friznit** [comment]
Still paying attention....but we're completely unable to repro the problem and so we're rather at a loss as to how we can help you.  Fwiw, I have 50+ players using the latest ALiVE without issues on a dedi server.

**Comment by alasdhairm** [comment]
Would streaming a couple instances of the crash on Twitch tomorrow night be helpful?

**Comment by friznit** [comment]
Still not seeing this issue our end so I can only assume it's a local PC problem and not ALiVE related.  Let us know if you manage to figure it out!
