### ISSUE TITLE
Roadblocks spawn in blacklisted areas

### ISSUE THREAD

**Issue by nateberkopec** [ALiVEOS/ALiVE.OS#191]
If I place a civillian objective module w/a Occupation OPCOM and add a blacklist to that module, I would expect roadblocks to *not* spawn in the blacklisted markers. It seems like they currently do.

**Comment by SpyderBlack723** [comment]
Can you verify your blacklist is working correctly and then provide a repro mission. The code already filters out objectives that are outside of TAOR's and inside blacklists.

**Comment by nateberkopec** [comment]
Sure. Just so I understand correctly, how is spawning *supposed* to work at the edges of TAOR's? Are roadblocks or OPCOM AI (at least via the Civ Obj module) *ever* supposed to spawn outside of a TAOR?

**Comment by SpyderBlack723** [comment]
TAOR's and Blacklists simply filter out objective centers. If the center of an objective is covered by a blacklist, that objective is removed from placement (same process for TAOR if the objective is inside it).

**Comment by nateberkopec** [comment]
Alright cool, I understood correctly. There's no active objective anywhere near where these roadblocks are spawning, so I'll provide a repro mission.

**Comment by nateberkopec** [comment]
[blacklistREPRO.Tanoa.zip](https://github.com/ALiVEOS/ALiVE.OS/files/637321/blacklistREPRO.Tanoa.zip)

Here ya go. Try the mission a few times, eventually a roadblock will spawn on the road you're facing, which is in a blacklisted marker.

I fully concede I may just not completely understand how blacklists work here.

**Comment by nateberkopec** [comment]
As an update, I rearranged the TAORs and things seem to be working as expected now - I think I may have just hit a bad edge case in the test mission above. It seems like roadblocks spawn at the edge of civillian objectives, but in the mission above the way the edge of the civ objectives line up with the TAORs/blacklists may be causing problems.
