### ISSUE TITLE
Add composition environment setting to index data

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#192]
Ok so we need to add environment tags to those islands in the static data...

Example:
https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/main/static/tanoa_staticData.sqf#L25

Values are Desert, Woodland, Pacific, Urban

Desert = A2 desert assets (CUP)
Woodland = A2 woodland assets (CUP)
Pacific = APEX assets
Urban = Arma 3 assets

Feel free to submit PR for all the maps ;)

http://alivemod.com/forum/conversation/post/16485

**Comment by friznit** [comment]
1. Add environment tags

`ALiVE_mapCompositionType = "Desert";`
`ALiVE_mapCompositionType = "Woodland";`
`ALiVE_mapCompositionType = "Pacific";`
`ALiVE_mapCompositionType = "Urban";`

- [ ] abramia
- [ ] beketov
- [ ] bozcaada
- [ ] dakrong
- [ ] dya (Diyala)
- [ ] noe (Nogova)
- [ ] panthera3
- [ ] pja305 (N'Ziwasogo)
- [ ] pja307 (Dariyah)
- [ ] pja308 (Gunkizli)
- [ ] pja310 (Al Rayak)
- [ ] saru (Sarugao)
- [ ] sugarlake
- [ ] tanoa
- [ ] taviana (Taviana A3)

2.  Split all map staticdata except default/IF from maps.hpp into own files (And add enviro tags)

Default (Altis, Stratis, Koplic, Wamako, Imrali, Wake, Gorgona)
Iron Front maps

- [ ] Esseker
- [ ] Mogadishu, Nam (Pandora)
- [ ] Kunduz
- [ ] Hindu Kush
- [ ] Bornholm
- [ ] Isla Duala
- [ ] Lingor
- [ ] Fallujah
- [ ] everon2014
- [ ] Namalsk
- [ ] smd sahrani a3
- [ ] SMD Sahrani (& variants)
- [ ] Thirsk & ThirskW
- [ ] Chernarus; Chernarus Summer; Sturko; Tavi
- [ ] Chernarus Winter
- [ ] Helvantis
- [ ] Podagorsk
- [ ] Celle2
- [ ] Shapur
- [ ] Takistan
- [ ] Zargabad
- [ ] CLAfghan
- [ ] Hazarkot
- [ ] Isola Di Capraia; napf
- [ ] Caribou
- [ ] Tigeria
- [ ] Fata
- [ ] Afghan Village
- [ ] Sangin (hellskitchen)
- [ ] Torabora
- [ ] Qom
- [ ] Utes
- [ ] Kalu Khan
- [ ] Reshmaan
- [ ] Aliabad
- [ ] Bystrica
- [ ] Bukovina
- [ ] Australia
- [ ] MSKE
- [ ] Kunar
- [ ] Kapaulio

**Comment by tupolov** [comment]
Just a note. 

CUP maps should use either Woodland or Desert as these compositions are made from CUP objects.

Maps made for A3 using vanilla A3 objects should use Urban.

Maps made for A3 using Tanoa assets should use Pacific.

**Comment by Whigital** [comment]
For the second part of this task, is this what you meant:

https://github.com/Whigital/ALiVE.OS/tree/Move_from_Maps_to_staticData/addons/main/static

In that case, i'll clean up maps.hpp and do a PR .....

**Comment by friznit** [comment]
Nice work so far and yes, it makes it a lot easier to maintain if each map's data is in a separate file.  staticdata.sqf was getting too long to navigate!

**Comment by Whigital** [comment]
@friznit / @tupolov 

shouldn't `ALiVE_mapCompositionType = "Urban";` be added for the default maps in Maps.hpp , or set somewhere else ?

https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/main/static/Maps.hpp#L60

Does the IF maps need a tag too ?
