### ISSUE TITLE
Hostage Rescue hostage doesn't get out of ambient animation

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#194]
I attempted this mission a few times last night. In all instances, the hostage joins the player group and audibly responds to commands, but doesn't get out of his kneeling-with-hands-tied ambient animation. I tested this on a dedicated server, though this was with mods (3CB was the player faction).

I'm more than happy to provide more information and/or provide any rpts in a vanilla situation if needed.

**Comment by HeroesandvillainsOS** [comment]
@Tupolov So I'm trying to duplicate this with a very simple test mission on Stratis, utilizing some of the features I was using in my "real" mission last night which prompted me to open the ticket (assymetric enemy, persistence enabled, etc). However, I'm stumbling on a slight issue even getting started with the repro. Half a dozens test with this in just SP and the action to free the NATO hostage never appears on-screen when I get close to him: https://www.dropbox.com/s/oprw1kfchee4tey/test.Stratis.pbo?dl=0

This did not happen to me yesterday during my "real" modded mission yesterday. The action always showed up. I don't think I'd be missing any necessary features with this repro. I've also verified my game files through Steam which didn't help. Maybe today's hotfix broke the function or did I miss something?

Requires just ALiVE and CBA.

**Comment by highhead** [comment]
i can confirm this. 

As a fix I suggest 2 things:

a. fix in mission.
b. add switchMove "" and enableAI "MOVE" when adding/removing a unit to from a group with Commander Actions / Personell

**Comment by highhead** [comment]
done in dev. when the hostage joined the player group the locality was switched from server to the players group, breaking the upcoming AI commands which were still issued on server. now letting the ambient anims finish, reset them give it a sec and then joining player did the trick.
