### ISSUE TITLE
[Question] Virtualizing synced unit

### ISSUE THREAD

**Issue by mihal190** [ALiVEOS/ALiVE.OS#195]
My question is very simple, is there any chance to spawn a unit in building? i want to use snipers in tower on some missions, but 90% times alive ignore them or spawn in middle of the tower. im trying to virtualize unit that i placed in editor  but it allways spawn on ground any sugestions?

**Comment by coachwn** [comment]
Most times the units in ALiVE will climb into towers and onto rooftops automatically if they spawn nearby those types of places that they will have a way to climb up via stairs or ladders.

If you want to do it manually you have to spawn in a unit manually and then drag them up using the ALT key and place in the towers. It helps having Ares Achilles Expansion or regular Ares mod for the Zeus users.

**Comment by friznit** [comment]
If it's an individual unit (not a group) then it will spawn back in exactly where you placed it, assuming the object you are placing the unit on is not a simpleobject and has a suitable location for the game to put the AI.  Note that The Virtual AI Commander may take possesion of any profiles from his side and move them as well.

It is possible to manipulate virtual AI profiles via script using the profile id, allowing you to define where they spawn and to prevent the AI Commander tasking them.

First you need to get the profile id:
`private _profile = [ALIVE_profileHandler, "getProfile",_profileID] call ALIVE_fnc_profileHandler;`

Then you can set the position (chance _this to your x,y,z position)
`[_profile, "despawnPosition",position _this] call ALIVE_fnc_profileEntity;`

Setting a profile to "busy" will prevent the AI Commander from giving it orders
`[_profile, "busy",true] call ALIVE_fnc_profileEntity;`
