### ISSUE TITLE
New Feature Request:  Selective Virtualization of Non-Virtualized units after mission start.

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#199]
I'd like to request...if possible..the ability to virtualize units after mission start WITHOUT profiling every single unit in the game.

A prime example of why this would be useful is a naval invasion.  I can initiate an amphibious assault using editor placed AI units with waypoints to get to the beach and disembark.  

THEN...I could go into the ALiVE menu and choose to virtualize those units so that the OPCOM to take control of them from here on out and they would count against the rest of the friendly profile pool.

It would also allow me to KEEP other vehicles I've placed, units I've placed such as machine gun nests, etc. from being virtualized if I don't want them to be.

This could also be useful for people who use Zeus to drop in units/vehicles as they could add forces to the OPCOM, virtualize them...and still have there other non-profiled units remain non-profiled.

**Comment by friznit** [comment]
You could simply profile those units in a trigger area using ALiVE_fnc_createProfilesFromUnitsRuntime.  Something like `[false, _someListOfGroups, _someListOfVehicles] call ALIVE_fnc_createProfilesFromUnitsRuntime;`

**Comment by AUTigerGrad** [comment]
So place that exact code in a trigger on the beach?  Or is "_someListofGroups" a placeholder for the actual unit groups that would enter that trigger zone?

**Comment by friznit** [comment]
You can get a list of groups inside the trigger.  __someListofGroups = list _myTrigger;

**Comment by marceldev89** [comment]
Untested but this _should_ work for a trigger:
```
_groups = []; { _groups pushBackUnique (group _x) } forEach thisList; [false, _groups, []] call ALIVE_fnc_createProfilesFromUnitsRuntime;
```

**Comment by highhead** [comment]
should by theory work! just ensure the trigger fires only once :)

**Comment by friznit** [comment]
Add to wiki script snippets
