### ISSUE TITLE
Script error using manually placed combat support assets (Artillery)

### ISSUE THREAD

**Issue by SavageCDN** [ALiVEOS/ALiVE.OS#2]
When using custom assets for Combat Support as per wiki (Advanced Vehicle Placement):
http://alivemod.com/wiki/index.php/Combat_Supp

Repro using BLU_F:
- player unit
- single crewed Mk6 mortar
- ALiVE required
- ALiVE virtual AI
- ALiVE Combat Support
- sync mortar to CS module

Place in init field of Mk6 mortar:
`this setVariable ["CS_TYPE","ARTY"];`
(works fine)

Adding this to init:
`this setVariable ["CS_ARTILLERY_HE",50];`

Results in:
```
15:53:15 ALiVE [m_7|160] Module ALiVE_sup_combatsupport INIT
15:53:15 Error in expression <",groupID (group _entry)];

_he = ["HE",parsenumber(_entry getvariable ["CS_arti>
15:53:15   Error position: <parsenumber(_entry getvariable ["CS_arti>
15:53:15   Error parsenumber: Type Number, expected Bool,String
15:53:15 File x\alive\addons\sup_combatsupport\fnc_combatSupport.sqf, line 144
```

**Comment by SavageCDN** [comment]
mission.sqm

http://pastebin.com/kb3PxyVf

**Comment by SpyderBlack723** [comment]
Number must be entered with quotes

ex:

this setvariable ["CS_ARTILLERY_HE","50"];
