### ISSUE TITLE
Update AI Skill Module

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#20]
There have been several updates to the way AI is handled in Arma 3, and the ALiVE AI skill module lacks some of the new functionality and format.

For example, we now have "Suppression" and "Fleeing Coefficient" settings among others that are missing from the module. Might also be worth looking into that the format may have changed from actual numeric values (0.9, 0.5) to percents.

Seems there is also no way to change it across the board per faction as far as I know. Would be a great feature to expand because ALiVE already has a module for this specific reason.

**Comment by tupolov** [comment]
https://community.bistudio.com/wiki/setSkill_array

Doesn't look like AI Skill settings have been updated with these two skills?

**Comment by tupolov** [comment]
@Vegas

**Comment by Vegas** [comment]
AI skills are always the challenge with Arma. The documentation is not always the best (or the most updated).

What's interesting, if you install 3DEN Enhanced, when you open a unit's skill settings, you have a ton of options that are not normally there. We have a fleeing coefficient, and "suppression" settings. Without this tool however, all we have is the unit "skill" slider.

This leads me to believe that there are new settings that are not documented on that skill array, especially since with marksman DLC, we got the "suppression overhaul". Perhaps this is worth looking into?

3DEN Enhanced: http://www.armaholic.com/page.php?id=30461

**Comment by Vegas** [comment]
@tupolov

**Comment by tupolov** [comment]
You can't set a suppression co-efficient, just how much AI is suppressed at a certain point in time (which is what that mod offers). 

With ALiVE you can set courage which may or may not have an impact on suppression.

With fleeing, i'm pretty sure its a function of that courage setting, we can check, if not then we could potentially add the fleeing value.

**Comment by SpyderBlack723** [comment]
https://community.bistudio.com/wiki/allowFleeing
(obj/group) allowFleeing (scalar: 0-1)

No way to set suppression resistance

**Comment by SpyderBlack723** [comment]
9e9fa4e2a4b3a5508d92a50230fb3a29c6300fd6
