### ISSUE TITLE
Request: Way to see Objective numbers in editor before you startup

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#206]
I am not sure if this exists or not but I was chatting about it with a couple of guys in our community as we were working on our respective missions this evening. 

Is there a way to see how many objectives you have setup in your mission BEFORE you hit "Play Scenario" in the editor? If not is it possible to add that functionality to the ALiVE module somehow or is that a BI function that we are unable to get any traction on due to the way code works?

Thanks

**Comment by friznit** [comment]
No, because the modules do not initialise until the mission runs.  If you run the mission with the module in debug mode and take a screenshot of the map you can use it as a reference for where all the objectives are.

**Comment by coachwn** [comment]
Yeah that is kinda my issue with why I am asking if there is a way since the mission crashes with a CTD before I can see in debug and it relates to the OPCOM and objectives. I will have to retry since it has been a few weeks since I attempted to load that mission so I don't have an rpt available.

**Comment by nateberkopec** [comment]
@coachwn post RPT files
