### ISSUE TITLE
Confirm Weather module works with BIS latest changes

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#208]
1. Confirm weather sync
2. Implement real weather - Done
3. Check ACE compatibility - https://github.com/acemod/ACE3/tree/master/addons/weather

https://community.bistudio.com/wiki/Category:Command_Group:_Environment

**Comment by HeroesandvillainsOS** [comment]
+1 on the snow effects.

**Comment by tupolov** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/c6927d5e823bd270b3ca62044573472a30f5001c
https://github.com/ALiVEOS/ALiVE.OS/commit/fc149fbbb59c1b3247859289e2bac898c8045139

**Comment by tupolov** [comment]
BIS ticket list for reference

https://feedback.bistudio.com/T76596 (primary)
https://feedback.bistudio.com/T77468 setDate issue
https://feedback.bistudio.com/T64106 JIP
https://feedback.bistudio.com/T79824 Weather over time
https://feedback.bistudio.com/T72655 simul sync disparity
https://feedback.bistudio.com/T61395 Long discussion
