### ISSUE TITLE
Change Adv Markers keybind

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#21]
BIS implemented line drawing in patch 1.60 using CTRL-LMB.  Adv Markers conflicts with this.  Need to change it to an alternative key and/or a double click.

Might as well remove the line drawing element too - not sure anyone uses it much.

Would be nice to see if we can persist BIS line drawing.

**Comment by bux578** [comment]
FYI. We have removed the ACE3 line drawing and will probably use "Alt" + "Click" for rotating our map tools.
https://github.com/acemod/ACE3/pull/3864

**Comment by tupolov** [comment]
We now use CTRL+ALT and LMB/RMB to add/delete ALIVE Advanced Markers

**Comment by SpyderBlack723** [comment]
d58df11
