### ISSUE TITLE
Civilian interaction improvements

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#210]
Civilians like to run around a lot, making it difficult for the player to search and interrogate them. I'd like to see a system put in place that allows players to have access to the Assymetric civilian options (speak to, gather intel, arrest, search inventory) from an on-screen action that would force the civilian to stop moving, and that could possibly lead to an all encompassing civilian interaction UI.

There are a few ways I think this could done:

1. Formally integrating Spyder Addon's Civilian Interaction module, and fixing its remaining issues.
2. A "stop" or "talk to" on-screen action that forces a civ to stop and leads to an all new UI that can access intel (when available), conversation influence options (when available, such as "talk to muezzin") arresting/freeing, and inventory.
3. A simple on-screen "stop" command with no UI at all (this would still be an improvement over chasing civs around the battlefield).

**Comment by Vegas** [comment]
A little more on this:

In addition to chasing them around (gotta get that PT in whenever you can..) sometimes when civilians are in their "I'm talking to myself and it is very important" animation loop, you are unable to interact with them properly. Perhaps remove this loop function, or when a player interacts with them it disables movement and animations until player closes the dialogue.

Spyder's addons are amazing and should totally be expanded upon.

[http://i.imgur.com/25FkmQU.jpg](url)

**Comment by HeroesandvillainsOS** [comment]
I'm not aware of any issues with animations breaking interaction. Can you be more specific? For the record, I'm talking about how vanilla (CBA/ALiVE) ALiVE functions when using the mouse-wheel and inventory search options to interact with civs.

**Comment by SpyderBlack723** [comment]
We will take door number 1

**Comment by friznit** [comment]
ALL HAIL SPYDERBLACK

**Comment by SpyderBlack723** [comment]
https://github.com/ALiVEOS/ALiVE.OS/tree/Module_Civilian_Interaction

**Comment by HeroesandvillainsOS** [comment]
Woo hoo!!!!! 

Number 1 was my favorite one which is why I listed it first. :)

**Comment by HeroesandvillainsOS** [comment]
Closing this seeing as Spyder has begun developing a new interaction system.
