### ISSUE TITLE
Saving server freezes when commander has no profiles

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#211]
When there's a commander module placed down that doesn't have control of any profiles the module never fully initializes and causes the saving process to freeze during the pausing of active modules.

The actual freeze happens at [mil_opcom/fnc_OPCOM.sqf:1386](https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/mil_opcom/fnc_OPCOM.sqf#L1386) and it seems that the `"OPCOM_FSM"` variable is never set.

[Original report](http://alivemod.com/forum/2655-stuck-on-saving)

**Comment by friznit** [comment]
Why would you have an AI Commander without any troops to command?

We could add a fail safe to exit the OPCOM module if it has no profiles but that may have unintended consequences.  I'd suggest a better solution would be to ensure the AI Comd has some profiles - could just be a single off map unit synced.
