### ISSUE TITLE
Update official ALiVE server

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#217]
Update Arma 3
Update mods
Update scripts
Update extensions
Update server config 
Upload new showcase missions

**Comment by tupolov** [comment]
I've updated Arma 3, CBA and ALiVE
We need a paid steam account or a script ( @marceldev89 ) to sync CUP content
Extensions and scripts have been updated.

**Comment by marceldev89** [comment]
> paid steam account ~or~ and a script
Fixed that for you :smile:
