### ISSUE TITLE
Logistics choppers collide when delivering BCR's

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#218]
I realize this may be related more with the engine, rather than ALiVE itself, but I'd love to see some improvements done to prevent Logistics choppers from running into each other and crashing during the touchdown/take off process.

Although I think the best solution would be to either increase the spacing between choppers, or let them 'take their turn' before the next chopper attempts to complete his delivery, yesterday I observed an almost perfect BCR attempt. However, the second to last chopper slightly clipped an object when landing (it was still fully flight functional, but sputtering smoke from the engine).

Because it was very slightly damaged, during the take off after dropping off his troops, the chopper was moving slightly off-balance and clipped another helicopter that was also taking off at the same time, and both crashed to the ground.

I get there may be some strategic element where enemy players or AI may want to attempt to destroy the delivery choppers, but if the above solution isn't possible with spacing or turn-taking, I suggest disabling damage on BRC Logistics choppers completely.

**Comment by HeroesandvillainsOS** [comment]
I'm currently doing an unrelated vanilla test on Stratis, when 5 minutes into the mission, NATO gets heli resupply and it results in this:

[img]http://i.imgur.com/ByJrr02.jpg[/img]

I understand there is probably no perfect way to make everyone happy on this, and that spawning units out of nowhere is less than ideal, but this is a very common occurrence. The helicopter formations are too tight. If they have to stay, they should be spread out further and/or let each chopper take it's turn completing the delivery before the next one attempts to land and unload.

**Comment by HeroesandvillainsOS** [comment]
Here you go @highhead 

https://www.dropbox.com/s/kh7egxxv8bsm7sl/BCR_Test.Stratis.pbo?dl=0

Just spawn and stay where you are and fast-forward around 15 minutes. BCR's should automatically arrive directly in front of you. If they arrive with more than just a few (which two times in a row, 8+ arrived simultaneously), you'll see the colliding. 

Some screens:
[img]http://i.imgur.com/RguntOF.jpg[/img]
See how many choppers there are? I count at least 8. Then...
[img]http://i.imgur.com/5AjlIil.jpg[/img]

**Comment by highhead** [comment]
thanks! For the record:

- Choppers get created at the main LOGCOM pos even if players are near, also leading to colliding choppers.

- Maybe changing the vehicleDismount parts to real structured land commands avoids choppers picking the same landing spot.

- Idea of filling up a chopper fully to its max capacity and not only putting one group in also reduces the needed transport vehicles

**Comment by HeroesandvillainsOS** [comment]
I'm feeling like this has been properly resolved. In the event anyone thinks it can use additional work, I'll reopen the ticket.
