### ISSUE TITLE
Update ALiVE Debug Console

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#22]
The debug console accessed through Admin Actions currently has outdated camera and spectator functions. These functions have been overhauled by BIS (the spectator was redone shortly after End Game Tournament, and the Splendid Camera was redone with 1.60). These should be updated in the console, as the buttons are currently accessing old call functions.

A simple change, but well worth it!

**The new spectator command:** BIS_fnc_EGSpectator
Unsure about new splendid camera function.

**Comment by tupolov** [comment]
![20160613140128_1](https://cloud.githubusercontent.com/assets/1871500/16008357/8449483e-316f-11e6-99a9-a93e80cd926b.jpg)

This one?

**Comment by tupolov** [comment]
We are using the BIS RscDisplayDebugPublic

The one above is RscDisplayDebug

**Comment by Vegas** [comment]
@tupolov The debug console I am talking about, is when you open the ALiVE menu (app data key), and go to Admin Actions>Debug Console

**Comment by tupolov** [comment]
Yes i am aware of what you are talking about. I'm asking you what BIS debug console you want to see. The one we use or the one above.

**Comment by Vegas** [comment]
Hmmm, difficult decision.

The console shown above has more features and can actually accomplish a lot more, however, the current one is very simple and would be easier for newer people to grasp.

Personally, I would like to see this new one added into ALiVE. But I can see both having their own benefits.

**Comment by tupolov** [comment]
At the end of the day, these are BIS made debug consoles that we open up. One is the public one (which is simple), the other is for dev/modders. If BIS have updated functions and their public debug console doesn't use them, this is a BIS bug. We wouldn't want to overwrite a BIS console, incase they update it at a later date.
