### ISSUE TITLE
[Amb_civ] Add ambient building lights and smoke

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#225]

**Comment by Vegas** [comment]
There used to be a rare chance for a radio to spawn inside houses or other buildings which players could hear through the walls.
As simple as this seems, it actually added a lot of immersion.

If you need help with sound fx or mixing, don't hesitate to ask. It would be awesome to hear military radio traffic around enemy camps and hilarious *ahem* "cultural" music or television sounds coming from houses.

**Comment by SpyderBlack723** [comment]
Nothing changed, that can still occur.

**Comment by Vegas** [comment]
It seems to be extremely rare though. Would still love to see it expanded upon. The beauty is in the details.

**Comment by highhead** [comment]
There was a regression where ambient music didnt play. That was fix with latest release. Can you please retry that?

Also keep in mind civilians have a life. They will listen to music when doing housework and thats happening with a higher chance in the evening, when sun goes down until 2300, when they go to bed.

**Comment by highhead** [comment]
PS: expanding on that is a nice idea. I'll take a look how complex it would be to add it to strategic places

**Comment by Vegas** [comment]
@highhead You're the man!

I know there are some ambient radio traffic sounds that can be pulled from A3's sound files, and there are additional sounds from A2 and OA that could also be pulled. These could play from strategic places or vehicles. ACE2 back in the day had a module that added "Radio Traffic" coming from ambient vehicles too that utilized these sound files. Might feel more ALiVE!

The radio sounds already within A3 are classified as music. Found at this link: https://community.bistudio.com/wiki/Arma_3_CfgMusic

#'s 90-119
