### ISSUE TITLE
Alive modifies weapon info font and font size

### ISSUE THREAD

**Issue by rebelvg** [ALiVEOS/ALiVE.OS#23]
Alive modifies weapon info font and font size. Vanilla font and size is much more better right now.
Alive - http://i.imgur.com/yf5Pk48.jpg
Vanilla - http://i.imgur.com/6Xstv5f.jpg

**Comment by SpyderBlack723** [comment]
Looks like me that CBA is the cause, not ALiVE.

**Comment by rebelvg** [comment]
Just tried with CBA only, hud has vanilla font and font size.

**Comment by tupolov** [comment]
Found the issue... will update
