### ISSUE TITLE
[Feature request] Always show commander objectives on map

### ISSUE THREAD

**Issue by Taxen0** [ALiVEOS/ALiVE.OS#230]
Hello,

This is a feature simple request from me and my gaming group. We would love if the C2ISTAR module had an additional field called "Always show commander objectives" or maybe "Show commander objectives on map", with the usual options of "side", "faction", "All" or a "override"-box.

What it would do is to always show the additional information (map markers) that you normally access by using "show commander objectives" from the "Intel"-menu, to all players on the regular map at all times, so you don't have to have access to the Intel menus at all to get the information.

We feel like this would make the mod more accessible to groups that might not be as advanced and help keep the more casual players in the loop regarding what happens in the mission without forcing them to fiddle with menus. Might feel like a minor thing but it would really enhance the experience even further for my group.

Thank you for a great 2016 and I hope this year will be just as good! =)

Thread on forum: http://alivemod.com/forum/2629-how-to-toggle-show-commander-objectives-by-script

**Comment by tupolov** [comment]
We should probably look at this inconjunction with this ticket https://github.com/ALiVEOS/ALiVE.OS/issues/40 and this one https://github.com/ALiVEOS/ALiVE.OS/issues/308

**Comment by DavisBrown723** [comment]
Closing this in anticipation of upcoming intel changes. Unlikely we will show all objectives on the map, but currently attacked/defended objectives will be visible. Potentially could add a module option to permanently display all objectives if it's requested.
