### ISSUE TITLE
Test aircraft placement on Tanoa

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#231]
Reports of exploding helis.

Also worth testing heli compositions and it they conflict with placement

**Comment by coachwn** [comment]
I have seen this with non-ALiVE missions but not with ALiVE based missions. Are there any mission files that someone is having this issue with specifically?

**Comment by friznit** [comment]
Tested Tanoa and is good enough for now.  Further refinement as part of ATO
