### ISSUE TITLE
Possible Duplication of Roadblocks when using Asymmetric OPCOM

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#234]
Persistent roadbocks introduced a possible regression.

**Comment by highhead** [comment]
Repro: 

- Start a persistent Mission with Insurgency set up correctly (incl. CQB and MIL IED). See wiki in case.
- Wait until a roadblock has been set up
- Save mission
- Reload mission
- Roadblocks will be setup on the outskirts until there are no more roads available or distance to selected roadPos is > 100 mtrs
