### ISSUE TITLE
Civilian population randomly not creating virtual troops (OPCOM failing)

### ISSUE THREAD

**Issue by highhead** [ALiVEOS/ALiVE.OS#237]
Sometimes military civ placement does not set up troops even if correct module settings are used. Esp. with initialisation-changes already existing mission - that worked properly - can break suddenly (expierienced on dev branch), civ placement stops to work - OPCOM tells you it cannot find troops for that faction.

**Comment by HeroesandvillainsOS** [comment]
@Highhead, thanks for fixing this. I've encountered this issue for quite some time intermittently with older missions. It's nice to see you back man! I appreciate all the improvements you've made recently!
