### ISSUE TITLE
Reinforcements parachuted in are destroyed. 

### ISSUE THREAD

**Issue by Snoutmaster** [ALiVEOS/ALiVE.OS#247]
Please improve the Resupply of troops. Heavy armour and large trucks are unrealistically parachuted in and they explode when landing on roofs and other vehicles. These reinforcements need too be brought in by ships at the port. Even use the new transport aircraft in Apex to bring in reinforcements.

**Comment by friznit** [comment]
The design question here was "how should Logistics spawn Battle Casualty Replacements when players are within range of the Logistics HQ?"

- Not all maps have ports or airports
- There are no transport ships in ArmA
- Not all mods/factions will have transport aircraft
- ArmA AI and aircraft really don't get along without a lot of hacky scripting

On balance, given that you could reasonably expect players to be mostly in the field and not at the Logistics HQ, we decided not to expend too much effort in this area.  Given the constraints, options boil down to simply spawning the units in or parachuting them in.  Neither is ideal, but parachuting at least gives some sort of sense that they've been cargo dropped.
