### ISSUE TITLE
[Feature request] Make possible to completely remove access to autogenerated and built-in tasks

### ISSUE THREAD

**Issue by Asmodeuz** [ALiVEOS/ALiVE.OS#250]
from the relevant ALiVE module (in this case _Player Command/Control (C2ISTAR)_ ?).

This would suggest that there would only be access to _"Create a task"_ feature but not to _"Generate a task"_ and _"Auto generate tasks for my side"_ features by the decision of the mission maker.

Currently autogenerated tasks can be disabled but these can be enabled at any time through the commander's tablet.

Relevant discussion http://alivemod.com/forum/2657-actually-disabling-auto-generated-tasks

**Comment by highhead** [comment]
PS: also fixed script errors ofc
