### ISSUE TITLE
[Feature request] Make possible for the virtualized AI profiles to capture Sectors provided by BIS

### ISSUE THREAD

**Issue by Asmodeuz** [ALiVEOS/ALiVE.OS#251]
thus broadening ALiVE mod's accessibility when there would be easy-to-use ways to create missions that rely on large-scale sector control (multiple towns as an example) and where ending missions rely on controlled sectors.

Relevant discussion http://alivemod.com/forum/2507-let-virtual-ai-capture-sector-control

**Comment by SpyderBlack723** [comment]
This should probably be functionality provided by the BIS module. Such as providing a custom condition code for capture. Highly doubt there is really a way for ALiVE to externally tap into the sector module in a graceful way.

**Comment by Asmodeuz** [comment]
Mhm, I figured in advance that would be the case.
Kind of sad that no matter how ALiVE strives to deliver a living, organic battlefield with a few mouse clicks the whole concept imHo gets dragged down for not providing easy-to-use tools for creating end-mission conditions that ALiVE itself could adhere.
Now I am here as a player between a rock and a hard place forced to appeal either the devteam of the modification or the game developer to make changes. Go figure how's that going to end.

**Comment by SpyderBlack723** [comment]
Can sectors not be activated/deactivated by triggers? Seems to be a lack of flexibility on the module's part. ALiVE provides functions to determine which side controls an area.

**Comment by Asmodeuz** [comment]
The whole sector control setup is dependant on a trigger that will act as the zone (or "sector") that can be captured.

I did create a small example mission with @CBA and @ALiVE where I placed the good old _((count ([getposATL thisTrigger, 200, ["EAST","entity"]] call ALIVE_fnc_getNearProfiles)) > 0);_ in the trigger's **Condition** field. Other settings in the trigger are

- **Type:** None
- **Activation:** Anybody
- **Activation type:** Present
- **Repeatable** checked
- **Server Only** unchecked

for reasons unknown to me using the allmighty ALIVE_fnc_getNearProfiles doesn't provide any positive results in this case.

Could there be another script snippet that would work better in this case, something..anything?


Here's a quick reference picture about how and with what modules + a trigger a working sector control setup is made:
http://i1370.photobucket.com/albums/ag278/testusah123/sector_control_modules_zpscwub75g6.jpg

Here are the files for the small test mission I made (in .PBO and .sqm format)
https://www.dropbox.com/s/39cd0buqtyqw62n/alive_sectorcontrol_test.Stratis.pbo?dl=0
https://www.dropbox.com/s/bnjavn4xjgp6ed2/alive_sectorcontrol_test.Stratis.zip?dl=0

In the test mission **Spawn radius** is set to 400m and debug mode is enabled in the Virtual AI system module.
When the mission begins one can observe how an OPFOR AI profile enters the sector control area and nothing happens in the 'capture meter' (marked with **A**) on the right side of the screen.
Then with ALiVE's _Admin Actions_ enable teleporting and teleport so close to the sector (but stay outside!) to make the OPFOR AI profile to spawn. One can now observe how the 'capture meter' begins to fill up unless the player forces the AI profile to despawn by moving far enough.
