### ISSUE TITLE
[Feature Request] Insurgent installations discoverable by grouped AI

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#256]
Grouped AI are occasionally smart enough to walk through a building on their own and also when commanded to move to a location. If an installation is present, I'd like it to tap into C2ISTAR map Intel logic and reveal the location to the player. If possible, a sound or radio chat notification to go with it would be nice but that's not essential.

It seems to me some kind of framework for discovering installations is already incorporated into ALiVE with virtual profiles. If this could be extended to grouped AI in some way, I think it would add a lot to the mode and make clearing towns a lot more efficient.

**Comment by highhead** [comment]
As much as I'd like this feature, it is pretty expensive if performed in "realtime", involving regular nearEntities checks for spawned units and another check for virtual AI (with lets say a little bigger detection radius) on every installation present. Triggers I'd like to avoid completely. Not sure if thats really "worth it", but I will try it.

**Comment by HeroesandvillainsOS** [comment]
Yeah I see. If it comes at the cost of FPS then seriously don't worry about it. AI are so dumb anyway I can almost never get them to take cover behind a building, let alone get them to search one. I figured if it could be easily implemented it would be cool, but there are probably 100 better things you could be doing to improve ALiVE if this request is performance costly and time consuming to boot.

**Comment by highhead** [comment]
best "fit" I could find was to ignore virtual AI completely and only use a nearEntities check on every installation still on Altis it would mean 50-70 spawned loops for every installation.

Alternative would be a check against those 70 installation vs. 200 spawned AI at once (in a dense mission) = 14000 checks divided to several frames with fnc_ArrayFrameSplitter which finishes the task in time but would have a slight impact on FPS (though I think it would be below 1 FPS (not mesured enough, in those dense missions everything piles up ofc).

still not sure how it would scale for several players, and low FPS situations.

**Comment by HeroesandvillainsOS** [comment]
I see. I see you're pondering several options, but the one where you'd have installations be ignored by Virtual AI wouldn't be worth the trade off to me. As it stands, Virtual AI can't destroy the installations (from what I've seen) but it is still very useful when they reveal them (via map Intel). I rely on it actually and it would mean more to me (personally) to have that stay in-tact than it would to get them revealed by physical spawned in AI.

**Comment by HeroesandvillainsOS** [comment]
The more I think of this feature, the less crucial I feel that it is (small addition that would come at a high cost). Closing.
