### ISSUE TITLE
Teleported grouped AI occasionally begin walking backwards

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#257]
When opening the commander tablet and using admin privileges, when teleporting a grouped AI, they occasionally begin walking backwards, and don't stop walking backwards until they reach their initial teleport point, and infinitely stop following commands. This appears to be more frequent when the AI is in combat mode (orange icon on their Fkey profile).

**Comment by SpyderBlack723** [comment]
Please repro with only CBA and ALiVE running if you haven't already. Don't see this being an issue caused by ALiVE, most likely another mod or Arma itself.

**Comment by HeroesandvillainsOS** [comment]
Yeah I think you're right and I may be a little premature on this ticket and also agree it's probably engine related. Though tough to say because AI teleporting is very unique to this mod. Every once in a while when I want to mix things up, I'll download some popular SP Workshop missions and have admittedly seen similar behavior when team-switching to a unit in combat mode too (the guy you switch too automatically moves backwards and won't stop and it can't be corrected).

I'll close this and try to repro with CBA/ALiVE only and then post a rpt in the ALiVE forums so you guys can at least see first if it's caused your mod or not before bringing it back here.

**Comment by SpyderBlack723** [comment]
Reopen if you find otherwise
