### ISSUE TITLE
AI Blob Mass In Corner Of Map - HC Entity Spawning Them In

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#267]
Ok, I'm not even sure what to make of this one... but something seems wrong here.

http://i.imgur.com/vGdLYS5.jpg

- AI are in a massive blob in the bottom left corner of the map. There are no objectives there.
- Opened Zeus to see what is going on because massive lag spike
- Headless Client virtual entities are visible, and because they are there, all the AI is spawned in to game-space.

Not sure what is causing the blob. Also not sure why HCs have the power to be registered as players and cause these profiled units to be spawned in.

**Comment by coachwn** [comment]
It is a map error. I was told that many maps don't exactly represent the proper areas at times and AI will spawn in there and usually under water or in the ground and they will die once they sit there long enough. I have tried blacklisting that area on Saharani and Chernarus and it doesn't work. They still get dropped in there.

**Comment by HeroesandvillainsOS** [comment]
Awhile back, @SavageCDN suggested placing the HC module way WAY off to the side in the editor. So far off that it in no way could be viewed as actual playable map. Maybe worth a try? Kick it off to the corner like a bad module so you can barely see it!

I don't run a HC myself. But I remember reading about the issue and reading his suggestion.

**Comment by Vegas** [comment]
@HeroesandvillainsOS Very good idea there. I will try this.
- I still think HCs should be blacklisted from even being able to spawn ALiVE AI in though. This is one of those *ahem* interesting scenarios for sure.

**Comment by SpyderBlack723** [comment]
Not sure if you can distinguish HC's from normal players. They exist in the allPlayers array which causes them to spawn in units.
