### ISSUE TITLE
Unable To Blacklist Strange "Yellow Arrow" Areas

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#269]
It would appear that despite reindexing of the map, some maps continue to have issues and start spawning AI in on these weird yellow arrows in the far bottom corner.

I'm not entirely sure if this is something that is even fixable, but placing blacklisted marker areas over top of them does not stop anything from spawning there. Nor does it prevent objectives from being generated there.

It would also appear that AI commander and OPCOM consider these arrows extremely important objective areas thereby breaking C2ISTAR objectives. For example, a hostage rescue task will always tell you to return hostages to this yellow arrow, and the enemy deploys large numbers of troops to protect this yellow arrow with a big blob.

**Reference Images:**
"wtf yellow arrow"
http://i.imgur.com/UvZtVFY.jpg

"Massive Blob"
http://i.imgur.com/vGdLYS5.jpg

**Maps Known To Have This Occur (that I have tested at least)**

- Reshmaan Province
http://www.armaholic.com/page.php?id=17246

- Taskistan
(CUP)

Any advisory or suggestions would be appreciated.

**Comment by HeroesandvillainsOS** [comment]
I'm thoroughly going through missions on Takistan and Reshmaan now as we speak (I have a ticket open regarding a persistence bug). I don't see this at all.

Would this be related to the headless client issue you reported? These sound like the same ticket.

https://github.com/ALiVEOS/ALiVE.OS/issues/267

**Comment by HeroesandvillainsOS** [comment]
Ok, I'm certainly not the kind of person that can solve your problem, but I was messing around in the editor yesterday and noticed CUP has arrows that look an awfully lot like this available as objects in the editor. Is it possible this object was placed there by someone? Is this a mission you made?

What I'd personally like to see with this: I'd like to see a test done with the headless client module removed. I'd also like to make sure Military Logistics isn't placing any priority to this mysterious place, so I'd advise trying a test without the HQ options for Logistics, or just removing it entirely.

I looked at my Takistan and Reshmaan missions again yesterday just to be sure and I don't see this. Now I can't be certain that this place might not get picked up at some time down the road during a persistent campaign, but for 30 minutes after mission start, nothing unusual is going on.

I'll see what happens after a few Logistics BCR replacements.

**Comment by Whigital** [comment]
We have never seen this on our Taki missions. That arrow is a helper object, so it might be one of the other mods you're running using it for some sort of reference.

The curious thing is at it tends to appear at [0,0,0], which usually means default pos or hide it away from other things on the map. Unqualified guess is that it might have to do with the targeting pod thingy on the F-18.

Try removing mod by mod and see if it disappears.

**Comment by HeroesandvillainsOS** [comment]
I use Spyder Addons so you can probably rule that out too

**Comment by HeroesandvillainsOS** [comment]
Vegas what was the cause of the yellow marker?
