### ISSUE TITLE
Open sourcing ALiVEClient.dll

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#27]
Are there any plans to open source the ALiVEClient.dll?

**Comment by tupolov** [comment]
Yes at some point. We're open to having people contribute to the closed source project (C#) until we feel its in a position to be open source.

**Comment by marceldev89** [comment]
Alright, I have a few ideas floating about to make the indexing experience a bit less painful both in usage and setting it up (judging by the issues on the alivemod forums). That would, among things, involve porting the DLL to C++ for automation purposes. I'm not sure how involved the DLL is with the whole indexing process though.

**Comment by marceldev89** [comment]
Hmm I guess I should ask the question as well.. Is it possible to get access to the DLL to see what it does exactly and whether I need it or not? :smiley:

**Comment by tupolov** [comment]
I'll set you up with access tomorrow.

**Comment by marceldev89** [comment]
Is this still a goal?

**Comment by tupolov** [comment]
To be honest not sure. The ALiVEClient today is really only used for indexing. It has some functionality to enable map image export to War Room and uploading images from in game to War Room (WIP).

I guess in theory we should add both ALiVEClient and ALiVEPlugIn to the repo and include scripts to build etc. Need to check both for any possible security issues.
