### ISSUE TITLE
[Feature Request] Allow Defining of FOB For Players (Starting Position)

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#275]
**Current System**
There is currently no way to tell ALiVE systems where players are spawning, where their respawn point is, or where they have essentially established their FOB (that I know of at least). Most of the time, we have to actually blacklist an area (like a military outpost or airfield) so that nothing spawns there if we want to reserve the location for use by players.

**Suggestion**
Allow defining of a Player FOB or Player Starting Position through a module (might be a nice addition to the Custom Objective module). This will allow more options when it comes to how ALiVE handles players.

**How This Can Help**
- Allowing players to define their starting point would allow the tasking system to use it as a return point for hostage type objectives that are generated, or any other type of retrieval tasks.
- This could incorporate a "no spawn radius" so that players do not have to put a blacklist marker over their FOB, they could just drop a module.
- AI Commanders could (if synced) use this "known position" to launch attacks on player FOBs every so often, or perhaps add an "allow attacks" true/false option. That by itself would be epic.

**Comment by HeroesandvillainsOS** [comment]
Aside from returning the hostage back to your FOB (which is a cool idea), all of this can be done easily with blacklist markers and custom obj modules. 

If you want the enemy to place a high priority on your FOB, put a high priority cust obj on it. And for me, markers are great for blacklisting spawns because I can make them in multiple shapes and sizes and cover the exact dimensions I'm going for.

**Comment by shukari** [comment]
Is it possible to do a wiki page that explain which priority is high and which one low... also the size... i never know if the priority must be 100 or 1000000... is there a common value for something...

**Comment by SpyderBlack723** [comment]
http://alivemod.com/wiki/index.php/FAQ#What_do_the_numbers_mean_.2850.7C150.29_next_to_the_placement_modules_in_debug.3F
