### ISSUE TITLE
[Bug C2ISTAR - Task SabotageBuilding

### ISSUE THREAD

**Issue by flibble666** [ALiVEOS/ALiVE.OS#276]
Getting the following error when tryong to start a SabotageBuilding  (destroy infrstrutor)  auto task.
 
arma 3 version: latest stable
Alive version: ALiVE_1.2.9.1701291
CBA_A3 version latest steam workshop
no other mods running 
players at time of error: 2

`name: Land_Shop_City_03_F, shape: a3\structures_f_exp\commercial\shop_city_03\shop_city_03_f.p3d, index: -1, matrices: 4
 0:21:00 C2ISTAR - Task SabotageBuilding - OPCOM index 1 selected as objective at position [5960.71,12063.8]
 0:21:00 C2ISTAR - Task SabotageBuilding - Buildings in MIL cluster c_51: [e4581400# 243913: pillboxbunker_01_rectangle_f.p3d]
 0:21:00 C2ISTAR - Task SabotageBuilding - There are no buildings to attack at the target area!
 0:21:00 Error in expression <ype]);

if!(isNil "_taskSet") then {
if(count _taskSet > 0) then {

_managedTask>
 0:21:00   Error position: <count _taskSet > 0) then {

_managedTask>
 0:21:00   Error count: Type Bool, expected Array,String,Config entry
 0:21:00 File x\alive\addons\mil_C2ISTAR\fnc_taskHandler.sqf, line 557
 0:21:33 Server: Object 4:212 not found (message Type_93)
 0:21:51 C2ISTAR - Task SabotageBuilding - OPCOM index 1 selected as objective at position [5960.71,12063.8]
 0:21:51 C2ISTAR - Task SabotageBuilding - Buildings in MIL cluster c_51: [e4581400# 243913: pillboxbunker_01_rectangle_f.p3d]
 0:21:51 C2ISTAR - Task SabotageBuilding - There are no buildings to attack at the target area!
 0:21:51 Error in expression <ype]);

if!(isNil "_taskSet") then {
if(count _taskSet > 0) then {

_managedTask>
 0:21:51   Error position: <count _taskSet > 0) then {

_managedTask>
 0:21:51   Error count: Type Bool, expected Array,String,Config entry
 0:21:51 File x\alive\addons\mil_C2ISTAR\fnc_taskHandler.sqf, line 557`

**Comment by highhead** [comment]
seems like its happening in vanilla, can you please provide the mission you are using? Thanks!

**Comment by highhead** [comment]
please reopen when you can post the mission, where this is happening! Thanks again!
