### ISSUE TITLE
CQB Blacklist units still showing up after being posted in init for CQB module.

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#278]
Any reason why some units I am attempting to blacklist are still showing up regardless of being blacklisted or not? I have several units that I don't want to spawn in my CQB module and the ones at the top of the code are not spawning but the ones that are towards the end are spawning. 

http://pastebin.com/pjGt77TM

Any help here would be greatly appreciated; and if it is a bug I am glad to continue testing it out while I am working on my mission.

**Comment by eric963** [comment]
Have the same issue where somewhere down the list it stops blacklisting.  I know everything is spelled correctly and formatted correctly because if I paste the section to the init of a placement module it blacklists all units correctly.

Give that a try till this gets looked at.

**Comment by coachwn** [comment]
Wondering if I could break up the blacklist and place it into 2 different modules????

**Comment by coachwn** [comment]
I think this is an issue over and above the aspect of ALiVE. I think this is a combination of things with something from BI as well. Going to close it and then we will see what happens.
