### ISSUE TITLE
[Feature request] Add needed functionality for using the "optional commander's tablet"

### ISSUE THREAD

**Issue by Asmodeuz** [ALiVEOS/ALiVE.OS#279]
More of a reminder this one but: the optional commander's tablet model ([https://github.com/ALiVEOS/ALiVE.OS/blob/master/images/ALiVE_PSD/ALIVE_mapbag.png](url)) got merged back in December last year. So here's hoping it could also become available sometime in the future.

Relevant discussion: http://alivemod.com/forum/2556-acquiring-a-ww2-commanders-tablet

**Comment by SpyderBlack723** [comment]
Controls might need rearranged. Create new dialog inheriting the current one (beware dialog inheritance handling is poor).

Handle which display should be shown using a variable (module option to choose display?).

**Comment by SpyderBlack723** [comment]
Buttons will need rearranging for this to function properly.

- Vertical Size is smaller
- Horizontal size is larger

**Comment by SpyderBlack723** [comment]
Curious if it would still look ok if ripped apart by each side, and stitched over the current interface to maintain size and prevent doubling future work :)

**Comment by Asmodeuz** [comment]
I just made a pull request for the updated template. Spyder, could you take a look and see how the interface goes now with the edges?

**Comment by SpyderBlack723** [comment]
Still struggling with this, increasing image size decreases in-game tablet size...

**Comment by Asmodeuz** [comment]
Naturally if there's something I could do I am always willing to give a try.

On another note there's just so much I can do other than sending resized image when requested.

Somehow I don't understand how this **image** seems to be behaving so differently than the official template (which is also nothing else than an image).

**Comment by SpyderBlack723** [comment]
Nobody understands half the stuff that occurs when working UIs in Arma.

**Comment by SpyderBlack723** [comment]
b179f7c6e05e3c8978ae233b4b5d0b1919f3c530
