### ISSUE TITLE
ALiVE_fnc_getParkingPosition selects parkingpositions too close to building walls

### ISSUE THREAD

**Issue by highhead** [ALiVEOS/ALiVE.OS#281]
...which causes exploding vehicles.

from my tests: seems like isFlatEmpty (and therefor also BIS_fnc_findSafePos) ignores walls of buildings (and takes the center position of the building as distance anchor). Guess thats nothing new, but causes also to be problematic with getParkingPosition.

![20170204163436_1](https://cloud.githubusercontent.com/assets/13004589/22619610/ac365fd8-eaf8-11e6-9973-d9380daa6786.jpg)

**Comment by highhead** [comment]
Improved function to take into account buildings, walls and other terrain objects better, and avoid moving vehicles off road into buildings.

As the parking positions are dynamically generated there is still a small chance for vehicles to bounce esp. in dense cities. this is unavoidable for now but going by the repro mission provided in #277 I get a 19/20 chance to have no exploding vehicle.

**Comment by HeroesandvillainsOS** [comment]
Thanks Highhead.
