### ISSUE TITLE
[Map Indexing] Isla Duala 3.8 script errors and civ spawns

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#284]
Not sure if Icebreakr's maps just have inherent issues with ALiVE compatibility, but I indexed his newest version (which is supposed to be unobfuscated) and testing the index, there are script errors galore and no civilian spawns at all, even though I ensured all enterable ones would allow it.

The rpt for the indexing and IndexTest session: https://www.dropbox.com/s/q3hm4fi1jt2rdv2/isla_duala_index.rpt?dl=0

The index: https://www.dropbox.com/s/dhhyeumhtpdd96g/isladuala3.zip?dl=0

**Comment by Scotty-Z** [comment]
I'm having the same issue, had it on Panthera too

**Comment by HeroesandvillainsOS** [comment]
Yeah I figured it was worth trying seeing as he said he finally unblocked the PBO's. But yeah something is really wrong.

**Comment by friznit** [comment]
Problems is in isladuala3_staticData.sqf

ALIVE_civilianPopulationBuildingTypes array got too big and didn't terminate properly (line must end with `];` )

Simply remove the last part of the line so it ends with `"a3\structures_f\households\house_big01\i_house_big_01_v1_dam_f.p3d"];` should do the trick.  It's an unfortunate limitation of ArmA.  It shouldn't matter to the index too much if a couple of houses are missing, but if you're worried about that you can manually add a final structure "house", which will pick up anything and everything with house in the name (see some of the older, manual indexes if you want to see how it looks)

Re-index that and you should be golden.

**Comment by HeroesandvillainsOS** [comment]
Thanks Friznit. Yes I've seen "house" written in old indexes before (Sangin, for example), so I'll go through the files and close the lines, and try to add house to it too. Though I'll certainly need you to look it over for me once I'm done.

At this stage, will I need to enter the editor anymore or do you think we can get this done and proper with notepad? The last part of your comment is a bit confusing. Not sure if I need to clean this up and re-index (without the object categorization), or if manually editing with a text editor will be enough.

**Comment by friznit** [comment]
You need to fix the static data file then re-run the indexing process - obviously set it to skip the object categorisation because you now have an existing staticdata file.

**Comment by HeroesandvillainsOS** [comment]
Ok no problem. Quick question. When using existing static data, I see I need to put the x folder inside @ALiVE\indexing\mapname

This folder path doesn't generate until I begin the indexing process. After every index, to delete this folder so it's fresh to generate new data for each index. So to do this with Isla Duala, do I need to create my own indexing\mapname path myself and stick my current x folder in there before doing the reindex?

**Comment by friznit** [comment]
Or if you're lazy like me, run it normally once to let it create the folder path, then escape out and delete everything that isn't x\alive\addons\main

i.e. delete analysis/strategic/civ & placement folders and start again.

**Comment by HeroesandvillainsOS** [comment]
Oh wow, ok thanks for the breakdown. I was definitely going to do this wrong. Didn't realize the only file I wanted to use from my current index was just the fixed staticData. Thanks. I should (hopefully) have this done within the next day or two.

**Comment by HeroesandvillainsOS** [comment]
@Friznit Everything seems to be good after cleaning up the staticdata and re-indexing. 

https://www.dropbox.com/s/dhhyeumhtpdd96g/isladuala3.zip?dl=0

As the story goes, I did have to make some judgement calls on this map. Quite a few actually (such as not allow most non-enterable OPX buildings to spawn civs, etc. That seems to be the consensus on how to handle those buildings so I followed suit). Anyway, I think everything looks fine now, but if anything stands out to anyone and they feel like manually editing the statdata, I definitely don't mind generating the cluster data again if need be.

Anyway, if you get a sec and can test the index, that would be sweet. And thanks for the help.

**Comment by AUTigerGrad** [comment]
I'll grab this index tonight and test it on one of my missions to make sure it's working properly.

**Comment by HeroesandvillainsOS** [comment]
Thanks man. I'd be curious to get your take on it. As I said, my time was super limited in testing this, but I have a suspicion if an insurgency is even possible on this thing, one would need to essentially let civs spawn at the max. And even then, some areas would likely be "dead" zones for civvies due to the crazy amount of non-enterable OPX stuff (though don't take my word on any of this, please test it).

That said, I was pleasantly surprised in one town I went to where even though it was pretty much all OPX, some decorative shacks on the outskirts  had civs spawn and they populated my immediate area nicely, running into the city proper, and doing their civvie thing. :)

Another thing is, now that it's error free, I see this map has an unholy amount of objectives (beware of load times!). And I'd say it's almost equal in military objectives to civ objectives too which is highly unusual for any map I've ever looked at, but I guess this is how Icebreakr rolls.

Let me know what you think but bare in mind, I don't really think there's anything I could or would do differently if I had to index it again. This is why I was suggesting if someone was intimately familiar with specific building types and classnames that I may have made a bad call on, that they manually add them to the static data for me, and then I can generate the clusters again.

As I said, I feel good about the way I handled it but I know people have been waiting for this index for a long long time and I really do want it to be as perfect as possible.
