### ISSUE TITLE
Orbat creator's auto generator creates incorrect civilian CfgGroup classname

### ISSUE THREAD

**Issue by DarrellJMartin** [ALiVEOS/ALiVE.OS#285]
**Issue**
I first spotted it when using the addon 'CUP Takistani Civilians by AUTigerGrad'
[https://forums.bistudio.com/topic/200068-takistan-civilians-for-cup/](url)

When auto generator creates a civilian CfgGroup the classname is incorrect causing a warning message and popup when it's loaded into the game:

```
10:26:18 Warning Message: No entry 'bin\config.bin/CfgGroups/CIV.side'.
10:26:18 Warning Message: '/' is not a value
```

The bad line is in the autoGen.hpp output:

```
class CfgGroups {
    class CIV {
```
   
This should be auto generated as:

```
class CfgGroups {
    class Civilian {
            name = "Civilian";
            side=3;
```
**Repro**
Select 'Civilians' for Side.  'Export'->'Full faction' outputs the wrong CfgGroups classname to the clipboard
![arma3 2017-02-09 13-40-29](https://cloud.githubusercontent.com/assets/8157728/22786087/0e0fbaae-eecf-11e6-93df-37b8a633ccf9.png)

**Comment by SpyderBlack723** [comment]
Fixed with 50cac6051f14662153192c5e813546b5de668986

Thanks for the awesome ticket!
