### ISSUE TITLE
[sys_profile] Profiles are not being spawned when resuming a mission on dedicated

### ISSUE THREAD

**Issue by SpyderBlack723** [ALiVEOS/ALiVE.OS#290]
1. Occurs only when Pause Modules option in ALiVE (Required) module is set to true
2. Profiles continue to be simulated

Server RPT: https://drive.google.com/file/d/0Bw_0pq1lFzt9Rjd1LVQ0ZklQVW8/view?usp=sharing

Forum Post: http://alivemod.com/forum/2763-units-not-spawning-into-view-from-virtualization/0#p18679

**Comment by coachwn** [comment]
NOOOOOOOOOOOOO! I was hoping to utilize the pause functionality in my upcoming mission. Guess we will go back to the old "Hope ALiVE doesn't shit on us again" thought process till this is fixed.

**Comment by SpyderBlack723** [comment]
Please test for yourself before making an assumption. This feature has been in the mod for several releases and we've had no prior reports so this could very well be a case of something else causing Init to fail.
