### ISSUE TITLE
Civilians stay in formation

### ISSUE THREAD

**Issue by Ghost-USML** [ALiVEOS/ALiVE.OS#291]
in the new update of alive civs now spawn in groups and stay in formation wedge when they respawn
[AMB_CIV] #205 Single group maintained for all ambient civilians
[AMB_CIV] #205 Simplified ambient vehicles chance algo
its unrealistic they behavior and the leader wont stop form screaming  orders.

how to reproduce
place ambient civs module and wait for them to spawn 
wait a couple of secs so all of them get to the formation

**Comment by coachwn** [comment]
@Scotty_Z this might be part of out issue as well.

**Comment by SpyderBlack723** [comment]
Already foxed

**Comment by coachwn** [comment]
I understand it is fixed but we are seeing missions in testing where all the civs run out of towns and get into formation around their "leader". I am using CIV_F on Tanoa and seeing this happen. Thanks for being ahead of the game there @SpyderBlack723.
