### ISSUE TITLE
Faction generated in ORBAT Creator not showing up with gear in mission

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#294]
I just need someone to work through this and let me know if the code output is correct for the individual troops? Something is off in how it all is working in the mission. In the editor it shows up correct but when on a dedicated server its off somehow. Here is the faction output from the ORBAT and already packed up for play.

https://www.dropbox.com/s/pc0z4pra3s804ey/%4015th_PLA.rar?dl=0

I can provide an RPT file if needed along with mods for the mission I am working on.
15th PLA Steam link faction: [http://steamcommunity.com/sharedfiles/filedetails/?id=867968975](url)
Mission Mods: [http://steamcommunity.com/sharedfiles/filedetails/?id=869939527](url)

**Comment by SpyderBlack723** [comment]
Do you have the correct mods on the server?

**Comment by coachwn** [comment]
Yep its weird....I can't understand what is going on here.

**Comment by coachwn** [comment]
I have no idea whatsoever about the reasons these guys are showing up without gear in their vests and uniforms. They are showing gear when I break them down from the editor but looking at how ORBAT Creator outputs that text file its really weird.

**Comment by SpyderBlack723** [comment]
If it works on client and not the server then it only leads me to believe there is an issue with unsycned mods. Try cresting a vanilla test faction and seeing if that works.

**Comment by coachwn** [comment]
@SpyderBlack723 OK quick question since the ORBAT is your baby. What is happening with all the quotation marks and commas and brackets from this output? This if for my PLA Fire Team Leader slot and is just one example of what is happening; class name in my faction is "O_15thPLA_Fire_Team_Leader_01"

`init = "if (isServer) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['vme_pla_qbz95_1GL','','','VME_Eotech_557_Magnifier_DOWN',['VME_QBZ95_1_30Rnd_DBP10',30],['VME_1Rnd_HE_GL',1],'VME_rail_scopes'],[],['vme_pla_qsw06','','','',['VME_QSZ92_20Rnd_DAP92',20],[],''],['PLA_CombatUniform_SGCB',[['acc_flashlight',1],['ACE_fieldDressing',4],['ACE_morphine',2],['ACE_elasticBandage',4],['ACE_epinephrine',2],['ACE_packingBandage',4],['ACE_MapTools',1],['ACE_EarPlugs',1],['Chemlight_yellow',1,1],['Chemlight_red',1,1]]],['PLA_T15Vest_RD',[['SmokeShellGreen',1,1],['SmokeShellRed',1,1],['HandGrenade',2,1],['1Rnd_HE_Grenade_shell',5,1],['1Rnd_Smoke_Grenade_shell',1,1],['1Rnd_SmokeRed_Grenade_shell',1,1],['1Rnd_SmokeGreen_Grenade_shell',1,1],['1Rnd_SmokeYellow_Grenade_shell',1,1],['1Rnd_SmokePurple_Grenade_shell',1,1],['VME_QBZ95_1_30Rnd_DBP10',5,30],['VME_QSZ92_20Rnd_DAP92',2,20],['SmokeShell',2,1]]],['PLA_AssaultPack_Base',[['VME_1Rnd_HE_GL',9,1],['VME_1Rnd_Smoke_GL',2,1],['VME_QBZ95_1_30Rnd_DBP87',2,30]]],'VME_PLA_Helmet_R','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','ACE_NVG_Gen1']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";`

**Comment by coachwn** [comment]
I will get around to making a new faction this afternoon when I have some time.

**Comment by SpyderBlack723** [comment]
I replaced th method of adding gear with setunitloadout because it is MP compatible and is shorter in length. Empty quote marks are simply empty item spots (like not having are secondary etc).

**Comment by JustOtherAnotherDude** [comment]
Same error here. Preview the units on the editor, and they show with the changes applied. Load them ingame, and the clothes are nowhere to be seen. It loads everything gear related, except the uniform, and the gear inside it.

The test was done using vanilla clothes (U_C_man_sport_3_F, for example), but still get the clothing from the first parent class (LOP Boko haram riflemam). The setUnitLoadout is correct. Everything works fine when the code is executed manually on the player. Maybe it gets overwritten or something.

The rpt is clean, and I can provide the faction pbo, but there is nothing special about it.

**Comment by SpyderBlack723** [comment]
Items appear to be added locally to the server, so players cannot see them, but the AI will still use them. setUnitLoadout is apparently not using the proper methods for adding gear in MP.

**Comment by JustOtherAnotherDude** [comment]
New test just done. setUnitloadout works perfectly when executed by the server. The MPRespawn on the other hand... "MP EHs are added on every PC and execute on every PC, apart from MPRespawn, that only executes at the locality where unit respawns." 

Maybe there is another method to call _onSpawn?

**Comment by SpyderBlack723** [comment]
That is only executed on players. From what I understand, this issue concerns AI, which cannot respawn.

**Comment by JustOtherAnotherDude** [comment]
Ahhhh, nevermind that, you are right. Still, is weird that only the uniforms won't work.

**Comment by coachwn** [comment]
I don't have issues with the uniforms. I have issues with no weapon magazines or grenades showing up and in some cases no weapons like rocket launchers.

**Comment by coachwn** [comment]
Reworked faction again today and did an export on the faction with the newest released version of ALiVE and Arma 3 and still not change from what I stated when I started this.

**Comment by coachwn** [comment]
We are still having this same issue with another faction not showing up with ammunition, gear, etc... when ALiVE spawns them in on our mission. We did not make the faction we are currently using. It is the [African Factions for CUP](http://steamcommunity.com/sharedfiles/filedetails/?id=810913902) that @AUTigerGrad made.

**Comment by coachwn** [comment]
Is there a possible workaround on this or should I just stop utilizing ORBAT made factions until/unless BI addresses the setunitloadout problem? 

I made a [post](http://alivemod.com/forum/conversation/post/20681) about it on the ALiVE forums a couple of weeks ago with no additional way to work around it short of just not using the ORBAT Creator right now.
