### ISSUE TITLE
No random patrols

### ISSUE THREAD

**Issue by Knight1981** [ALiVEOS/ALiVE.OS#299]
We have the problem (with all maps and factions, also vanilla) that no random patrols will be spawned around the player. Only CQB enemys in buildings, random camps and civilians in buildings are working fine but no random patrols e.g. in forests are spawning. Do you have an idea what could be wrong?

CBA: 3.2.1.170227
Alive: 1.3.0.1702201

**Comment by HeroesandvillainsOS** [comment]
Unit won't spawn randomly in forests. They need objectives to spawn. You can increase the likelihood of patrols in the beaten-paths by using the random camps option in the MIL Placement Objectives module, and/or create your own custom objectives though.

And note, units will patrol through "empty" areas as they make their way to objectives.

**Comment by friznit** [comment]
There is no such ALiVE functionality.

**Comment by Knight1981** [comment]
Oh okay, damn. We deactivated the camps, maybe that is the reason why we only have enemys in the citys walking around but no patrols through the jungle and forests :-/
