### ISSUE TITLE
[sup_player_resupply] Add wind indicator and drop zone position estimation to tablet

### ISSUE THREAD

**Issue by DavisBrown723** [ALiVEOS/ALiVE.OS#302]
Tablet should show the current wind direction and strength, and maybe even an estimated position based on the object's weight (if that is a factor), current wind speed, and current wind direction.

**Comment by friznit** [comment]
See also #324

**Comment by DavisBrown723** [comment]
Not really necessary with https://github.com/ALiVEOS/ALiVE.OS/issues/324
