### ISSUE TITLE
Roadblock Persistence reloading error

### ISSUE THREAD

**Issue by willithappen** [ALiVEOS/ALiVE.OS#304]
`17:16:38 Error in expression <ebug"] call ALIVE_fnc_CP;

while {count ALiVE_civ_placement_ROADBLOCK_LOCATIONS >
17:16:38   Error position: <ALiVE_civ_placement_ROADBLOCK_LOCATIONS >
17:16:38   Error Undefined variable in expression: alive_civ_placement_roadblock_locations
17:16:38 File x\alive\addons\civ_placement\fnc_CP.sqf, line 609`

This seems to cause failure in loading/saving of object persistence and stops placement of ALiVE Markers.

Can provide more info if needed. Only noticed this recently after a save appeared to save correctly and then vehicles that were moved were replaced at original positions.

[arma3server_2017-03-08_17-03-04.txt](https://github.com/ALiVEOS/ALiVE.OS/files/826956/arma3server_2017-03-08_17-03-04.txt)

[aliveplugin_2017-03-08_17-13.txt](https://github.com/ALiVEOS/ALiVE.OS/files/826955/aliveplugin_2017-03-08_17-13.txt)

EDIT: This may also have corrupted my data that begins saving to war-room http://alivemod.com/forum/2788-alive-war-room-not-displaying-recent-data mentioned there.

**Comment by willithappen** [comment]
The roadblock/camp saving in ALiVE Data had to be disabled due to errors stopping correct saving/loading of data.

Also relates to a stop in info being sent to the war-room as info linked above.

**Comment by HeroesandvillainsOS** [comment]
Can you try the ALiVE RC version and see if it's resolved? Sounds like it's the same issue as this which is fixed in the test build: https://github.com/ALiVEOS/ALiVE.OS/issues/261

**Comment by HeroesandvillainsOS** [comment]
Link to RC: https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.3.0.1702201

**Comment by willithappen** [comment]
Greetings, i've been otherwise occupied an not able to test the RC Build. Will using this and then returning to use the public branch cause any data issues?

I'd be happy to confirm the error no longer occurs, however, i'm concerned it would corrupt our current status in our campaign.

**Comment by HeroesandvillainsOS** [comment]
I'd never recommend using a newer version and then going back to an older version but who knows. I was more or less saying I had the same issue and I think they fixed it, but a simple test mission would confirm that if you have the time to set something up to test with.

**Comment by marceldev89** [comment]
I don't think there have been major data changes so my bet would be on that the (current) stable and test builds are mostly compatible data wise.
