### ISSUE TITLE
Insurgency Demo

### ISSUE THREAD

**Issue by Neodyn** [ALiVEOS/ALiVE.OS#306]
It seems there is a problem with ALIVE spawned enemy Units in the Insurgency Demo. 
If one of this units got killed, no intel will drop (Intel ratio 100%). If i place a unit via ZEUS every killed unit drops an intel.
Mybe there is an handle issue: https://github.com/ALiVEOS/ALiVE.OS/blob/master/demo/MP/ALiVE_Insurgency_Redux.Altis/functions/fn_handlerRegister.sqf ?

**Comment by HeroesandvillainsOS** [comment]
Hazey hasn't updated this mission in a long time and it's my understand quite a few of the features are not working right now.

This insurgency is quite different from the traditional (and supported) insurgency model that's included in ALiVE, and uses custom scripts that haven't been updated in a while. I do believe if you look on BI forum, in Hazey's thread, some users have done their best to update it though, so maybe take a look there.

**Comment by highhead** [comment]
I also made a nice Insurgency Demo for Tanoa and thought I'd share it with you! Enjoy!

http://s000.tinyupload.com/index.php?file_id=84005196486004055624

I will close this ticket, as the old version is not maintained by us anymore! You might be lucky on the BI forum though!
