### ISSUE TITLE
Units in garrison dancing

### ISSUE THREAD

**Issue by ShizCalev** [ALiVEOS/ALiVE.OS#307]
Units in a garrisoned position (ie in a building or bunker) are exhibiting the same dancing issue as CBA had with taskdefend due to the usage of the broken setUnitPos "UP" command. 

Units will try to go prone per AI logic but get stuck in an animation loop due to the script trying to force them to stand back up, resulting in them not shooting unless the enemy gets within 2m of the target.

Related issue with the same command; https://github.com/CBATeam/CBA_A3/issues/551

Affected file; https://github.com/ALiVEOS/ALiVE.OS/blob/83c2de4841eec0611cef91c5c7c07cb780a8018b/addons/x_lib/functions/behaviour/fnc_groupGarrison.sqf

**Comment by SpyderBlack723** [comment]
Specifically, 

> Yeah so after some testing, I think this is the result of the combination of disableAI "PATH" and setUnitPos "UP".

**Comment by highhead** [comment]
hmm, i am not getting the dancing issue with A3 1.68, ALiVE (master) and CBA_A3 (3.2.1.170227), Altis.

Is there a way to repro that?

**Comment by highhead** [comment]
ahh seen, needs to be under fire
