### ISSUE TITLE
Error with weather query - "you must supply a location query" w/ GetWeather

### ISSUE THREAD

**Issue by ShizCalev** [ALiVEOS/ALiVE.OS#309]
http://pastebin.com/HTC4vvnq

Getting this error when using real weather w/ alive weather module. It's pulling the location correctly, however it's giving an error when it queries for today's weather.

**Comment by SpyderBlack723** [comment]
@tupolov

**Comment by friznit** [comment]
Try OS/VIENNA

Wunderground codes are slightly different from ISO codes.

**Comment by ShizCalev** [comment]
@friznit same thing with OS/Vienna. It just returns more cities.

http://pastebin.com/LF045BAs

**Comment by ShizCalev** [comment]
Hm. Also getting a buffer overrun if I try a simpler location like NY/New_York

http://pastebin.com/Qe9Jb12d
