### ISSUE TITLE
Can't Blacklist Vehicles From Peristence

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#31]
From what I can tell, there seems to be no way to stop vehicles from saving with persistence enabled.
Using the Player Logistics (Disable) module, we have a field for Blacklist, which works perfectly with normal objects (like ammo crates, supply boxes etc), but does not work at all with vehicles of any kind (air, land, sea).

I have tried inputting classnames of the vehicles, as well as syncing the vehicles with the module. No effect.

Being able to blacklist vehicles from persistence saving would be a great feature to add simply because bases can get messy very quickly if people do not park things back exactly where they are supposed to go, because wherever players leave vehicles when they disconnect, is where they are going to be when we load back in.

**Repro:**
1. Open eden editor
2. Place player unit
3. Place vehicle of any kind
4. Place ALiVE modules - including Player Logistics (Disable)
5. Input the classname of the vehicle you placed into the Blacklist field of the Player Logistics (Disable) module
6. Preview, get in your vehicle, move it to a new position, get out.
7. Save your session

**Comment by tupolov** [comment]
From what I can see in the code, vehicles are updated when someone gets out of the vehicle. This code does not consider the blacklist...

https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/sys_logistics/fnc_logistics.sqf#L860
