### ISSUE TITLE
x\alive\addons\main\static\chernobylzone_staticdata.sqf not found

### ISSUE THREAD

**Issue by Robdemi** [ALiVEOS/ALiVE.OS#311]
I have done research and have seen what this actually is. I tried using the map index module but I can not make it work with the map that I am trying to Index. I keep getting an error and it's telling me to check my RPT. Was wondering if you are able to index this map and put it in the future release. 

This is the map I am trying to index http://www.armaholic.com/page.php?id=21332

this is my RPT file https://justpaste.it/14sax

**Comment by HeroesandvillainsOS** [comment]
Which option are you using in the indexing object categorization? You'll want to select the option where you need to classify them yourself. I think this might be what's causing your error.

**Comment by Robdemi** [comment]
I think I put yes.

**Comment by HeroesandvillainsOS** [comment]
Did you classify the buildings yourself after you said yes? Or is it failing the second you open the tablet and click map indexer?

**Comment by HeroesandvillainsOS** [comment]
Post a screenshot of your indexing module so I can see the options you selected.

**Comment by Robdemi** [comment]
Have no idea what that means. I tried to follow the instructions on the Alive index page and I never had to do that.

**Comment by Robdemi** [comment]
I'm currently at work. I'll put it up when I get back.

**Comment by HeroesandvillainsOS** [comment]
For this map, since no existing staticData exists, you'll need to use the option for you to manually classify the objects. After opening the tablet, you'll get taken the object categorizing UI where you'll have to choose what kind of object everything is (civ, mil, etc). That's assuming it's all working correctly. When you get a chance, open the module and share a screenshot and I think that can help narrow down the issue.

**Comment by Robdemi** [comment]
http://i.imgur.com/CiqNqSp.jpg

**Comment by HeroesandvillainsOS** [comment]
It's possible the map PBO name is case sensitive. I don't know this to be true but it's worth a shot. Can you double check that you have it written correctly? "Chernobylzone.pbo"

Are you running -filePatching?

**Comment by HeroesandvillainsOS** [comment]
Chernobyl Zone is a Workshop only mod, right? If so, I don't think your path is correct. It would be stored in !Workshop by default.

Also, make sure your @ALiVE is in the Arma root folder. Do not use the !Workshop path for your ALiVE when indexing maps. I have two versions of ALiVE, specifically for map indexing purposes. I play with the Workshop one, and index with the mirror which I keep in my Arma root.
