### ISSUE TITLE
Alternative tablet model not found when accessing Intel-section

### ISSUE THREAD

**Issue by Asmodeuz** [ALiVEOS/ALiVE.OS#312]
First of all, thank you so much for including the alternative tablet model as part of your great modification and even more so (Spyder!) for creating an easy way to select between the two currently available models!

I took the alternative cover for a test ride and noticed that when accessing _Commander Actions >_ --> _Intel_ the game displays an error **Resource SCOMTablet_MapBag not found** and the tablet doesn't get displayed. See linked picture for reference: http://s1370.photobucket.com/user/testusah123/media/Mapbag_Intel_ResourceNotFound_zpsp006rtxx.jpg.html

On the other hand the other sections (_Personnel, Logistics, Tasks, Operations, Send SITREP, Send PATROLREP_)  work flawlessly.

**Comment by SpyderBlack723** [comment]
Already fixed

**Comment by SpyderBlack723** [comment]
Will be available with next release

**Comment by SpyderBlack723** [comment]
Oops

**Comment by Asmodeuz** [comment]
Lighting fast! Have to appreciate that!
