### ISSUE TITLE
CQB weapons spawning on porches and inside walls of houses on Tanoa?

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#314]
As the title says I am seeing more CQB weapons spawning right inside the wall on front porches and balconies than on roof tops in towns. The AI soldiers manning the CQB static weapon is partially in the wall and often times doesn't react or see people when they walk right up on them. Is there something I am doing wrong on my mission or is this an unintended consequence of wanting them to be in emplacements on the rooftops?

[http://steamcommunity.com/sharedfiles/filedetails/?id=890692259](url)

[http://steamcommunity.com/sharedfiles/filedetails/?id=890692472](url)

Just recently started noticing mortar emplacements as well and they are in same places as the others.

[http://steamcommunity.com/sharedfiles/filedetails/?id=897068547](url)

**Comment by coachwn** [comment]
Any ideas on this one?

**Comment by SavageCDN** [comment]
I'm guessing those porches and balconies are considered 'rooftops' by the game.. not sure if there is an easy way around this unless we can blacklist those building types from spawning statics.. @highhead ?

**Comment by coachwn** [comment]
@SavageCDN I can try that on my next update of the mission. Right now I am updating it to see if it stops things like this from happening. At the moment I have completely disabled the CQB static weapons function because it was just too much and if I need weapons to spawn in then I will drop them via Zeus on rooftops and place a unit on it then profile that unit via the alive admin console.

**Comment by friznit** [comment]
Should be improved a bit but may always be an issue due to BIS things.
