### ISSUE TITLE
Ambient Sea Patrols set waypoints on land

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#315]
Starting today I began noticing the way that AI sea patrols work is they generate in the water but invariably they want to drive their boats onto land and then go walk for several KM.

[http://steamcommunity.com/sharedfiles/filedetails/?id=890692683](url)

**Comment by HeroesandvillainsOS** [comment]
404 not found on your image

**Comment by highhead** [comment]
There is no AI path planning done at all. The way it works is, that if a group touches water a boat of the faction is created and a waypoint is set for the nearest shore to the final destination in relation to the current groups position. There is and there will not be any advanced route plotting. Of course, if you prefer it the old way, you can just switch it off again.

**Comment by highhead** [comment]
Wanted to add: sorry if this closing seemed to be blatant. Are you talking of sea patrols (the option on the placement modules) or the new "sea transport" feature on Virtual profiles modules.

From the screenshot it looks like a random patrol on a nearshore-island that got random waypoints passed on the main land and therefore is trying to move by boat over water.

**Comment by coachwn** [comment]
No these are boat with occupants  that I have created in my faction and they are working in the sea patrol option that is turned on in one of the modules (Sorry can't remember which right off top of my head). This boat and all others will spawn in the along the coast and will set a waypoint into the nearest landmass. If the troops who are part of the boat would exit the boat and then patrol it would be one thing. However none of the troops exit the boats when they touch land and instead attempt to continue driving along towards the next waypoint. I can supply video if needed.

**Comment by friznit** [comment]
Have repro'd - set up a basic Alive mission on Tanoa with Zeus enabled.  Go into Zeus and observe some sea patrols setting waypoints on land

**Comment by tupolov** [comment]
If sea patrols have divers, they will set waypoints in land around any nearby objectives. This shouldn't involve boats though. The boat waypoint system is setup to never have waypoints on land or have land between waypoints.

**Comment by coachwn** [comment]
None of the patrols have divers. Also most of the time the boats appear with their initial waypoints immediately off the coast and then they have waypoints that will be off in the middle of the various islands in the Tanoan map area. Sometimes the AI in the boats get out and walk the patrol route until they have to swim and then they swim the rest of the route. Other boats will continue attempting to drive and will damage the boats or blow them up.

**Comment by tupolov** [comment]
Someone got a repro mission for me? Upload unbinarized mission?

**Comment by coachwn** [comment]
@tupolov I just read where @friznit had a repro mission he had done. IF you want to download my entire mission and give it a look I can point you at the Steam Workshop for all the mods...however I understand that you may want a basic version so I can put one together if Friznit does not have his repro mission available still. Just let me know.
