### ISSUE TITLE
[sup_command] Intel menu color keys have onclick EH's attached

### ISSUE THREAD

**Issue by SpyderBlack723** [ALiVEOS/ALiVE.OS#317]
The listbox should not have any on-selected event handlers attached when it's displaying a color key..

**Comment by HeroesandvillainsOS** [comment]
Sorry if unrelated but I think it's the same thing. When clicking the unit marking, you get taken to a menu to select side-types (BLUFOR, OPFOR, etc) in a similar way to the color keys.

Example, I'm playing as BLUFOR. Select unit marking (which reveals units on the tablet map) but the left side menu will let me click on sides (which don't do anything, not that I expected them to). 

I'm assuming the sides revealed in the list in the tablet are also a key, and not designed to be interacted with (am I wrong on that?). Perhaps whatever fix you guys implement for this can be extended to the side-types, to make it clear the sides in the list are just keys and not to be confused with 'click to reveal new/different info?'

**Comment by SpyderBlack723** [comment]
That is the color key, the functionality remains the same. Just don't click the list for now.

**Comment by HeroesandvillainsOS** [comment]
Ok. Gotcha. I thought you were just talking about the color key/guide what the different intel markers represent. Thanks for clearing that up.

**Comment by SpyderBlack723** [comment]
2d201f806e8d330c0bf46b46aba5422d981624dc
