### ISSUE TITLE
Transport Combat Support occassionally won't land and hovers into outerspace

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#319]
Odd issue. Transport support choppers, in some circumstances, will take Land or Pickup orders, fly to the location, then instead of touching down, will immediately begin ascending to Heaven.

Here is a repro mission that demonstrates this clearly on Takistan (Requires CBA, ALiVE, CUP Terrains): https://www.dropbox.com/s/upizpvowrnn5fab/Transport_test.Takistan.pbo?dl=0

Repro steps:
1. Open the commander tablet and combat support
2. Select the transport chopper FALCON ONE and give him a Land order
3. Have him land on the marker directly in front of you that I placed in the mission
4. Wait a minute or two for him to arrive (I purposely placed this chopper on the opposite side of a mountain at a different base to your south)
5. Once he arrives, watch how he levels out, then at the moment you'd expect him to being his landing processes towards the ground, he'll immediately start to raise his elevation up and up and up until you can't see him anymore.

**Comment by docbuchanan** [comment]
Also experience this.  Tried different maps, different birds from vanilla and from
Mods.  No luck.  Thought it was vcom so removed that and the NOAi variables I had set, not alleviated.  It seemed to be fixed in an earlier update but now it is back.  Frankly transport is not usable at the moment, because they also won't land after rtb

**Comment by HeroesandvillainsOS** [comment]
@docbuchanan It took me in the neighborhood of 8 editor hours to isolate this into a 100% reproducible mission.sqm 

And even in this repro mission, I can call the same chopper in the same fashion to just about any other map location than the one this repro requires and the bug doesn't appear. So in other words, I find this bug to be extremely rare.

What map are you using? Can you repro it without mods aside from the map? I have a hunch this is related to elevation and something screwy messing with land waypoints.

**Comment by highhead** [comment]
sounds like a challenge... on it

**Comment by highhead** [comment]
so - thats weird.

but it's not ALiVE. We are using a "GET OUT" order on the given position, and even trying to override issues by creating with a fake helipad makes the heli go up straight on the given position.

It could maybe be recreated with A3 only and get out waypoint, but as the simple workaround is to chose a position nearby (like 500 mtrs off) I am not going to dig deeper. 

in your case heroes, just shift the base if this landing spots causes it in your mission. if thats an option?

**Comment by HeroesandvillainsOS** [comment]
Sure that's an option. I'm a bit reluctant to just leave this be though, because although this particular location is unique to Takistan, I'd have to assume on other maps this could be more frequent depending on the terrain.

So what's the cause in your best estimation, exactly? Is it the GET OUT waypoint mucking up due to the elevation the helo needs to take to this particular base?

The reason I ask is, I would like to make a non-ALiVE, vanilla only repro so I can report it and demonstrate it to the Arma BI Devs. You have a much better grasp on this stuff than me. What would be your best guess for how I can easily recreate this in the editor (I've never really experimented with vanilla waypoints too much)?

And do you think I could find a suitable spot for this freak out on Altis, Stratis or Tanoa?

**Comment by docbuchanan** [comment]
So my current mission is on FATA.  I have a very hard time getting a uh-80/uh-60 to land, little birds do better.  Chinooks don't do it at all.  Fata in general and the FOBs on FATA are cramped.  LZs are always close to some structure... which is not ideal.  And the ground is often more uneven than other maps in the field.  AND it's rather mountainous.  Which leads me to believe it's something with the function to find a safe landing position, and not wanting to get too close to structures or too steep a slope.  Or perhaps like you said, elevation.  Sometimes though, they'll pick the most unsafe position imaginable and actually land there.. like on top of enemy, or a Hemtt.  Quite hilarious.  

Yes I can reproduce in vanilla and those birds do better but it's still there.  Rhs is by far the worst for it.  Thing is... tons of groups use rhs including mine.  

This has often been an issue in ALiVE for me, so I tried it on Tanoa and Altis with better success, but still probably a greater fail rate than success rate.  In general... Helicopters are plain hard to get right.  Assuming there IS a function like the one I'm talking about, maybe try loosening the position restrictions?  Or make it land on the dot, every time, and depend on player sense to pick the right spot.  Not sure man.  Perhaps use positionASL over ATL, or vice versa.  Haven't looked at function.  But yeah it's something there.

**Comment by HeroesandvillainsOS** [comment]
Also, the worst past about this is, is it's something that can't be recovered from. So imagine, you're playing with your friendly online and you happen upon one of these spots unknowingly. It's certain death! And you lose your chopper too. :(

**Comment by docbuchanan** [comment]
Yeah the only way around it is to rope in, if you're using ace.  But for a pick up... at a hot Lz... when trying to sell a 450 man unit on ALiVE and the bird straight up says screw you and leaves us there when seconds from the ground... it's bad, lol.

**Comment by HeroesandvillainsOS** [comment]
@docbuchanan I don't want to get too far off topic here. Trust me, I can emphasize. I play on FATA and CLAFHAN lots of odd maps too and agree the landing and RTB'ing could always be better and less frustrating. But this helo hovering towards heaven thing is a bit different I think.

Is that's what's happening to you? I just don't want to get multiple complaints tied into the same thread and just want to ensure we're talking about the same bug (helos flying into outer space! Lol).

**Comment by docbuchanan** [comment]
Well my issue is it will go to land, then stop, take off, try a different spot, stop, go back to the first.  Rinse repeat.  Eventually it'll give up and hover.  Same thing happens for resupply.

**Comment by coachwn** [comment]
If you have a 450 person unit why are you using ALiVE for logistics to supply reinforcements of players? Not criticizing at all but Arma as a whole has NEVER been reliable for automated landing and pickups or anything. 

ALiVE is great but honestly our group; which has been using ALiVE since it was in Alpha back in 2013; has never utilized it for any of the logistics functions for the players. The primary reason is that there are way to many issues for the system to function properly in my opinion. Heck I see it daily when we attempt to have AI fast rope into an LZ as a QRF against our players  who are fighting as insurgents.

**Comment by docbuchanan** [comment]
You raise a good point in that on operations the heli stuff would not be implemented.  However we "train" twice a week down to 4 man teams, and often during those sessions we don't have the benefit of an aviation element accompanying us.  It's also intended for use as a recruiting server someday, so there's that.  Suffice to say, to implement anything in the group one must prove efficacy beyond a shadow of a doubt.  If that makes sense.

**Comment by coachwn** [comment]
I get it. If you guys want to see how we utilize it feel free to drop by on our server and take a look. Also I will be glad to let you have our current mission for some play testing and functionality work as well. [www.spearheadgaming.net](url)

**Comment by HeroesandvillainsOS** [comment]
@highhead I'm running a couple of non-ALiVE tests on this specific flight course on Takistan, and I can't seem to reproduce the issue. 

1. If I place a GET OUT waypoint, so basically a straight line from the southern base to the troubled spot, the helicopter actually comes in just left of that really high mountain, and lands just fine.

2. If I give the helicopter a MOVE waypoint, forcing him just a bit to the right so he has to scale the high mountain to get that that same landing zone, and then give him a GET OUT waypoint at the troubled location, he still lands just fine.

I'm not doing anything to alter flyinheight or anything like that.

Is it possible there's something more going on here. If vanilla GET OUT works ok, I'm still leaning towards ALiVE being part of the problem. Can you tell me more about what happens behind the scenes when a "land" order is given to a support chopper. Is it simply a GET OUT waypoint, with flyinheight and speed adjusted internally?

Any ideas why I can't reproduce this without ALiVE?

**Comment by highhead** [comment]
It's a bit different!

We are using _chopper land "GET OUT" (for "land") and _chopper land "GET IN" (for pickup), not waypoints. So it may be related to those commands (which basically should hover a bit over ground and not land completely). In vanilla, it would mean placing a move waypoint over the broken spot and then call (vehicle player) land "GET OUT" in A3 vanilla debug console.

**Comment by HeroesandvillainsOS** [comment]
Thanks. I can set this up later. Can you get me the functioning code in a literal example? So if I name the chopper p1, I give it a move waypoint and then type (p1) land "GET OUT" in debug?

Then what do you think...send the repro to BIS or CUP?

**Comment by HeroesandvillainsOS** [comment]
This issue is reproducible without ALiVE using GET OUT waypoints, so seeing as it's unrelated to the ALiVE mod, I'm closing the ticket. The best guess at the time being is this is somehow related to ground objects interfering with the landing logic, because on an empty base, the chopper lands just fine.

**Comment by docbuchanan** [comment]
As stated in the BI documentation, get out waypoints are not used for transport of cargo personnel, since they make all units get out.  and transport unload does not work with player controlled groups.  If alive is using this waypoint... would explain the issue.  Sorry to comment after close, but I'm fairly convinced the issue is ALiVE related.  Unless as commented, I'm perhaps using the wrong issue for the problem I've described.

**Comment by SpyderBlack723** [comment]
This issue is related to helicopters not landing, this is solved by removing the nearby objects. I don't see the relation between waypoints types...

**Comment by HeroesandvillainsOS** [comment]
@highhead provided me with some pretty definitive proof this is related to objects in some way. Regardless, because I don't pretend to know the exact problem, this can be duplicated without ALiVE. @docbuchanon if you can come up with a solid way to repro the issue, I'd encourage you to forward your findings to BIS (or CUP, in the event it's related to one of their objects in some way).

My repro mission is above so feel free to mess around with it and see what you can come up with.

**Comment by HeroesandvillainsOS** [comment]
Also, I'm more than happy to reopen this if you can determine ALiVE is the issue, but I don't see that being the case at this point in time.

**Comment by highhead** [comment]
The issue was replicated with the mission above and all ALiVE modules deleted - so ALiVE not running at all - in a regular vanilla chopper ("B_Heli_Transport_01_F") and a regular "get out" waypoint. The chopper went to the skies everytime.

Removing all hand-placed objects from that base made the chopper land regulary.

**Comment by pablodma** [comment]
Hi everyone!
I've been experiencing this issue for a while. Also noticed that ARTY isn't responding to fire mission commands, and SUPPORT just fly around and doesn't engage any targets.  This only happens after being playing the mission for a few hours. Once it starts to fail, then you cannot fix it, even if you restart the server and delete database (I'm using a non-alive system to save locally mission progress)
Heres my RPT file. It will be great if anyone could help me to detect any problem

https://pastebin.com/ArXU30XF
Thanks!

**Comment by pablodma** [comment]
Nevermind, i've just fixed the issue by moving alive support units out from HC
`this setVariable ["acex_headless_blacklist", true];
`
