### ISSUE TITLE
Zeus Virtual AI 'Anchor'

### ISSUE THREAD

**Issue by aritsune** [ALiVEOS/ALiVE.OS#321]
So right now ALiVE correctly spawns in profiles around the Zeus camera, however when the curator tries to remote control a unit in the area they all despawn (I assume this is because the camera goes to [0,0,0] during remote control, and I think there's no way to detect which units are being remote controlled).
My suggestion to sort-of-fix this is to have a Zeus module you can place down that ALiVE will treat as a player and will spawn things around, kind of like an anchor, that way Zeus can remote control units that aren't near any players. Since this would be kind of abusable to nuke the server's performance, you could limit the amount of anchors that can be placed down at any one time.

**Comment by SpyderBlack723** [comment]
@friznit Requesting scope evaluation

**Comment by highhead** [comment]
It is definatly out of scope, but there were some similar Zeus requests and I decided to take a look at it, while I was on it. I improved it in a way, that you can now remotely control units and the controlled character will be treated as a player object.
