### ISSUE TITLE
Masses of Units Spawn At Map Origin [Grid 000,000]

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#322]
So, I had a previous issue report regarding this problem some weeks ago, but ended up cancelling it due to a lack of information and/or a consistent reproduction mission.

**Issue report:**

On certain maps only (this issue does not appear to happen on Startis, Altis, etc), masses of units spawn at the map origin, which is grid [000,000], or the bottom left corner of the map. This mass of units does not despawn and continues to multiply over time (mass of units gets larger and larger), until you reach your predefined limit of groups allowed. Weird "yellow arrows" are also visible when in Zeus at map origin.

**Why this is bad (should be obvious)**

Aside from totally destroying performance on a server, this also caps the unit limit, causing players to experience groups "spawning on top of them" when they attack objectives. My specific server setup utilizes a mainframe server, and a second box hosting 5 headless clients. After about an hour of this blob "having babies", server fps drops to <15. No bueno!

**Additional Information Gathered**

Originally, I thought this issue was simply related to the lack of helipads issue, which was mentioned to be somewhat fixed in the last update. This was my original assumption simply because at times, I have seen this issue spawn nothing but helicopters and pilots. That said, I believe this issue is not directly related to the helipad issue.

I have gone back to reindex some of the maps that experience this issue, and cannot see anything directly wrong with the indexes. Verifying staticData.sqf for the map shows nothing out of place or missing.

In addition, the only categories missing from this particular staticData.sqf that I am looking at, is the following:

ALIVE_militaryAirBuildingTypes = ALIVE_militaryAirBuildingTypes + [];
ALIVE_civilianAirBuildingTypes = ALIVE_civilianAirBuildingTypes + [];

Considering I am having infantry groups spawning ridiculous amounts of dudes at map origin, I would argue that this problem is unrelated to the missing helipads, but not having helipads defined may have caused this issue to happen with helicopters and pilots in certain scenarios.

**Reference Images**

http://i.imgur.com/kCs5ZWT.jpg

http://i.imgur.com/mVHyn3x.jpg

http://i.imgur.com/IE0jJH4.jpg

I believe this is somehow being caused by the reinforcement system. I will continue to look for solutions and try to better narrow down what exactly is causing this to happen. Any input appreciated... o7

**Comment by Vegas** [comment]
**Update**

Totally related to reinforcement systems.

I seem to have found a temporary "Macgyver" solution to prevent this. Essentially place a Military Logistics module, disable everything, sync it to AI commander. Done.

**Reference Image**

http://i.imgur.com/dl3FhWv.jpg

**Comment by Vegas** [comment]
**Update**

This appears to only occur "sometimes" on mission startup. I can literally load the mission file one time, error does not occur, load same file again, error happens. This is very odd.

**Comment by Vegas** [comment]
**Update**

I am continuing to run tests in hopes of figuring out wtf is causing this issue, here is some additional information.

- Compositions can also sometimes spam-spawn at map origin, so you have roadblocks and bunkers all over the place with the blob of infantry.
- This blob does not continue to multiply unless there is a player near that map origin location. However, if you are running Headless Clients, they are held over this location and cause neverending blob spawn. Same deal happens if you have more than one respawn location for players, and allow them to choose where to respawn, until they choose, their body is held over map origin causing blob to keep multiplying.
- Placing blacklist marker over this location has no effect
- Running full debug to look for objectives, there is no objective at this location showing up.
- When having tasks generated, hostage task will tell you to return the hostage to this map origin location, thereby making the blob very angry.
- Jumping into Zeus and deleting the units in the blob has no effect, they just spawn right back after being deleted.

Still looking for answers....

**Comment by highhead** [comment]
2 questions:

- Happening in a mission with only ALiVE and CBA on either Stratis, Altis or Tanoa?

- Happening if not using Military Logistics at all?

**Comment by coachwn** [comment]
I have seen this happen on all maps using ALiVE; Reshmaan, Sahrani, Isla Duala, Lingor, Altis, Stratis, Tanoa, etc...

Also for our group it is not the entire unit but anywhere from a few to several enemy troops that this happens to and its not just on start up but rather when the enemy units are spawned into the game via camera tool or players triggering according to parameters.

**Comment by marceldev89** [comment]
This also seems to be happening with (non dedicated) hosted MP according to reports on Discord.

**Comment by marceldev89** [comment]
Did this issue also appear in A3 1.66?

**Comment by coachwn** [comment]
I have been seeing this since the beginning of Arma 3 on ALiVE servers we host. I honestly have only played  on a few other ALiVE servers but we have never really hosted a vanilla MP server for long. I might put one up on our box just to get a look.

**Comment by AUTigerGrad** [comment]
@Vegas  What's your steam username?  Would you mind if I shoot you a friend invite and pick your brain regarding using more than 1 HCs on a server?  Just had a few basic questions to ask.  FYI..I've also seen this issue on several maps with ALiVE for a good while now.  Haven't really paid attention to the number spawning in though.  I have noticed recently (after latest ARMA/ALiVE update) that the AI spawned in by ALiVE will run in place/get stuck...almost as if the server has crashed....however, the server has NOT crashed, and all players and any non AI spawned units (i.e. a unit I plop down with Zeus) will move fine, while the ALiVE units will continue to run in place.  This typically occurs after the mission has been up for a few hours.  If I reset the server....the ALiVE units will go back to functioning ok but it may occur a few hours later again.

**Comment by coachwn** [comment]
@AUTigerGrad Is that behavior specific to an ALiVE running with HC's? We stopped using HC's a long time ago in all our missions and we don't see that problem at all. I do see pathing problems with the AI going and doing goofy things though.

**Comment by Whigital** [comment]
First thing that comes to mind is BIS_fnc_findSafePos and similar functions that return map_origin [0,0,0] when no suitable area is found. Or something involving buildingPos. From the screenshots it looks like its not every unit in the group that spawns at the origin, which might point to a positioning issue.

We see this too, but not the amount described here. And when we leave the TAOR, they despawn with the rest of their group.

**Comment by AUTigerGrad** [comment]
@coachwn  I've never seen that occur until the last update (ARMA + ALiVE).  We've used one HC on our server for almost 2 years now with no wackiness that I can tell.  But this "running in place" that resembles almost a rubber band effect but ONLY from ALiVE spawned units has occurred at least once during our last 2 campaigns.  It fixes after a server restart, but tends to occur again with no real set timeframe.  So I'm not sure what's causing it.

**Comment by coachwn** [comment]
@Whigital yes when you leave the spawn radius those individuals do leave as well. Since we moved to several different TAOR's we have cut down on the numbers of individual units spawning like that but it is still very prevalent and I would tend to agree with you regarding the BIS Functions causing the thing.

**Comment by HeroesandvillainsOS** [comment]
Can anyone provide a repro mission, with just CBA, ALiVE and whatever the map is, and a detailed list of repro steps when the mission is loaded please?

**Comment by Vegas** [comment]
@AUTigerGrad Steam: [LTC] Vegas =21st=

@HeroesandvillainsOS I am getting closer to figuring this out. Running a test mission with the gang tonight to see if it occurs under new adjustments. After the session, I will post my findings and attempt to produce a repro mission using the bare bones setup.

**Comment by highhead** [comment]
Hi!

Is this happening if you disable Military Close Quarters Combat module?

**Comment by Vegas** [comment]
@highhead My current theory is that the issue is related to the CQB module, specifically the density settings.

Still working on putting together a good repro to send for debug...

**Comment by highhead** [comment]
Please also try this RC: https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.3.1.1704141

I have squashed some bugs regarding spawning of profiles in there!

**Comment by tupolov** [comment]
@highhead There's a bug in ALiVE_fnc_groupGarrison. For some reason certain building positions are not valid and therefore the unit is set to position 0,0,-184. Suggest you validate building position before moving units or requesting a doMove

**Comment by highhead** [comment]
seems like object-classes have been changed so that defense-objects like Land_BagFence_Round_F and others not returning buildingpositions anymore and defaulting to 0,0. Removing that class for garrison positions plus validating buildingpositions for 0,0 should fix or at least massively reduce spawns of units at 0,0.

https://github.com/ALiVEOS/ALiVE.OS/commit/f6a54d7428f4ea32658a4bde4c8872d1bc5b37b1

please report back once it is deployed.

**Comment by highhead** [comment]
https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.3.5.1705121

Could you please try this new RC! Thanks!

**Comment by coachwn** [comment]
Maybe a separate issue but I have noticed that sometimes units will set a way point out at the same 0,0,0 position either when spawned in by ALIVE or when placed by Zeus and given a way point to follow. Typically the way point out at that possible is a cycle way point.

**Comment by highhead** [comment]
is it happening with this RC?

**Comment by coachwn** [comment]
@highhead sorry was on my phone and thought I was replying to my April 12 comment. I will check the RC version tonight on our test server and see what happens.

**Comment by friznit** [comment]
Various fixes implemented.  Let's keep an eye on it.
