### ISSUE TITLE
Cannot select Asymetric control type in the Military AI Commander Module

### ISSUE THREAD

**Issue by boyofcow** [ALiVEOS/ALiVE.OS#327]
Hi,

I am trying to make an asymetric mission.

I am unable to select anything in the drop down box for AI control type in the Military AI Commander Module. When I click on the drop down icon or the box itself, I get the menu bleep as if something has been selected and the box closes. Other drop down boxes work as normal.

I have tried this with Alive and CBA mods  (from Steam Workshop) only,  loaded after veryfing the integrity of game cache.

Steps to recreate:

Open arma with CBA and ALIVE loaded  as from steam workshop.
open the editor with a VR level, (same applies to altis and stratis)
place a Military AI commander module
double click on module or right click attributes 
click on drop down box icon to the right of the control type option... no selection should be possible.

Thank you for a great mod. Sorry if the solution has been posted or if I haven't completed this issue correctly.

**Comment by SpyderBlack723** [comment]
Up to BIS to fix, nothing we can do. Use your keyboard to manipulate the dropdown or drag the window.

**Comment by boyofcow** [comment]
Thanks. I see how the option is available when moving the window and that it was the third option down in any module.

Thanks for the pointer

**Comment by nateberkopec** [comment]
Yeah this is an ARMA core bug. Such a bummer.

**Comment by highhead** [comment]
You can get around it by switching interface size between small/normal in A3 options.
