### ISSUE TITLE
Infinite load screen on ALiVE Dev build

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#338]
I've got infinite load screens occuring like crazy..on old missions, new missions, completely fresh from scratch missions.  The only time I don't get one is if I literally create one from scratch and immediately preview..if it was previously saved or made even once after restarting ARMA...I get the inifinite load screen.  Doesn't even matter about the modules because it will work..then I'll exit ARMA without adding/changing anything...then reload mission..hit play...infinite load screen.   I've tested with only vanilla settings, as well as with RHS factions.  Same thing...infinite load screens unless I have started from scratch and immediately hit preview after placing modules.  If I exit from the editor/ARMA then come back into it with a previously working mission..it won't work after restarting the game.  

I have no such issues with the current release build.  I was only running ALiVE, ACE, RHS, JBAD, and the Lythium map in these tests.  As I mentioned...switching to ALiVE Release client with the same mods...everything works as intended.  Switch back to ALiVE Dev build....infinite load screens.

**Comment by SpyderBlack723** [comment]
Need RPT

**Comment by AUTigerGrad** [comment]
https://www.dropbox.com/s/upoj4ql9ifgrbz6/Arma3_x64_2017-05-08_12-16-04.rpt?dl=0

Mission on Stratis

CBA and ALiVE Dev ONLY (no other mods active)

Infinite load screen immediately on preview....mission was built from scratch 5 min earlier.  Didn't even restart the game.  Froze on first try.

**Comment by AUTigerGrad** [comment]
Another one with AI Commander debug set to yes

https://www.dropbox.com/s/d33vsx3iszd9q2i/Arma3_x64_2017-05-08_13-40-38.rpt?dl=0

**Comment by highhead** [comment]
Issue seems to have slipped in with this commit: https://github.com/ALiVEOS/ALiVE.OS/commit/2c23505bf95cc84f42c93def51142495a78e6cd3#diff-938cd4b7a357247f6d042e088db629fc

on a fix

**Comment by highhead** [comment]
fixed, do not use asym occupation setting until this is deployed to avoid the infinite LS, thanks for bringing this up!
