### ISSUE TITLE
Alive takes up all of the ram and never loads to the main menu

### ISSUE THREAD

**Issue by kripto202** [ALiVEOS/ALiVE.OS#339]
mods:
- cba a3 stable
- alive stable

My friend tries to load into arma when he has just alive and cba turned on and he can't get into his main menu when the main menu background is static disabled. When he has the static background turned on, he is able to get to the main menu but when he starts to render, something takes up his ram and bascially crashes his game. He is the only one in the group that has this problem.

rpt files: https://drive.google.com/open?id=0Bx9A54dNGq2rOGRWLW85YWZkMjg

**Comment by kripto202** [comment]
[arma3_x64_2017-05-13_00-16-27.zip](https://github.com/ALiVEOS/ALiVE.OS/files/998346/arma3_x64_2017-05-13_00-16-27.zip)
some more log files that was created by arma troubleshooter

**Comment by SpyderBlack723** [comment]
I don't see ALiVE loaded in any of those RPT files, many of them indicate no mods loaded. If a game loaded with no mods is crashing, then you will have better luck opening a support ticket on BIS's own feedback tracker.

**Comment by kripto202** [comment]
If he runs all of our mods except for alive, it works perfectly. As soon as he turns on alive, the problem arises.

**Comment by SpyderBlack723** [comment]
Please ask him to verify his game cache and double check he is running the latest stable version of alive, cba, and Arma.

**Comment by kripto202** [comment]
He has verified and reinstalled arma. In mod location, we use the workshop. He even tested in armaholic to see if it would be the workshop version, still the same result.

**Comment by SpyderBlack723** [comment]
He can try removing aliveclient.dll

**Comment by kripto202** [comment]
same results

**Comment by kripto202** [comment]
he keeps seeing this issue pop up "no params given for alive_fnc_bus"

**Comment by SpyderBlack723** [comment]
That message is intended.

We have just released a new update that he can test and hope to get lucky.

With the plugin removed, there really isn't anything we can do to cause a crash of the game. The only suggestion I can offer is to remove pbo's in groups until it starts working.

**Comment by kripto202** [comment]
this is what he said just recently "I am the one having the issue. I have tried uninstalling, reinstalling, using two different drives(HDD and SSD) running both in admin, 32 and 64 bit, with only alive and with all. Still gives me the issue. If I turn on the static main menu it works, but the moment I enter a server or the main menu(with the animated one) it hangs on the loading screen. It seems to me like it only happens when it needs to start rendering something, and only with Alive enabled."

**Comment by kripto202** [comment]
He took out the preint file and everything works.

**Comment by SpyderBlack723** [comment]
Can you please link (via github) the file to which you are referring? Thank you.

**Comment by kripto202** [comment]
https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/main/XEH_preInit.sqf

**Comment by SpyderBlack723** [comment]
Ok, can you ask him to do the following please:

1. Delete all existing RPT files.
2. Load Arma with only CBA and this version of ALiVE: https://www.dropbox.com/s/9qzx8qlp50egauz/ALiVE_test.RAR?dl=0

3. Try to reproduce the crash
4. Report back here whether or not it crashed, posting the RPT if it did.

Thanks. We may have to iterate this process a few times depending on the results, but hopefully it's rather quick.

**Comment by kripto202** [comment]
he will get back to you on monday or tuesday

**Comment by DragonBlade117** [comment]
Okay, Home. Downloading it now and will test it tonight.

**Comment by DragonBlade117** [comment]
Still spiking. It takes all of my 32 GBs of RAM in a matter of seconds if I have the animated main menu up or when I try to enter a map. Only running the latest version of CBA from Steam and the alive_test.

**Comment by SpyderBlack723** [comment]
Can you load into the game with **just** CBA loaded.

1. Open Editor (Any map)
2. Pause Game
3. Enter into debug console

```
tmp = [(ActionKeys "User20" select 0),[false,false,false]];
["ALiVE","openMenu", "Open Menu (Requires Restart)", {playsound "HintCollapse"}, {}, tmp] call CBA_fnc_addKeybind;
```

4. Press `Local Exec`
5. Report back whether or not it crashes

Thanks

**Comment by DragonBlade117** [comment]
Testing now, will drop an update momentarily.

**Comment by DragonBlade117** [comment]
Executing that didn't crash it, but knocked my frames down to 2 a second. Taking up a consistent 17.5 GBs of RAM.

**Comment by SpyderBlack723** [comment]
Your problem likely lies with CBA then, will try to reroute it to them.

**Comment by SpyderBlack723** [comment]
@commy2 Any ideas?

**Comment by commy2** [comment]
Needs a valid RPT file preferably of a session that only did what this post describes: https://github.com/ALiVEOS/ALiVE.OS/issues/339#issuecomment-303933663
The RPT files in the OP are all from sessions without any mods (`-mod=`).

**Comment by marceldev89** [comment]
@commy2 the archive posted in https://github.com/ALiVEOS/ALiVE.OS/issues/339#issuecomment-301225424 contains 2 RPTs with mods loaded (`Arma3_x64_2017-05-13_00-22-00.rpt` and `Arma3_x64_2017-05-13_00-24-52.rpt`).

**Comment by DragonBlade117** [comment]
Okay. Here we go.

**Comment by DragonBlade117** [comment]
[ArmaReport_Log_20170607T052547_Drago.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1056942/ArmaReport_Log_20170607T052547_Drago.zip)
![pt1](https://user-images.githubusercontent.com/12104353/26863402-7009a5be-4b20-11e7-8eff-03f77750549e.png)
![withoutthatfileinpbo](https://user-images.githubusercontent.com/12104353/26863404-724a34ba-4b20-11e7-94ca-c5f1096b5036.png)
![withstandardalive and with test version created earlier](https://user-images.githubusercontent.com/12104353/26863405-744ce4a6-4b20-11e7-903a-36bce4ab797e.png)

**Comment by DragonBlade117** [comment]
Second picture is with my modified pbo without that preinit.
Third picture is the result of trying to run both versions of the Alive I was given. Just uploaded the report from the crash of the test. Let me know if you want the other. But they both have the same effect and I suspect the same cause between both versions.

**Comment by DragonBlade117** [comment]
Bump?

**Comment by SpyderBlack723** [comment]
@commy2 in case you never saw the logs

**Comment by coachwn** [comment]
I don't think it's a problem with Alive; our community is running 30GB+ of mods right now and we aren't having this issue with anything since we went to 64 bit arma. I think you have a messed up install of arma somehow. I wouldn't mind doing a teamviewere session with you to see if I can help locate what's wrong.

**Comment by SpyderBlack723** [comment]
@coachwn We've already established that it something related to CBA keybinding

@DragonBlade if you by any chance have another keyboard, I would recommend using that one instead and seeing if that fixes the issue.

**Comment by DragonBlade117** [comment]
What does the keyboard have to do with it? Would that have anything to do if the game eats the memory when it has to render but runs fine up until then? And it did start to chug when I executed that command, but it still let me look around at 2 fps while taking much more RAM than usual. I will try it though. Already reinstalled arma twice.

**Comment by SpyderBlack723** [comment]
The issue is with registering a keybind callback with Arma, this issue doesn't belong to ALiVE. Nobody is really jumping to offer you help, so I'm merely offering suggestions.

**Comment by DragonBlade117** [comment]
I appreciate that. But what does the physical keyboard have to do with it and why didn't it do it before do you think?

**Comment by SavageCDN** [comment]
If it's a USB keyboard then yes it can cause crashes (rare but I've seen it).  If your mobo supports PS/2 connections then try using a PS/2 keyboard to see if it stops the crashing.  If not, try using a different USB port for the keyboard.  It's a shot in the dark but an easy one to take.

**Comment by Lookst** [comment]
Did you get it fixed? Getting this same problem rn.

**Comment by DragonBlade117** [comment]
I swapped keyboards, reinstalled drivers, used different USB ports and nothing. Glad someone else who is having this problem found it the post though. It is infuriating.

**Comment by DragonBlade117** [comment]
I have to go to work now, but if anyone has any suggestions I will try them when I get back tonight.

**Comment by marceldev89** [comment]
Someone that is having this issue please report it at https://github.com/CBATeam/CBA_A3/issues since it's an issue with CBA apparently.

**Comment by friznit** [comment]
> If you have the out of memory crash when loading the game with alive, you have three options. (1) Wait for a resolution of https://github.com/CBATeam/CBA_A3/issues/715 (2) roll back to CBA 3.3.1 (Yay withsix. Boo workshop.) (3) find another keybind (without alive loaded) for user20 that doesn't have a numeric value like 9.39524e+008 as mine does.

**Comment by MaHuJa** [comment]
The solution that has worked for me is to load arma 3 with only CBA,
1) Completely unbind custom action 20
2) Rebind it to something with a sane value
3) Run ```["ALiVE","openMenu", "Open Menu (Requires Restart)", {playsound "HintCollapse"}, {}, [0,[false,false,false]], false, 0, true] call CBA_fnc_addKeybind;```
then restart with alive.
