### ISSUE TITLE
Latest Dev version:  ALiVE markers not persisting after player exit

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#340]
Our entire group is seeing this on the latest Dev version.

ALiVE persistent markers vanish after player exiting.  Tried player exiting again to see if it refreshed them, but no markers period.  Sporadically....markers will reappear after a player exit but it's not consistent.

Did not have this issue with the current Released version.

**Comment by highhead** [comment]
Will need a reliable repro! Please try with latest RC! Please see below.

Steps I did:

- Bang a fully fleshed ALiVE persistent mission (setting "cloud") on Tanoa on the dedi running @ALIVEServer and Warroom access (of course).

- Placed a marker with ctrl + click, OPFOR named it TEST1
- Disconnected to lobby via "Player Exit" button!
- Disconnected from server totally
- Reconnected to server lobby, rejoined game => Marker TEST1 was still there

- Placed a marker with ctrl + click, BLUFOR and named it TEST2
- Disconnected to lobby via "Abort" button!
- Rejoined game => All Markers (TEST1 and TEST2) were still there

- Placed a marker with ctrl + click, INDEP and named it TEST3
- Added a SpotRep with text "TEST3"
- Disconnected to lobby via "Player Exit" button!
- Rejoined game => All Markers (TEST1 and TEST2 and TEST3 incl. SpotRep) were still there
- Disconnected to lobby via "Player Exit" button!
- Disconnected from server totally
- Reconnected to server lobby, rejoined game => All Markers (TEST1 and TEST2 and TEST3 incl. SpotRep) were still there

vanilla mission used: http://s000.tinyupload.com/?file_id=46851718126800053727
ALiVE RC: https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.3.5.1705161

A3 dedicated server and client version:
Type: Public
Build: Stable
Version: 1.70.141764
