### ISSUE TITLE
Prerelease Build 1.3.5: Persistence Saving stalls at Military Logistics

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#341]
https://images.discordapp.net/.eJwVylEOwiAMANC7cADaAqtllzGEETazCYH6Zby7-vH-3tu8xmlWs6v2uQJsx8xtbHZqG6kWW1urZ0n9mDa3C5JqyvtVnjqBGAMyMXv5kyDgKaD3iBKjW8SzEDikGy6_G51DvpN99Go-XyO3IyY.cJrwGr_zeiNGAnb-CU_qJaCbiQw?width=1125&height=633

When attempting to save mission progress, the save process stalls at` Military Logistics.

I attempted 5 saves, both with Military Logistics module persistent set to yes...and with Military Logistics module persistent set to no.  Even set to no, Military Logistics appears on the save screen as "saving data" and never advances past that. 

Pic included.  I do not have logs turned on my server but could if needed.  Be advised, I attempted a vanilla ALiVE mission save and the same thing occurred.  Can anyone else replicate this issue?

**Comment by highhead** [comment]
fucking good catch again

**Comment by AUTigerGrad** [comment]
That's what I'm hear for highhead lol

**Comment by highhead** [comment]
btw. if you have issues opening the debug console in MP... I also have seen that...

**Comment by AUTigerGrad** [comment]
yup, I have.  FYI, I sent you a friend request on steam (Auburnalumni)

**Comment by highhead** [comment]
can you please turn sys data debug "on" and post your rpt and @aliveserver log - just to be sure! thanks!

**Comment by AUTigerGrad** [comment]
I can..it will be a couple of hours.  Got a guy at my house about to repair my desk that my PC sits on.  But I'll do so afterward.

**Comment by highhead** [comment]
have it sorted in DEV, was a regression introduced here: https://github.com/ALiVEOS/ALiVE.OS/commit/2947cf3cfb79a27bbe75388356bcd934c5db8ac5

need some tests but will push soon

**Comment by AUTigerGrad** [comment]
sweet!! New ARMA update just dropped too so I can test with latest ARMA as well once you push.

**Comment by highhead** [comment]
its in master, not sure when next RC is coming - we may aim for a full release now

**Comment by AUTigerGrad** [comment]
Barring any bugs from the ARMA update, I'm all for a full release.  We've been playing on the last RC for several days now on the dedi and other than the persistent markers being "finnicky" and the saving stall, I've seen no other issues that I can speak of.

**Comment by highhead** [comment]
markers not showing sometimes is a different issue and existing for long. disconnect reconnect should work around that.
