### ISSUE TITLE
All Placement modules spawn 1 guard group in addition to number selected in placement options

### ISSUE THREAD

**Issue by SavageCDN** [ALiVEOS/ALiVE.OS#342]
As reported on ALiVE forums:

> when using custom objectives that if you tell the module that you want one infantry group, it will spawn one group inside the custom marker zone, but it will also spawn a group outside of that zone. So instead of only getting one group of units I end up with two

http://alivemod.com/forum/2944-custom-objectives-making-more-unit-groups-than-you-tell-it-to/

Trying to get more info (mods used, if any)

**Comment by SavageCDN** [comment]
So options are zero groups or 2 or more groups?

**Comment by SpyderBlack723** [comment]
Should always place a guard group, that's probably unintended. Maybe a moduke option would be a good way to convey this to users (and provide flexibility? Thoughts? @friznit @highhead

**Comment by SavageCDN** [comment]
Makes sense just confusing to users methinks

**Comment by HeroesandvillainsOS** [comment]
So it will always add one? 2=3, 3=4, etc?

**Comment by friznit** [comment]
Unless there's a technical reason why this needs to happen, it sounds like a bug.  Given that I am using override settings then the placement modules should only spawn the number of groups that I define.

**Comment by SpyderBlack723** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/bd060b555c9f5141fdd9787348f63002105fb527 This has been adjusted for CMP modules
