### ISSUE TITLE
Usability: change integer entries to drop downs

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#346]
Change Virtual Combat Speed and Smooth Spawn to drop downs (Very Fast, Fast, Regular, Slow, Very Slow where Regular is default 1 for Combat Speed and 0.3 for Smooth Spawn)

CQB module static placement to low, medium, high, very high

**Comment by SpyderBlack723** [comment]
What should the increment ratios be for the change-in-level?

ie.

Virtual Combat Speed Ratio of 2
    Very Fast = 4
    Fast = 2
    Regular = 1
    Slow = 0.5
    Very Slow = 0.25
