### ISSUE TITLE
Support 'Pickup' Request and IR Markers

### ISSUE THREAD

**Issue by Fletcher225** [ALiVEOS/ALiVE.OS#347]
Hello all I have a mission setup on tanoa with 3 factions. Using RHS for the US and RUS and Syndikat for the IND. Having an issue, request a pickup at night, with pilots not seeing a IR marker.

I got out of the game and only loaded ALiVE and CBA. Recreated my mission with CSAT and NATO.

I'm testing this on the CSAT side for right now.

I have used IR Grenade"CSAT" and before I used the IR flare, Chemlight(IR) and IR Strobe. I have also tested by changing out the pilots headgear too.

The pilots just keep flying around requesting for an IR marker. Maybe somebody has an idea. :) Thanks.

**Comment by Whigital** [comment]
Checking the transport FSM, only *WEST/BLU_F* IR Strobes (`B_IRStrobe`) gets detected:

https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/sup_combatsupport/scripts/NEO_radio/fsms/transport.fsm#L767

*EAST/OPF_F* and *GUER/IND_F* (`O_IRStrobe` and `I_IRStrobe`) wont work. Maybe use the baseclass `IRStrobeBase` which all 3 classes inherit from ?

**Comment by Fletcher225** [comment]
confirmed. only ir grenades[NATO] only works.
When using only the Alive and CBA mod you don't get strobes just ir grenades NATO,CSAT,AAF and flares.

I'll switch out the CSAT ir grenades with NATO ones for my Russians. :) 

Thanks.

**Comment by Whigital** [comment]
The `B_IRStrobe` is the actual ammo that gets dropped on the ground. *IR Grenade [NATO]* (`B_IR_Grenade`) is the magazine you see in your inventory.

**Comment by Fletcher225** [comment]
Oh ok ya I only type what I actually see in-game sry. :)

**Comment by Whigital** [comment]
No worries, just wanted to clarify :)

**Comment by SpyderBlack723** [comment]
Good catch, I will change to the base class each inherits from.

**Comment by Fletcher225** [comment]
Thanks man! Ya all I do at home here is test test test :)

**Comment by SpyderBlack723** [comment]
511142f2bf3ff7bf7f1da1ebd11a14574244b025
