### ISSUE TITLE
Option Request - Disabling faction 'Reinforcements Available' texts

### ISSUE THREAD

**Issue by Fletcher225** [ALiVEOS/ALiVE.OS#348]
Heya, somebody had posted on ALiVE forums about a possibility to have an option to disable the 'available reinforcements' text that pops up on the screen :) At first I thought that this was a debug feature I had to shut off. :) Thanks!

**Comment by Opendome** [comment]
Haha that was me

**Comment by friznit** [comment]
Debug text should be off by default.  However, might be nice to implement some more immersive text to indicate when logistics are requested/delivered, similar to how ATO does.

**Comment by highhead** [comment]
Changed with https://github.com/ALiVEOS/ALiVE.OS/commit/1167f02daa9698423eaa1f819cfde566254c343c

**Comment by highhead** [comment]
For documentation, comms about this in our Slack channel:

At the moment current reinforcement level is communicated to the reinforcements-side after delivery. This is intended. I can either...

- change the content of the text (please deliver the text)
- Remove the text completely
- put it "behind debug"

I am not going to invest a lot of time to make an option on the module, as its not worth the hazzle.

friznit [12:44] 
put it behind debug
