### ISSUE TITLE
Possible bug that popped up where TAOR's are shown on map

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#349]
OK just went to the new release version yesterday and didn't change anything with my TAOR markers to allow them to be shown on the map. So now every time we look at the map they are showing the areas where things are set to spawn...IT does not show debug though...[Here is the picture](http://steamcommunity.com/sharedfiles/filedetails/?id=931101689); any ideas?

**Comment by SpyderBlack723** [comment]
If they are showong, they are not being recognized. I would debug further in the editor.

**Comment by coachwn** [comment]
OK so figured out the problem...when I updated ALiVE to the newest version yesterday; somehow it copied over all items I had placed on the map as exact duplicates in the exact same spot. I noticed that last night but I also noticed that some items didn't duplicate so I didn't think about the TAOR being duplicated. Anyway its been fixed.
