### ISSUE TITLE
Fold UCAV wings on spawn to prevent assplosion

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#352]
UCAV sentinel is too wide for the hangars on altis/stratis and will explode on spawn.  The wings need to be folded:

```
this animate ["wing_fold_l", 1, true]; 
this animate ["wing_fold_r", 1, true]; 
this animate ["wing_fold_cover_l", 1, true]; 
this animate ["wing_fold_cover_r", 1, true];
```

More here: https://community.bistudio.com/wiki/BIS_fnc_AircraftSystemsInit

**Comment by friznit** [comment]
@tupolov have you implemented a workaround?

**Comment by tupolov** [comment]
Fixed
