### ISSUE TITLE
Bug: BCRs are not replaced to original starting levels through persisted mission saves

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#356]
Blufor Battle Casualty Replacements will work fine for the first portion of the campaign...but over the duration of the campaign and after several server saves/loads, etc. it appears that Blufor no longer reinforces their battle casualty replacements.

I've attempted static reinforcement in a remote area completely devoid of enemy forces to be a stable loading point. I've tried doing infinite number of reinforcements. I've tried multiple combinations. But inevitably...after a period of time..Blufor units dwindle down to almost nothing.

Per MarcelDev on the ALiVE Forum....
"I haven't noticed but it is reflective of how the code works. Basically the starting troop numbers used for BCRs aren't persisted between sessions meaning that every session the numbers will be reset to the count of profiles on the field from the previous session (or if profiles aren't persisted, the amount the placement modules spawned). Steadily decreasing the numbers until they just don't reach the BCR threshold anymore.

Put up a ticket on github, this shouldn't be happening. "

This is obviously a pretty major issue, especially for Assymetric campaigns...as the Friendly forces will continue to dwindle to nothing, regardless of how many reinforcements are available.  This means that after a few server saves...the Assymetric profiles will be all over the place and there will be no opposition to them via friendly profiles.

**Comment by AUTigerGrad** [comment]
After further testing...I can confirm that reinforcement levels drop to 0 after at least one server save.  Changing Military logistics persistence to NO in the module will allow for a temporary workaround as it resets levels to default every time...but through 4 separate tests....I can conclude on my end that Military Logistics reinforcement levels break if they are set to be persistent on a module.

**Comment by HeroesandvillainsOS** [comment]
Two separate issues mentioned here. The Force Pool reverting to 0 when loading a persistent save has been fixed in the current 1.3.7 pre-release. So that just leaves initial group count for each side not persisting the original mission start numbers. Good catches on both of these, by the way AUTigerGrad.

**Comment by marceldev89** [comment]
Fix available in https://github.com/ALiVEOS/ALiVE.OS/pull/397. Once merged all is good again. :)
