### ISSUE TITLE
Roadblocks spawning on runways and sideways on roads

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#360]
New mission we are putting up and we have the roadblocks spawning on runways and not in line with roads on Isla Duala 3.8 map.
[https://github.com/Spearhead-Gaming-Milsim/Operation-Wildfire/issues/13](url)

**Comment by tupolov** [comment]
Are you using ZEC or ALiVE compositions? We corrected for ZEC's checkpoint orientations, but looks like he may have fixed recently.

There's a fix coming in next ALiVE release for runways.

**Comment by coachwn** [comment]
@Scotty_Z is the guy who built the mission so I tagged him to get back with you on this issue.

**Comment by Scotty-Z** [comment]
Alive compositions is what I'm using

**Comment by Neodyn** [comment]
Also same issue on Takistan. Alive is placing roadblocks an Rasman airfield

**Comment by coachwn** [comment]
Same map but Roadblock attempting to get placed on a bridge on Isla Duala 3.8.

[http://steamcommunity.com/sharedfiles/filedetails/?id=965701578](url)

**Comment by coachwn** [comment]
Still having this issue with the latest version of ALiVE on our server. Not sure if it is related to the mods or not but we are using ALiVE compositions for the roadblocks. We have turned the roadblock feature off going forward but I wanted to make sure you guys knew about this in the current version.

[Roadblocks not aligned with roadway](http://steamcommunity.com/sharedfiles/filedetails/?id=971924731)

**Comment by tupolov** [comment]
Thanks will hunt them down, maybe a few outliers in ZEC alignments
