### ISSUE TITLE
ORBAT Creator show script error

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#361]
RPT: https://gist.github.com/shukari/1fd0ad98c67bc3e82d7036154d894047

**Comment by SpyderBlack723** [comment]
I'm not seeing any ALiVE-related errors in that RPT. There are plenty from LOP and some from the official A3 functions which we cannot fix.

**Comment by shukari** [comment]
```
17:53:09 Error in expression <,
["put",		23]
];


private _ctrlList = _display displayctrl (			960 + 		26);
{
>
17:53:09   Error position: <_display displayctrl (			960 + 		26);
{
>
17:53:09   Error Nicht definierte Variable in Ausdruck: _display
17:53:09 File A3\functions_f_bootcamp\Inventory\fn_arsenal.sqf [BIS_fnc_arsenal], line 2179
```
That pops up everytime i open the ORBAT Creator... i suppose it open something wrong so a vanilla script crashed.

**Comment by SpyderBlack723** [comment]
Yes, somebody broke the preload function of the arsenal awhile back, nothing we can do about it unfortunately.

**Comment by dixon13** [comment]
I see this error all the time. BIS hasn't fixed it yet.
