### ISSUE TITLE
[FeatureRequest] Dropdownmenu for supported factions

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#362]
Why there is no dropdownmenu for all available factions in ... thats over complicated many times.

**Comment by AUTigerGrad** [comment]
Make sure you have at least one objective within the TAOR you are using.  We are using RHS factions in 2 campaigns right now with no issues.

**Comment by shukari** [comment]
i changed the ticket now... the problem is i wrote both rhs factions in the commander and a placement module... he doesnt like that ^^

**Comment by HeroesandvillainsOS** [comment]
I'm really not understanding this ticket. Can you clarify? If you want multiple factions for one commander, you just name the factions in the OPCOM module and use separate obj modules for each faction.

**Comment by SpyderBlack723** [comment]
Placement modules can only support one faction, if you need to spawn two factions, you need two modules. Please re-open if this is not the issue you are referring to.
