### ISSUE TITLE
Add ability for players to "destroy" roadblocks permanently

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#363]
Currently, there is no way to "destroy" or "defeat" roadblocks.  Even when killing all enemies at the roadblock..you can not clear the road.  The composition will also spawn back after server restart so there needs to be a game logic that shows the roadblock as "destroyed" so that players don't end up with dozens of roadblocks that are essentially indestructible.  This also causes havoc on Spyder's traffic ambience.

**Comment by coachwn** [comment]
Agreed...I have turned off roadblocks for the most part in our missions just to eliminate this same issue.

**Comment by tupolov** [comment]
what if we add an action on the roadblock that allows you to remove it? Then it is not stored from that point on.

**Comment by coachwn** [comment]
Ok but wouldn't another one just spawn in to take its place somewhere else?

**Comment by tupolov** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/6462717551b8feb76119a1f4e30b04ac72d2c2ea Done!
