### ISSUE TITLE
Military and Civilian Placement AI do not follow waypoints, appear 'stuck'

### ISSUE THREAD

**Issue by speedweasel** [ALiVEOS/ALiVE.OS#365]
AI spawned using the Military Placement and Civilian Placement modules do not consistently follow waypoints set by the AI Commander or set manually by Zeus.

Example mission is at: https://drive.google.com/open?id=0B0p8coCqY4Z0TzU3Y3hreDB4WDA
1.	Run the mission and go into the Zeus interface.
2.	Observe nearby units that have waypoints set but do not follow those waypoints.  Note in the Zeus interface that these affected units appear to be assigned a first waypoint named ‘0 MOVE’.  Correctly functioning units appear to be assigned a first waypoint named ‘1 MOVE’.
3.	Click RMB to assign a new waypoint to an affected unit.  Note that the first new waypoint for an affected unit will always be named ‘0 MOVE’ and the unit will never follow this waypoint.  
4.	Click RMB again to assign a new waypoint to the same affected unit from step 3.  Note that when a fresh waypoint is given to an affected unit the new waypoint will automatically show as additional waypoint preserving the ‘0 MOVE’ waypoint.  The new waypoint does not overwrite ‘0 MOVE’.  The unit will never follow ‘0 MOVE’ and so never completes any of the waypoints.

Expected Behaviour
Units spawned by the AI Commander should follow all waypoints set by the AI commander.
Units spawned by the AI Commander should follow all waypoints set by Zeus.
New waypoints given by clicking RMB should overwrite all existing waypoints

Observed Behaviour
Some units spawned by the AI Commander do not consistently follow waypoints.

**Comment by tupolov** [comment]
What happens without ALIVE loaded?

**Comment by speedweasel** [comment]
> What happens without ALIVE loaded?

I need ALiVE loaded in order to use the Military Placement modules, right?  I don't think I understand the question.

Units placed manually through the Zeus interface always follow waypoints with or without ALiVE loaded.  Their first waypoint is always numbered 1.

**Comment by speedweasel** [comment]
I just tested again using a new mission with no mods.  AI units placed manually in Zeus follow waypoints correctly every time.  The first waypoint is always numbered '1'.

When running ALiVE, units placed by the Military Placement or Civilian Placement modules have a high chance of receiving a waypoint called '0 MOVE' that they will never follow.

**Comment by SpyderBlack723** [comment]
Waypoints in Arma are a bit odd, there is always a "0" waypoint that is essentially pointless. They will never follow it.

**Comment by speedweasel** [comment]
> Waypoints in Arma are a bit odd, there is always a "0" waypoint that is essentially pointless. They will never follow it. This is correct behavior.

Currently, numerous units placed by ALiVE are essentially ineffective.  They remain fixed where they spawn and do not patrol, follow waypoints or react to enemy presence.   

If the "0" waypoint is a red-herring, that's good to know but currently about a quarter of all AI  units spawned by the Military Placement or Civilian Placement modules aren't doing their job.  That's the problem I'm trying to fix.  :)

**Comment by tupolov** [comment]
So I just ran your mission and looked at the units placed near the player. They follow the ALIVE assigned waypoints fine?

You should note that some units in a group will be "garrisoned" and holding at a building position and won't move to the waypoint. Sometimes this building position is just outside the building, so it looks like they are not moving.

As Spyder say, units spawned via script always get a 0 MOVE waypoint, they won't move until assigned another waypoint. There are exceptions, units brought in by LOGCOM will not have a waypoint initially, they will sit and wait to be tasked by OPCOM.

I could not find any groups that just had a 0 MOVE waypoint only.

**Comment by friznit** [comment]
Unable to repro this.  Played an ALiVE mission for 3 hours with 40 players on a dedi server using a fairly typical mod pack (ACE, RHS, TFAR etc) and peaked at 480 AI spawned.  Groups continued to follow move and cycle waypoints throughout.
