### ISSUE TITLE
BUG: Forcepool drops to 0 after at least one persistent restart with Mil Log set to YES on persistent

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#367]
When setting  Mil Logistics to persistent of YES....reinforcement force pool drops to 0 after a server restart with at least one server save and exit on mission.

**Comment by HeroesandvillainsOS** [comment]
I can confirm this bug with just ALiVE and CBA. Upon loading a persistent save from the DB, the Logistics tablet says the Force Pool is 0. Though note, it mostly just says "Waiting..." (probably a separate bug), but you can briefly see it say 0 and there is no pool available.

Here is a server rpt but bare in mind, I don't have any modules debugged for this: https://www.dropbox.com/s/tj3jfzlk8t3mol0/arma3server_x64_2017-06-27_21-27-57.rpt?dl=0

**Comment by GunnyDev** [comment]
Fixed in above commit, thanks for the report

**Comment by HeroesandvillainsOS** [comment]
Seems to be fixed in 1.3.7.
