### ISSUE TITLE
Malden 2035 / OPCOM Waiting for Ai System

### ISSUE THREAD

**Issue by Tress16** [ALiVEOS/ALiVE.OS#368]
I can't play Malden 2035 with ALiVE.
Everytime I get the follow issue:

https://steamuserimages-a.akamaihd.net/ugc/850466977097036475/B33E3C8D54F50B3C0D2F229B4C1562E39715A556/

**Comment by friznit** [comment]
Index is only available in the dev version of ALiVE.  Release due Soon™

**Comment by Tress16** [comment]
OK. Thx
