### ISSUE TITLE
Helicopters blowing up/not spawning on helipads on Malden Index on RC Build

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#369]
Tested last night with just CBA and ALiVE.

Helos were spawning on walls/fences, etc. and not on helo pads.  Malden 2035 index with latest ALiVE RC Build posted here.

**Comment by HeroesandvillainsOS** [comment]
@highhead

**Comment by friznit** [comment]
Fixed with the reindex
