### ISSUE TITLE
Aircraft blow up at catapult when preparing to launch (ATO module)

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#371]
Using CBA and ALiVE,

F-181 Black Wasps as they throttle up at the catapult launch will explode before takeoff.  Happened each time ALiVE tried to send one up for a mission.  This was on Malden 2035.

**Comment by AUTigerGrad** [comment]
I tested on Stratis and everything worked fine so I'm assuming it has something to do with the Malden index, etc.  Worked great on Stratis.

**Comment by tupolov** [comment]
More robust in the dev build, but yes noticed the aircraft sometimes crash on takeoff

**Comment by tupolov** [comment]
I repro'd this on Malden too. Have logged a ticket with BIS here: https://feedback.bistudio.com/T125951

Works mostly fine on Altis and Stratis.

**Comment by tupolov** [comment]
Have improved the takeoff code, but still reliant on BIS function during actual takeoff.
