### ISSUE TITLE
V44 X Blackfish (Armed) doesn't seem to engage when used as CAS

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#372]
So there was a report on Reddit here: https://www.reddit.com/r/arma/comments/6j3uug/v44_blackfish_is_the_ultimate_pacifist/

That the Blackfish wasn't doing its job when used as ALiVE CAS CS, with one user sharing a known editor workaround:

"You can make an AI-manned blackfish attack targets like so:
Split the pilot to a different squad from his gunners Give the pilot a loiter waypoint on your target, make his combat mode careless so he won't attack targets head on. Make sure the gunners are in a separate squad and their combat mode is not careless (otherwise they won't shoot)"

I'm testing this myself in the editor, and it is pretty clear that this plane is extremely hesitant to fire on enemy infantry, vehicles, and helicopters by default with the ALiVE mod. I've issued all orders to this VTOL (SAD, Attack and Run, and even Loiter hoping it would defend itself; all using the fire at will option), and other than in one instance where it "might" have fired using it's door guns (honestly, I don't think it was. I think it was being shot at but it's was hard to say definitively because it was kind of far away at the time), it simply will not engage at all.

**Comment by HeroesandvillainsOS** [comment]
Probably unrelated but I did see this at one point during the test (current stable ALiVE version, not the RC floating around): [img]http://i.imgur.com/9BL51nQ.jpg[/img]

**Comment by GunnyDev** [comment]
This is a BIS issue and logged via the feedback tracker here https://feedback.bistudio.com/T117808, no matter what we try and do, it will not engage. Closing because BIS.

**Comment by HeroesandvillainsOS** [comment]
Thanks Gunny.
