### ISSUE TITLE
New Feature Assymetric Warfare: Support flags

### ISSUE THREAD

**Issue by speeeedycom** [ALiVEOS/ALiVE.OS#373]
You frequently see that rebel factions use flags or graffiti to indicate that they control a certain area and/or town. This might be a nice feature in Assymatric Warfare that even without 'intel' enabled on the C2iStar your able to spot from a distance (using for instance binoculairs) if a town or certain area is controlled by a faction.

**Comment by HeroesandvillainsOS** [comment]
I don't feel like there are enough flags available to insurgent factions in the game for this to work for more factions than it wouldn't.

Then you have to consider what to do with the flag once the area is taken back (would probably require a new command to lower old flag and raise new flags, for example).

I'm not trying to deter creative requests though. This is a neat idea, it's just it would need to be fully thought out, implemented for vanilla and modded factions, and then written and applied.
