### ISSUE TITLE
[Feature Request] Manual task generation shouldn't include factions not used in the scenario

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#374]
Some players are getting confused on how to properly manually generate a task, and are using factions not available in the scenario.

Example: C2ISTAR is overridden in the module to only allow LOP_AM_OPF. This works for auto-generated tasking. However, if you manually create a task, factions such as OPF_F are allowed to be selected, and will result in a broken task because CSAT isn't being used.

I'd like to either have the available factions list limited to only factions available to OPCOM, or only the faction(s) defined in the C2ISTAR module.

**Comment by tupolov** [comment]
I've tested this and didn't see any "broken" tasks when using a faction that is not in game. Can you elaborate on broken tasks.

**Comment by HeroesandvillainsOS** [comment]
Yes I can! Don't believe reports from users on the forums! I had a few messages on this and took it at face value, but you are 100% correct, the tasks seem to work no matter what faction you select. Both reports said if you requested a faction not existent in the scenario, the mission would generate and not have enemies nearby. It made sense in my mind, but you are right. They work no matter what.

Gonna close this. Although I'd like to be able to shorten the list and limit it to just the factions I use in the mission, my reason for opening the feature request because the alternative meant a mission could break. Which it won't. Sorry about that.

**Comment by kgrosvenor** [comment]
On another note, i see where you were going with this, is there a way to limit the tablet to restrict it for more immersion? For e.g i shouldnt be spawning in 2035 soliders in vietnam
