### ISSUE TITLE
ORBAT created Factions spawn a backpack at the base of the teamleader within ALiVE

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#375]
All ORBAT created or edited factions will spawn in with a backpack laying on the ground at the foot of the team leader.  This is not a Task Force Radio issue as this is occuring without TFAR active and with only CBA and ALiVE as active mods.  Zeus placed ORBAT groups do not spawn a backpack but any ORBAT profiles spawned by ALiVE do spawn the backpack on the ground.

**Comment by coachwn** [comment]
I haven't tried it without TFAR but if it shows up for me when I check it that will be a nice find and maybe something that we have been attributing to TFAR all along.

**Comment by HeroesandvillainsOS** [comment]
This is definitely not related to TFAR. I'm seeing to too and am not using TFAR. I think it's related to ORBAT.

**Comment by SpyderBlack723** [comment]
43c4692f40c95c13687a7039736dd2397345e2f3
