### ISSUE TITLE
Error when joining group in operations

### ISSUE THREAD

**Issue by ragingbowels** [ALiVEOS/ALiVE.OS#379]
Hi,

I am getting the following error when trying to join a group in operations.  I am transported to the area but the actual join fails.  During the process I get the error below.

![20170630205122_1](https://user-images.githubusercontent.com/29823104/27765070-72576df6-5e5d-11e7-9c52-8778ced1a8c2.jpg)

Here is the link to the alive forum where I original posted this issue.

http://www.alivemod.com/forum/3044-error-while-joining-group-in-operations  

Thank you for a great mod and continued support!!

**Comment by GunnyDev** [comment]
Seems this is being called in unscheduled. Causing the exception to be thrown.

**Comment by GunnyDev** [comment]
Commited Fix, needs testing.

**Comment by ragingbowels** [comment]
Hi Gunny,

Whats the best way to test this fix?  Download the code and insert it into the pbo as a new sqf with the updates?

Sorry I am a bit new to this.  I will definitely test it, just need to know the best method.

Thanks!!

**Comment by GunnyDev** [comment]
We usually test it internally prior to releasing it into the wild.

However if you don't mind testing it for me, I can send you the pbo later on which you can use to test.

**Comment by ragingbowels** [comment]
Sure feel free to send it over.  I am more than happy to test it.
