### ISSUE TITLE
String Table

### ISSUE THREAD

**Issue by sargken** [ALiVEOS/ALiVE.OS#38]
I don't think English is supported in the string table and you have a lot of entry's with English in the string table. Also Double entry STR_ALIVE_INDEXER_MAPPATH_COMMENT.

I think it should be Original instead of English.

**Comment by SpyderBlack723** [comment]
English is supported

@tupolov STR_ALIVE_INDEXER_MAPPATH_COMMENT --> two different sets of text

**Comment by tupolov** [comment]
https://community.bistudio.com/wiki/Stringtable.xml

says English is supported, but we should probably switch to Original

**Comment by sargken** [comment]
16:07:08 Unsupported language English in stringtable
That's the reason why I bring it up. Spams the RTP.

**Comment by tupolov** [comment]
Already fix bro
