### ISSUE TITLE
Logistics tablet Force Pool says "WAITING..." indefinitely as soon as delivery options pop up

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#380]
ALiVE CBA only. 1.3.7 pre-release. I have logistics delivery allowed for ground, VTOL and paradrop. When opening the Logistics menu, you can briefly see the Current Force Pool, but as soon as the delivery options pop up, the force pool says "Waiting..." and doesn't change.

**Comment by GunnyDev** [comment]
Hi Heroes, can you send me a link to your mission please.

I'm not seeing the issue using pre-release and latest CBA.

Thanks

**Comment by marceldev89** [comment]
I've seen this happen as well over a long stretch of time. I think it mostly happened when running on a dedicated server.

**Comment by GunnyDev** [comment]
Ok thanks me for the info will let it run for a bit and check.

**Comment by HeroesandvillainsOS** [comment]
It's on a dedicated server and immediate. I'll post the mission here in a sec.

**Comment by HeroesandvillainsOS** [comment]
@GunnyDev Here you go: https://www.dropbox.com/s/irukmgqb642fs9v/ALiVE-Tanoa_Showcase.Tanoa.pbo?dl=0

**Comment by GunnyDev** [comment]
Fix in

**Comment by HeroesandvillainsOS** [comment]
This appears to be fixed in the current RC build. Closing. Will reopen if anyone still have issues.
