### ISSUE TITLE
Units Spawn Stuck, Won't Move

### ISSUE THREAD

**Issue by runedog48** [ALiVEOS/ALiVE.OS#382]
### Prerequisites

* [✗] Can you reproduce the problem using ALiVE and CBA Only? ( Tested briefly )
* [✓] Are you running the latest version of ALiVE ?
* [✓] Are you running the latest version of CBA_A3?
* [Pending] Have you attached an unbinarized SQM?
* [Pending] Have you attached your RPT
* [Pending] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Units spawn stuck and hunched over, unable to move. Their move orders were given but they will not move at all even if I move their position with Zeus and manually give them a move order.

### Steps to Reproduce

1. Create any mission
2. Play the mission
3. Watch as mostly enemy units get stuck

**Expected behavior:** Units are freely able to move about and wage war.

**Actual behavior:** Units are stuck bent over in a funny state unable to move or process any orders other than shooting enemies in sight.

### Additional Info

The server being used is running Ubuntu 16.04, it's not public and I'm the only one who ever gets on.

Video: https://youtu.be/P8J8oUo2C1s

They're stuck in some sort of state, I observed that when they went unconscious from being shot ( ACE Medical ) and became conscious again they escaped whatever state they're in and started moving around properly. Also, I've noticed that if one group is affected, all the groups nearby ( maybe globally ) tend to be affected as well.

List of mods I'm trying to use together: 
```
@cba_a3;
@ace;
@alive;
@mcc;
@enhancedmovement;
@enhancedsoundscape;
@dynasound;
@bloodlust;
@suppress;
@cupcore;
@cupmaps;
@cupcwa;
@cupweapons;
@cupunits;
@cupvehicles;
@cupcompat;
@kunduz;
@adr97

```

**Comment by SavageCDN** [comment]
Can you provide your server's RPT file?

**Comment by runedog48** [comment]
Just noticed that prerequisites have been added when creating a ticket, I'll fill them out when I get logs of this bug occurring. I didn't initially have logging enabled because Linux things, but it's enabled now.

**Comment by speedweasel** [comment]
Have the same problem running only CBA_A3 and ALiVE.  See here:

https://github.com/ALiVEOS/ALiVE.OS/issues/365

**Comment by tupolov** [comment]
I just tested the provide vanilla mission in #365 and couldn't repro the issue.

@runedog48 can you repro this with just CBA and ALiVE?

**Comment by runedog48** [comment]
No, I was no able to reproduce the problem without mods when I briefly tested it. I just uploaded a video that demonstrates the problem well.
https://youtu.be/P8J8oUo2C1s

**Comment by runedog48** [comment]
This seems to be a CUP related issue. I switched from CUP to RHS due to file size and have not had units getting stuck when using RHS.

( Sorry for double post )

**Comment by Whigital** [comment]
I'm guessing this is either `Enhanced Movement` or `Supressed` causing this. ALiVE does nothing more than hand out waypoints, not micro managing aninamtions of induvidual AI.

Our group run `Enhanced Movement` alongside `ALiVE`, `ACE`, `RHS` and a host of other mods and never seen this.

**Comment by highhead** [comment]
As this issue has not been replicated with ALiVE & CBA and has been "fixed" by the mission maker by just switching to another mod we will close this issue for now! Feel free to re-open once that issue can be replicate with vanilla assets and ALiVE fucking up waypoints!
