### ISSUE TITLE
Custom Aircraft not launching with MACC

### ISSUE THREAD

**Issue by Burdy323** [ALiVEOS/ALiVE.OS#384]
### Prerequisites

* [N] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [https://ufile.io/nzkqu - requires UNSUNG ] Have you attached an unbinarized SQM?
* [https://ufile.io/gxjqg] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [https://pasteboard.co/GzqRejO.png] Have you attached screenshots of the Parameters set on the offending Module?

### Description
MACC does not recognize custom aircraft - get suck on "aircraft not available".

### Steps to Reproduce

Attempt using the MACC module with any custom hand placed aircraft.

**Expected behavior:** [What you expected to happen]
MACC to recognize the aircraft.
**Actual behavior:** [What actually happened]
MACC does not recognize the aircraft.

**Comment by tupolov** [comment]
Have you tried aircraft other than those in UNSUNG? I.e. another custom faction with aircraft?

**Comment by Burdy323** [comment]
I have not, however, like I said earlier I did try to make a custom faction consisting of only UNSUNG aircraft to make sure it just wasn't an issue with the default UNSUNG faction. I'll try and test another mod when I get the chance

**Comment by tupolov** [comment]
Can you once in game with ATO, access the debug console and type the following:

`hint str(["classnameofUNSUNGaircraft"] call ALiVE_fnc_getAircraftRoles);`

Then hit execute and see what info comes up on screen.

**Comment by Burdy323** [comment]
Yeah that appears to be the issue - they're all miscategorized (E.G - no matter the type, end up under CAS for the most part). 

I figured this may be the issue. Is there any manual line of code you can add to the vehicles INIT to define what it's role is? May want to add that to the WIKI as well (if there is), because this will probably be an issue for a few mods i'd imagine.

**Comment by tupolov** [comment]
Out of interest, what are these aircraft and what are they armed with?

**Comment by Burdy323** [comment]
F111's, F4's, SuperSabres... No matter the variant though, most carry explosive ordnance on the belly. This leads to most if not all CAP Variants of Aircraft being classified as CAS

**Comment by tupolov** [comment]
But do they carry Air to Air or Air to Ground missiles? That's the specific requirement for CAP/DCA and SEAD respectively.

**Comment by Burdy323** [comment]
Yeah, looks like it. Sidewinders meet that specification yeah?

**Comment by tupolov** [comment]
ok, one final ask.

For the aircraft with missiles (sidewinders or others) type the following into the debug console:

`diag_log format[">>>>>>>>>>>>>>FOR ALIVE: %1 <<<<<<<<<<<<<<<<","classnameofaircraft"];  
{ diag_log str(_x);} foreach ("classnameofUNSUNGaircraft" call BIS_fnc_magazinesEntityType);`

and then cut and paste the results from your RPT into this ticket. Thanks!

**Comment by Burdy323** [comment]
```
19:10:01 ">>>>>>>>>>>>>>FOR ALIVE: uns_A7_CAP <<<<<<<<<<<<<<<<"
19:10:01 """uns_1030Rnd_M61_HEI"""
19:10:01 """uns_AIM9Ex4"""
19:10:01 """uns_2Rnd_A7Fuel"""
19:10:01 """uns_AIM9Dx2"""
19:10:01 """uns_54Rnd_pylonblank"""
19:10:01 """120Rnd_CMFlare_Chaff_Magazine"""

```

**Comment by tupolov** [comment]
Ok for the AIM9s....

`ammocfg = configFile >> "CfgAmmo" >> (getText(configFile >> "CfgMagazines" >> "uns_AIM9Ex4 >> "ammo")) ; hint str(getNumber(ammoCfg >> "missileLockMaxSpeed"));`

What are the values?

**Comment by tupolov** [comment]
There was a missing " 

Code updated above

**Comment by Burdy323** [comment]
Got it - the number returned is 0

**Comment by tupolov** [comment]
Ok, looks like UNSUNG missiles are not configured according to BIS standards. Could you get us the whole ammo config for the AIM9? Also worth asking the UNSUNG guys to update the ammo config.

**Comment by SavageCDN** [comment]
Added this info to wiki FAQ and MACC sections editor notes

**Comment by Burdy323** [comment]
Anyway to the config within the config viewer? Got the AIM9 ammo config open in the CFG Viewer, but cant figure out how to copy everything in it.

Likewise, tried going into the planes config.bin, but everything in there was encrypted.

**Comment by tupolov** [comment]
`ammo = (configfile >> "CfgAmmo" >> "Aim9") call BIS_fnc_getCfg; [ammo] call ALiVE_fnc_inspectConfig;` check your RPT

**Comment by Burdy323** [comment]
Syntax error
`ammo = (configfile >> "CfgAmmo" >> "Uns_AIM9E") call BIS_fnc_getCfg; [ammo, true] call ALiVE_fnc_inspectConfig;`

14:51:20 Error in expression <ammo = (configfile >> "CfgAmmo" >> "Uns_AIM9E>
14:51:20   Error position: <= (configfile >> "CfgAmmo" >> "Uns_AIM9E>
14:51:20   Error Reserved variable in expression

By the way, I added you on steam Tupolov. Have a couple more ALIVE related issues that i'm not to sure are on my end or vice versa

**Comment by tupolov** [comment]
ok try above again, apologies

**Comment by tupolov** [comment]
any news?

**Comment by Burdy323** [comment]
Sorry - been busy tinkering w/ the ALIVE custom HQ's we talked about yesterday - despite spawning over 20 groups through the custom objectives, having priority set to 999, and making sure they have HQ's via the debugger, still running into all the groups being killed off with no logistics within 20-40 mins.

And still getting an error :

`21:33:47 Error in expression <} else {false};

_text = " ----------- "+_cfg+" ----------- ";
[_text] call ALIV>
21:33:47   Error position: <+_cfg+" ----------- ";
[_text] call ALIV>
21:33:47   Error +: Type Config entry, expected Number,Array,String,Not a Number
21:33:47 File \x\alive\addons\x_lib\functions\diagnostics\fnc_inspectConfig.sqf [ALiVE_fnc_inspectConfig], line 1815
21:33:47 Error in expression <} else {false};

_text = " ----------- "+_cfg+" ----------- ";
[_text] call ALIV>
21:33:47   Error position: <+_cfg+" ----------- ";
[_text] call ALIV>
21:33:47   Error Generic error in expression
21:33:47 File \x\alive\addons\x_lib\functions\diagnostics\fnc_inspectConfig.sqf [ALiVE_fnc_inspectConfig], line 1815
`

**Comment by tupolov** [comment]
Ok, apologies I should have checked the code. Use this (I've tested this)

```
ammotype = getText(configFile >> "CfgMagazines" >> "Uns_AIM9E" >> "ammo"); 
{diag_log format["%1 : %2", _x, [_x] call BIS_fnc_getCfgData];} foreach (configProperties [configFile >> "CfgAmmo" >> ammotype]);
```

WRT LOGCOM, can you turn on debug on Mil Logistics, run your mission and post the RPT to the forums or on a suitable ticket (not on this ticket). Thanks!

**Comment by Burdy323** [comment]
Here ya go 

`
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9E/model : \uns_missilebox\FRL_AIM9X\FRL_AIM9x"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9E/proxyShape : \uns_missilebox\FRL_AIM9X\FRL_AIM9x"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9E/minRange : 200"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9E/maxRange : 2000"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9E/thrust : 800"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9E/maxSpeed : 1500"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9E/cmImmunity : 0.85"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/hit : 400"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/indirectHit : 180"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/indirectHitRange : 6"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/minRangeProbab : 0.7"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/midRange : 750"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/midRangeProbab : 0.95"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/maxRangeProbab : 0.6"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/maneuvrability : 75"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/thrustTime : 500"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/maxControlRange : 2000"
11:49:49 "bin\config.bin/CfgAmmo/Uns_AIM9D/weaponLockSystem : 2"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/simulationStep : 0.002"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/airFriction : 0.026"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/sideAirFriction : 0.003"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/cost : 1000"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/timeToLive : 35"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/trackOversteer : 1"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/trackLead : 1"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/initTime : 0.5"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/fuseDistance : 250"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/CraterEffects : AAMissileCrater"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/explosionEffects : AAMissileExplosion"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/effectsMissileInit : RocketBackEffectsRPG"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/muzzleEffect : BIS_fnc_effectFiredHeliRocket"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/effectsMissile : missile3"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/whistleDist : 20"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/lockType : 0"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/irLock : 1"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/airLock : 2"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/aiAmmoUsageFlags : 256"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/soundHit1 : [""A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_01"",2.51189,1,1900]"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/soundHit2 : [""A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_02"",2.51189,1,1900]"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/soundHit3 : [""A3\Sounds_F\arsenal\weapons\Launchers\Titan\Explosion_titan_missile_03"",2.51189,1,1900]"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/multiSoundHit : [""soundHit1"",0.34,""soundHit2"",0.33,""soundHit3"",0.33]"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/CamShakeExplode : any"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/CamShakeHit : any"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/CamShakeFire : any"
11:49:49 "bin\config.bin/CfgAmmo/uns_MissileBase_AA/CamShakePlayerFire : any"
11:49:49 "bin\config.bin/CfgAmmo/uns_missileBase/manualControl : 0"
11:49:49 "bin\config.bin/CfgAmmo/uns_missileBase/soundHit : [""\uns_compat\ca\Weapons\Data\Sound\explosion_large1"",19.9526,1]"
11:49:49 "bin\config.bin/CfgAmmo/uns_missileBase/soundFly : [""\uns_compat\ca\Weapons\Data\Sound\rocket_fly1"",0.1,1.5]"
11:49:49 "bin\config.bin/CfgAmmo/uns_missileBase/soundEngine : [""\uns_compat\ca\Weapons\Data\Sound\noise"",0.00316228,1]"
11:49:49 "bin\config.bin/CfgAmmo/uns_missileBase/supersonicCrackNear : [""\uns_compat\ca\Weapons\Data\Sound\supersonic_crack_close.wss"",1,1]"
11:49:49 "bin\config.bin/CfgAmmo/uns_missileBase/supersonicCrackFar : [""\uns_compat\ca\Weapons\Data\Sound\supersonic_crack_50meters.wss"",1,1]"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/explosionSoundEffect : DefaultExplosion"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/deflecting : 0"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/dangerRadiusHit : -1"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/suppressionRadiusHit : 30"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/HitEffects : any"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/Components : any"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/maverickWeaponIndexOffset : 0"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/htMin : 60"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/htMax : 1800"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/afMax : 200"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/mfMax : 100"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/mFact : 0"
11:49:49 "bin\config.bin/CfgAmmo/MissileBase/tBody : 0"
11:49:49 "bin\config.bin/CfgAmmo/MissileCore/simulation : shotMissile"
11:49:49 "bin\config.bin/CfgAmmo/MissileCore/missileLockCone : 50"
11:49:49 "bin\config.bin/CfgAmmo/MissileCore/visibleFire : 32"
11:49:49 "bin\config.bin/CfgAmmo/MissileCore/audibleFire : 32"
11:49:49 "bin\config.bin/CfgAmmo/MissileCore/visibleFireTime : 20"
11:49:49 "bin\config.bin/CfgAmmo/Default/access : 3"
11:49:49 "bin\config.bin/CfgAmmo/Default/underwaterHitRangeCoef : 1"
11:49:49 "bin\config.bin/CfgAmmo/Default/typicalSpeed : 900"
11:49:49 "bin\config.bin/CfgAmmo/Default/explosionForceCoef : 1"
11:49:49 "bin\config.bin/CfgAmmo/Default/isCraterOriented : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/craterShape : "
11:49:49 "bin\config.bin/CfgAmmo/Default/weaponType : Default"
11:49:49 "bin\config.bin/CfgAmmo/Default/animated : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/shadow : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/cartridge : "
11:49:49 "bin\config.bin/CfgAmmo/Default/tracerColor : [0.7,0.7,0.5,0.04]"
11:49:49 "bin\config.bin/CfgAmmo/Default/tracerColorR : [0.7,0.7,0.5,0.04]"
11:49:49 "bin\config.bin/CfgAmmo/Default/soundFall : ["""",1,1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/soundFakeFall : [""soundFall"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitGroundSoft : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitGroundHard : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitMan : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitArmor : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitIron : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitBuilding : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitFoliage : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitWood : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitGlass : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitGlassArmored : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitConcrete : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitRubber : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitPlastic : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitDefault : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitMetal : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitMetalplate : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitTyre : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitWater : [""soundHit"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/soundImpact : ["""",1,1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactGroundSoft : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactGroundHard : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactMan : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactIron : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactArmor : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactBuilding : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactFoliage : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactWood : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactGlass : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactGlassArmored : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactConcrete : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactRubber : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactPlastic : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactDefault : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactMetal : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactMetalplate : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactTyre : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/impactWater : [""soundImpact"",1]"
11:49:49 "bin\config.bin/CfgAmmo/Default/grenadeFireSound : []"
11:49:49 "bin\config.bin/CfgAmmo/Default/grenadeBurningSound : []"
11:49:49 "bin\config.bin/CfgAmmo/Default/deflectionSlowDown : 0.8"
11:49:49 "bin\config.bin/CfgAmmo/Default/explosive : 1"
11:49:49 "bin\config.bin/CfgAmmo/Default/craterWaterEffects : ImpactEffectsWater"
11:49:49 "bin\config.bin/CfgAmmo/Default/effectsSmoke : SmokeShellWhite"
11:49:49 "bin\config.bin/CfgAmmo/Default/effectsFire : CannonFire"
11:49:49 "bin\config.bin/CfgAmmo/Default/effectFlare : FlareShell"
11:49:49 "bin\config.bin/CfgAmmo/Default/effectFly : "
11:49:49 "bin\config.bin/CfgAmmo/Default/mineJumpEffects : "
11:49:49 "bin\config.bin/CfgAmmo/Default/waterEffectOffset : 0.45"
11:49:49 "bin\config.bin/CfgAmmo/Default/directionalExplosion : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/explosionAngle : 60"
11:49:49 "bin\config.bin/CfgAmmo/Default/explosionDir : explosionDir"
11:49:49 "bin\config.bin/CfgAmmo/Default/explosionPos : explosionPos"
11:49:49 "bin\config.bin/CfgAmmo/Default/explosionEffectsDir : explosionDir"
11:49:49 "bin\config.bin/CfgAmmo/Default/minimumSafeZone : 0.1"
11:49:49 "bin\config.bin/CfgAmmo/Default/soundTrigger : []"
11:49:49 "bin\config.bin/CfgAmmo/Default/soundActivation : []"
11:49:49 "bin\config.bin/CfgAmmo/Default/soundDeactivation : []"
11:49:49 "bin\config.bin/CfgAmmo/Default/minTimeToLive : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/laserLock : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/nvLock : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/artilleryLock : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/hitOnWater : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/lockSeekRadius : 100"
11:49:49 "bin\config.bin/CfgAmmo/Default/artilleryDispersion : 1"
11:49:49 "bin\config.bin/CfgAmmo/Default/artilleryCharge : 1"
11:49:49 "bin\config.bin/CfgAmmo/Default/autoSeekTarget : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/shootDistraction : -1"
11:49:49 "bin\config.bin/CfgAmmo/Default/explosionTime : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/icon : "
11:49:49 "bin\config.bin/CfgAmmo/Default/submunitionAmmo : "
11:49:49 "bin\config.bin/CfgAmmo/Default/explosionType : explosive"
11:49:49 "bin\config.bin/CfgAmmo/Default/mineTrigger : RangeTrigger"
11:49:49 "bin\config.bin/CfgAmmo/Default/mineBoundingTime : 3"
11:49:49 "bin\config.bin/CfgAmmo/Default/mineBoundingDist : 3"
11:49:49 "bin\config.bin/CfgAmmo/Default/mineInconspicuousness : 10"
11:49:49 "bin\config.bin/CfgAmmo/Default/mineFloating : -1"
11:49:49 "bin\config.bin/CfgAmmo/Default/mineDiveSpeed : 1"
11:49:49 "bin\config.bin/CfgAmmo/Default/minePlaceDist : 0.5"
11:49:49 "bin\config.bin/CfgAmmo/Default/suppressionRadiusBulletClose : -1"
11:49:49 "bin\config.bin/CfgAmmo/Default/dangerRadiusBulletClose : -1"
11:49:49 "bin\config.bin/CfgAmmo/Default/caliber : 1"
11:49:49 "bin\config.bin/CfgAmmo/Default/whistleOnFire : 0"
11:49:49 "bin\config.bin/CfgAmmo/Default/NVGMarkers : any"
11:49:49 "bin\config.bin/CfgAmmo/Default/minDamageForCamShakeHit : 0.55"
`

**Comment by Burdy323** [comment]
In the meantime though, as I suggested earlier, is there a manual line of code you can drop into the unit's INIT in order to manually categorize units? I foresee this being very useful in the future as I can only imagine that UNSUNG won't be the only mod with unfriendly configs

**Comment by tupolov** [comment]
No not today.

**Comment by tupolov** [comment]
Basically the UNSUNG missile config is out of date. I'm surprised as Eggbeast is usually on top of this stuff. 
https://community.bistudio.com/wiki/A3_Targeting_config_reference

I'll look at multiple ways to cover the qualification - we want to avoid static overrides etc.

**Comment by tupolov** [comment]
I've added a check for `"airLock"` which should cover "legacy" ammo that doesn't have the A3 1.70 targeting config.

**Comment by Burdy323** [comment]
Understandable. Here's something I thought about : say you are playing with FOW or IFA3 - you said that the aircraft sorting (for CAP at least) is linked to the missile ordinance on the aircraft. How would this work for the older era propeller planes?

**Comment by tupolov** [comment]
Checked IFA3 and the guns they use on aircraft use the `"airLock"` property, so aircraft will be registered appropriately.
