### ISSUE TITLE
Placing ALiVE Advanced Marker causes player unit to teleport to marker position

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#386]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [Y] Have you attached an unbinarized SQM?
* [N/A] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N/A] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Place an advanced marker with left ctrl + alt + left click and your player gets teleported to the marker position

### Steps to Reproduce

1. Press left ctrl + alt + left click anywhere on the map 

**Expected behavior:** 

An advanced marker would be placed without me being teleported

**Actual behavior:** 

I get teleported to the Advanced Marker position

**Repro mission**

https://www.dropbox.com/s/irukmgqb642fs9v/ALiVE-Tanoa_Showcase.Tanoa.pbo?dl=0

**Comment by SpyderBlack723** [comment]
This only happens in the editor because BIS sets a teleport hotkey.

**Comment by HeroesandvillainsOS** [comment]
Right with alt plus left click. ALiVE always disabled this in the editor, correct?

**Comment by HeroesandvillainsOS** [comment]
Maybe I'm just now noticing it. I can close this.  Could have sworn in any mode, including editor, ALiVE overrides this feature. I'll close if this is intended behavior and just play in SP.
