### ISSUE TITLE
Replace stacked event handlers with mission event handlers

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#388]
The `BIS_fnc_addStackedEventHandler`, `BIS_fnc_removeStackedEventHandler` and `BIS_fnc_executeStackedEventHandler` functions will be removed in A3 1.74 (1.73). They are supposed to be replaced by `addMissionEventHandler`.

Files using stacked event handlers (might be commented out at places):
- `addons/sys_data/tests/fnc_DataInit.sqf`
- `addons/sys_perf/fnc_perfInit.sqf`
- `addons/sys_statistics/fnc_statisticsInit.sqf`
- `addons/main/fnc_pauseModulesAuto.sqf`
- `addons/main/XEH_postServerInit.sqf`

**Comment by tupolov** [comment]
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#PlayerConnected
