### ISSUE TITLE
SYS PLAYER does not restore the player state when mission is launched

### ISSUE THREAD

**Issue by highhead** [ALiVEOS/ALiVE.OS#392]
### Prerequisites

* [yes] Can you reproduce the problem using ALiVE and CBA Only?
* [yes] Are you running the latest version of ALiVE ?
* [yes] Are you running the latest version of CBA_A3?
* [yes] Have you attached an unbinarized SQM?
* [no] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [no] Have you attached screenshots of the Parameters set on the offending Module?

### Description

SYS PLAYER does not restore player state after loading a saved mission.

### Steps to Reproduce

1. Load a formerly saved mission on a dedicated server, where sys player was active and player data has been stored to DB.

**Expected behavior:** [What you expected to happen]

Player state is restored.

**Actual behavior:** [What actually happened]

Player state is not restored.

**Additional information:

This happens on mission start (maybe the EH does not fire on briefing screen?).  The data loads in fine, but only player state is not restored. If you click "abort" (to not override the already loaded player state) and reconnect, the player state is restored fine.

new_test_alive_jetz.Altis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1150327/new_test_alive_jetz.Altis.zip)

**Comment by tupolov** [comment]
Fixed in Dev
