### ISSUE TITLE
Ambient civ vehicles spawn in the air and float to the ground

### ISSUE THREAD

**Issue by Neodyn** [ALiVEOS/ALiVE.OS#393]
Some civilian vehicles are generated on Takistan in the sky and fall to the ground during the mission.

**Comment by Neodyn** [comment]
Ok so i'll provide a sample mission. 
Or you can have my final mission but there are some mod dependencies. What du you prefer?

**Comment by friznit** [comment]
Vanilla only please - ALiVE & CBA

**Comment by Neodyn** [comment]
Here is a sample mission: https://www.dropbox.com/sh/4vdisabsfef24st/AABFkthW_xJatfj_2C-6g3Dna?dl=0
Switch into Zeus take a helo and fly arround. But on CUPS Terrain it is easy to reproduce this issue.

**Comment by marceldev89** [comment]
Fixed in https://github.com/ALiVEOS/ALiVE.OS/commit/d90d3e115d486a883801f62cb167aba527b1bfc2, hopefully.

**Comment by friznit** [comment]
Tested
