### ISSUE TITLE
Logistics radio chatter only uses BLUFOR regardless of faction or side

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#398]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [RC] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [Y] Have you attached an unbinarized SQM?
* [Y] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N] Have you attached screenshots of the Parameters set on the offending Module?

### Description

When requesting Military Logistics supply delivery, the radio chatter is BLUFOR, even if you're playing as an OPFOR faction such as OPF_F. The radio chat dialogue also says BLUFOR.

### Steps to Reproduce

1. Place ALiVE required, Virtual AI, Player Combat Logistics, OPCOM set to OPF_F, MIL Placement MIL Obj to OPF_F and Military Logistics synced to OPCOM set to faction only
2. Place an OPF_F player on the map and press play
3. Open the Player Combat Logistics and request any kind of supply unit or object
4. The radio chatter and radio chat dialogue is of a BLUFOR unit and says BLUFOR in the dialogue

**Expected behavior:** I'd expect the radio chatter to tap into the unit and logistics faction. For OPF_F I'd expect Farsi as the audible language. 

Possible request: I'd also like if the faction is BLUFOR British 3CB, that the audible voices for request and confirmation be British like the units. Currently it's still NATO.

**Actual behavior:** OPF_F radio chatter is confirmed by BLUFOR. And confirmation voice is BLU_F and the OPF_F unit making the request sometimes never says anything when putting a request in.

Mission: https://www.dropbox.com/s/79wsaxdq5f50s97/logistics_test.Stratis.zip?dl=0

Rpt: https://www.dropbox.com/s/sho1re2qs2kqds4/Arma3_x64_2017-07-26_09-12-44.rpt?dl=0

**Comment by tupolov** [comment]
This seems to be the code at fault https://github.com/ALiVEOS/ALiVE.OS/blob/33b1f208056875ad803e927098d5516e24712137/addons/sup_player_resupply/fnc_PR.sqf#L611

```
 // Create HQ Audio source
            if (_audio) then {
                ALIVE_PR_HQ = (createGroup west) createUnit ["Logic", [10,10,1000], [], 0, "NONE"];
                ALIVE_PR_HQ setGroupId [(getText(configFile >> "CfgHQIdentities" >> "HQ" >> "name"))];
                ALIVE_PR_HQ setIdentity "EPC_B_BHQ";
                ALIVE_PR_HQ kbAddtopic["ALIVE_PR_protocol", "a3\modules_f\supports\kb\protocol.bikb"];
            };
```
