### ISSUE TITLE
Integrate RHS Logistics staticData mappings

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#399]
This is a General to-do ticket for fully integrating RHS ALiVE compatible factions into ALiVE's Military Logistics data.

- [x] Map RHS USAF [Integrated? Yes]
- [x] Map RHS AFRF [Integrated? Yes]
- [x] Map RHS GREF [Integrated? Yes]
- [x] Map RHS SAF [Integrated? Yes]
- [ ] Reference ALiVE code and remove/re-write any old references 

RHS USAF static mapping: https://www.dropbox.com/s/he074uwlho0orh3/RHS%20USAF.zip?dl=0

RHS AFRF static mapping: https://www.dropbox.com/s/ogesh3laqgr528t/RHS%20AFRF.zip?dl=0

RHS GREF static mapping: https://www.dropbox.com/s/ufvu2e6isqybkxl/RHS%20GREF.zip?dl=0

RHS SAF static mapping: https://www.dropbox.com/s/oclchdwv71pk0uw/RHS%20SAF.zip?dl=0

**Comment by HeroesandvillainsOS** [comment]
@marceldev89

**Comment by marceldev89** [comment]
> My issue with GREF and SAF is that air transport is spawning but not moving to waypoints from where the heli spawns, and that ground transport I don't think is spawning at all.

**Comment by HeroesandvillainsOS** [comment]
Closing. Everything seems to be working fine and will reopen if anyone spots anything or has any suggestions for asset types.
