### ISSUE TITLE
Change default behaviour on units called in with Logistics

### ISSUE THREAD

**Issue by AshEdwardsDesign** [ALiVEOS/ALiVE.OS#404]
Currently, when calling in units using the Logistics menu, the default behaviour is set to "Reinforce".

For me personally, when I use this module, 99% of the time it is because I want to call in some units or vehicles for my own personal use (i.e. I set them to "Join player squad").

Does it not make sense for "Join player squad" to be the default option instead of "Reinforce"? I'm going to assume that it's the most common use of the module (I might be wrong of course)?

I'm constantly forgetting to change it to "Set player squad" and then wonder why the units I called in are running away from me :P

**Comment by marceldev89** [comment]
We had a little discussion about this last night and a good middle ground would be to remember the last picked option.

**Comment by AshEdwardsDesign** [comment]
That is actually something I hadn't even considered @marceldev89, a very good idea indeed 👍

**Comment by AshEdwardsDesign** [comment]
Another thing to possibly consider would be the ability for us to apply a choice (Join player squad for example) to multiple assets in the payload list at once, or, a global choice that applies across the entire payload.

I might just be making it more convoluted though ;)
