### ISSUE TITLE
Refine IED spawning in insurgency mode

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#405]
IED's will only spawn in clusters without building positions (noted by Tupolov), causing IED's to be pretty sparse on most maps when the IED module is synced to an Asymmetric OPCOM.

**Comment by tupolov** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/f6a61e68e2f76f9201800e39d280b062addee436
