### ISSUE TITLE
C2ISTAR: Delete task breaks autotasking [Workaround]

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#406]
Add option to decline an autotask and generate a new one in the event that a task fails due to shitty AI or is otherwise borked.  Currently if a task fails there's no way out and no further tasks will spawn, which is a bit of a pain.

**Comment by tupolov** [comment]
Just delete the task using the combat tablet???

**Comment by friznit** [comment]
That breaks autotasking

**Comment by friznit** [comment]
Workaround is to disable then re-enable autotasking

**Comment by highhead** [comment]
this should be fixed! please use edit task via commanders tablet and set it to success or fail.
