### ISSUE TITLE
MIL/CIV MP empty ambient vehicles exploding when spawned

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#407]
Ambient vehicles created by military placement are placed too close to building and explode on spawn.

**Comment by HeroesandvillainsOS** [comment]
Civ vehicle spawns should probably be looked at too. At least as far as the current release is concerned. I was walking and also zeusing around objectives on Takistan the other day and ambient civ vehicle spawns were spawning on top of buildings.

**Comment by highhead** [comment]
civ vehicle spawns should be fine now

**Comment by highhead** [comment]
fucking dynamic vehicle placement fuckry

assigned to myself

**Comment by highhead** [comment]
Now works fine for Ambient civilians, and MIL MP. There is no ambient vehicle option in CIV MP.

I am going to close that for now, please feel free to reopen in case of further issues!

**Comment by highhead** [comment]
btw. tested on Altis and Stratis with all settings to high/extreme
