### ISSUE TITLE
CQB Sectors Do Not Save (Repro Included)

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#411]
**ALiVE Version: Pre Release Build 1.3.7.1708111**

**CQB sectors do not save once cleared to the database.** 
With debug and logs running on a server, you can see it register as cleared during the session, however once a session is saved and restarted, data on cleared sectors is not restored. I'm almost entirely sure this issue has been happening for a long while now and is not something that happened in this new pre release build.

I've attached a simple Altis repro mission that only requires CBA and ALiVE. 

- Run this on a server connected to DB
- Kill some bad guys 
- Run a save and you will see it is not persisted.

Download repro mission [here](https://mega.nz/#!NhdgHaoa!9EhYK1EbgwVnlDOI4YwZDKtD31Z_K7UIuAXtQ6dWHCA)

**Comment by Vegas** [comment]
@tupolov @highhead @marceldev89

**Comment by marceldev89** [comment]
Hmm... In my testing everything worked as intended. I'll check it again. :)

**Comment by Vegas** [comment]
@marceldev89 Cool, let me know if you are able to repro or not. Maybe I'm just missing something here...

**Comment by HeroesandvillainsOS** [comment]
There has been additional commits in master regarding CQB saving that are not in RC. This in all likelihood will explain why you're still having issues Vegas. I can get you a newer build if you'd like to confirm it's working as intended now.

**Comment by Vegas** [comment]
@HeroesandvillainsOS Perfect. Please send that my way and I'll give it a test to confirm it is working properly.

**Comment by HeroesandvillainsOS** [comment]
@Vegas Here you go: https://www.dropbox.com/s/feyxiss5lllewi7/%40ALiVE.zip?dl=0

**Comment by Vegas** [comment]
@HeroesandvillainsOS Many thanks. Will test tonight and update the ticket.

**Comment by marceldev89** [comment]
Persistence was completely broken, my bad. :smile:

**Comment by Vegas** [comment]
@marceldev89 Thanks for the update. Is it back in working order now? Will I need to download an update?

**Comment by Vegas** [comment]
Can confirm that it is still broken on my end with the build I am running (packaged by Heroes) ^^

**Comment by marceldev89** [comment]
The build from @HeroesandvillainsOS doesn't contain the fix. You can replace mil_cqb.pbo in Heroes build with https://www.dropbox.com/s/cluoye91b0qq8gb/mil_cqb.pbo?dl=1 which has the fix. :)

**Comment by Vegas** [comment]
@marceldev89 Thanks! o7
