### ISSUE TITLE
Orbat faction issue

### ISSUE THREAD

**Issue by Wirpy** [ALiVEOS/ALiVE.OS#415]
Right so after I created a custom faction in Orbat with normal infantry in groups, I've put them in their own mod folder and then inside the workshop folder in Arma 3.

When I try launch my game it crashes and this comes up: https://gyazo.com/313c55ec6ab061eaebcca8d79fc1d34a

My config is here:
https://pastebin.com/2V7qUWRb

Anyone care explain why this happens, fix it and tell me how I prevent it in the future?

**Comment by marceldev89** [comment]
Seems like something went wrong with the import/inheritance. You should be able to replace
```
class I_Scavcopy1_Rifleman_AK_74_02 : I_Scav__01 {
```
with
```
class I_Scavcopy1_Rifleman_AK_74_02 : I_Scav__01_OCimport_02 {
```
and
```
class I_Scavcopy1_Rifleman_Mosin_01 : I_Scav__01 {
```
with
```
class I_Scavcopy1_Rifleman_Mosin_01 : I_Scav__01_OCimport_02 {
```
and
```
class I_Scavcopy1_Rifleman_AK_74_2_01 : I_Scav__02 {
```
with
```
class I_Scavcopy1_Rifleman_AK_74_2_01 : I_Scav__02_OCimport_02 {
```

As for why this happened, no clue. @SpyderBlack723 probably knows. :smile:

**Comment by Wirpy** [comment]
https://pastebin.com/kyGBdhxA
https://gyazo.com/96ea54cf09aa3f76e130b8018e892986

Did what you said but still same issiue.

**Comment by marceldev89** [comment]
That's the same issue, just find the class it's complaining about and append `_OCimport_02` to the bit after the colon `:`.
