### ISSUE TITLE
Feature Request: Virtual AI Anchor

### ISSUE THREAD

**Issue by scottb613** [ALiVEOS/ALiVE.OS#416]
Feature Request: I use ALiVE a bunch as strictly the OPFOR - amphibious assaults are probably one of my favorite aspects of ArmA and my BLUFOR are usually fixed assets not virtualized... I found that once I sync assets to the Virtual Module they no longer follow my scripts and become completely autonomous under the control of the Military Commander Module... So - if I launch some air assets to soften up the LZ - they arrive at the LZ and all the OPFOR are virtualized so there's nothing there to soften up - they only spawn - unrealistically - when I get close... My fixed air assets just hovering above them as they spawn are sitting ducks... Is there a way to make a second "player presence" active at your target area that would allow virtualized assets to spawn - thereby - having two sides represented in the planned battle location - while I'm still back at base with the troop insertion packages ??? If I'm at the base - there are usually no OPFOR there within the radius so from a performance standpoint I can afford to move the active battle (spawn) area somewhere else on the map and I arrive on scene to whatever mayhem results from the real battle...

Regards,
Scott

**Comment by highhead** [comment]
Yes - there is a workaround -> place an UAV (a small drone suffices) and hide it (hideObject or via editor)

**Comment by highhead** [comment]
Tested myself - that UAV trick only works if you connected to it as a player, which isn't what you need.

**Comment by scottb613** [comment]
Hi...

Thanks so much for your interest and trying ! I think Marcel mentioned it wasn't possible in the BIS thread but that it may have been of interest to include at some point - hence the ticket... Nice thinking outside the box as well !
👍

Regards,
Scott

**Comment by tupolov** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/fbd16062b33676cd38cacae444f8770894d6c97b

**Comment by SpyderBlack723** [comment]
This will be possible with the upcoming changes to ProfileSpawner

**Comment by SpyderBlack723** [comment]
You can add an object to the ALiVE_SpawnSources array to have it spawn nearby profiles
