### ISSUE TITLE
[Feature Request] MACC support in USS Nimitz

### ISSUE THREAD

**Issue by KRDucky** [ALiVEOS/ALiVE.OS#419]
Please include support for the USS Nimitz carrier in ATO / MACC.

**Comment by friznit** [comment]
Nimitz will need catapults to be defined in order to work with MACC, as we just hook into the USS Freedom (BIS) scripts.  The only wriggle room we have is to change spawn height of aircraft.  Beyond that everything relies on Nimitz mod to implement the BIS catapult system.
