### ISSUE TITLE
Add variable to disable VCOM on Combat Support & LOGCOM Crew

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#420]
Add ` _unit setvariable ["VCOM_NOAI",true]` to Combat Support crew (aircfrat and arty) and LOGCOM heli crews by default, so that I don't have to run a script in init.

**Comment by tupolov** [comment]
Arty and Helis only - including LOGCOM?

**Comment by friznit** [comment]
Yes.  Jets are excluded from VCOM by default.

**Comment by tupolov** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/cf6133bf4841f2421b8d3e6ce8f19861710a2327
