### ISSUE TITLE
fnc_AI_distributor undef var error in Custom Obj module

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#429]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [x] Have you attached screenshots of the Parameters set on the offending Module?

### Description
```
["ALIVE AI >
18:59:22   Error Undefined variable in expression: alive_require_initialised
18:59:22 File \x\alive\addons\main\fnc_AI_Distributor.sqf [ALiVE_fnc_AI_Distributor], line 1805
18:59:22 Error in expression < 0;
private _debug = false;

waitUntil {ALiVE_REQUIRE_INITIALISED};
```

### Steps to Reproduce

1. Place playable char + ALiVE (Required) + Virtual AI (both on default settings)
2. Place OPCOM + Mil Placement (Mil Obj); faction NATO / BLU_F
3. Place Mil Placement (Custom Obj)

**Expected behavior:** [What you expected to happen]
N/A

**Actual behavior:** [What actually happened]
Error as above

![image](https://user-images.githubusercontent.com/12999059/30557447-2e7dec22-9ca6-11e7-8b3c-286bd47da5c6.png)

**Comment by marceldev89** [comment]
Fixed in https://github.com/ALiVEOS/ALiVE.OS/commit/567bfffe6414be7d2be56f8cc4601f19142da559

**Comment by Whigital** [comment]
Goddammit, even setup a dev environment and rebuilt the modules to make sure nothing crazy would happen. I guess I need a better debug/test mission with most of the modules placed.

*Here we go again, breaking ALiVE with fluke commits*
