### ISSUE TITLE
Add VBIEDs to the Asymmetric AI Commanders capabilities

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#430]
You can use the ALiVE_fnc_createVBIED to create a VBIED out of a specific vehicle. Alternatively, you can use ALiVE_fnc_placeVBIED to place them across a specific location. Works similar to the IED functions.

**Comment by highhead** [comment]
Will need to create dummy car wrecks or other civ vehicles based on the currently used civilian factions since Amb Civ vehicles a. will be used by civilians themselves and b. it is very possible no cars will be spawned yet when the trigger fires on players entering the triggerzone.
