### ISSUE TITLE
Error "Undefined base class".

### ISSUE THREAD

**Issue by Pansarskytte** [ALiVEOS/ALiVE.OS#431]
Hi, i'm relatively new to modding and such tings.

Anyway, i'm currently working on a faction. Using AliVE ORBAT creator to create it.
 
 ALiVE and CBA are updated.
an error occured. " https://gyazo.com/90eb417268eb9a7b9a368e556c4b5eb8"
another one         "https://gyazo.com/93d4ec84fd4e4f90c24326a9bf3b9b3c"
Feel free to change anything, will be very grateful for the help and some tips (?) !

Link to dropbox: https://www.dropbox.com/sh/g1hu1qva0ljn8a2/AAA_Vp0CgUn5-kphsZ8Gc0T6a?dl=0
For the other error " https://www.dropbox.com/sh/5bzml1pkhvh0sq1/AADaFKh0mXbDV4L2LYPNHEOxa?dl=0"
Many thanks in advance.

Pansarskytte.

**Comment by DavisBrown723** [comment]
These _should_ be working now, please reopen if not. You may need to re-output for start over to make sure the output is up-to-date.
