### ISSUE TITLE
Ability to Disable Installations and Roadblocks unavailable once a mission has been saved at least once.

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#433]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only? Yes
* [ ] Are you running the latest version of ALiVE ? Yes
* [ ] Are you running the latest version of CBA_A3? Yes
* [ ] Have you attached an unbinarized SQM? no
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)? no
* [ ] Have you attached screenshots of the Parameters set on the offending Module? no

### Description
Can disable roadblocks and installations on initial mission start.  Once mission has been server saved and reloaded...option to disable both is unavailable.

### Steps to Reproduce

1. Start an insurgency
2. Go to a roadlbock or installation...disable it.  You'll have option.
3. Server save and exit mission....then reload it
4. Try to disable another installation or roadblock

**Expected behavior:** Me Disable!! (Happy)

**Actual behavior:** Me NO Disable!! (Sad)

**Comment by highhead** [comment]
- Roadbollox fixed
- All other installations can be disabled also on persistent mission (cannot repro, please reopen with a vanilla mission attached)
