### ISSUE TITLE
Verify RHS static data has integrated 0.4.3 additions/removals 

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#438]
This is a reminder ticket for me to go over today’s RHS update and ensure the merged data is complete and functioning as intended

**Comment by HeroesandvillainsOS** [comment]
There were a few vehicles added here and there with 4.3.0. Updated hpp files which should be ready for merge. @marceldev89 can you help me out? Should be as simple as to replace the existing ones with these (SAF didn't add anything useful, so the one in master can stay as is). I made this easy for you this time. :)

https://www.dropbox.com/s/yhzje1z4paqm0gr/RHS_AFRF.hpp?dl=0
https://www.dropbox.com/s/69lfesd5kbqg7qb/RHS_GREF.hpp?dl=0
https://www.dropbox.com/s/yhzje1z4paqm0gr/RHS_AFRF.hpp?dl=0

**Comment by marceldev89** [comment]
Added them with https://github.com/ALiVEOS/ALiVE.OS/commit/fa0c2497acd505ace884c6e80ec61a6a91364506 :-)

**Comment by HeroesandvillainsOS** [comment]
Thanks Marcel!!!
