### ISSUE TITLE
Advanced Markers Autosave Bug Found

### ISSUE THREAD

**Issue by Amahvan** [ALiVEOS/ALiVE.OS#439]
### Prerequisites

* [Y ] Can you reproduce the problem using ALiVE and CBA Only?
* [ Y] Are you running the latest version of ALiVE ?
* [Y ] Are you running the latest version of CBA_A3?
* [ N] Have you attached an unbinarized SQM?
* [ Y] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ N] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[When autosave is turned on (in this case, every 6 hours) Advanced markers will all be erased, and ALiVE confirmation popup & ALiVE map tab access will no longer appear, but the game and player positions will still load persistently.

Disabling autosave in the module within the mission file appears to fix this problem.] 

### Steps to Reproduce

1. [Create a basic Alive Mission file and include autosaving in the Alive Required module] 
2. [Join the game, add some persistent advanced markers, and test to be sure alive persistence is working correctly]
3. [once confirmed alive persistence is working correctly, allow enough time to pass for the autosave feature to occur (in my case it was every 6 hours), then sever save and exit at some point AFTER the autosave.]

**Expected behavior:** [Loading into game should keep persistence as normal. ]

**Actual behavior:** [After autosave, persistence is kept for mission and player states, but all advanced map markers disappear, alive confirmation no longer occurs, alive tab in map no longer appears, and advanced markers can not be placed on the map anymore.]

**Comment by Amahvan** [comment]
RPT file:

https://drive.google.com/file/d/0B0PAS352MV0AUVpFd0hoelhBR2M/view?usp=sharing

**Comment by highhead** [comment]
Thanks for the detailed report! Could you please attach the Server RPT too? Thanks in advance!

**Comment by Amahvan** [comment]
We've since taken down that server and begun a new campaign. Sorry!

**Comment by highhead** [comment]
thanks!

"Create a basic Alive Mission file and include autosaving in the Alive Required module"

As there is no option on the Required module (and also there is none on ALiVE Data module), there are two possibilities now...:

- If you are talking of the ALiVE Player Options module "Auto save interval" option, then you may want to take into account, that this option is only autosaving the players state and nothing else. So if haven't clicked "save server" all the markers placed in that session will be gone. But you can do the following...

- If you are referring to http://alivemod.com/wiki/index.php/Persistence and put `900 call ALiVE_fnc_AutoSave_PNS` in the init of the Required module it won't work - you need to put it in initServer.sqf of your mission folder instead, then everything will be saved. Be aware it causes desync and lag for about 2 seconds everytime its callled!

**Comment by highhead** [comment]
PPS:

I have tested a simple vanilla setup with autosaving set to 60 seconds working fine, and also attached the RPT if you want to compare it to yours if it reoccurs again and the above doesn't help:

[test_player_persistence_1.Stratis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1408622/test_player_persistence_1.Stratis.zip)

[autosave.txt](https://github.com/ALiVEOS/ALiVE.OS/files/1408631/autosave.txt)
