### ISSUE TITLE
ORBAT vehicles under ground and some units invisible

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#442]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only? Yes
* [ ] Are you running the latest version of ALiVE ? Yes
* [ ] Are you running the latest version of CBA_A3? Yes
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Using ORBAT, when copying or importing a faction...some assets are invisible in orbat.  Also, vehicles are stuck in ground.  Lastly, when importing units from previously created faction config, units gear that was changed is removed and units are either fully or partially naked.

**Comment by tupolov** [comment]
I fixed the ground issues with latest commit.

Will look at why faction copy and import isn't working.
