### ISSUE TITLE
AI moving off the map

### ISSUE THREAD

**Issue by TheFetzen** [ALiVEOS/ALiVE.OS#446]
The issue is, that i can see that entities appear outside the actual playable maps.

Happens in all of my missions, sooner or later. Sometimes after 20-30 minutes, sometimes it takes a few hours. There is (in my case) nothing to do in order to reproduce the problem.

I built the attached map fresh, because i wanted to make sure that there are no outdated/copied/corrupted modules in there. So in theory this should be a simple and clean ALiVE setup. Still the problem occurs. This is confusing. Maybe its not a bug and I am doing something wrong on a very basic level? But then what? 

[files.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1404244/files.zip)

**Comment by HeroesandvillainsOS** [comment]
So I ran the mission with some additional debug parameters turned on, and after 3 hours fast forwarding in the editor, although I don't have any profiles off the playable map, it does appear profiles are not moving at all. I think it might be related to this error message, although to be fair, fast forwarding could be breaking some scripts here (although I've personally never had issues ff'ing in the SP editor before);

https://imgur.com/goHpjP7

Using this version of the mission: https://www.dropbox.com/s/ipakh8f4h2g4wym/Altis_offmap.Altis.zip?dl=0

The rpt with OPCOM, Virtual AI and LOGCOM debugged: https://www.dropbox.com/s/eep77hsxp5qvmrt/Altis_offmap.rpt?dl=0

**Comment by TheFetzen** [comment]
So here is another version as requested.
I reduced the size of TOAR and total number of objectives. Tried to see if it occurs on lower unit counts too - which it does, but it took me longer to reproduce the issue..

To reproduce the problem i kill units with arty. The more the better. So it might turn out to be better to increase the unit count again for testing. But it is definitely relating to reinforcements that come into the game later. Some-lots of them spawn in nirvana.

i notice a lot of spam in the logfile. stuff like this:
 0:58:45 Server: Object 2:44688 not found (message Type_93)
 0:58:45 Server: Object 2:44689 not found (message Type_93)
 0:58:45 Server: Object 2:90524 not found (message Type_121)

new mission file, server rpt and screenshots included here

[files.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1464512/files.zip)

**Comment by bradon** [comment]
got the same behaviour after 6 hours runtime. First profile to misbehave for me was 1141st, all reports I've seen have been for 700th profile and up. Don't know if that information is useful yet, but is that the kind of thing you've seen (so, you've never seen it on < 400th profile)?

**Comment by TheFetzen** [comment]
Hi Brandon,

Thanks for looking into this!

No, the info with "doesnt seem to happen on low unit counts" was apparently premature. It just seems to take much longer until the error occurs, when unit counts are low. 

So it probably just relates to the number of units that i kill off with the arty, or the number of reinforcements respectively. I still cant tell if it is an error that affects a certain (small) proportion of all units from beginning, or an error that occurs after a certain duration/number of respawns.

I cant do it reliably, but a few times i got the issue after 20 minutes only. That was with very high number of AI and objectives.

**Comment by highhead** [comment]
Thanks for the report and confirmation! I will try to use your mission and replicate it (somehow).

**Comment by highhead** [comment]
This is a hard nut.

I have been in for 3 hours (i think) now killing OPFOR profiles and watching for issues, still had no "offsite" creation :(

Biggest Issue I am seeing here is that even with your repro - and I am sure there is this issue you mentioned - I need to repro it in a reasonable time. I was hoping triggering enough reinforcements would show the issue, but after 3 hours with constant reinforcements going on I still couldn't see profiles either being created offsite or moving offsite (or despawning to that outside-of-map-pos). Hypotetically, if finally there would be some profile outside created right in that second I am typing this, and after some analysis I could really get a grip on that issues starting point and put in some rogue debug it would still take another 3 hours to validate - and so on.

Could you please turn the Military Logistics debug on to true and rerun your mission again, because from the rpt it looks fine, there is no negative position at all (f.e. [-3000,-17252.7,0] or something like this, the requests all look like this:

AI LOGCOM Side: EAST Type: HELI_INSERT From: [15236,17252.7,0] To: [12675.8,14776.3,0], Dist: 3561.93, Dir: 45.9532, Water: false, Sling: true, Heavy: false

sidenotes:
a. for some reasons the OPFOR reinforcement heli was an ind_f vehicle, which got shot down if profiles were active.

b. I had it running at 2x-4x speed and suddenly some profiles wouldnt move anymore. Turned off speed acc. and teleported near them and back out again and it was fine. So running acc. speed, even at 2x will fuck up scripts badly... sadly...

**Comment by TheFetzen** [comment]
Good news everyone! ... sort of

so I did some more testing with interesting results

- I removed the logistics module and built in a little script that uses JMANs spawn function
- Each side has a spawnmarker on which all the entities spawn. 
- TACOMs are set to 'objectives only', so the map starts empty (apart from a few units that seem to be required to avoid a 'no groups defined for the faction' error)

I did that to have better control over the amount of units also. 
I started with the following values and increased those later to 300 for opfor and 200 for buefor i think. 
		ProfileMaxBLUFOR = 150;
		ProfileMaxOPFOR = 150;
		ProfileMaxINDEPENDENT = 0;
global variables that can be set on the fly if you want to change them, or in the "fez\fez_reinforce.sqf"

So all seems ok, entities spawn, ALiVE takes over command at one point...  but then, after i had the mission run over night, and even though the ALiVE reinforcement system is not in place and units spawn at designated points, i have units off the map.

Naturally that makes me think, that the bug is not in the reinforcement system of ALiVE. The only way the guys can get to where they are is by being told to go there. The attached screenshots show though, that the TOARs are far away.

Debug is now on for all OPCOMs, TACOMs and VAIS

Script produces an RPT output that shows the profile counts and what units spawn where. Not sure if you wanted that on or off. produces long rpt because it shows the current profile counts every 10 seconds, but at least you should be able to see what happens.

noticably i have this all over the rpt, and have no clue what it means:
 0:16:04 OPCOM side: EASTWARNING! Max. duration exceeded!state OPCOM: analysisstate TACOM: waiting for dataduration: 585

FILES below
[files.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1479683/files.zip)

Unfortunately the only recommendation that i have to make testing less of a time consuming thing is just run it on a server and wait it out. At least you dont have to watch it all the time. Found no way to produce the result ad hoc.

regarding @highhead sidenotes:
a) there is some file called staticdata for alive that sets the vehicles to be used for reiforcements. i havent set that for this test mission. always found it weird that this is not setup correctly from the start.

b) happened to @HeroesandvillainsOS too. I test on server though and dont speed things up

**Comment by TheFetzen** [comment]
BTW if it is of any help, i can leave the thing running when i have the situation. Contact me on Discord and i give you access to look at it first hand

**Comment by highhead** [comment]
Thanks! Will look into it some more - but what caught my eyes was your OPCOM has 309 objectives... is this intended? What if you use a reasonable number of about 80-100?

**Comment by DavisBrown723** [comment]
The screenshot indicates that server FPS is likely extremely low and/or something (bug) is causing scripts to stall out. This may cause profile simulation to take an extremely long time and therefore provide a super large multiplier for profile movement that causes them to overshoot a long long ways.
