### ISSUE TITLE
Option to filter ruins in CQB

### ISSUE THREAD

**Issue by Ligthert** [ALiVEOS/ALiVE.OS#448]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Currently CQB and Civ modules place units in the ruins of buildings on maps using CUP or CWA assets. The result of this are units behind walls of non-enterable buildings able to snipe off players who care unable to fight back.

### Steps to Reproduce

1. Take something like NAPF or any CWA/ArmA map and use CQB+Civs modules to populate towns and cities. 
2. Look at a city with the following house-types:
`_buildingBlackList = ["CUP_A1_dum_mesto_in","CUP_A1_Dum_m2","CUP_A1_Dum_mesto2L","CUP_A1_Dum_mesto3","CUP_A1_stanice","CUP_A2_dum_m2","CUP_A2_dum_mesto2l","CUP_A2_dum_mesto3","CUP_A2_housev_1i1_dam","CUP_A2_housev_2l_dam_ruins","Land_cwa_stanice","Land_cwa_dum_m2","Land_cwa_dum_mesto2l","Land_Dum_mesto2l"];` and chances are that you'll see civs in the walls.

**Expected behavior:** [What you expected to happen]
Units not like rats in the walls.

**Actual behavior:** [What actually happened]
Rats in the walls

### Possible solutions

* Tell the auto-indexer to ignore these buildings in the future
* Remove these buildings from the current indices

**Comment by highhead** [comment]
- unticked vanilla (CBA & ALiVE) as its modded.
- For CIV modules the solution is a correct index, that does not use that buildings. There should be a re-indexing request set up for those maps.

Looking into CQB some more

**Comment by HeroesandvillainsOS** [comment]
What maps? Could you list them?

**Comment by highhead** [comment]
CQB module has always benn totally independend from the indexing process and looks up all enterable buildings on the map. As soon as there is at least one buildingposition defined on a building this building could potentially be selected as a CQB location. Strategic buildings (defined in ALiVE_MIL_CQB_STRATEGICHOUSES) will be subtracted if chosen "regular" (civilian) but only those will be left if chosen "strategic" on the CQB module. Strategic buildings can be defined via ALiVE_MIL_CQB_CUSTOM_STRATEGICHOUSES. This makes CQB working on all maps, even those that are not indexed.

Possible solutions:

** If ruins can RELIABLY detected DYNAMICALLY via config
---- Add an optional filter to fnc_getEnterableHouses for ruins
-------- Lookup all usages of fnc_getEnterableHouses and adapt
---- Filter for ruins in fnc_CQB
-------- TBD: add an option to the CQB module (default false to be backwardcompatible)?

** Manual approach
---- Add a Building-Blacklist field on the module (similar to the "units_blacklist")

**Comment by highhead** [comment]
choose :)

**Comment by highhead** [comment]
or better said: 6 million ways to die! Choose one!

**Comment by highhead** [comment]
btw. I have to tell yah, that if those buildings are just wrongly configured (f.e. have a buildingposition defined somewhere inside but are not enterable from outside), only the blacklist-option will help.

**Comment by bradon** [comment]
If we can do it some-what reliably, (avoiding false-positives being more important imo), we could do it dynamically where possible and have a manual blacklist as a fallback
