### ISSUE TITLE
Error when going back into Editor

### ISSUE THREAD

**Issue by alpha117** [ALiVEOS/ALiVE.OS#451]
Happens everytime I go from game back into editor

![image](https://user-images.githubusercontent.com/30005040/32059521-4ec8309c-ba64-11e7-8689-c26ba8f6981b.png)

**Comment by Whigital** [comment]
That is ProjectOPFOR trying to use an ALiVE function. The author has been made aware of the issue. More info here http://alivemod.com/forum/2807-new-error-with-1-68-and-project-opfor/0#p19035
