### ISSUE TITLE
Map Indexer Module

### ISSUE THREAD

**Issue by alpha117** [ALiVEOS/ALiVE.OS#452]
What do I need to do to get this to index a new map?

Thanks

**Comment by Whigital** [comment]
Some useful resources:
http://alivemod.com/wiki/index.php/Map_Indexing
http://alivemod.com/forum/conversations/all?search=indexing

The forums (http://alivemod.com/forum/) is a great source for information regarding most things ALiVE

**Comment by alpha117** [comment]
Thanks,

So module not ready yet.

Any idea of the time frame?

**Comment by Whigital** [comment]
Its ready, working. Follow the guide on the ALiViki ....

**Comment by alpha117** [comment]
Thanks
