### ISSUE TITLE
Error in C2ISTAR Tasks Dialogue

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#457]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM? ALiVE MP Demo Malden
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [x] Have you attached screenshots of the Parameters set on the offending Module?

### Description

```
14:38:48 File \x\alive\addons\mil_C2ISTAR\fnc_C2ISTAR.sqf [ALiVE_fnc_C2ISTAR], line 4070
14:38:49 Error in expression <Text ctrlSetText "";

if (_autoGenerate == "Constant" || _autoGenerate == "None">
14:38:49   Error position: <== "Constant" || _autoGenerate == "None">
14:38:49   Error ==: Type Bool, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
```

### Steps to Reproduce

1. Place C2ISTAR with Auto Tasks enabled
2. Open C2ISTAR menu in game

**Expected behavior:** Menu opens with no errors

**Actual behavior:** Error as above

![image](https://user-images.githubusercontent.com/12999059/32106933-02940dd8-bb25-11e7-9e36-c6649c5d67c2.png)

[Arma3_x64_2017-10-27_13-05-41.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1422212/Arma3_x64_2017-10-27_13-05-41.zip)

**Comment by highhead** [comment]
i cannot replicate that. Mission attached...
[basic_test.Stratis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1422419/basic_test.Stratis.zip)

**Comment by friznit** [comment]
Occurs when you try to disable autogenerated tasks.  Regression caused by the addition of strategic vs tactical mission types.
