### ISSUE TITLE
Error message received on Dev Build - Infinite load screen after errors

### ISSUE THREAD

**Issue by AnAngrySalad1** [ALiVEOS/ALiVE.OS#476]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y (Dev Branch)] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [Y] Have you attached an unbinarized SQM?
* [Y] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)? https://paste.ee/p/IhRIx
* [N (default)] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Loading the mission with a player, Alive Required, Alive CQB and Virtual AI causes an error and then gets stuck in infinite load. All settings are defaulted. 

### Steps to Reproduce

1. Place modules and player character.
2. Run the mission.

**Expected behavior:**

Expected civilian areas all over the map to be populated for CQB (as a test). 

**Actual behavior:**

Infinite load screen after errors:

first error: https://media.discordapp.net/attachments/107240321892511744/385427963354677259/image.png

second error: https://media.discordapp.net/attachments/107240321892511744/385456046531149824/image.png

**Comment by AnAngrySalad1** [comment]
Attached mission.sqm

[mission.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1514729/mission.zip)

Note: This works on stable branch

**Comment by Whigital** [comment]
Cant repro with latest prerel build (`1.5.1.1711281`)

**Comment by highhead** [comment]
Also cannot reproduce with current master branch and latest version of A3 (tac-ops, stable).

**Comment by AnAngrySalad1** [comment]
Guys - we were still getting this with all builds. Its now been resolved, it was something our end. We saved our missions in the config with a 0 or 1 and that is what was causing the issue. This can be closed. 

Thanks for all your help and for looking into it, appreciate it.
