### ISSUE TITLE
Feature Request: Fleeing Civilians In Combat - Civilian Placement Module

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#479]
**Issue With Current System**

Civilians are notorious for not caring that people are dying around them, or homes are being destroyed. It's always been an issue for Arma games where they sort of just "go for long walks" in the middle of firefights, really killing immersion, or at least causing players to question their sanity. Combat is not the time to make friends with the locals, therefore, it should be made clear what is a combat situation and what is a calmer environment.

**Project Proposal**

Find a non-intrusive way to create more realistic ambient civilian life by adding fleeing actions where civilians will look visibly scared, and run for cover. This will ensure they are (mostly) out of the way during firefights, and create an extremely realistic effect for players to experience when fighting first starts in a town or village - because you should see townspeople running all over seeking cover.

**ALiVE Implementation**

Similar workarounds for civilian fleeing actions have been accomplished through adding event handlers "firednear" to spawned civilian units, and causing them to use the "scared" animations while running to pre-defined cover points.

I would suggest ALiVE use roughly the same method.
- Add a "firednear" event handler
- Trigger animation changes (visible fear)
- Run to either civilian house spawnpoint (interior), or nearest CQB location
- Cooldown timer (or similar method) to trigger return to normality

**Features Added To Following Module**
- Civilian Placement Module
- Perhaps a blacklist for specific unit classnames, in case mission creators don't want certain units to flee

**Comment by Vegas** [comment]
Documentation has been released detailing the new Civilian Presence module BIS released with Tact Ops DLC.

This already includes fleeing actions and combat behavior for civilians. How would this work within ALiVE?

https://community.bistudio.com/wiki/Arma_3_Civilian_Presence

**Comment by DavisBrown723** [comment]
@marceldev89 
Wasn't there some investigation done regarding this feature? I think there was a conclusion by changing some AI values/settings but can't remember. I can't find any references to related changes.

**Comment by tupolov** [comment]
We already have civ AI behaviour based on hostility.

I think its a good idea to have Civs flee back to their house of origin if there is any firing going on nearby.

Probably could be implemented via the civ command system. Add a command called flee and trigger if there's combat going on nearby.

**Comment by tupolov** [comment]
Completed in dev
