### ISSUE TITLE
Unable to stop aysmmetic opcoms

### ISSUE THREAD

**Issue by stcrowe** [ALiVEOS/ALiVE.OS#48]
Using the below code to stop all opcoms, you will find that the code never completes if one of the opcoms has controltype asymmetric.

```
 _opcom = _x;
    _stopped = [_opcom,"stop"] call ALiVE_fnc_OPCOM;

     player sideChat format ["%1 stopped %2", _opcomID, _stopped];

} foreach OPCOM_INSTANCES;

player sideChat "All Done";
```

**What is happening**
The code does not complete because any opcom with controltype asymmetric never exits out of its FMS script. 

Calling  [_opcom,"stop"] call ALiVE_fnc_OPCOM, will lead to _exitFMS being set true on both the opcom's TACOM_FSM and OPCOM_FSM.

Then the script waits until each FMS returns nil (lines 1403 and 1404)

```
waituntil {sleep 1; isnil {[_logic, "TACOM_FSM"] call ALiVE_fnc_HashGet}};
waituntil {sleep 1; isnil {[_logic, "OPCOM_FSM"] call ALiVE_fnc_HashGet}};
```

If the opcom's controltype is asymmetric, then TACOM_FMS will return nil right away because asymmetric opcoms don't have a TACOM_FMS, but the OPCOM_FMS, which in this case is  insurgency.fsm has no exit. Therefore, this script will run indefinitely waiting for insurgency.fsm to exit.

**Solutions:**

- If insurgency.fsm is not suppose to have an exit by design, then you guys need to add checks to make sure that the opcom is not of controltype  asymmetric.

- If insurgency.fsm is suppose to have an exit, then you may need to go back and review the FMS script.

Notes:

- This also effects [_opcom,"loadData"] call ALiVE_fnc_OPCOM because it calls [_opcom,"stop"] call ALiVE_fnc_OPCOM

- This also effects [] call ALIVE_fnc_OPCOMLoadData because it calls  [_opcom,"loadData"] call ALiVE_fnc_OPCOM

**Comment by SpyderBlack723** [comment]
@highhead
