### ISSUE TITLE
Error in fnc_profileSimulator

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#481]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ? (DEV)
* [x] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM? Use same mission in other ticket
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module? N/A

### Description

This appears to happen if you spawn something then move away before its had time for everything to fully spawn in.  Easily reproduceable by moving around with Zeus, but also with planes if set to spawn things.

Can be "fixed" by allowing time for stuff to spawn in properly before moving away.

[Arma3_x64_2017-12-02_15-35-44.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1523968/Arma3_x64_2017-12-02_15-35-44.zip)

```
16:46:52 Error in expression <_hashGet;
private _unitAssignments = + (_vehAssignment select 2);

reverse _unit>
16:46:52   Error position: <_vehAssignment select 2);

reverse _unit>
16:46:52   Error reverse: Undefined variable in expression: _vehassignment
16:46:52 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2698
```

### Steps to Reproduce

1. Create simple mission
2. Spawn stuff (aircraft or zeus)
3. Despawn stuff before it's all finished spawning.

**Expected behavior:** [What you expected to happen]
Error handling

**Actual behavior:** [What actually happened]
Errorz

**Comment by highhead** [comment]
I have moved forth and back with zeus on Air Superiority mission (Altis) - which has many vehicles - for like 15 mins. and sadly didnt get the error once. I know the error is there, but I fail to reliably reproduce it in a sensible amount of time.

Could you please upload your mission, maybe I can speed it up with this. Thanks!

**Comment by jacleland** [comment]
This problem also seems to result in a significant server FPS drop over time. Initially, my server runs at a consistent 50 sFPS, but drops to between 2 and 4 sFPS for a couple of seconds. This drop in sim cycles per second coincides with the logging of the aforementioned error:


```
3:04:14 Error in expression <_hashGet;
private _unitAssignments = + (_vehAssignment select 2);

reverse _unit>

 3:04:14   Error position: <_vehAssignment select 2);

reverse _unit>

 3:04:14   Error reverse: Undefined variable in expression: _vehassignment

 3:04:14 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2735

 3:04:27 Error in expression <_hashGet;
private _unitAssignments = + (_vehAssignment select 2);

reverse _unit>

 3:04:27   Error position: <_vehAssignment select 2);

reverse _unit>

 3:04:27   Error reverse: Undefined variable in expression: _vehassignment

 3:04:27 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2735

 3:04:40 Error in expression <_hashGet;
private _unitAssignments = + (_vehAssignment select 2);

reverse _unit>

 3:04:40   Error position: <_vehAssignment select 2);

reverse _unit>

 3:04:40   Error reverse: Undefined variable in expression: _vehassignment

 3:04:40 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2735

 3:04:57 Error in expression <_hashGet;
```

[http://ee.jamescleland.com/fps.jpg](http://ee.jamescleland.com/fps.jpg)

**Comment by SpyderBlack723** [comment]
Fixed pending next release
4d283e5
