### ISSUE TITLE
orbat overwriting output configs

### ISSUE THREAD

**Issue by coaxjack** [ALiVEOS/ALiVE.OS#483]
Version 1.5.1.1711281 (most recent release)

I will set up a new faction in orbat and make sure the items I put on are specified correctly in the Autogen file, and after loading it back up everything has been written over back to defaults. I can't explain why arma is writing over the file while loading it.

**Comment by tupolov** [comment]
Have you included your units in cfgPatches?

**Comment by coaxjack** [comment]
Yeah, use the autogen and CFGpatches files to make a .pbo every time. It still keeps writing over my changes for some reason. The thing is, it retains some items, like uniforms and headwear, but reverts back to default plate carrier and MX rifle.

Would I be better off starting from a single man with no equipment and a uniformClass of U_basicbody, then inheriting the rest of the faction from that?

**Comment by Nemanjic7** [comment]
I need help. 
1. i made group of desired faction
2. export "full faction" to clipboard
3. download fresh GitHub example pbo folder with both CfgPatches and autogen .hpp files. Make .pbo and put fresh maked .pbo to new folder and rename it so the line looks like:   @New_faction/addons/newfaction.pbo . It is on the desktop and then I copy that to main root of course like every other addon and set in launcher everything well, then start arma and on loading get an error:

![capture](https://user-images.githubusercontent.com/36847225/36669505-6c7e76ae-1af5-11e8-8203-a947909dc604.JPG)
So, or I wrongly exporting from ORBAT itself or making some mistake at creating .pbo. 
Please help

**Comment by Nemanjic7** [comment]
Just to add, I already search for this error and found that there is possibility of double defines in Cfg and let say it is in my case, but in that case, I do something wrong when making .pbo or naming .pbo or exporting from ORBAT.

**Comment by Nemanjic7** [comment]
sorry guys. I resolved.Will post here if someone needs help too. Found this clear answer from guy name spyderBlack (moderator or some sort of god for Alive mode) on BiForums 
https://forums.bohemia.net/forums/topic/202000-alive-how-do-i-export-a-faction-with-orbat/?tab=comments#comment-3148745
>>>Select the faction in the ORBAT Creator and click (on the top menubar) Export >> Full Faction
Post the data that was copied to your clipboard to the autogen.hpp file
Then click Export >> CfgPatches
Post the data that was copied to your clipboad to the CfgPatches.hpp file
The wiki will explain where to obtain the mod template file and how to construct the mod from there.<<<

**Comment by DavisBrown723** [comment]
Why be a king, when you can be a god

Please reopen if this issue if you're still having issues.
