### ISSUE TITLE
Feature Request: Drop Off option for Transport Helicopters

### ISSUE THREAD

**Issue by dev614** [ALiVEOS/ALiVE.OS#486]
It would be great to have an option for the transport vehicles to "drop off", meaning go to the location, perform a typical transport unload, then return to base autonomously. This is all possible at the time through the land/RTB features, but to all be integrated into one command would be much easier and convenient.

**Comment by DavisBrown723** [comment]
Closing this due to length of uptime and the recent addition which allows players to talk to the pilot while outside of the transport vehicle which should make this process a bit easier.
