### ISSUE TITLE
Mods with type-specific factions are difficult for the user

### ISSUE THREAD

**Issue by bradon** [ALiVEOS/ALiVE.OS#496]
In IFA, LIB_PANZERWAFFE is a faction that only has armor groups.

To place combined arms, the user needs to add multiple placement modules, specifying to spawn only that group type from that faction (using the group overrides in the placement module)

A better solution would be to allow multiple factions specified in a placement module

**Comment by Will-Nichols** [comment]
You can add in specific factions in the array portion where you don't have them defined via the drop down menu in the module. Simply write in the classname of the faction in the text field separated by comma's. That takes care of the need for multiple modules unless you want different sizes of units spawning in those areas. At which time you will need to have different modules for the different faction specific groups.
