### ISSUE TITLE
Redundant specifying of factions

### ISSUE THREAD

**Issue by bradon** [ALiVEOS/ALiVE.OS#497]
Users need to specify faction in both the mil commander module and placement modules. 

Can the faction's be determined from the placement module for the commander, so it's not necessary to specify them twice?

**Comment by DavisBrown723** [comment]
This would break backwards compatibility and generally reduce the number of tools you have at your disposal when mission making (there are situations where you might not want every faction being placed to be controlled by OPCOM).
