### ISSUE TITLE
Transport infantry across water

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#5]
Problem: currently profiles will move across water.  Spawned infantry units will attempt to swim.  We need a lightweight method to detect water crossings and prevent infantry crossing unless they have suitable transport.

(This is a different issue to profiles spawning in the water, which was fixed - profiles that are on the water will spawn on nearest landmass.  This problem is related to units that are already spawned by have a move waypoint that crosses water)

If a transport heli or boat is available, either from a cfgGroup spawned by Mil Placement or manually added and Profiled, the inf group will request transport, get picked up and dropped off at nearest land in direction of travel towards objective.

**Comment by SpyderBlack723** [comment]
Partially addressed with (in dev) feature that enables infantry profiles to cross water with boats (integrated into sys_profile). OPCOM now also attempts to prevent vehicle profiles from being assigned to objectives across water.

**Comment by tupolov** [comment]
#c9eccdb365e28663b4622fdc61feb4f5f8523830
