### ISSUE TITLE
Request for Deniland map for alive

### ISSUE THREAD

**Issue by cbff33** [ALiVEOS/ALiVE.OS#501]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [ ] Are you running the latest version of ALiVE ?
* [ ] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by bradon** [comment]
see #9  for indexing requests
Indexers: Note that deniland has enough objects to trigger the too long output cutoff bug when indexing
PR #500 is an attempt at fixing it (still needs testing)
If i will try index it again myself today or tomorrow
