### ISSUE TITLE
combatSupportAdd - Arty Commented Out

### ISSUE THREAD

**Issue by firefly2442** [ALiVEOS/ALiVE.OS#502]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[combatSupportAdd](https://github.com/ALiVEOS/ALiVE.OS/blob/c3f7b268c90403a57b4887093af6455fe49728e1/addons/sup_combatsupport/CfgFunctions.hpp#L39) references `alive\addons\sup_combatsupport\scripts\NEO_radio\functions\misc\fn_supportAdd.sqf`.  However, [in the file](https://github.com/ALiVEOS/ALiVE.OS/blob/c3f7b268c90403a57b4887093af6455fe49728e1/addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_supportAdd.sqf#L179) the entire "ARTY" section is commented out.  Is there something special about ARTY that prevents [post-init setup](http://alivemod.com/wiki/index.php/Script_Snippets#Adding_CAS_units_post-init)?

Thanks

### Steps to Reproduce

N/A

**Comment by firefly2442** [comment]
Possibly related: https://github.com/ALiVEOS/ALiVE.OS/pull/42

**Comment by Whigital** [comment]
All the CS stuff is initialized from the CS module via `ALiVE_fnc_combatSupport`: (https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/sup_combatsupport/fnc_combatSupport.sqf#L272-L318)

Arty specifically at: https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/sup_combatsupport/fnc_combatSupport.sqf#L570-L733

Just pop a sup_combatsupport and a sup_artillery module down, set the options and sync them, thats it.

**Comment by firefly2442** [comment]
Thank you.
