### ISSUE TITLE
Armored units wont move after coming out of virtual space

### ISSUE THREAD

**Issue by Djevzi** [ALiVEOS/ALiVE.OS#507]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

All module parameters were tested on default settings.

RPT: https://www.dropbox.com/s/u83xr8bg8rhbixi/Arma3_x64_2018-03-31_23-06-37.rpt?dl=0
Mission: https://www.dropbox.com/s/y8a5mqffcckp9zs/Mission.zip?dl=0

### Description

Tanks, APC's or any other kind of armored units (except cars) will stop moving after spawning in after being in virtual space regardless of having an active waypoint. This only happens in specific parts of the map but I feel like there are more parts where it happens than those where it doesn't. I only tested it on Altis so far.

### Steps to Reproduce

1. Load up the mission included and play.
2. Order any type of armored vehicles through player combat logistics near the player character.
3. Wait for the units to get into spawn range and observe as they stop moving towards the waypoint.

**Expected behavior:** The armored units spawn in and drive to their waypoint.

**Actual behavior:** The armored units stop moving when they come into spawn range from virtual space. This is not limited to player combat logistics but simply any waypoint issued armored units on the map.

**Comment by DavisBrown723** [comment]
This is caused by issues with spawning where the vehicle is left uncrewed. If any of these issues remained this issue can be re-titled and re-opened.
