### ISSUE TITLE
Hostage Rescue Join Team Error

### ISSUE THREAD

**Issue by da59fifty** [ALiVEOS/ALiVE.OS#508]
### Prerequisites

* [Y ] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [Y] Have you attached an unbinarized SQM?
* [Y] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N] Have you attached screenshots of the Parameters set on the offending Module?

### Description

When I generated a hostage rescue mission and hold down space bar to save the hostage I get an error preventing me from completing the task. The error occurs when the hostage joins my team. There was another issue posted with a similar error that seemed to be fixed but I am unable to get it working with the lastest version of ALiVE and CBA_A3.
https://github.com/ALiVEOS/ALiVE.OS/pull/503

 `0:57:17 Error in expression <eep 1;

[_hostage] joinSilent _saver;
(group _saver) selectLeader _saver;

_tas>
 0:57:17   Error position: <group _saver) selectLeader _saver;

_tas>
 0:57:17   Error group: Type Group, expected Object
 0:57:17 File \x\alive\addons\mil_C2ISTAR\tasks\fnc_taskRescue.sqf [ALiVE_fnc_taskRescue], line 2297`

### Steps to Reproduce

1. Create a misssion with two AI Commander's linked
2. Link two Mil. Placement modules
3. Link one Mil. Placement to one AI Commander and do the same to the other module
4. Place the C2ISTAR Module and generate a hostage rescue mission
5. Select short distance, OPFOR, side, yes.
6. Attempt to rescue hostage

**Expected behavior:** [I expect to have the hostage join my team and trigger the hostage pickup task complete and activate the drop off task.]

**Actual behavior:** [The hostage joins my team and an error pops up preventing the task from being completed and the mission is prevented from finishing.]

[Arma3_x64_2018-04-03_00-35-08.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1870284/Arma3_x64_2018-04-03_00-35-08.zip)
[Test%20Mission%20for%20Alive.Tanoa.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1870285/Test.20Mission.20for.20Alive.Tanoa.zip)

**Comment by shukari** [comment]
#503 fixed this issue

**Comment by da59fifty** [comment]
@shukari I just re-download the alive mod off of the alive website and I got the same error.
![20180409225706_1](https://user-images.githubusercontent.com/31520636/38533988-b26a92e0-3c49-11e8-85dd-8c63263fc0d0.jpg)

**Comment by shukari** [comment]
I fixed this issue and it will be fixed in the next release.
This change is not published atm.

**Comment by da59fifty** [comment]
That makes sense. When does an update normally get released?

**Comment by shukari** [comment]
Pre-Release is out but public release need some time... you can download the pre-release ;D
