### ISSUE TITLE
Warroom doesnt show mission replay

### ISSUE THREAD

**Issue by Ghost7K** [ALiVEOS/ALiVE.OS#509]
### Prerequisites

* [yes] Can you reproduce the problem using ALiVE and CBA Only?
* [ yes] Are you running the latest version of ALiVE ?
* [ yes] Are you running the latest version of CBA_A3?
* [no ] Have you attached an unbinarized SQM?
* [no] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [no ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Hey guys,

i have a problem with the warroom Mission replay. It seems to be empty, means i cant see any activity on it exclude the time and the message box (for things like player connected) in the right corner in the top. Used Browser: Google Chrome

### Steps to Reproduce

1. Open the Warroom
2. Choose mission for replay
3. View the non existing mission replay

**Expected behavior:** [What you expected to happen]
See the movement of Players, kills and other interactions
**Actual behavior:** [What actually happened]
Only showing the map, the hint player connected and the timeline
![image](https://user-images.githubusercontent.com/38039879/38249518-352d4e00-374c-11e8-87e0-36933a65cc84.png)

**Comment by tupolov** [comment]
You got a link?

**Comment by Ghost7K** [comment]
http://alivemod.com/war-room/showoperation?name=W%C3%BCstenvogel%20%7C%20ALiVE&map=Altis&clan=7K

**Comment by tupolov** [comment]
Thanks, will look into it!

**Comment by Will-Nichols** [comment]
Getting nothing for our units replay now of the [current mission.](http://alivemod.com/war-room/showoperation?name=Tanoa%20Takedown&map=Tanoa&clan=TFRed#)

**Comment by marceldev89** [comment]
@Will-Nichols it seems like something changed on our server that caused the map images to be behind a login. Not sure what's up but I've passed it along to the people that can do something about it. ^^

**Comment by Aarnoman** [comment]
Any update at this stage?

**Comment by tupolov** [comment]
ok discovered that our hosting company locked down public access to the webserver serving the map images :( trying to fix.
