### ISSUE TITLE
CS Slingloading bugs

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#51]
~~1.  Selecting Slingloading = Yes in a CS transport heli will spawn a load of boxes with gear around the HLS.  This should be optional and the boxes should be empty, otherwise it's going to mess with mission making.~~

~~2.  With the option set to "NO", Sling loading is still an option in the CS tablet for transport aircraft, however they will go through the motions of picking up an object but won't deploy slings, getting stuck in an endless cycle.~~

~~3.  Set to Yes, heli successfully picks up a light vehicle but then becomes unresponsive.  It replies to further requests but does not move (in this case slowly flying backwards until it crashes)~~ Narrowed it down to a specific vehicle that it was having issues with (prowler).  Works fine with boxes and other light vehs.

**Comment by friznit** [comment]
https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/?p=3063695

Manually placed transport helis throw a sling load error

**Comment by SpyderBlack723** [comment]
https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/?p=3063695

Manually placed transport helis throw a sling load error

Fixed in a1b2d367b065f127efc97012da895bb5494f2b67

**Comment by tupolov** [comment]
Fixed, please test and close.

**Comment by friznit** [comment]
1.  Place a crewed transport heli with init line `this setvariable ["CS_TYPE","transport"];`  returns error:

```
23:55:31 Error in expression < else {
_slingloading = false;
};
if (_cont > 0) then {
private ["_containers">
23:55:31   Error position: <_cont > 0) then {
private ["_containers">
23:55:31   Error Undefined variable in expression: _cont
23:55:31 File x\alive\addons\sup_combatsupport\fnc_combatSupport.sqf, line 363
```

Comment:  need to add the setvar to disable slingloading to the wiki.  What is it?

2.  If the a heli fails to grab an object when ordered, it will return to hover but become unresponsive to further hook/unhook commands.  It will respond to move commands though very slowly.

Other than that, transport modules are working as intended.

**Comment by SpyderBlack723** [comment]
> Comment: need to add the setvar to disable slingloading to the wiki. What is it?

"transport_slingloading"

**Comment by tupolov** [comment]
[http://i.imgur.com/2oGXNwK.jpg](url)
