### ISSUE TITLE
Vehicle damage not persisting

### ISSUE THREAD

**Issue by eric963** [ALiVEOS/ALiVE.OS#510]
### Prerequisites

* [Y ] Can you reproduce the problem using ALiVE and CBA Only?
* [ Y] Are you running the latest version of ALiVE ?
* [ Y] Are you running the latest version of CBA_A3?
* [Y ] Have you attached an unbinarized SQM?
* [ Y] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N ] Have you attached screenshots of the Parameters set on the offending Module?

### Description
After doing a server save and exit, the damaged vehicle is back to 100% on the next mission load.

### Steps to Reproduce
Get in the vehicle and move to a new location.  Exit vehicle and shoot out all 4 tires.  Get back in vehicle and wait a bit then exit the vehicle.  Do a sever save and exit. Restart the mission and the vehicle appears at it last location but is at 100% (No damage).

**Expected behavior:** [What you expected to happen]
On the next mission load the vehicle should be in its damaged state.

**Actual behavior:** [What actually happened]
On the next mission load the vehicle is at 100% when it should be damaged.

[Arma3_x64_2018-04-05_20-30-14.txt](https://github.com/ALiVEOS/ALiVE.OS/files/1882315/Arma3_x64_2018-04-05_20-30-14.txt)
[Vehicle_Damage_Test.Stratis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1882316/Vehicle_Damage_Test.Stratis.zip)

**Comment by DavisBrown723** [comment]
Is this still happening? Haven't had any other reports of persistence failing.

**Comment by eric963** [comment]
I’ll re-test it tonight and post results.

**Comment by eric963** [comment]
1.7.1.1807171
Replaced all modules and ran the exact same test as above.

Vehicle damage still not persisting.

[Arma3_x64_2018-07-25_17-19-42.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2229639/Arma3_x64_2018-07-25_17-19-42.txt)

[Vehicle_Damage_Test_2.Stratis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/2229641/Vehicle_Damage_Test_2.Stratis.zip)

I shot all 4 tires of the MRAP got inside it and Wheels were showing RED.  Got out of the vehicle and did the save.  Restarted mission everything was where I moved the MRAP to but it had no wheel damage.

I did see this in the rpt. file thou, this is from where I did the save.  I'm pretty sure that second to the last entry should be for vehicle damage and its showing  0 which should probably be a number greater than zero.


17:29:16  ------------------ Inspecting Hash -------------------- 
17:29:16    k: B_MRAP_01_F_18925842
17:29:16      k [0]: ASL_ID v: B_MRAP_01_F_18925842
17:29:16      k [1]: ASL_TY v: B_MRAP_01_F
17:29:16      k [2]: ASL_PO v: [1766.67,5878.32,-0.328609]
17:29:16      k [3]: ASL_VD v: [[-0.970035,0.242966,-6.37252e-005],[2.76493e-005,0.000372669,1]]
17:29:16      k [4]: ASL_CA v: [[],[],[],[[["arifle_MX_F"],[3]],[["30Rnd_65x39_caseless_mag","100Rnd_65x39_caseless_mag","HandGrenade","1Rnd_HE_Grenade_shell","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","16Rnd_9x21_Mag","SmokeShell","SmokeShellGreen","SmokeShellOrange","SmokeShellBlue","NLAW_F"],[16,6,1,10,4,4,4,4,12,4,4,4,4,2]],[["FirstAidKit","H_HelmetB"],[10,1]]],[]]
17:29:16      k [5]: ASL_FU v: 0.999398
17:29:16      k [6]: ASL_DA v: 0
17:29:16  ------------------ Inspection Complete -------------------- 



and here is the section after restarting the mission.


17:29:38 ALiVE SYS LOGISTICS persistence load data started
17:29:38 LOAD SYS LOGISTICS, CREATE DATA HANDLER!
17:29:38  ------------------ Inspecting Hash -------------------- 
17:29:38    k: B_MRAP_01_F_18925842
17:29:38      k [0]: ALiVE_SYS_LOGISTICS_ID v: B_MRAP_01_F_18925842
17:29:38      k [1]: ALiVE_SYS_LOGISTICS_TYPE v: B_MRAP_01_F
17:29:38      k [2]: ALiVE_SYS_LOGISTICS_POSITION v: [1766.67,5878.32,-0.328609]
17:29:38      k [3]: ALiVE_SYS_LOGISTICS_VECDIRANDUP v: [[-0.970035,0.242966,-6.37252e-005],[2.76493e-005,0.000372669,1]]
17:29:38      k [4]: ALiVE_SYS_LOGISTICS_CARGO v: [[],[],[],[[["arifle_MX_F"],[3]],[["30Rnd_65x39_caseless_mag","100Rnd_65x39_caseless_mag","HandGrenade","1Rnd_HE_Grenade_shell","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","16Rnd_9x21_Mag","SmokeShell","SmokeShellGreen","SmokeShellOrange","SmokeShellBlue","NLAW_F"],[16,6,1,10,4,4,4,4,12,4,4,4,4,2]],[["FirstAidKit","H_HelmetB"],[10,1]]],[]]
17:29:38      k [5]: ALiVE_SYS_LOGISTICS_FUEL v: 0.999398
17:29:38      k [6]: ALiVE_SYS_LOGISTICS_DAMAGE v: 0
17:29:38  ------------------ Inspection Complete -------------------- 
17:29:38  ------------------ Inspecting Hash -------------------- 
17:29:38    k: B_MRAP_01_F_18925842
17:29:38      k [0]: ALiVE_SYS_LOGISTICS_ID v: B_MRAP_01_F_18925842
17:29:38      k [1]: ALiVE_SYS_LOGISTICS_TYPE v: B_MRAP_01_F
17:29:38      k [2]: ALiVE_SYS_LOGISTICS_POSITION v: [1766.67,5878.32,-0.328609]
17:29:38      k [3]: ALiVE_SYS_LOGISTICS_VECDIRANDUP v: [[-0.970035,0.242966,-6.37252e-005],[2.76493e-005,0.000372669,1]]
17:29:38      k [4]: ALiVE_SYS_LOGISTICS_CARGO v: [[],[],[],[[["arifle_MX_F"],[3]],[["30Rnd_65x39_caseless_mag","100Rnd_65x39_caseless_mag","HandGrenade","1Rnd_HE_Grenade_shell","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","16Rnd_9x21_Mag","SmokeShell","SmokeShellGreen","SmokeShellOrange","SmokeShellBlue","NLAW_F"],[16,6,1,10,4,4,4,4,12,4,4,4,4,2]],[["FirstAidKit","H_HelmetB"],[10,1]]],[]]
17:29:38      k [5]: ALiVE_SYS_LOGISTICS_FUEL v: 0.999398
17:29:38      k [6]: ALiVE_SYS_LOGISTICS_DAMAGE v: 0
17:29:38  ------------------ Inspection Complete --------------------

**Comment by DavisBrown723** [comment]
🤔

**Comment by the-star** [comment]
Think the issue lies here:
https://github.com/ALiVEOS/ALiVE.OS/blob/52405e751e9a900ac593a93fbd7ff162b23cfa13/addons/sys_logistics/fnc_getObjectDamage.sqf#L32

[damage](https://community.bistudio.com/wiki/damage) returns the damage state of the whole vehicle rather than each individual hitpoint. Shooting off tires does not affect the damage state in this instance. Note, this issue can be replicated this without ALiVE as it's a vanilla issue.

One potential fix is to to use something like [getAllHitPointsDamage](https://community.bistudio.com/wiki/getAllHitPointsDamage). I am not entirely sure how this command plays with objects other than vehicles so I'll have to look into it more.

**Comment by DavisBrown723** [comment]
@tupolov

**Comment by trapw0w** [comment]
This is good to close. Fixed in https://github.com/ALiVEOS/ALiVE.OS/pull/703
