### ISSUE TITLE
Persistence not working (Local or Cloud)

### ISSUE THREAD

**Issue by Damsous** [ALiVEOS/ALiVE.OS#511]
### Prerequisites

* [Yes ] Can you reproduce the problem using ALiVE and CBA Only?
* [Yes ] Are you running the latest version of ALiVE ?
* [Yes ] Are you running the latest version of CBA_A3?
* [No ] Have you attached an unbinarized SQM?
* [ Yes] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [No ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

The persistence was working fine with the previous Alive version (ALiVE_1.5.3.1801061).
Now its not possible to save progression, when i click on server save and exit the save screen pop-up but nothing happen (profile, location....) and the game restart.
I can Load a mission saved with the previous Alive version.
I try to start a fresh one with Alive and CBA, same error no save. (save work with previous alive version).

The player stat and action are recorded on the war room (see Altis_War) 

### Steps to Reproduce

1. [Start the mission]
2. [Place the FOB Crate somewhere, move the crate with R3F log and drop it, and kill something]
3. [Server save and exit]

**Expected behavior:** [Saved game]

**Actual behavior:** [Game not Save]

You can find client and server RPT, Plugin and mission file here : 
https://drive.google.com/open?id=1GDAdfo_ZMvBWUThLwgiU7snFu0YJsSv9

**Comment by tupolov** [comment]
Hey Damsous.

Thanks for the report!

I just tested saving and loading in the cloud with our Quick Start mission on Stratis. Everything worked fine. Logistics can be seen saving here and loading from my RPT. I couldn't open your RAR for some reason.

Saving
```
2018/05/02, 13:31:53 ALiVE OPCOM - SAVE DATA Please wait at least 5 minutes before saving again!
2018/05/02, 13:31:53 ALiVE Exit - Server Save CQB State
2018/05/02, 13:31:54 ALiVE Exit - Server Save Logistics State
2018/05/02, 13:31:55 ALiVE Exit - Server Save Markers State
2018/05/02, 13:31:55 ALiVE SAVE SYS MARKER DATA HAS NO ENTRIES: ["#CBA_HASH#",[],[],any]! DO NOT SAVE...
2018/05/02, 13:31:55 ALiVE Exit - Server Save SPOTREP State
2018/05/02, 13:31:55 ALiVE Exit - Server Save SITREP State
2018/05/02, 13:31:55 ALiVE Exit - Server Save PATROLREP State
2018/05/02, 13:31:55 ALiVE Exit - Server Save ML State
2018/05/02, 13:31:56 ALiVE Exit - Server Save Task State
```

Loading
```
'] CMD: SendJSON ['GET','sys_logistics/NSG_basic_1','']
2018/05/02, 13:38:30  ------------------ Inspecting Hash -------------------- 
2018/05/02, 13:38:30    k: B_Heli_Light_01_F_29971867
2018/05/02, 13:38:30      k [0]: ALiVE_SYS_LOGISTICS_ID v: B_Heli_Light_01_F_29971867
2018/05/02, 13:38:30      k [1]: ALiVE_SYS_LOGISTICS_TYPE v: B_Heli_Light_01_F
2018/05/02, 13:38:30      k [2]: ALiVE_SYS_LOGISTICS_POSITION v: [2997.2,1867.49,-0.37883]
2018/05/02, 13:38:30      k [3]: ALiVE_SYS_LOGISTICS_VECDIRANDUP v: [[-0.572681,0.81976,-0.0055177],[-0.00248975,0.00499144,0.999984]]
2018/05/02, 13:38:30      k [4]: ALiVE_SYS_LOGISTICS_CARGO v: [[],[],[],[[[],[]],[[],[]],[[],[]]],[]]
2018/05/02, 13:38:30      k [5]: ALiVE_SYS_LOGISTICS_FUEL v: 1
2018/05/02, 13:38:30      k [6]: ALiVE_SYS_LOGISTICS_DAMAGE v: 1
2018/05/02, 13:38:30      k [7]: _rev v: 1-1e52ba08228309e04a4984d8265666d8
2018/05/02, 13:38:30  ------------------ Inspection Complete -------------------- 
2018/05/02, 13:38:30 ALiVE SYS LOGISTICS - Deleting object 6b6f8080# 163969: heli_light_01_f.p3d which has been destroyed in a previous session!
2018/05/02, 13:38:30 ALiVE [m_6|45] Module ALiVE_SYS_LOGISTICS INIT COMPLETE TIME:  1.13196
```

I also tested moving a crate...

```'] CMD: SendJSON ['GET','sys_logistics/NSG_basic_1','']
2018/05/02, 13:50:02  ------------------ Inspecting Hash -------------------- 
2018/05/02, 13:50:02    k: B_Heli_Light_01_F_29971867
2018/05/02, 13:50:02      k [0]: ALiVE_SYS_LOGISTICS_ID v: B_Heli_Light_01_F_29971867
2018/05/02, 13:50:02      k [1]: ALiVE_SYS_LOGISTICS_TYPE v: B_Heli_Light_01_F
2018/05/02, 13:50:02      k [2]: ALiVE_SYS_LOGISTICS_POSITION v: [2997.2,1867.49,-0.37883]
2018/05/02, 13:50:02      k [3]: ALiVE_SYS_LOGISTICS_VECDIRANDUP v: [[-0.572681,0.81976,-0.0055177],[-0.00248975,0.00499144,0.999984]]
2018/05/02, 13:50:02      k [4]: ALiVE_SYS_LOGISTICS_CARGO v: [[],[],[],[[[],[]],[[],[]],[[],[]]],[]]
2018/05/02, 13:50:02      k [5]: ALiVE_SYS_LOGISTICS_FUEL v: 1
2018/05/02, 13:50:02      k [6]: ALiVE_SYS_LOGISTICS_DAMAGE v: 1
2018/05/02, 13:50:02      k [7]: _rev v: 2-04a9cdb70ade4aa83b9ad00d2d99d58b
2018/05/02, 13:50:02    k: Box_NATO_WpsSpecial_F_30001874
2018/05/02, 13:50:02      k [0]: ALiVE_SYS_LOGISTICS_ID v: Box_NATO_WpsSpecial_F_30001874
2018/05/02, 13:50:02      k [1]: ALiVE_SYS_LOGISTICS_TYPE v: Box_NATO_WpsSpecial_F
2018/05/02, 13:50:02      k [2]: ALiVE_SYS_LOGISTICS_POSITION v: [2984.66,1844.7,0.0367584]
2018/05/02, 13:50:02      k [3]: ALiVE_SYS_LOGISTICS_VECDIRANDUP v: [[-0.660726,-0.748686,0.0539446],[0.0711707,0.00905755,0.997423]]
2018/05/02, 13:50:02      k [4]: ALiVE_SYS_LOGISTICS_CARGO v: [[],[],[],[[["arifle_SDAR_F","arifle_MXM_F","srifle_LRR_F","srifle_DMR_03_F","srifle_DMR_02_F","MMG_02_black_F"],[1,1,1,1,1,1]],[["30Rnd_65x39_caseless_mag","7Rnd_408_Mag","20Rnd_762x51_Mag","20Rnd_556x45_UW_mag","30Rnd_556x45_Stanag_red","10Rnd_338_Mag","130Rnd_338_Mag"],[6,8,6,3,3,8,3]],[["optic_Aco","optic_Aco_smg","optic_Hamr","optic_SOS","optic_Holosight","optic_NVS","optic_tws","optic_tws_mg","optic_MRD","optic_DMS","optic_LRPS","optic_AMS","optic_AMS_khk","optic_AMS_snd"],[1,1,1,1,1,1,1,1,1,1,1,1,1,1]]],[]]
2018/05/02, 13:50:02      k [5]: ALiVE_SYS_LOGISTICS_FUEL v: 1
2018/05/02, 13:50:02      k [6]: ALiVE_SYS_LOGISTICS_DAMAGE v: 0
2018/05/02, 13:50:02      k [7]: _rev v: 1-9b622964ea8d5d28f1a89e9eb0d81b60
2018/05/02, 13:50:02  ------------------ Inspection Complete -------------------- 
2018/05/02, 13:50:02 ALiVE SYS LOGISTICS - Deleting object 6b264080# 163969: heli_light_01_f.p3d which has been destroyed in a previous session!
```
You can see the crate is loaded back in a new position.

**Comment by bradon** [comment]
Does it save correctly on the server, and load, but just doesn't finish showing things in the tablet, and doesn't exit the mission clientside?

**Comment by Damsous** [comment]
@bradon Yeah that doesn't finish showing things in the tablet, when i do a save and exit 5 second later im back in the lobby, mission restarted but progression is not save, i don't understand cause that work good with the previous version.

@tupolov Maybe there an issue with the R3F logistic script ? (i use the old way LOGIC_ALIVE in require alive module) + this line in relacher.sqf
[LOGIC_ALIVE,"updateObject",[R3F_LOG_joueur_deplace_objet]] call ALIVE_fnc_logistics; 

I put other link not in winrar 
Server RPT : https://drive.google.com/open?id=1BMyIjgNPqkHapnMNrM7QVoojFMfpg_MS
Client RPT : https://drive.google.com/open?id=1mmb9I_8ChX71dPXH2GmubMafxGdXECQx
Alive Plugin : https://drive.google.com/open?id=1PniBI2j5zYcCGUvDWweZ0Jdvv1dCCMJe
MP Mission : https://drive.google.com/open?id=10OHTGz6Pc66mCFv3EIWYPyGP-Lgwqkxv

I will try to start a fresh mission without script

**Comment by marceldev89** [comment]
We probably rely on at least 1 person being on the server at start. Can't think of any other reason that would cause `-autoInit` to break persistence.

**Comment by DavisBrown723** [comment]
> [LOGIC_ALIVE,"updateObject",[R3F_LOG_joueur_deplace_objet]] call ALIVE_fnc_logistics;
This doesn't work by the way, you need to use ALiVE_SYS_LOGISTICS instead of LOGIC_ALIVE. You can also go without naming the module in the editor. Closing this because -autoinit is known to break ALiVE.
