### ISSUE TITLE
Air Commander doesn't recognize helicopters

### ISSUE THREAD

**Issue by VulpesVelox1758** [ALiVEOS/ALiVE.OS#515]
********WIP***********

### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [N] Have you attached an unbinarized SQM?
* [Y] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [Y] Have you attached screenshots of the Parameters set on the offending Module?

**[Included RTP-File](https://drive.google.com/open?id=1nZsEfCrzAXWOJntHtO_D9Xw1fBU5Iu__)**
**[Included Mission PBO](https://drive.google.com/open?id=1ItQIUOOwgjPImHM5nqrAHp2dvIczrSAt)**

### Description

Spawned or editor placed helicopter do not take off and idle on the spawn position. Planes work correctly, as you can see in my included screenshots. The Air commander (config: ) 

![unbenannt10](https://user-images.githubusercontent.com/39021941/39776656-c77b6190-5301-11e8-920b-99a673f65f28.png)

is initialized successfully and Air units are correctly virtualized. (proof for virtualization:) 

![heli virtualization](https://user-images.githubusercontent.com/39021941/39776501-5b8bc650-5301-11e8-99f8-adb426b20caf.png)

After launch errors start to show up, most of them referencing aircraft and most of them recurring.

![error1](https://user-images.githubusercontent.com/39021941/39776296-b7c83b3e-5300-11e8-9611-47ff07d72129.png)
 this one only shows up on mission start

![error2](https://user-images.githubusercontent.com/39021941/39776252-898d0178-5300-11e8-898f-bdda27bae2e3.png)

![error3](https://user-images.githubusercontent.com/39021941/39776373-f4cc20ae-5300-11e8-8c5e-bf7f5194eaf5.png)

![error4](https://user-images.githubusercontent.com/39021941/39776389-fdf3f4f4-5300-11e8-9bdb-55dc6df96e88.png)

![error5](https://user-images.githubusercontent.com/39021941/39776403-0560480a-5301-11e8-8d1c-59ca644e5e15.png)
the last two ocurred shortly after one another. Both show up regularly

It doesn't matter if helicopters are editor placed and virtualized or spawned in by the Military Ai Commander. I made sure that helicopters of variing types were present for different tasks. Also parts of Military Logistics don't seem to work namely those that are carried out by helis.

### Steps to Reproduce

I set up a fairly standard mission with two opposing factions that spawn from smaller and one larger spawn-zone. I let the air assets be placed by the, to the AI Commander synced, Air Commander and place extra helis for each faction too. I made sure that placed units are virtualized correctly. For all the above shown errors to occur I had to wait some time in the mission with the last one coming at ~20 min.

**Expected behavior:** [What you expected to happen]

Air commander using spawned and editor-placed helicopters appropriately

**Actual behavior:** [What actually happened]

Helicopters idle on spawned position.

**Comment by tupolov** [comment]
Hey man, apologies for the late response, looking at this now. Thank you for an awesome bug report!

**Comment by tupolov** [comment]
So I reviewed your mission:

1. You can only have 1 ATO per side (not per faction). ATO will register friendly faction aircraft.
2. You have to place EMPTY aircraft manually, not aircraft with crew
3. Turn on debug in ATO and check the RPT to see what is going on (and for submitting bug reports)

I'll add code to handle the errors you witnessed, but please update your mission and retest.
