### ISSUE TITLE
Alive 1.6.1.1804271 is not up in PlayWithSix

### ISSUE THREAD

**Issue by Kicillof** [ALiVEOS/ALiVE.OS#518]
### Description

The latest Alive version in PlayWithSix and SyncWithSix is the 1.5.3.1801061 and the 1.6.1.1804271 has been out for more than a month now in alivemod.com, Steam Workshop and Armaholic, but not in PWS. I'm not aware if this is a PWS/SWS issue and they are taking their time validating your new version or you haven't uploaded it. 

Considering that all my clan addons depends of a PlayWithSix repository, it would be really helpful to have the latest Alive version there, just like always until now.

I'll leave here a screenshot where it shows all the latest Alive versions on PWS: 

![aliveversionissue](https://user-images.githubusercontent.com/38118007/40701218-81d4e04a-63b3-11e8-8de0-eaa039a8d27b.png)

### Steps to Reproduce

1. Open PlayWithSix or SyncWithSix
2. Search for the Alive mod.
3. Check out the latest version up.

### 

Thank you for your time.

**Comment by coachwn** [comment]
PWS likes to take their sweet time on all things. 

Which is why our group quit using them years ago and we moved directly to Steam Workshop for all mod updates...plus its faster.

**Comment by Kicillof** [comment]
@Will-Nichols I'm aware, but I never saw they taking this long. It's usually a couple of days or a week max for new version to be up. 

Besides, I would love to use something like Steam Workshop but the auto-update thing will screw my mission since we heavily use the Alive persistence, so the editors usually test the new mods before launching the general update for everyone else. The only good thing about PWS is the ability to create repositories with mods in the version that you want, with the option of going back. Everything else is pretty bad.

**Comment by marceldev89** [comment]
You can notify them about updates on their forum and/or their Discord but I think @bradon was already going to do that.

**Comment by Will-Nichols** [comment]
@Kicillof you know you can turn off the autoupdate aspect from Steam Workshop right? Also PWS is a dead thing now and will not be returning.

**Comment by friznit** [comment]
There's nothing to stop you rehosting ALiVE on Steam as a _private_ mod only.  I do this for my group by having all members become "friends" of the group on steam (i.e. we have steam user called VOLCBAT).  It's simple to maintain the list of friends by removing past members and you can control when the mods are updated.  For bonus points, create a Steam collection for new members to subscribe to.

We only ask that you do _not_ make any rehosted copies of ALiVE _publicly_ available (e.g. for public servers), as this would confuse everyone with multiple different versions kicking around.

**Comment by Kicillof** [comment]
@friznit Thanks for the tip! I did it when I saw that withSIX stopped working.
