### ISSUE TITLE
Unable to save the persistence.

### ISSUE THREAD

**Issue by Kicillof** [ALiVEOS/ALiVE.OS#519]
### Prerequisites

* [No] Can you reproduce the problem using ALiVE and CBA Only?
* [Yes] Are you running the latest version of ALiVE ?
* [Yes] Are you running the latest version of CBA_A3?
* [No] Have you attached an unbinarized SQM?
* [Yes] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [Yes] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Hello! I'm having trouble saving the persistence on my Duala mission. When I select the Server Save and Exit option on the menu it just send me back to the lobby. I have already disabled -autoinit on the commandline. 

The server .rpt state this, but the IP and Groupname are just fine:

```
19:36:50 ALiVE Extension (ALiVEPlugIn) Error: ['StartALiVE','ERROR','You are not authorized to access ALiVE War Room with this account. Check IP and Groupname.'] CMD: StartALiVE ['true']
19:36:50 ALIVE_SYS_DATA START PLUGIN: YOU ARE NOT AUTHORIZED
19:36:50 YOUR SERVER EXTERNAL IP ADDRESS AS SEEN BY WAR ROOM: 192.99.17.149 (Ensure it matches with your War Room server entry if you have any issues)
19:36:50 DATA: Attempting to load ALiVE web services config.
19:36:51 ALiVE Extension (ALiVEPlugIn) Error: ['{"error":"unauthorized","reason":"Name or password is incorrect."}
'] CMD: SendJSON ['GET','sys_data/config','']
19:36:51 ALiVE-0 CANNOT CONNECT TO CLOUD SERVICE, DISABLING WEB SERVICES
19:36:51 ALiVE-0 EXITING DATA INIT AS CANNOT CONNECT TO COUCHDB
19:36:51 DATA: Waiting for global DISABLED variable...
19:36:51 DATA: SYS DATA enabled: false
```
When I try to save:
```
19:48:44 ALiVE Exit - mode: SAVESERVERYO
19:48:44 ALiVE Data is disabled, so server save will not occur, aborting...
```

Besides, i'm confused about this:

![screenshot_3](https://user-images.githubusercontent.com/38118007/42291750-1512253c-7fa4-11e8-89f8-04ddce1e075d.png)

Up here you have the AliveServer log (left) and my alive,cfg (right). As you can read there, there is a difference in some numbers (ID maybe?) and username? between the alive.cfg that I downloaded and the one that the server is reading. Could this be a the problem?

I'm attaching down here my .rpt, the server .rpt, the AliveServer log and a capture of the Alive Data module.

[Arma3_x64_2018-07-04_13-03-33.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2164153/Arma3_x64_2018-07-04_13-03-33.txt)

[arma3server_2018-07-04_19-34-25.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2164150/arma3server_2018-07-04_19-34-25.txt)

[aliveplugin_2018-07-04_16-26.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2164147/aliveplugin_2018-07-04_16-26.txt)

![20180704155450_1](https://user-images.githubusercontent.com/38118007/42291628-42714112-7fa3-11e8-9bf1-a7cd318e23bc.jpg)

### Steps to Reproduce

1. Log as Admin
2. Select Server Save and Exit

**Expected behavior:** Alive Tablet would show up and persistence will be saved

**Actual behavior:** It just sent me back to the lobby

**Comment by bradon** [comment]
The 5984 thing is specifying a port on the alive server, it does not need to match your group ID.

You've double checked you have the right IP and Hostname on the warroom config for the server?

**Comment by Kicillof** [comment]
@bradon The War Room config is the same I've been using since at least a year and a half. I've been using the same server with the same IP but with 3 o 4 different missions with persistence and all of them worked just fine.

But, just in case: My server host is "Host Havoc", so in Hostname I placed that. Is that ok? (That has been like that since the beginning). Also, the IP is fine, and without the port as requested.

Thank you for you response.

**Comment by tupolov** [comment]
Some how ALiVE is picking up the wrong config file. As you noted the username is wrong in your RPT.

Remove any config files you have and download the corect config file from your group page.

**Comment by Kicillof** [comment]
@tupolov Apparently the server is using an alive.cfg that found inside the server (C:\Users\TCAGame\AppData\Local\ALiVE\alive.cfg) and not the one I have on my computer (...\AppData\Local\ALiVE). Is it there any way to make Alive to use the one I have on my computer -as it should- and not the one that found inside the server? 

I'm contacting Havoc Support as well.

Thanks!

**Comment by tupolov** [comment]
The instructions on War Room are explicit about ALiVE requiring the config file to be put on the machine acting as a server.

Please follow the instructions on War Room

**Comment by tupolov** [comment]
Closing issue.
