### ISSUE TITLE
Error undefined variable in expression: _position after ATO fired

### ISSUE THREAD

**Issue by AngusDLX** [ALiVEOS/ALiVE.OS#520]
### Prerequisites

* [yes] Can you reproduce the problem using ALiVE and CBA Only?
* [yes] Are you running the latest version of ALiVE ?
* [yes] Are you running the latest version of CBA_A3?
* [yes] Have you attached an unbinarized SQM?
* [yes] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [no] Have you attached screenshots of the Parameters set on the offending Module?

RPT: https://pastebin.com/ZT1Pd4kN

Mission: https://drive.google.com/file/d/1aCFxiZ5O0LA9vWvGov0QuBFGgPZ47YV-/view?usp=sharing

### Description
As soon as the mission is started and one of the first ATO's is fired, an error appears on the screen:

`13:36:36 Error in expression <S_%1", format["%1_dir", _objectiveID]], _position getPos [100, _dir]];
_m setMar>
13:36:36   Error position: <_position getPos [100, _dir]];
_m setMar>
13:36:36   Error Variável indefinida na expressão: _position
13:36:36 File \x\alive\addons\fnc_analysis\fnc_liveAnalysis.sqf [ALiVE_fnc_liveAnalysis], line 2323`

### Steps to Reproduce

1. Start the mission and wait ATO's start
2. Error will pop up

**Expected behavior:** No error

**Actual behavior:** Error

![arma3_x64 2018-07-17 14-20-22-572](https://user-images.githubusercontent.com/35405396/42834894-3b95d45e-89ce-11e8-90c9-520661ee5342.jpg)

**Comment by tupolov** [comment]
Are you using version 1.7.1 published today on Steam?

**Comment by AngusDLX** [comment]
Yes Tupov!

**Comment by tupolov** [comment]
```14:16:09 Error in expression <;S_%1", format["%1_dir", _objectiveID]], _position getPos [100, _dir]];
_m setMar>
14:16:09   Error position: <_position getPos [100, _dir]];
_m setMar>
14:16:09   Error Variável indefinida na expressão: _position
14:16:09 File \x\alive\addons\fnc_analysis\fnc_liveAnalysis.sqf [ALiVE_fnc_liveAnalysis], line 2323```

**Comment by tupolov** [comment]
Working on a fix for that error.

**Comment by tupolov** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/9581355e3f281c10da4e718535c6d65f169d60bd Fixed
