### ISSUE TITLE
Airplane called by the player via logistics falls on the ground and explodes.

### ISSUE THREAD

**Issue by AngusDLX** [ALiVEOS/ALiVE.OS#521]
### Prerequisites

* [ Yes] Can you reproduce the problem using ALiVE and CBA Only?
* [Yes ] Are you running the latest version of ALiVE ?
* [Yes] Are you running the latest version of CBA_A3?
* [No] Have you attached an unbinarized SQM?
* [ No] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [No] Have you attached screenshots of the Parameters set on the offending Module?

### Description

If you access the logistics and order a plane, it will spawn at low altitude and hit the ground

### Steps to Reproduce

1. Access logistics via tablet
2. Request an Airplane
3. See the  pyrotechnics show lol

**Expected behavior:** NO BOOOM

**Actual behavior:** BOOM

**Comment by AngusDLX** [comment]
Oh I forgot, sorry D: 

Mission: https://drive.google.com/open?id=1slcYxVcRvINXtd-Xj7fQWVIOiLyGzadW

RPT: https://pastebin.com/wkBv1YWk

**Comment by the-star** [comment]
I'm assuming this issue is with calling in an airplane by helicopter/VTOL insertion?

Could you clarify the following:
1. Does this happen with all types of airplanes?
2. Does this happen with vehicles other than airplanes?

**Comment by the-star** [comment]
Just a quick update on this issue, I have a potential fix but I'll need to do more testing.

**Comment by AngusDLX** [comment]
If you want someone for tests, I'm free for the entire year.

**Comment by the-star** [comment]
Thanks for the offer @AngusDLX, I'm going to take you up on it.

You can download my fork here: https://github.com/the-star/ALiVE.OS/releases/tag/v0.1-plane. Make sure not to run my fork with the real ALiVE at the same time. I put labels on my fork with my username (the-star) to make it easier to identify.

I know it does not work 100% so feedback/RPT on your observations, etc is appreciated.

**Comment by AngusDLX** [comment]
I did some tests and I have some observations to make:

Aircraft like the A164 do not explode 90% of the time, they can recover quickly.

Aircraft like the F18 blow up 70% of the time, they spawn at a very steep angle and can not recover

Perhaps raising the spawn altitude and changing the angle will work better. Obs: I have tested in Altis and I imagine that in mountainous areas like for example the airport of Loy Manara in the Takistan the altitude can be a problem

**Comment by the-star** [comment]
Thanks for the update. I loaded up the (old) build I had you test and I noticed the issue as well. I made some commits since and will update this post when I have the download link.

**Comment by the-star** [comment]
@AngusDLX updated my previous post. Don't think GitHub notifies on edit so I'm posting this just in case.

**Comment by AngusDLX** [comment]
Thanks The Star, I will download it today and will give you the feedback as soon as possible. Sorry for not seeing it before, GITHUB does not notify me about anything.

**Comment by AngusDLX** [comment]
All created without any kind of failure, many thanks the Star bug solved!!!

certified by my cat who was watching the jets too and trying to get them on the screen xD
