### ISSUE TITLE
The error caused by BI after the tac ops DLC is making the server using ALiVE become unstable

### ISSUE THREAD

**Issue by AngusDLX** [ALiVEOS/ALiVE.OS#522]
### Description

Bohemia add on Tac Ops DLC the danger event system controlled by the engine.

The problem is that this event system is conflicting with the ALiVE for some reason caused by Bohemia's own code

The error is caused when a civilian is in the midst of an firefight. This error is triggered and knocking down the server fps (sometimes freezing) and generating a gigantic RPT log.

The only solution I found to not have these problems on the server is to not place the civil modules so they do not spawn, which makes the asymmetric war unusable.

I've seen several people reporting this issue on Steam as well.

Could a workaround exist? I'm opening a ticket for BI to alert them about this problem but I'm afraid they will not give a damn about.

The error:

`Error in expression <[];

_threat = [_this,_threatsNew] call bis_fnc_cp_main;

_t = time + (_this ca>
2018/07/21, 11:32:29   Error position: <bis_fnc_cp_main;

_t = time + (_this ca>
2018/07/21, 11:32:29   Error Undefined variable in expression: bis_fnc_cp_main
2018/07/21, 11:32:29 Error in expression <time > _t>
2018/07/21, 11:32:29   Error position: <_t>
2018/07/21, 11:32:29   Error Undefined variable in expression: _t
`

**Comment by HeroesandvillainsOS** [comment]
Not posting the rpt and sample mission for tickets like this is not optional. Anyway, thank for the report. I’ve seen this error too. Could you post the mission and full rpt please?

**Comment by DavisBrown723** [comment]
@Heroes

We know what the issue is for this one already so no rpt needed.

**Comment by HeroesandvillainsOS** [comment]
Oh ok I see now. Closed #495

Can anything be done on the ALiVE side or only from BI?

**Comment by DavisBrown723** [comment]
ff6c6681ceffc81ee9019d80fec32111d4c3d99a

**Comment by AngusDLX** [comment]
omgggggggggg thanksssssssssss <3
