### ISSUE TITLE
Error position: <reverse _unitAssignments;   { { [_comman>

### ISSUE THREAD

**Issue by AngusDLX** [ALiVEOS/ALiVE.OS#528]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

This error happens in a varied way. Sometimes he only shoots at the beginning and sometimes in the middle of a normal game.

`Error in expression <+(_vehAssignment param [2, [], [[]]]);

reverse _unitAssignments; 

{
{
[_comman>
2018/08/13, 14:51:52   Error position: <reverse _unitAssignments; 

{
{
[_comman>
2018/08/13, 14:51:52   Error reverse: Type Number,Not a Number, expected Array
2018/08/13, 14:51:52 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2670`

### Steps to Reproduce

1.Start the mission
2. Move around the map or use admin teleport

**Expected behavior:** No error

**Actual behavior:** Error

SQM: https://drive.google.com/open?id=1TZ_hMP-dw7l9XLmghAGo9DOhNyq_GHUr
RPT:https://drive.google.com/open?id=1ws1_EaIoD02T_Ie8PCWticNGdi1T2Dzu

**Comment by AngusDLX** [comment]
The error apparently disappeared after the last ALiVE update
Solved

**Comment by marceldev89** [comment]
The issue still existed but also has been fixed a few days ago. See https://github.com/ALiVEOS/ALiVE.OS/issues/546 for a fix.
