### ISSUE TITLE
Insertion waypoint for Combat Support Transport Helos ignores Height slider

### ISSUE THREAD

**Issue by bux578** [ALiVEOS/ALiVE.OS#53]
Using ALiVE 1.07 it seems that height is ignored when issuing an Insertion command.
ACE3 FastRoping needs <= 30m height as the ropes aren't that long.

Haven't tested it yet with the new release.

**Comment by SpyderBlack723** [comment]
Can't repro on open land, can repro when trying to insert above forest (likely the same for buildings). AI refuses to go below their flyInHeight.

Will see if I can hack something together.

**Comment by SpyderBlack723** [comment]
Fixed in aaa6aa21d34324599d7f1690980172c51e16d8af
