### ISSUE TITLE
Persistence not working. Problem with War Room database?

### ISSUE THREAD

**Issue by Kicillof** [ALiVEOS/ALiVE.OS#531]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [x] Have you attached screenshots of the Parameters set on the offending Module?

### Description

I'm having trouble with saving the persistence since almost a week. When I press Server Save and Exit button, it doesn't show the Alive Tablet, it just takes me back to the lobby.

AliveServer log

> [2018-08-26 09:18:49] [info] ALiVEPlugIn v2.1a-
> [2018-08-26 09:18:49] [debug] >>> ParseMessage [StartALiVE ['true']]
> [2018-08-26 09:18:49] [debug]     Function: StartALiVE
> [2018-08-26 09:18:49] [debug]     Params:
> [2018-08-26 09:18:49] [debug]             - [true]
> [2018-08-26 09:18:49] [info]     Disable Performance Monitor: true
> [2018-08-26 09:18:49] [info]     Reading 'alive.cfg'
> [2018-08-26 09:18:49] [info]     Configuration found: C:\Users\TCAGame\AppData\Local\ALiVE\alive.cfg
> [2018-08-26 09:18:49] [info]     No URL in config. Using default.
> [2018-08-26 09:18:49] [info]     Configuration 'alive.cfg' read OK.
> [2018-08-26 09:18:49] [debug]     Alive Config:
> [2018-08-26 09:18:49] [debug]         Type:  JSON
> [2018-08-26 09:18:49] [debug]         User:  deje6ifi8a8akuwa9ubu9o7yqafazusa
> [2018-08-26 09:18:49] [debug]         Pass:  xxxxxxxxxxxxxxxx
> [2018-08-26 09:18:49] [debug]         Group: Simlatina
> [2018-08-26 09:18:49] [debug]         URL:   http://db.alivemod.com:5984
> [2018-08-26 09:18:49] [info]     Checking WarRoom access...
> [2018-08-26 09:18:49] [info]     URL: http://alivemod.com/api/authorise?group=Simlatina&localDB=false
> [2018-08-26 09:18:50] [info]         WarRoom access granted.
> [2018-08-26 09:18:50] [info]     Checking DB access...
> [2018-08-26 09:19:11] [error] ###### curlGet ######
> [2018-08-26 09:19:11] [error]     Error: curl_easy_perform() failed
> [2018-08-26 09:19:11] [error]     RAW:   Couldn't connect to server
> [2018-08-26 09:19:11] [error] ###### HandleMessage - StartALiVE ######
> [2018-08-26 09:19:11] [error]     Error: curlGet() failed
> [2018-08-26 09:19:11] [error]     RAW:   ['curlGet','ERROR','curl_easy_perform() failed']
> [2018-08-26 09:19:11] [debug]     Return value [['StartALiVE','ERROR','['curlGet','ERROR','curl_easy_perform() failed']']]
> [2018-08-26 09:19:11] [debug] |/-\ Elapsed time: 21662.8ms
> [2018-08-26 09:19:11] [debug] >>> ParseMessage [ServerAddress]
> [2018-08-26 09:19:11] [debug]     Function: ServerAddress
> [2018-08-26 09:19:11] [debug]     Params:
> [2018-08-26 09:19:11] [warning] ALiVE not initialized yet!
> [2018-08-26 09:19:11] [info]     ServerAddress - Querying for IP @ ipify.org
> [2018-08-26 09:19:11] [info]         IP returned: 192.99.17.149
> [2018-08-26 09:19:11] [debug]     Return value [['192.99.17.149']]
> [2018-08-26 09:19:11] [debug] |/-\ Elapsed time: 45.042ms
> [2018-08-26 09:19:11] [debug] >>> ParseMessage [GroupName]
> [2018-08-26 09:19:11] [debug]     Function: GroupName
> [2018-08-26 09:19:11] [debug]     Params:
> [2018-08-26 09:19:11] [warning] ALiVE not initialized yet!
> [2018-08-26 09:19:11] [info]     GroupName: Simlatina
> [2018-08-26 09:19:11] [debug]     Return value [['Simlatina']]
> [2018-08-26 09:19:11] [debug] |/-\ Elapsed time: 0ms
> [2018-08-26 09:19:11] [debug] >>> ParseMessage [SendJSON ['GET','sys_data/config','']]
> [2018-08-26 09:19:11] [debug]     Function: SendJSON
> [2018-08-26 09:19:11] [debug]     Params:
> [2018-08-26 09:19:11] [debug]             - [GET]
> [2018-08-26 09:19:11] [debug]             - [sys_data/config]
> [2018-08-26 09:19:11] [debug]             - []
> [2018-08-26 09:19:11] [warning] ALiVE not initialized yet!
> [2018-08-26 09:19:32] [error] ###### curlGet ######
> [2018-08-26 09:19:32] [error]     Error: curl_easy_perform() failed
> [2018-08-26 09:19:32] [error]     RAW:   Couldn't connect to server
> [2018-08-26 09:19:32] [error] ###### HandleMessage - SendJSON ######
> [2018-08-26 09:19:32] [error]     Error: curlGet() failed
> [2018-08-26 09:19:32] [error]     RAW:   ['curlGet','ERROR','curl_easy_perform() failed']
> [2018-08-26 09:19:32] [debug]     Return value [['SendJSON','ERROR','['curlGet','ERROR','curl_easy_perform() failed']']]

Now, I've already re-edited the mission, replaced all Alive modules and also replaced the alive.cfg file, but the problem is still there.

Either way, **back in 2016 a guy reported the same problem that I have and it was told that the Alive War Room database ran out of space.** You can check this out here on the Alive Forum: [http://alivemod.com/forum/1661-war-room-stopped-working/0](http://alivemod.com/forum/1661-war-room-stopped-working/0)

I'm attaching here:

- a mission with Alive and CBA only that has the exact same issue: [mission.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2322155/mission.txt)
- my .rpt [DUALA-Arma3_x64_2018-08-26_18-03-08.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2322158/DUALA-Arma3_x64_2018-08-26_18-03-08.txt)
- server .rpt [DUALA-arma3server_2018-08-27_00-36-08.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2322157/DUALA-arma3server_2018-08-27_00-36-08.txt)
- AliveServer log [DUALA-aliveplugin_2018-08-26_09-18.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2322156/DUALA-aliveplugin_2018-08-26_09-18.txt)

### Steps to Reproduce

1. Execute a mission with Alive Persistence
2. Try to save the server

**Expected behavior:** Save persistence

**Actual behavior:** Doesn't save persistence

**Comment by DavisBrown723** [comment]
Duplicate issue has more information on it
