### ISSUE TITLE
Talk to pilot outside of helicopter

### ISSUE THREAD

**Issue by xetra11** [ALiVEOS/ALiVE.OS#532]
### Description

When me and my squad drops after I told the transport helicopter to land I want the transport to RTB asap. Therefore I actually talk to him while still inside as the last man. Then after I ordered him to RTB I quickly try to get out of the helicopter before he leaves with me still inside.

### Steps to Reproduce

**Expected behavior:**
I would love to have an option while outside of the helicopter to actually talk to the pilot OR even have like a RTB option while around the helicopter. Kinda like yelling at him to get lost ;)

**Actual behavior:** 
Talking is only possible inside the helicopter. If I am outside the helicopter I need to open the ALiVE tablet and choose Combat Support >> Transport >> RTB. This is pretty annoying while getting dropped into a hot zone 🗡 

Thanks for your awesome work!

**Comment by the-star** [comment]
Heya @xetra11, I opened up a PR for the talking to pilot feature.

If you're interested in the RTB feature, could you open up another ticket for it?

**Comment by xetra11** [comment]
Extracted feature: https://github.com/ALiVEOS/ALiVE.OS/issues/534

**Comment by xetra11** [comment]
@the-star 

Mybe this feature can be more immersive when combined with ACRE2:

> You can only talk to a pilot outside the helicopter if using the "infantry telephone" or have the same frequency the radio rack of the helicopter is on.

This surely creates a dependency to ACRE2 but in fact this will only be applied when ACRE2 is installed. Should be optional by settings.

**Comment by the-star** [comment]
@xetra11 I hardcoded the max talk range to be 50 meters (2d distance). How do you feel about this?

About the ACRE thing, I'll think about it if my changes get merged. I think the best way to implement it is to use a special variable. Then, the other mod maker/mission maker can alter this provided variable with the necessary functionality. This provides a level of indirection to prevent too much dependency on any one mod.

**Comment by xetra11** [comment]
@the-star  
About ACRE2: Aye! Inversion of Control eh ;)

If I find time I gonna test your branch. But since it is possible to talk to the pilot outside the helicopter it should be good. Where I find 50m a bit too large? Don't know how it feels from within the game engine.

**Comment by the-star** [comment]
I appreciate any help with testing. If you want the PBOs, you can find them [here](https://github.com/the-star/ALiVE.OS/releases/tag/v0.1-slingload_talk). Note that my release contains both the talking to pilot and slingload RTB fixes.

**Comment by xetra11** [comment]
**Meta**
@alive-the-star
@cba_a3

Map:  Stratis

Units/Modules: 

- Alive (Req)
- Player Combat Support
- Transport Module with default chopper

✔️ Worked as expected! I love it. Adds smooth control to helitaxi dropoffs
