### ISSUE TITLE
Scream/Signal RTB to pilot outside of helicopter

### ISSUE THREAD

**Issue by xetra11** [ALiVEOS/ALiVE.OS#534]
### Description

When in combat and jumping out of a helicopter while it landed it is a pain to choose the Combat Support *order to RBT* for the given helicopter.

### Steps to Reproduce

**Expected behavior:**
When outside of a helicopter and within 2m-3m you have the action to "Order to RBT" to the nearest helicopter. This should simulate a handsignal or screaming at the pilot to "get the hell out of the combat zone"

**Additional polished behaviour:**

- Only allow this feature around a cone area where the pilot or the co-pilot could actually see you
- Play animation when using this action to show a specific hand signal that fits to a "get outta here"

**Actual behavior:** 
Nothing - you can not tell the pilot what to do outside the helicopter.

**Comment by xetra11** [comment]
extracted from #532

**Comment by the-star** [comment]
Oh, this is the RTB feature you wanted. I misread your other issue and thought you wanted an auto-RTB feature after the completion of a waypoint.

**Comment by xetra11** [comment]
Well this would be nice, too - problem here is on what condition would you make it happen? When all non-crew passengers left the helicopter?

And how would you make this an option? Like a new movement option besides *move*, *land*, etc. choosable in the Combat Support Setup?

**Comment by xetra11** [comment]
Hm the timer can make things easier to implement but also more frustrating since sometimes the pilot AI just fails to really land fast enough or completely.

**Comment by friznit** [comment]
Waypoints, triggers and timers can get really whacky in a high load environment where server fps is suffering.  Wherever possible it's better to have explicit actionable features, such as the other half of this ticket which uses a simple cursorTarget approach.  IMO that should be sufficient to meet both use cases and the value gained by adding an alternative timed RTB as well is quite low given the level of effort and risk of breaking things.

**Comment by the-star** [comment]
I'll put this on the back burner as I agree with what you said about the other ticket being a good compromise.
