### ISSUE TITLE
Error in expression (Undefined variable) in fnc_taskHandler.sqf

### ISSUE THREAD

**Issue by Asmodeuz** [ALiVEOS/ALiVE.OS#536]
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [X] Have you attached an unbinarized SQM?
* [X] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [X] Have you attached screenshots of the Parameters set on the offending Module?

### Description

When using ALIVE_MIL_C2ISTAR module in a mission an error appears during mission launch. For some reason this error appears only occasionally when previewing the mission through the in-game editor but the error is always output when testing the mission in a dedicated server environment.

The below screenshot is showing **Auto Task BLU** set to _Constant_. Regardless of the selected setting (choices are _Constant_, _Strategic_, _None_) there the error will still get output:
![image](https://user-images.githubusercontent.com/12435032/44959124-929ecf00-aef2-11e8-8b0b-4e3530aa4f24.png)

Below you can see the error within a short excerpt from the dedicated server RPT output:

```
18:30:08 ALiVE_sys_acemenu: ACE interact_menu not active or no interface found, exiting
18:30:13 OPC DATA [1.41489e+009," ","Asmodeus",false,3]
18:30:13  Mission id: c8667b601ac979828278b338657a9cae1f4aba24
18:30:13 OPC DATA [2,"","__SERVER__",false,2]
18:30:13 "Null playerUID sent to getPlayerByUIDOnConnect"
18:30:13 "Null playerUID sent to getPlayerByUIDOnConnect"
18:30:14 Ragdoll - loading of ragdoll source "Soldier" started.
18:30:14 Ragdoll - loading of ragdoll source "Soldier" finished successfully.
18:30:15 "ALiVE - Starting Garbage Collector..."
18:30:16 ALiVE_fnc_HashGet retrieved wrong input [any,"debug",false] from ALiVE_fnc_hashGet!
18:30:16 Error in expression <logic, _args] spawn {
private _debug = [_logic, "debug", false] call ALIVE_fnc_h>
18:30:16   Error position: <_logic, "debug", false] call ALIVE_fnc_h>
18:30:16   Error Undefined variable in expression: _logic
18:30:16 File \x\alive\addons\mil_C2ISTAR\fnc_taskHandler.sqf [ALiVE_fnc_taskHandler], line 2328
18:30:18 ALIVE PLAYER TASK REQUEST ["WEST","BLU_F","CaptureObjective",[["#CBA_HASH#",["debug","active","position","side","profileID","type","objectType","vehicleAssignments","vehiclesInCommandOf","vehiclesInCargoOf","leader","unitClasses","unitCount","group","companyID","groupID","waypoints","waypointsCompleted","positions","damages","ranks","units","speedPerSecond","despawnPosition","hasSimulated","isCycling","activeCommands","inactiveCommands","spawnType","faction","isPlayer","_rev","_id","busy","timeLastSim"],[false,false,[13996.9,18947.9,0],"EAST","OPF_F-entity_15","entity","OIA_InfTeam",["#CBA_HASH#",[],[],any],[],[],<NULL-object>,["O_soldier_TL_F","O_soldier_AR_F","O_soldier_GL_F","O_soldier_LAT_F"],0,<NULL-group>,"","",[],[],[[13996.9,18947.9,0],[13996.9,18947.9,0],[13996.9,18947.9,0],[13996.9,18947.9,0]],[0,0,0,0],["SERGEANT","CORPORAL","PRIVATE","PRIVATE"],[],[2,4,6],[0,0],false,false,[["ALIVE_fnc_garrison","spawn",[200,"true",[0,0,0]]]],[],[],"OPF_F",false,"","",false,156.236],any]],"OPCOM",true]
18:30:23 ALiVE [m_21|190] Module ALiVE_mil_logistics INIT COMPLETE TIME:  15.957
18:30:23 ALiVE [m_22|190] Module ALiVE_mil_logistics INIT COMPLETE TIME:  15.656
```

### Steps to Reproduce

1. Download the test mission [C2ISTAR_errors_CBA_ALIVE.Altis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/2343669/C2ISTAR_errors_CBA_ALIVE.Altis.zip)
2. Test the mission first through the in-game editor and observe for possible debug information on the screen when starting the mission. The error appears less frequently when testing through the in-game editor. Just in case check the RPT file for the error. If the error does not manifest itself when testing through the editor then export the mission as multiplayer (mission)
3. Upload the mission PBO into a dedicated server. Start the mission and observe the error get output into the server RPT file

### Note
I have used the mission that I attached to this issue to test a couple of additional issues regarding C2ISTAR autotasking. This is why the binarized mission file comes accompanied with two additional files (_init.sqf_ and _staticData.sqf_)

**Comment by the-star** [comment]
Do you get this error even if you don't have init.sqf and staticData.sqf?

I'm trying to understand the order of initialization here as I'm fairly certain this is caused by a race condition.

**Comment by Asmodeuz** [comment]
Yes this error manifests itself even if I rip out _init.sqf_ and _staticData.sqf_ and when there's nothing but _mission.sqm_ in the mission PBO.
Here's that version: [C2ISTAR_errors_CBA_ALIVE.Altis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/2386831/C2ISTAR_errors_CBA_ALIVE.Altis.zip)

When testing remember that the error gets output always in a dedicated server environment but "only" occasionally when testing through the in-game editor.

**Comment by the-star** [comment]
Thanks for the awesome ticket @Asmodeuz.

I got around to testing this issue and I can reproduce it 100% with a dedicated server.
