### ISSUE TITLE
Main Menu - Needs 1.62 Support

### ISSUE THREAD

**Issue by sargken** [ALiVEOS/ALiVE.OS#54]
You can see that with ACE running the Alive Buttons get overtaken by ACE's button. 
http://images.akamai.steamusercontent.com/ugc/280730548757688515/F57BD499C857ADA242647D51DA0002E0DB0BA2C3/

**Comment by bux578** [comment]
Could be related: https://gyazo.com/6c2757ffccff4590ea82ac82bf8567ee
("Intel / News" top left corner)

**Comment by sargken** [comment]
Something is also blocking my access to the Single Player Buttons.  I don't know which mod it is.

**Comment by SpyderBlack723** [comment]
> Something is also blocking my access to the Single Player Buttons. I don't know which mod it is.
I only have a problem with that when ACE is loaded, not sure if it's been updated for APEX yet.

**Comment by PabstMirror** [comment]
I think TFAR adds the intel/news windows which is blocking the center area

**Comment by friznit** [comment]
We fixed the front page stuff to be compatible with Apex.  It works fine with only ALiVE & CBA installed.

**Comment by bux578** [comment]
Good point @PabstMirror. 
TFAR hasn't been updated for ages.

**Comment by HeroesandvillainsOS** [comment]
I'm feeling with the new calmness of the (excellent) new menu screen, the hardcore ALiVE Arma-theme music may be about due for a replacement?

**Comment by sargken** [comment]
Would it be ok to edit tfr and release a "patch" for it

**Comment by friznit** [comment]
You'll have to ask that mod team.  As this is not an ALiVE bug, closing the ticket.

**Comment by bux578** [comment]
Though the OP's issue is a different one than the TFR issue
