### ISSUE TITLE
MACC spawns plane the wrong way on scramble

### ISSUE THREAD

**Issue by Fletch43** [ALiVEOS/ALiVE.OS#543]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only? Yes
https://www.dropbox.com/s/u1zj4q6mpxt0t31/AltisMACC.mp4?dl=0

* [ ] Are you running the latest version of ALiVE ? Yes
* [ ] Are you running the latest version of CBA_A3?Yes
* [ ] Have you attached an unbinarized SQM?yes
https://www.dropbox.com/s/lsxaatomrjxeo3a/mission.sqm?dl=0

* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?no. 

* [ ] Have you attached screenshots of the Parameters set on the offending Module?Yes
https://www.dropbox.com/s/0o4d02clq70ip40/20180916140103_1.jpg?dl=0

### Description

Hey there gents. At the Altis Selakano airport I noticed that planes will spawn the wrong way from the runway. Was wondering if there was a way to index those other runways?
### Steps to Reproduce

1. Ran CBA/Alive set up a simple invasion/occupation set down macc module at airport location 207 072 and waited.
2. Turned the module around
3. lifted snapped module

**Expected behavior:** [What you expected to happen]
Where ever I place the module I would think the plane should point into the direction toward the runway.

**Actual behavior:** [What actually happened]
The plane spawned towards the road towards leaving the airport.

**Comment by marceldev89** [comment]
Probably something for @tupolov to look at.

**Comment by tupolov** [comment]
Direction of module doesn't affect placement of aircraft.

MACC uses aircraft placed by the Mil Placement modules. If no planes exist, then it will spawn aircraft on helipads, in hangars and if no hangars on a taxiway. The direction is dictated by the direction of the taxiway. Unfortunately, it appears BIS don't have the taxiway pointing in the right direction.
