### ISSUE TITLE
Reverse _unitassignments line 2676

### ISSUE THREAD

**Issue by Fletch43** [ALiVEOS/ALiVE.OS#546]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only? No
* [ ] Are you running the latest version of ALiVE ? Yes
* [ ] Are you running the latest version of CBA_A3? Yes
* [ ] Have you attached an unbinarized SQM? Yes
https://www.dropbox.com/s/igf8udp443ztach/sept18.sqm?dl=0
* [ ] Have you attached your RPT (If the issue relates to data, also attach Server RPT and ALiVE Plugin Log)?Yes
https://www.dropbox.com/s/bj8eaj47op4of9h/sept18.rpt?dl=0
* [ ] Have you attached screenshots of the Parameters set on the offending Module? No

### Description
After about 9hrs of starting the server, I get this error repeating continuously. Not too sure where how to track this down. Where to look.
Error in expression <+(_vehAssignment param [2, [], [[]]]);

reverse _unitAssignments; 

{
{
[_comman>
 7:55:53   Error position: <reverse _unitAssignments; 

{
{
[_comman>
 7:55:53   Error reverse: Type Number,Not a Number, expected Array
 7:55:53 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2676

I tried looking into the ALiVE .pbo but didn't have the right decoding.

### Steps to Reproduce

1. Tried Alive and CBA only didnt happen. It's a mod for sure but just dont know where to look.
2. Tried debugging modules nothing shows up i dont get errors popping up in the middle of my editor screen while in preview.

Thanks for any insight.

**Comment by Fletch43** [comment]
Well, I'm tracking this problem down step by step :) This is an rpt with CBA, ACE and ALiVE.
https://www.dropbox.com/s/zb9voocxc2f29yy/2676ace.rpt?dl=0

This is an rpt and sqm using only cba and alive with a line 2137 error. 
https://www.dropbox.com/s/ijihdh20rxmerk0/2137.rpt?dl=0
https://www.dropbox.com/s/eavc53vbex4bzg3/cbaalive.sqm?dl=0

currently having the server run for another day see what happens.

**Comment by Fletch43** [comment]
Looks like maybe it's a setting from Ace that is causing some issues.
RPT from today CBA and ALiVE no issues looks like
https://www.dropbox.com/s/ytks1n8brmsb7fm/CBAALiVE.rpt?dl=0

**Comment by marceldev89** [comment]
This has been fixed a few days ago (https://github.com/ALiVEOS/ALiVE.OS/commit/c5404179442439abbdde7cae0f0f8009afb72ac6), should be part of the next release.

In the meantime you can use https://www.dropbox.com/s/5qftd7rzwacpm5z/sys_profile.pbo?dl=1 which contains the fix.
