### ISSUE TITLE
Respawn With Gear Broken

### ISSUE THREAD

**Issue by AngusDLX** [ALiVEOS/ALiVE.OS#548]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [x] Have you attached screenshots of the Parameters set on the offending Module?

### Description

The player does not return with the previous gear after dying and respawn, perhaps it has been broken by the new respawn System introduced by B.I? There is an error that also appears at the time of the initialization of the mission and when the player  respawn.

` Error in expression < select 0);
_isFlash = (_this select 0) isFlashlightOn _currentweapon;
_isIR = (>
 9:12:10   Error position: <isFlashlightOn _currentweapon;
_isIR = (>
 9:12:10   Error isflashlighton: Tipo Número, esperado Strings
 9:12:10 File \x\alive\addons\sys_player\fnc_player.sqf [ALiVE_fnc_player], line 2440
 9:12:10 Error in expression < select 0);
_isFlash = (_this select 0) isFlashlightOn _currentweapon;
_isIR = (>
 9:12:10   Error position: <isFlashlightOn _currentweapon;
_isIR = (>
 9:12:10   Error Erro genérico na expressão
 9:12:10 File \x\alive\addons\sys_player\fnc_player.sqf [ALiVE_fnc_player], line 2440`

### Steps to Reproduce

1. Go to the ATM on your right
2. Pick any loadout or pick random
3. Respawn

**Expected behavior:**
The player returns with the previous loadout

**Actual behavior:** 

The player returns with the loadout chosen in the editor.

RPT: https://paste.ubuntu.com/p/SsMVKW3KpT/
SQM: https://ufile.io/quz9l

![error](https://user-images.githubusercontent.com/35405396/45931613-b4660180-bf46-11e8-8e3b-b3ebd5b728dc.jpg)

**Comment by marceldev89** [comment]
I'm not entirely sure if the above fix actually fixes this specific issue but it does fix it in some cases. You can test it out with https://www.dropbox.com/s/6bp9s7bz0ln5sog/sys_player.pbo?dl=1. If it doesn't fix it then let me know. :slightly_smiling_face:

**Comment by AngusDLX** [comment]
Thank you Marcel! It's working!

However, a new error appeared after the respawn

9:02:47 Error in expression <et setAmmo [_weap, 0];
(_this select 0) forceWeaponFire [_weap, (_this select 1)>
  9:02:47 Error position: <forceWeaponFire [_weap, (_this select 1)>
  9:02:47 Error Number Type, Expected Strings
  9:02:47 File \ x \ alive \ addons \ sys_player \ fnc_player.sqf [ALiVE_fnc_player], line 2463

**Comment by marceldev89** [comment]
@AngusDLX another test pbo for you ^^: https://www.dropbox.com/s/6bp9s7bz0ln5sog/sys_player.pbo?dl=1

**Comment by AngusDLX** [comment]
Thank you Marcel! I tested it and the error disappeared. But a new behavior appeared! If a player has access to Zeus and he respawn, the player will lose access and only will get back if he leaves the server and log in again!

**Comment by marceldev89** [comment]
I don't think that's an ALiVE issue and I've seen something similar in the "known issues" category for a few missions. We might take a look at it to see if there's anything we can do but that probably deserves a new issue. Closing this one until something related to respawn gear happens again. :smiley:

**Comment by AngusDLX** [comment]
Okay, Marcel, thank you so much for the fix!
