### ISSUE TITLE
Error after completing a task that has been declared in StaticData.sqf

### ISSUE THREAD

**Issue by Asmodeuz** [ALiVEOS/ALiVE.OS#552]
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [X] Have you attached an unbinarized SQM?
* [X] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

_StaticData.sqf_ file can be used to blacklist certain tasks from being autogenerated by ALiVE (see: http://alivemod.com/wiki/index.php/Custom_Blacklists --> C2ISTAR Task Blacklists). This way only the tasks declared in the _StaticData.sqf_ file will be autogenerated for players.

Completing an autogenerated task that has been declared in the _StaticData.sqf_ file seems to end up in an error. I have so far tested this behaviour with four different autogenerated tasks and every time I complete the given task an error regarding this particular task will get output.

The autogenerated tasks that I have tested and the errors that get shown shortly after completing the given task are below:

**MilAssault**
`22:09:42 Error in expression < call ALiVE_fnc_Dump};
if (_taskFaction == "") exitwith {["C2ISTAR - Task MilAss>
22:09:42   Error position: <== "") exitwith {["C2ISTAR - Task MilAss>
22:09:42   Error ==: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
22:09:42 File \x\alive\addons\mil_C2ISTAR\tasks\fnc_taskMilAssault.sqf [ALiVE_fnc_taskMilAssault], line 1832`

**MilDefence**
`21:20:50 Error in expression < call ALiVE_fnc_Dump};
if (_taskFaction == "") exitwith {["C2ISTAR - Task Mil De>
21:20:50   Error position: <== "") exitwith {["C2ISTAR - Task Mil De>
21:20:50   Error ==: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
21:20:50 File \x\alive\addons\mil_C2ISTAR\tasks\fnc_taskMilDefence.sqf [ALiVE_fnc_taskMilDefence], line 1832`

**CaptureObjective**
`21:41:04 Error in expression < call ALiVE_fnc_Dump};
if (_taskFaction == "") exitwith {["C2ISTAR - Task Captur>
21:41:04   Error position: <== "") exitwith {["C2ISTAR - Task Captur>
21:41:04   Error ==: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
21:41:04 File \x\alive\addons\mil_C2ISTAR\tasks\fnc_taskCaptureObjective.sqf [ALiVE_fnc_taskCaptureObjective], line 1832`

**CivAssault**
`21:31:47 Error in expression < call ALiVE_fnc_Dump};
if (_taskFaction == "") exitwith {["C2ISTAR - Task Civ As>
21:31:47   Error position: <== "") exitwith {["C2ISTAR - Task Civ As>
21:31:47   Error ==: Type Array, expected Number,String,Not a Number,Object,Side,Group,Text,Config entry,Display (dialog),Control,Network Object,Team member,Task,Location
21:31:47 File \x\alive\addons\mil_C2ISTAR\tasks\fnc_taskCivAssault.sqf [ALiVE_fnc_taskCivAssault], line 1832`

### Steps to Reproduce

1. Download the test mission [autogen_task_errors_CBA_ALIVE.Altis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/2421309/autogen_task_errors_CBA_ALIVE.Altis.zip)
2. Play the mission through in-game editor
3. While in the mission complete the task that gets autogenerated first
4. Shortly after completing the task observe for debug information popup that tells about the error (or check the latest RPT-file)

Note: manipulate the _StaticData.sqf_ file by adding/removing tasks to get only the desired task(s) autogenerated

**Comment by Asmodeuz** [comment]
the-star: this issue can be reproduced with the base ALiVE and your fork.

A full RPT with debug enabled on the C2ISTAR module can be found from pastebin: https://pastebin.com/3m25bkqm
The paste will expire in two weeks so be sure to grab it before that :)
For testing I used the latest Steam version of ALiVE.

The error with tasking was output at 21:44:53 after completing a CivAssault task.

**Comment by the-star** [comment]
Hey bud, I got your RPT.

Could you remove your pastebin link? It has some extra info.

**Comment by the-star** [comment]
@Asmodeuz 
1. [Direct link to my PBOs](https://github.com/the-star/ALiVE.OS/releases/download/v0.2-exclude_milcustom_obj/alive_exclude_milcustom_obj2.zip)
1. [readme](https://github.com/the-star/ALiVE.OS/blob/exclude_milcustom_obj_publictest/readme.md)

The linked build is the same as the other one but includes a possible fix for this issue.

Appreciate your help. Let me know how it goes.

**Comment by Asmodeuz** [comment]
the-star:
I grabbed the latest build from you, restricted autogenerated tasks to only "CivAssault" in _StaticData.sqf_ and then went on to test and complete around 15 "Attack the civilian objective" missions without a single error in between.
Is there a need to test the other autogenerated tasks (MilAssault, MilDefence, CaptureObjective) or should the fix you have provided also affect those?

**Comment by the-star** [comment]
I think this fix should work for the other tasks as well as they all follow the same format.

If you get the chance, could you test the other tests just in case? I'll put up a PR for this fix in the meantime.

Thanks again for testing.

**Comment by Asmodeuz** [comment]
@the-star 
I went through the other tasks mentioned in this issue. Task creation happens now without errors for all of them and new tasks keep appearing after first completing the most current task.
