### ISSUE TITLE
Map Index not functioning

### ISSUE THREAD

**Issue by JGarmr** [ALiVEOS/ALiVE.OS#555]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [Y] Have you attached an unbinarized SQM?
* [Y] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [Y] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Map Indexer will not work beyond Wiki step 7. I have followed all preparation steps.
RPT Log: https://gist.github.com/JGarmr/c7230f622b5c0ebc05a32428ca497e0f
Unbinarized SQM: https://gist.github.com/JGarmr/b8b1ad977a05d7bac5e92d867a4224d5
Module Settings: 
![20180930141146_1](https://user-images.githubusercontent.com/37349483/46257496-ee8d5100-c4ba-11e8-88fc-761094b9a6a7.jpg)
ALiVE\indexing\ruha log:  [log.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2431523/log.txt)

### Steps to Reproduce

1. Open the Arma 3 Editor on the Ruha map.
2. Place down a player entity and the Map Indexing tool with the above settings.
3. Start the mission.
4. Open the map and scroll out entirely.
5. Open the ALiVE User Menu.
6. Select "Map Indexing".

**Expected behavior:**
A CMD window should open according to the Wiki.

**Actual behavior:**
Error message in RPT log and an error in the game saying something went wrong and referring to RPT.

**Comment by marceldev89** [comment]
Does this mean you got it working or did you rage quit? :smile:
