### ISSUE TITLE
Suggestion: CQB Random Patrols (CQB Enhancement)

### ISSUE THREAD

**Issue by bradon** [ALiVEOS/ALiVE.OS#559]
Use of the CQB Module as a drop-in module for making quick insurgency-style missions could be improved by adding random patrol spawns near CQB areas.

**Comment by xetra11** [comment]
What about defining a "Minor Module" which adds small enhancements of the Situation?
The Minor Module has a like a bunch of options like Patrolling etc. so you can add small tweaks to areas.

For instance you can either define a patrolling option for that Minor Module or set it up to allow civilian unrests (npc throwing stones at players lol) or whatever minor tweaks come in mind an we are able to enhance this minor module to add more "small" features.

**Comment by diveyez** [comment]
This is already in the ALiVE mod. You have to tweak the settings of the Close Quarters Battle module.
