### ISSUE TITLE
Undefined Base class 'Turrets'

### ISSUE THREAD

**Issue by 56curious** [ALiVEOS/ALiVE.OS#561]
Exported using orbat creator.

Imported units from a friends config. Updated with some vics and groups. Pasted and checked over cfgPatches. Built addon and error produced.

Googled error and saw to remove empty turret classes, searched for all empty turret classes and removed them with the replace feature. Same error.

Code: https://pastebin.com/1vuSdhZp

![image](https://user-images.githubusercontent.com/41159450/47644813-1b3e9200-db67-11e8-96b6-423d103b5c42.png)

**Comment by 56curious** [comment]
I fixed my issue.

It seems that the orbat creator doesn't like importing units. It added, for example, O_G_Offroad_01_F instead of O_G_Offroad_01_F_OCimport_02

This meant that it had no defined classes that were then used later. Fixed it by manually adding, but being careful to match the last number with what's defined above. 

It seems to add it on some vehicles, but not others. Perhaps it's not checking it correctly? Either way, hope this helps someone else in the future, or the dev team :D

**Comment by marceldev89** [comment]
I'm guessing it was closed during issue cleanup. Manually editing the file seems a reasonable workaround until we have a fix. I'll reopen it so that it doesn't get lost. :)

**Comment by kaalund89** [comment]
thx :) i write in C# and so on.. but the arma code i havent got a insight into and we where trying to make a DK faction. so it woudt be nice if it woudt get fixed bz again i dont know the syntax my self to fix it  manually :) so hope 4 a dummy version that works whitout manually intevension :)

**Comment by MeltedPixel** [comment]
Problem Fixed.
