### ISSUE TITLE
reverse _unitAssignment still throws error because it is not an array

### ISSUE THREAD

**Issue by xetra11** [ALiVEOS/ALiVE.OS#563]
### Description

This issue still exists.
In https://github.com/ALiVEOS/ALiVE.OS/issues/528 it was mentioned to be fixed with https://github.com/ALiVEOS/ALiVE.OS/issues/546

This is the commit:
https://github.com/ALiVEOS/ALiVE.OS/commit/c5404179442439abbdde7cae0f0f8009afb72ac6

I am unsure if this guard clause really works here. No enough SQF experience. But maybe sb. should doublecheck this. The issue still exists for me and is freezing down the profiling

**Comment by marceldev89** [comment]
I'm aware it didn't fix anything. I've made some further changes but those haven't made it into a (pre-)release yet.

What we really need is something that's fairly reproducible so that we can figure out where things go wrong somewhere deep inside the profile system.

**Comment by xetra11** [comment]
Pre-Release Build 1.8.2 fixed this for **me**

**Comment by xetra11** [comment]
> Pre-Release Build 1.8.2 fixed this for **me**

False Report!

Still occurs - but took a while longer than usual

**Comment by marceldev89** [comment]
I'll be tracking all these profile data overwriting issues at #564 from now on. Closing this one. :smiley:

**Comment by xetra11** [comment]
noooOoOOoOooooo......
