### ISSUE TITLE
More randomization needs to be given to unit spawning

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#566]
### Prerequisites

* [N - custom map issue] Can you reproduce the problem using ALiVE and CBA Only?
* [Y ] Are you running the latest version of ALiVE ?
* [Y ] Are you running the latest version of CBA_A3?
* [N ] Have you attached an unbinarized SQM?
* [N ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

As per this thread http://alivemod.com/forum/4522-can-there-be-some-more-randomization-added-in-unit-spawning-to-

When spawning in an area units seem to have no real randomization as to where they're placed. This can lead to towns having huge dead spots with no civilian presence.

### Steps to Reproduce

Shown in thread

**Expected behavior:** Civilian units should spawn fairly evenly across the area

**Actual behavior:** Civilian units all spawn through the same line in town until the pop limit is hit, so the civilian population is confined to one small part of the town leaving the rest empty.

**Comment by DavisBrown723** [comment]
The Active Limiter controls how many civilians can spawn at any one time, the other civilians still exist, they're just despawned.

**Comment by NZF-JDWang** [comment]
Ok but every time I come close to either of the towns in the pictures in the thread I linked, civilians ONLY spawn at the locations in the pictures the rest of the town is completely empty.

It's like the spawn limiter kicks in, but there's always a certain area of a town that gets looked at first. so in the case of that town on FATA as soon as you're in spawn range your civ "limit" gets taken up by the civs spawning in the strip down the middle of the town and so the ones on the edges never actually spawn.

At least that's been my experience.

**Comment by DavisBrown723** [comment]
Civilians spawn by cluster, so once the cluster is activated by the spawner, it loops through all civilians who live in the area and spawns them, that's why you see the same civilians who spawn each time.

**Comment by NZF-JDWang** [comment]
That's kind of my point, in the larger towns you hit the pop limit before most of the town spawns so you end up with one a small cluster in an otherwise empty/dead town.

My suggestion is that the array has some sort of randomization or something so the x amount of civs that spawn are spread better over that cluster rather than all in the one spot all the time.

**Comment by NZF-JDWang** [comment]
After all the testing I've done on my latest mission for our unit I think this could encompass not just civilians. Having started the same mission many many times in testing it becomes obvious that the same buildings will be populated to start the mission. 

This isn't a huge deal of course because it's only the mission makers/testers who will notice this, but if you're going to look into having a little more randomness in civilian spawns then it would be nice to carry that over to all units.

**Comment by tupolov** [comment]
I've improved the civ spawn system. There was an issue where the civ spawner just despawned civs in large areas, leaving dead zones. I've also improved the spawn/despawn now so that civs spawn around players. In dev.
