### ISSUE TITLE
ALiVE Spawned unit setting over 1000 waypoints

### ISSUE THREAD

**Issue by Will-Nichols** [ALiVEOS/ALiVE.OS#568]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?

[Server RPT file](https://www.dropbox.com/s/ddb2m9rvrf5u0xc/Tanoa%20Takedown%20Crazy%20Unit%20waypoint%20numbers.rar?dl=0)

* [ ] Have you attached screenshots of the Parameters set on the offending Module?
I have not but will be doing so today. Along with the simple reproduction mission.

### Description

Have any of you guys ever seen a unit set themselves over 1,000 waypoints (still climbing BTW and server is choking to death). We saw this last weekend and one unit set itself over 13,000 waypoints and brought the server to its knees begging for forgiveness. We had 10 players on the box then. Today I am on our test box checking something and found 1 unit that spawned in via ALiVE and its setting waypoints continuously. Obviously there is a conflict somewhere with the code but I am not sure where to find it or how to eliminate it. Having used VCOM with missions for almost 2 years now this is the first time I have seen this happen but I am not sure its VCOM as nothing is in combat; I am running Fen_A3 for limited items but this unit was spawned in via ALiVE.

[Way to many waypoints; ](https://steamcommunity.com/sharedfiles/filedetails/?id=1578447612)
[more waypoints](https://steamcommunity.com/sharedfiles/filedetails/?id=1578447738)
### Steps to Reproduce

1. Start mission and players join then notice some frame drops and go into Zeus.
2. Look around map and in the left sidebar and see a unit that has waypoint numbers just climbing through the roof.
3. Attempt to kill the unit but have to wait on the server to actually let you move the mouse over and smack the unit. Then server returns to normal.

**Expected behavior:** 
Did not expect to find a unit that starts replicating waypoints like a replicator from Stargate SG1.

**Actual behavior:** 
I think the Replicators have infected the ALiVE code.

**Comment by Freddo3000** [comment]
Second link seems to be wrong

**Comment by Will-Nichols** [comment]
>           Second link seems to be wrong

Was missing an 8 off the end. Thanks for the heads up.

**Comment by DavisBrown723** [comment]
Are you only seeing this with units that have been spawned into the game world (ie. Have been spawned by a player coming in range)?

**Comment by Will-Nichols** [comment]
From what I can tell yes; it is either a player or the Zeus camera that causes them to spawn in and do this. They seem to be random entities that just go stupid with the replication of waypoints. I thought it might have been VCOM looping but according to them VCOM only generates 2 waypoints then disables waypoint creation.

**Comment by DavisBrown723** [comment]
If you ever see this again, can you check the visible waypoints for the unit and see if any of them are of type CYCLE? My first guess is maybe VCOM uses a pattern of cycle waypoints that breaks our implementation.

**Comment by Will-Nichols** [comment]
If you look at the 2nd picture there several of them are cycle waypoints but they never get to them. That is from the same unit and about 10 seconds into the server choking itself to death.

**Comment by Will-Nichols** [comment]
>           If you ever see this again, can you check the visible waypoints for the unit and see if any of them are of type CYCLE? My first guess is maybe VCOM uses a pattern of cycle waypoints that breaks our implementation.

@Freddo3000 is there a way to check that in your code? ^^^

**Comment by Freddo3000** [comment]
VCOM never generates any cycle type waypoints.

**Comment by DavisBrown723** [comment]
d29f8410793b483443c07b2e36aa4c82972113d0
