### ISSUE TITLE
Spawn on squad is not working

### ISSUE THREAD

**Issue by shult12** [ALiVEOS/ALiVE.OS#57]
Place a player unit and group some AI's to it. 
Place the multispawn module and set it on spawn on squad.
Place a marker called respawn_west.
Write respawn = 3; in the description.ext file.
Test the mission and kill yourself in the game.

Instead of respawning next to the squad, you spawn on the marker while stuck spectating one of the AI's. If you have no one in the squad, you spawn and can play.

**Comment by friznit** [comment]
The management would like to make it clear that the last repro step refers to in game activity only.  We accept no responsibility for anyone taking this instruction literally.

Thanks for the report - will try to repro and get back to you.

**Comment by HeroesandvillainsOS** [comment]
Haha! Good catch Friznit. Don't play along with this one without reading the entire instructions first. :) What's at the end might surprise you.

**Comment by highhead** [comment]
Hi!

I am sorry but I cannot replicate this:

SP -> Deathscreen as intended
MP (hosted & dedicated) -> Puts you in spectating mode, so you can switch to the AI that you want to spawn on with the ARROWKEYS, and ENTER spawns you there (BACKSPACE for spawn on respawn_west).

Please give this test mission a shot (of course vanilla to exclude any mod intercompatibility issues): http://s000.tinyupload.com/?file_id=58041905414513937150

Please replicate it in any vanilla mission (only A3, ALiVE and CBA) and upload the mission with the repro-steps so I can get in closer.
