### ISSUE TITLE
Allow more than 1 classname to call in combat support

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#570]
Just a quick QoL request. 

I normally set a long range radio pack as the "call Combat Support item". But it would be nice to put in multiple items so we can list every long range radio pack rather than just a specific one.

Ie if the item is in this array then allow combat support.

**Comment by DavisBrown723** [comment]
Are you sure this doesn't work already? I think the current implementation would happen to work with this idea.

**Comment by NZF-JDWang** [comment]
Just tested it again with 2 backpacks and the alive tablet, it doesn't matter which you have you don't have access to the combat supports if you have more than 1 classname in the field.

**Comment by DavisBrown723** [comment]
af124924282cd081499bc13b57c1b6fa328e88df

**Comment by NZF-JDWang** [comment]
Currently have 
`UK3CB_BAF_B_Bergen_MTP_JTAC_H_A, UK3CB_BAF_B_Bergen_MTP_Radio_H_A, UK3CB_BAF_B_Bergen_MTP_Radio_H_A, UK3CB_BAF_B_Bergen_MTP_SL_H_A` in our CS module and only the first backpack in the list works.

I've also tried in quotes with no joy

**Comment by NZF-JDWang** [comment]
Just realised last night the C2ISTAR module could probably use the same treatment

**Comment by DavisBrown723** [comment]
Will try to take a look in next 2 days.

**Comment by DavisBrown723** [comment]
cb180ac
