### ISSUE TITLE
Add an "Interpreter role"

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#571]
After playing the BTC Hearts and Minds mission a bit, one thing I particularly enjoy is that you have an Interpreter role (defined via a setvariable in the units init) 

This is then the only player who can get intel from civilians. 
Everyone else can shout at civs to go away, get down etc but only the interpreter can get meaningful information. This makes detaining suspicious individuals until the "terp" can get to them a thing and also just adds that extra bit of immersion.

**Comment by tupolov** [comment]
Implemented in dev along with Spyder's civilian interaction.

**Comment by NZF-JDWang** [comment]
One small change I'd like to see is instead of say a sidechat message saying you're not authorized to talk to this person, maybe change that to something along the lines of you're unable to understand them (fits better as a roleplay mechanic then) 

Also is there a way to dynamically add people to the array of players capable of talking to civilians.

We run KP ranks on a lot of our missions, and it'd be cool to be able to start a player off unable to chat to civilians but then later on in the mission when they've ranked up a fair bit enable it now they've been "in country long enough to pick up the dialect"

Great stuff though, thanks for taking on my suggestion

**Comment by tupolov** [comment]
Added rank filter in dev.

Also you can reset the array of who has access to civ interact using:

`[ALIVE_civInteractHandler, "authorized", ["Tupolov","YourName","YourRank","YourClass","YourPUID","YourFaction"]] call ALiVE_fnc_hashSet;`

**Comment by NZF-JDWang** [comment]
Don't forget the dedicated server issue (I know you won't)
