### ISSUE TITLE
When removing Combat Support, they just respawn.

### ISSUE THREAD

**Issue by MrAtomik** [ALiVEOS/ALiVE.OS#572]
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

So, I needed to delete a Combat Support unit but when I called the function, he would end up respawning again as nothing had ever happened.

### Steps to Reproduce

1. Place a Combat Support unit on the map.
2. Use `ALiVE_fnc_combatSupportRemove` to remove the combat support unit.
3. Wait...

**Expected behavior:** The unit to be gone forever.

**Actual behavior:** Respawns after the death delay.

**Comment by DavisBrown723** [comment]
b5c4b1e74ceb71c8e1d74a9163948f2feb07c059

ALiVE_fnc_combatSupportRemove now properly prevents the respective asset from respawning.
You can now also remove artillery assets. _Adding_ artillery assets will take more time to figure out what's going on with the code.

**Comment by DavisBrown723** [comment]
06b7291b59a69c76af215796b3cb4045f1aa9ab4
3ec1a2bfdfd1394be2bb044bb2c0aead7f292647

All CS Assets can now be dynamically added and removed. All removed assets will cease respawning.

**Comment by DavisBrown723** [comment]
private _pos = getMarkerPos "m3";
private _class = "B_MBT_01_arty_F";
private _callsign = "monkey";
private _unitCount = 3;
private _rounds = [["HE",30],["ILLUM",30],["SMOKE", 30],["SADARM", 30],["CLUSTER", 30],["LASER", 30],["MINE", 30],["AT MINE", 30],["ROCKETS", 30]];
private _code = "";
["ARTY", [_pos,_class,_callsign,_unitCount,_rounds,_code]] call ALiVE_fnc_combatSupportAdd;

private _pos = getMarkerPos "m2";
private _dir = 0;
private _type = "B_Heli_Attack_01_F";
private _callsign = "monkey";
private _code = "";
private _height = "0";
["CAS", [_pos,_dir,_type,_callsign,_code,_height]] call ALiVE_fnc_combatSupportAdd;

private _pos = getMarkerPos "m1";
private _dir = 0;
private _type = "B_Heli_Transport_01_camo_F";
private _callsign = "monkey";
private _code = "";
private _height = "0";
private _slingloading = false;
private _containerCount = 0;
["TRANSPORT", [_pos,_dir,_type,_callsign,_code,_height,_slingloading,_containerCount]] call ALiVE_fnc_combatSupportAdd;

["WEST","ARTY","monkey"] call ALiVE_fnc_combatSupportRemove;
["WEST","CAS","monkey"] call ALiVE_fnc_combatSupportRemove;
["WEST","TRANSPORT","monkey"] call ALiVE_fnc_combatSupportRemove;

**Comment by MrAtomik** [comment]
Hey Davis!
Thanks for this update! It is very helpful.

However, it didn't work. They still respawned. I made sure that I had the right version, because the FSM was definitely in the array.

Also, this error popped up:
`'...tArray_%1", _sideIn],[]];
{
if (isnull (_x select 0) || {((_x select 0) == _veh)...'
Error Undefined variable in expression: _x

File x\alive\addons\sup_combatsupport\scripts\NEO_radio\functions\misc\fn_RespawnTransportAsset.sqf, line 46`

Thanks!

**Comment by DavisBrown723** [comment]
Ok I tested again and I cannot reproduce any errors, each CS asset is removed forever without respawning.

Can you share the details of your testing?
    Is the CS asset pre-placed in editor or added dynamically using ALiVE_fnc_combatSupportAdd?
    Is the CS asset being killed and respawned at all before you execute ALiVE_fnc_combatSupport?

**Comment by MrAtomik** [comment]
Thanks for your help.

I did some more testing by making a basic ALiVE mission and it worked fine.
I tried it with the mods and figured out that the scenario was causing the error.
I'll take a look at it.

Thanks!

**Comment by DavisBrown723** [comment]
If it's a mod under 1GB I can download and test, if not it'll have to wait a week or so for me.

**Comment by MrAtomik** [comment]
I did some edits on that test scenario and then they came back, but now I can't appear to reproduce it.

Something I can think of is because of lag. There is a lot of processes happening when we delete the units, and the respawn function may be ran before you set the variable. Just a potential idea.

If that doesn't fix it, I don't really know. Thanks for helping.

**Comment by MrAtomik** [comment]
Alright, we did some further tests and managed to get a scenario where it would not work.
There are two screenshots also inside the .zip file for reference.

On our first test, EAGLE ONE and EAGLE TWO respawned.
On our second test, EAGLE ONE respawned.

Thanks for the help.

[removeCS.zip](https://github.com/ALiVEOS/ALiVE.OS/files/2717340/removeCS.zip)

**Comment by DavisBrown723** [comment]
Still acknowledging this issue btw, I've been sick for a week.

Thanks for the repro.

**Comment by DavisBrown723** [comment]
It's always a race condition

f14b1b713bd70e5f3354eba2a7324f3d88e8a919

Please try again once you get the chance :)
