### ISSUE TITLE
Stop using compile dynamically

### ISSUE THREAD

**Issue by dedmen** [ALiVEOS/ALiVE.OS#576]
### Prerequisites

* Arma 3 version 1.90 or older, till back when remoteExec was added.

### Description

Every string that's passed to `compile` will be kept in cache till Arma exits. Meaning for something that's only used once (like most occurences of `call compile format`) it's basically a memory leak.

See: https://feedback.bistudio.com/T135718

https://github.com/ALiVEOS/ALiVE.OS/blob/b45b1a76ec32de8b8ffb2da0cbd83cb7d937c5a5/addons/missions/MPScenarios/ALiVE_Divide_and_Rule.Altis/fnc_vehicleRespawn.sqf#L45
Should be setVariable.
https://github.com/ALiVEOS/ALiVE.OS/blob/b45b1a76ec32de8b8ffb2da0cbd83cb7d937c5a5/addons/sys_indexer/fnc_autoUpdateStaticData.sqf#L37
getVariable.
https://github.com/ALiVEOS/ALiVE.OS/blob/b45b1a76ec32de8b8ffb2da0cbd83cb7d937c5a5/addons/sys_logistics/fnc_setObjectCargo.sqf#L58
Just use a if statement. That's also much faster than call compile.

**Comment by TheNightstalk3r** [comment]
On it ^^

**Comment by marceldev89** [comment]
See https://github.com/ALiVEOS/ALiVE.OS/pull/583 :wink:

**Comment by DavisBrown723** [comment]
For future reference, the compile cache will be removed as of the next Arma update. All strings will be compiled without caching - meaning longer compile times for repeat strings.

**Comment by dedmen** [comment]
>meaning longer compile times for repeat strings.

Back to how it was early 2017 when everyone was told to not use call compile format for things because it's slow. Currently it causes memory leak, in a couple weeks it will go back to slow.

**Comment by tupolov** [comment]
FIXED https://github.com/ALiVEOS/ALiVE.OS/commit/07cddd1334f496ab6629c0c2931158efc43e6ede
