### ISSUE TITLE
Feature Request - Civilian "hotspot" module

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#577]
There was talk a while back about having civilians gather in crowds etc. 

One thing I've always found missing was a busy marketplace. Being able to place a module down and have a higher concentration of civilians there during the daytime would allow mission makers to create some atmospheric situations.

A busy market place, or even perhaps unhappy civilians gathering outside a dictator's palace or government building. Just some way of having the civs gravitate there, linger for a while and then go about their day. A module similar to the vanilla civilian module which has the x and y values so you can set a zone for gathering would be really amazing. Bonus points if the module included a "time of day" option when it would be active. This could also work as a Call To Prayer style gathering method.

Also a perfect place for suicide bombers to strike? Maybe civilians gathering to receive supplies from IDAP trucks.  I'm sure there are countless uses.

You could go one step further and have civilians disperse/flee (the module essentially turn off for a time) when weapons are fired in the vicinity?

**Comment by NZF-JDWang** [comment]
Just as an aside I tried doing something with the new vanilla civilian spawning modules. They have the small waypoint module that you can set as a spot for the civs to go to and will act as a waypoint and or potential cover. 

it seems to work ok apart from the fact the civilians just walk there, and then move on. If they lingered there for

**Comment by TheNightstalk3r** [comment]
if you can already do it with default BIS modules, AliVE modules would basically be redundant as it already exists and needs to be pre-placed as you described?

Though it may not benefit from the caching system of AliVE.

**Comment by tupolov** [comment]
Completed in dev
