### ISSUE TITLE
Add option to disallow diary entries when creating a SPOTREP

### ISSUE THREAD

**Issue by xetra11** [ALiVEOS/ALiVE.OS#579]
### Description

When creating a SPOTREP it will be automatically added to the diary. When removing the SPOTREP it will not disappear from the diary. Since diary entries cannot be removed by default it should at least be possible to have a checkbox in the SPOTREP to disallow diary entries.

### Steps to Reproduce

1. Create a SPOTREP
2. Remove it
3. Check diary and be sad

**Expected behavior:**
When creating a SPOTREP I want to have the option to allow/disallow a diary entry out of it.

**Actual behavior:**
There will always be a diary entry added when creating a SPOTREP

**Comment by DarrellJMartin** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/9baec23e2d6152a0ecce7e8e83aca8c5bcbe65cc
![spotrep](https://user-images.githubusercontent.com/8157728/53251514-baf2d380-36b4-11e9-91c5-9907939f362d.jpg)

**Comment by xetra11** [comment]
Thanks a heap buddy!
Will make the integration with ALiVE one step more beautiful

**Comment by DarrellJMartin** [comment]
Yeah sure. I was going to put the boolean option in the marker's ctrl panel but thought it better to put it in the C2istar module params.
