### ISSUE TITLE
Length of line of data.mapname.sqf exceeds limit

### ISSUE THREAD

**Issue by bradon** [ALiVEOS/ALiVE.OS#580]
For a map with sufficiently large clusters, the length of a line can become too large and be truncated.
See #498 for a related issue and its fix.

Reproduced on nam2. Not reproduced on any other map so far.

**Comment by bradon** [comment]
Presumably, this is a limit related to how much we pass back from the extension

**Comment by tupolov** [comment]
Is this fixed? @bradon

**Comment by bradon** [comment]
No, I've only ever seen it on nam2 (and fixed the map manually, not too much was lost).
If its rare enough i don't see it as a priority. I set this issue up to see if we would get any extra reports of it happening (which would make it more of a priority).

I'm happy to give it a go fixing it if its wanted, but unless its a recurring issue wontfix might be appropriate.

**Comment by bradon** [comment]
Have not yet found a recurrance
