### ISSUE TITLE
Continuous 'Generic Error in Expression' Errors while playing in SP

### ISSUE THREAD

**Issue by Igneous01** [ALiVEOS/ALiVE.OS#582]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only? **yes**
* [x] Are you running the latest version of ALiVE ? **yes**
* [x] Are you running the latest version of CBA_A3? **yes**
* [x] Have you attached an unbinarized SQM? **yes**
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)? **yes**
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

I keep getting this error repeatedly in alive missions that I play in SP. I am only running CBA and ALiVE mods and I still get this error. It seems to cause less units to spawn and appears to be random.

### Steps to Reproduce

Load my mission file in editor. 

Attack an objective like Agios Dionysios

Errors begin to appear once units are being spawned into the zones (~10 minutes in for me)

**Expected behavior:** [What you expected to happen]

No errors being thrown. Units to be spawning.

**Actual behavior:** [What actually happened]

Few units appear to be spawning aside from the units from the CQB module.

This error keeps repeatedly appearing in rpt.

23:07:48   Error position: <select 1;
call compile _onCompletion;
};>
23:07:48   Error Generic error in expression
23:07:48 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
23:07:48 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>

RPT
[Arma3_x64_2019-01-28_23-23-14.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2806300/Arma3_x64_2019-01-28_23-23-14.txt)

Mission.sqm (RENAME .txt to .sqm)
[mission.txt](https://github.com/ALiVEOS/ALiVE.OS/files/2806301/mission.txt)

**Comment by marceldev89** [comment]
@DavisBrown723

**Comment by tupolov** [comment]
@marceldev89 did you fix this?

**Comment by marceldev89** [comment]
Yes I believe so, see https://github.com/ALiVEOS/ALiVE.OS/commit/36ab9e42295e63d3a2003179c9c352802c2a0069.
