### ISSUE TITLE
ALiVE_Mil_Logistics causing Headless client bugs and profile simulator is failing.

### ISSUE THREAD

**Issue by diveyez** [ALiVEOS/ALiVE.OS#587]
### Prerequisites

* [ x] Can you reproduce the problem using ALiVE and CBA Only?
* [x ] Are you running the latest version of ALiVE ?
* [x ] Are you running the latest version of CBA_A3?
* [ no] Have you attached an unbinarized SQM?
* [paste ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ no] Have you attached screenshots of the Parameters set on the offending Module?

### Description

ALiVE_Mil_logistics causing errors with profile simulator.

### Steps to Reproduce
Launch a mission with those modules in it, and watch the errors in RPT.

### Log:

2019/02/27, 22:43:10 ALiVE [m_24|190] Module ALiVE_mil_logistics INIT COMPLETE TIME:  88.1361
2019/02/27, 22:43:10 ALiVE [m_25|190] Module ALiVE_mil_logistics INIT COMPLETE TIME:  88.135
2019/02/27, 22:43:21 NetServer: trying to send a too large non-guaranteed message (len=1348/1356) to 1678849477
2019/02/27, 22:43:21 Message not sent - error 0, message ID = ffffffff, to 1678849477 (hc1)
2019/02/27, 22:43:21 NetServer: trying to send a too large non-guaranteed message (len=1348/1350) to 1216794069
2019/02/27, 22:43:21 Message not sent - error 0, message ID = ffffffff, to 1216794069 (SOCM R. Neff)
2019/02/27, 22:43:21 NetServer: trying to send a too large non-guaranteed message (len=1348/1351) to 1678849477
2019/02/27, 22:43:21 Message not sent - error 0, message ID = ffffffff, to 1678849477 (hc1)
2019/02/27, 22:43:21 NetServer: trying to send a too large non-guaranteed message (len=1348/1357) to 1216794069
2019/02/27, 22:43:21 Message not sent - error 0, message ID = ffffffff, to 1216794069 (SOCM R. Neff)
2019/02/27, 22:43:21 NetServer: trying to send a too large non-guaranteed message (len=1348/1357) to 1216794069
2019/02/27, 22:43:21 Message not sent - error 0, message ID = ffffffff, to 1216794069 (SOCM R. Neff)
2019/02/27, 22:43:21 NetServer: trying to send a too large non-guaranteed message (len=1348/1351) to 1678625398
2019/02/27, 22:43:21 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1349) to 1678625398
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1354) to 1678849477
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678849477 (hc1)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1350) to 1678625398
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1354) to 1678849477
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678849477 (hc1)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1349) to 1678625398
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1351) to 1678625398
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1352) to 1678625398
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:22 NetServer: trying to send a too large non-guaranteed message (len=1348/1349) to 1678625398
2019/02/27, 22:43:22 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:24 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:24   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:24   Error Generic error in expression
2019/02/27, 22:43:24 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:24 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:24   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:24   Error Generic error in expression
2019/02/27, 22:43:24 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:26 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:26   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:26   Error Generic error in expression
2019/02/27, 22:43:26 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:26 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:26   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:26   Error Generic error in expression
2019/02/27, 22:43:26 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:29 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:29   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:29   Error Generic error in expression
2019/02/27, 22:43:29 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:29 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:29   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:29   Error Generic error in expression
2019/02/27, 22:43:29 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:33 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:33   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:33   Error Generic error in expression
2019/02/27, 22:43:33 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:33 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:33   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:33   Error Generic error in expression
2019/02/27, 22:43:33 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:35 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:35   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:35   Error Generic error in expression
2019/02/27, 22:43:35 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:35 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:35   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:35   Error Generic error in expression
2019/02/27, 22:43:35 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:39 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error Generic error in expression
2019/02/27, 22:43:39 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:39 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error Generic error in expression
2019/02/27, 22:43:39 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:39 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error Generic error in expression
2019/02/27, 22:43:39 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:39 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:39   Error Generic error in expression
2019/02/27, 22:43:39 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1357) to 1678625398
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1353) to 1678830971
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678830971 (hc3)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1356) to 1678849477
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678849477 (hc1)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1351) to 1678625398
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1356) to 1678830971
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678830971 (hc3)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1351) to 1678849477
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678849477 (hc1)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1349) to 1216794069
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1216794069 (SOCM R. Neff)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1349) to 1678625398
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1355) to 1678849477
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678849477 (hc1)
2019/02/27, 22:43:39 NetServer: trying to send a too large non-guaranteed message (len=1348/1357) to 1678625398
2019/02/27, 22:43:39 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:40 NetServer: trying to send a too large non-guaranteed message (len=1348/1350) to 1678625398
2019/02/27, 22:43:40 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:40 NetServer: trying to send a too large non-guaranteed message (len=1348/1355) to 1678625398
2019/02/27, 22:43:40 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:41 NetServer: trying to send a too large non-guaranteed message (len=1348/1349) to 1678625398
2019/02/27, 22:43:41 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:41 NetServer: trying to send a too large non-guaranteed message (len=1348/1356) to 1678830971
2019/02/27, 22:43:41 Message not sent - error 0, message ID = ffffffff, to 1678830971 (hc3)
2019/02/27, 22:43:41 NetServer: trying to send a too large non-guaranteed message (len=1348/1357) to 1678625398
2019/02/27, 22:43:41 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:41 NetServer: trying to send a too large non-guaranteed message (len=1348/1354) to 1678830971
2019/02/27, 22:43:41 Message not sent - error 0, message ID = ffffffff, to 1678830971 (hc3)
2019/02/27, 22:43:41 NetServer: trying to send a too large non-guaranteed message (len=1348/1353) to 1678625398
2019/02/27, 22:43:41 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:41 NetServer: trying to send a too large non-guaranteed message (len=1348/1350) to 1678830971
2019/02/27, 22:43:41 Message not sent - error 0, message ID = ffffffff, to 1678830971 (hc3)
2019/02/27, 22:43:41 NetServer: trying to send a too large non-guaranteed message (len=1348/1351) to 1678625398
2019/02/27, 22:43:41 Message not sent - error 0, message ID = ffffffff, to 1678625398 (hc2)
2019/02/27, 22:43:46 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error Generic error in expression
2019/02/27, 22:43:46 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:46 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error Generic error in expression
2019/02/27, 22:43:46 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:46 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error Generic error in expression
2019/02/27, 22:43:46 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184
2019/02/27, 22:43:46 Error in expression <n {
private _onCompletion = _statements select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error position: <select 1;
call compile _onCompletion;
};>
2019/02/27, 22:43:46   Error Generic error in expression
2019/02/27, 22:43:46 File \x\alive\addons\sys_profile\fnc_profileSimulator.sqf [ALiVE_fnc_profileSimulator], line 2184

**Comment by xetra11** [comment]
Had the same - I think the last Release Client blocked those error printings but the issue still exists as far as I understood. Will be fixed soon - but should not conflict with anything

**Comment by DavisBrown723** [comment]
The profile sim issue has already been addressed with the latest pre-release. I also don't see any references to mil logistics errors.
