### ISSUE TITLE
Feature Request: CQB Static Weapons Spawn Distance

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#588]
**The Issue:**

Static weapons are currently tied to the CQB module and the spawn distance is the same as infantry. The problem with this is that static weapons (mortars, MGs, etc) have a much longer range than assault rifles and the like. Players in our sessions often have mortars and .50 cal turrets destroying them at close range. Any type of long-range recon is also not possible on these emplacements because players need to be so close to get them to spawn with the rest of CQB AI. It would be nice to call airstrikes on these emplacements to destroy them before players go marching into towns and the whole thing becomes active.

**The Suggestion:**

Create the ability to configure the spawning of CQB static emplacements separately from infantry. It can still be in the same module, but would be nice for better control and more realistic defense of towns utilizing these weapons. In my specific case, I often set the spawn radius for CQB around 500-700 meters depending on the scenario. Sometimes it's much less on larger city maps. Would be awesome to have the turrets be around 1200 meters for example. This would also create potentially awesome scenarios where the first thing engaging players in a town would be the static weapons, then the garrison force as you draw closer.

**Comment by marceldev89** [comment]
Agreed, that's how it should be. :smile:

**Comment by marceldev89** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/1f659a8c695f20c628e9f535931a0946869aafe6 done (but untested)! :)

**Comment by Vegas** [comment]
@marceldev89 You rock dude! Appreciate your time and thanks for the hard work. o7
