### ISSUE TITLE
[Military Logistics] Disable reinforcements by helicopter / force airdrop

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#59]
There's currently no way to disable reinforcements by helicopter (or any other method of insertion for that matter). Having helicopters inserting reinforcements during a WW2 era mission is a huge immersion killer...

**Comment by HeroesandvillainsOS** [comment]
It's sort of a buzzkill in Army versus Taliban missions too when I make them conventional rather than Assymetric. This is a good request.

**Comment by friznit** [comment]
@tupolov as previously discussed in #8 .  

> Add a filter to disable selected logistics transport types (airdrop, convoy, insertion). E.g. As a user, I want to disable heli insertion for immersion reasons in scenarios that don't have helicopters such as WW2.

Set Heli Reinforcment to No only prevents new Helis being introduced as BCRs.  It does not prevent transport helis being used to insert troops or sling load light vehicles.  We need to be able to disable the reinforcement delivery type as well as the object type being delivered.

**Comment by tupolov** [comment]
Limiting resupply assets to faction should help address this.

**Comment by friznit** [comment]
Still having issues reported on our forum that helis are not being disabled correctly.  Keeping this open for further testing.

**Comment by marceldev89** [comment]
Code seems to be fine, do you have links to those threads?

**Comment by friznit** [comment]
http://alivemod.com/forum/1859-heli-not-despawning-fixed/3#p14451

For example

**Comment by marceldev89** [comment]
Alright, that's most likely caused by the static faction mappings since I think that all RHS factions have a helicopter defined in their mappings. IMO it's probably best to add another option to the module to disable it all the way.

**Comment by tupolov** [comment]
There was a bug where heli's were not being limited to faction, that is now fixed.

Selecting no to heli resupply in the mil logistics module will also stop heli resupply.

**Comment by HeroesandvillainsOS** [comment]
Awesome! Thanks Tupolov!
