### ISSUE TITLE
vr_staticData.sqf not found

### ISSUE THREAD

**Issue by LVIThN** [ALiVEOS/ALiVE.OS#590]
### Prerequisites

* [Yes ] Can you reproduce the problem using ALiVE and CBA Only?
* [Yes] Are you running the latest version of ALiVE ?
* [Yes] Are you running the latest version of CBA_A3?
* [Yes ] Have you attached an unbinarized SQM?
* [Yes ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [Yes ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Script x\alive\addons\main\static\vr_staticData.sqf not found

### Steps to Reproduce

1. Place down down NATO unit
2. Place down ORBAT module
3. Play

**Expected behavior:** To go straight into the Tool.

**Actual behavior:** Got a pop-up. 

[ALiVE_Report.zip](https://github.com/ALiVEOS/ALiVE.OS/files/2960174/ALiVE_Report.zip)

**Comment by marceldev89** [comment]
If it breaks the ORBAT module then you can create that file in your mission folder (including the path). If not, feel free to ignore. There's not much point for VR to have a staticData file since it's an empty map. :)

**Comment by LVIThN** [comment]
Not really a bother to me. Didn't effect the ORBAT functions as far as I could tell. Never had it pop up before so thought I would just let ya know it exists. So on my end, I shall ignore haha

**Comment by marceldev89** [comment]
:+1:, I'll close this one then.
