### ISSUE TITLE
Feature Request - Ability to turn off MACC in sidechat

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#591]
Currently working on a mission where my players are working alongside another BLUFOR faction. I've given that faction a MACC so they can conduct helicopter CAS etc, but the constant sidechat makes me want to just remove it.

The feedback is cool, but there needs to be an off switch.

**Comment by marceldev89** [comment]
I've put all ATO messages behind a switch (at the bottom of the module settings) except for the initialization messages at mission start.
