### ISSUE TITLE
Update alivemod.com link and Steam Workshop Entry

### ISSUE THREAD

**Issue by HomebrewCocaine** [ALiVEOS/ALiVE.OS#594]
Current alivemod.com link and Steam Workshop entry push out version 1.7.0.1807121.

**Comment by marceldev89** [comment]
The download on our website is outdated for sure but the workshop version is fine. https://steamcommunity.com/sharedfiles/filedetails/?id=620260972

**Comment by tupolov** [comment]
Fixed
