### ISSUE TITLE
Identified Civilian and Enemy Spawn Issue

### ISSUE THREAD

**Issue by diveyez** [ALiVEOS/ALiVE.OS#596]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [_] Have you attached an unbinarized SQM?
* [_] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [_] Have you attached screenshots of the Parameters set on the offending Module?

### Description

If a map is improperly indexed, when using ALiVE the AI spawning will spawn 1 unit into a building it cannot enter or exit, and then the functions will fail entirely.

### Steps to Reproduce

Use alive on linogor, this is where I found it to happen first.

**Expected behavior:** Ignore buildings units cannot enter or exit

**Actual behavior:** It placed 1 enemy group in a building they cannot enter or exit, along with one civilian, and then stopped spawning other units.

**Comment by marceldev89** [comment]
This is an index issue and not something we should be handling during runtime. The point of the index is that we don't have to scan the map during runtime causing performance issues. Either volunteer to reindex the map or wait until someone has a personal interest to do so. We can't possibly maintain all the maps that we have indexes for.

As a side note, spawning units in non enterable buildings shouldn't cause any issues related to scripting, the unit will just do nothing but that's about it.
