### ISSUE TITLE
Feature Request - Add field for static weapon classes to CQB module

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#597]
Currently the CQB module only spawns vanilla statics which means if you're anything like me you'll almost never use that feature. What's more you have no control over the types of statics that spawn.

Instead how about a field in the CQB module where you can add the classnames of the static weapons you'd like to spawn. That way not only should modded statics be able to be spawned, but you can control the type (eg you may only want MGs not GMGs or mortars)

**Comment by DavisBrown723** [comment]
cd3a1a1d6feecff1e8dcaaadb0f05ba1dadfece4

**Comment by DavisBrown723** [comment]
Tested with no errors on my end.
Testing PBO if needed: https://www.dropbox.com/s/8htljqqksq0b1ml/%40alive.zip?dl=0
