### ISSUE TITLE
Player Combat Logistics module delivering empty ammo boxes or crashing helicopter

### ISSUE THREAD

**Issue by Borattata** [ALiVEOS/ALiVE.OS#598]
### Prerequisites

* [ Y] Can you reproduce the problem using ALiVE and CBA Only?
* [ Y] Are you running the latest version of ALiVE ?
* [ Y] Are you running the latest version of CBA_A3?
* [ Y] Have you attached an unbinarized SQM?
* [ Y] Have you attached your RPT (If the issue relates to data, also attach Server RPT and ALiVE Plugin Log)?
* [ N/A] Have you attached screenshots of the Parameters set on the offending Module?

### Description

SQM file here: https://pastebin.com/3y8CJGz3
RPT file here: https://pastebin.com/zuEU3x88

I have found either a bug or a set of bugs related to the Player Logistics and Player Combat Logistics modules. I am new to ALiVE so I've been unable to deduce if this is a single bug or multiple bugs. This is the behavior I am seeing:

1. When ordering combat supplies via helicopter insertion small enough not not require sling loading, I am unable to unload the combat supplies from the helicopter.
2. When ordering combat supplies via helicopter insertion large enough to require sling loading, I am unable to unload the combat supplies from the box that is delivered.
3. When ordering combat supplies via air drop, I am unable to unload the supplies from the box that is delivered.
4. When ordering combat supplies via road transport, I am unable to unload the supplies from the vehicle that is delivered.
5. When ordering combat supplies via helicopter insertion while all Player Logistics are disabled, the helicopter spawns and the crew and supplies box are immediately ejected. The helicopter crashes, then the crew somehow survives the fall and proceeds to the designated position on foot, at which point I receive a message that the supplies are delivered and the crew despawns.

### Steps to Reproduce

To reproduce bugs 1-4:
1. Load the .sqm I have linked via pastebin above.
2. Activate logistics actions via Player Options -> Activate Logistics Actions.
3. Go to Commander Actions -> Logistics, and order supplies according to the parameters below.
4. Wait for supplies to arrive.
5. Attempt to use the action "Load out cargo" on the vehicle or ammo box that is delivered.
6. Observe that no supplies or boxes are unloaded.

Supplies parameters to reproduce bugs as described under Description:
Bug 1: Order air lift via helicopter, Combat Supplies -> Ammo -> Basic Ammo [NATO], 1 unit.
Bug 2: Order air lift via helicopter, Combat Supplies -> Ammo -> Basic Ammo [NATO], 39 units.
Bug 3: Order air drop by transport plane, any Combat Supplies units.
Bug 4: Order resupply via road transport vehicles, any Combat Supplies units.

Bug 5 is harder to reproduce, as you have to be able to see the helicopter when it spawns and this is difficult to pull off because the spawn location seems to be non deterministic.
1. Using the .sqm I provided, open the editor and add a Player Logistics (disabled) module.
2. Set the Player Logistics (disabled) module to disable everything.
3. Start the scenario.
4. Order any supplies by helicopter.
5. Once you get a message saying "units are on way to destination", in the Logistics tablet screen click show status, select the request, and click show details. Observe where the yellow "Request Location" circle is.
6. Enable teleporting via Admin Actions > Enable Teleporting.
7. Teleport yourself to the yellow circle by clicking there on the map as accessed via the "M" key.
8. Look around for the smoking wreck, this will help you know approximately where the next helicopter will spawn.
9. Order helicopter inserted supplies to the same location as before.
10. Watch the sky for the helicopter to spawn. (It may not be exactly the same location as the prior one, but it's usually in sight)
11. Observe as the crew falls and the helicopter crashes.
12. Wait for the crew to arrive on foot to the destination and you will receive a "supplies delivered" message.

**Expected behavior:** In all cases, I expected to receive supplies that I could unload and use.

**Actual behavior:** The supplies were either unloadable, or the helicopter delivering them crashed.

**Comment by tupolov** [comment]
Fixed in dev.
