### ISSUE TITLE
Player Logistics actions show up in menu but don't work

### ISSUE THREAD

**Issue by armatourist** [ALiVEOS/ALiVE.OS#599]
### Prerequisites

* [ x] Can you reproduce the problem using ALiVE and CBA Only?- YES/PARTIALLY YES: Hurt Locker with a few 3DEN Mods active, but Getting Started: APEX with ALiVE+CBA only
* [ x] Are you running the latest version of ALiVE ? - YES
* [x] Are you running the latest version of CBA_A3? - YES
* [x ] Have you attached an unbinarized SQM? - NO, because I tested with ALiVE showcase missions
* [ x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)? - YES, and it's intentional that it is SP because before the upate, player logistics did work in SP
* [ x] Have you attached screenshots of the Parameters set on the offending Module? - NO, because this feature works by default unless the module is placed which disables it

### Description

Just as it says in the title: Player logistics shows the actions, but they don't do anything.  

### Steps to Reproduce

1. [First Step] - Activate the player logistics once ingame
2. [Second Step] - walk over to an ammobox and choose "carry object"
3. [and so on...] - observe if the box gets lifted by player character

**Expected behavior:** [What you expected to happen]

Ammobox floats in front of player character; moves with him

**Actual behavior:** [What actually happened]

Ammobox stays on the floor. 
[tourist_player_logistics_not_working_Hurt_Locker_SP.zip](https://github.com/ALiVEOS/ALiVE.OS/files/3077938/tourist_player_logistics_not_working_Hurt_Locker_SP.zip) 
[tourist_player_logistics_not_working_Geting_started_apex.zip](https://github.com/ALiVEOS/ALiVE.OS/files/3077943/tourist_player_logistics_not_working_Geting_started_apex.zip)

**Comment by marceldev89** [comment]
Should be fixed in next release with https://github.com/ALiVEOS/ALiVE.OS/commit/be5a37b00c309ff1e6d02a9902634e911dafcd7f.
