### ISSUE TITLE
[Suggestion] Separate hostility values in different Civ Pop areas

### ISSUE THREAD

**Issue by xetra11** [ALiVEOS/ALiVE.OS#607]
While reading through the new CIV POP updates I was wondering if it might be possible to add like a hostility count to certain location rather than the whole civ faction?

Maybe you can have like a faction wide hostility which increases/decreases very slowly and one per location/area or whatever which increases/decreases very fast since they get "personally" affected.

**Comment by DavisBrown723** [comment]
Hostility is already separated per cluster.
