### ISSUE TITLE
Feature Request - Call to Prayer

### ISSUE THREAD

**Issue by Rockfrog** [ALiVEOS/ALiVE.OS#608]
Loving the integration of Spyder Addons civilian interaction to the core ALiVE build, great stuff.

If possible, would be great to also add in the Call to Prayer functionality?  Is one of the most immersive features the players in our realism unit comment on every time they see and hear it.  Would be great to include it into the recent civilian 'realism & immersion' focus of the core mod.

**Comment by marceldev89** [comment]
I'm fairly sure call to prayer was included with the all the civilian improvements in the last update. :smile:

**Comment by DavisBrown723** [comment]
It iwas definitely added.

**Comment by friznit** [comment]
Yes
