### ISSUE TITLE
Please upload the optional PBO's to the workshop as seperate addons

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#614]
Because of the way Steam works if I add in the optional PBO's steam keeps trying to "fix" the install back to original.

If the optional PBO's are uploaded separately then they can be subscribed to and added/removed easily without Steam constantly trying to "fix" things.

**Comment by friznit** [comment]
There's nothing to stop you hosting them on a private (friends only) Steam workshop item.  That how I manage stuff for VCB - all the optional stuff from various mods like ACE & ALiVE go into a single folder together with a few other custom bits and bobs.  Saves mucking around with it every time a mod is updated.

**Comment by diveyez** [comment]
ALiVE.OS os opensource, make a copy, and host by yourself.

**Comment by friznit** [comment]
> ALiVE.OS os opensource, make a copy, and host by yourself.

Not quite - open source doesn't mean the license grants free unhindered redistribution (and in this particular case the Steam workshop T's & C's are actually more restrictive than CC).  All that notwithstanding I'd rather not have a second copy of any part of ALiVE publicly available on the Steam Workshop - it just complicates thing unnecessarily.  There's absolutely nothing to stop people hosting it in a private/friends only collection though and in fact I would encourage that approach.

**Comment by diveyez** [comment]
A solid and fair response. Can count on friznit to bring realism to the workshop and git discussions.
