### ISSUE TITLE
Idea for possibly persisting civilians 

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#615]
Currently when profiled, a unit is deleted and then recreated when unprofiled. This makes it almost (if not completely) impossible to persist units. Eg civilian names change, units with wounds are unwounded etc. You can't "get to know" the locals.

What if instead of deleting the unit when profiled, you left it where it was, disabled model, sim and anything else you need to? The when it's "unprofiled" you don't create a brand new unit but instead setpos the old unit and reenabled model/sim etc?

Some of the best game play we've had with ALiVE insurgencies is when we get intel on certain civilians being up to no good. This would allow proper persistence of civilians and enable manhunts that could last weeks.

This would also allow mission makers to create leaders/warlords/generals that could be profiled and yet still hunted by the players and still easily checked for with an !alive trigger.

I have no idea how to test how much difference in performance that would cost, but I do know the vanilla simulation manager works very well.

**Comment by DavisBrown723** [comment]
> units with wounds are unwounded
Just a headsup, we do persist unit/vehicle damages through spawn/despawn

**Comment by DavisBrown723** [comment]
Initial testings show promise. A more comprehensive analysis of how this will perform when integrated into ALiVE would need to be tested before making any final judgements.

`[] spawn {

	private _randomWorldPos = {
		[0 + (random worldsize), 0 + (random worldsize)]
	};

	private _groups = [];
	private _units = [];

	for "_i" from 1 to 100 do {
		private _group = createGroup west;
		private _groupUnits = [];

		for "_j" from 1 to 5 do {
			private _unit = _group createUnit ["B_RangeMaster_F", call _randomWorldPos, [], 0, "FORM"];
			_groupUnits pushback _unit;
		};
		
		_groups pushback _group;
		_units append _groupUnits;
		
		systemchat format ["Created Group: %1", _i];
	};
	
	{
		private _unit = _x;
		
		_unit allowDamage false;
		_unit hideObjectGlobal true;
		_unit disableAI "ALL";
		_unit enableSimulationGlobal false;
	} foreach _units;

	systemchat "Script Finished";

};`

**Comment by DavisBrown723** [comment]
Unfortunately, this really has no viability within ALiVE due to the fact that Arma has a unit limit of 1436. ALiVE can easily breach these values (if profiles are left unspawned) and thus this method does not scale in the manner we need.
