### ISSUE TITLE
Virtual Combat Support 

### ISSUE THREAD

**Issue by SanchezMilsim** [ALiVEOS/ALiVE.OS#616]
Sometimes maps dont have runway to use plane CAS or Helicopter CAS. Would be nice an option to make it virtual like vanilla support modules, and can include a delay before the aircraft spawn in module to simulate it come from far base.

Thanks!!

**Comment by friznit** [comment]
This is not in scope of ALiVE Combat Support - one of the principles of ALiVE is where possible to avoid "magic spawns."  Players (and AI) need to be able to overrun an airfield and destroy assets on the ground, which they can't do if they're virtual.

Helicopters don't need a runway.

There are several good mods that provide a virtual air support capability.
