### ISSUE TITLE
persist acre radios by base class

### ISSUE THREAD

**Issue by TomTucka** [ALiVEOS/ALiVE.OS#621]
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [X] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

users use player exit, next time they join the server certain players have issues and they can't here people on radios

### Steps to Reproduce

1. Player exit with ACRE radios in inventory
2. Rejoin
3. Try to use radios

**Expected behavior:** Radios work as normal
**Actual behavior:** Intermittent radio issues for players (normally fixed by getting a fresh radio)

RPT: https://gist.github.com/TomTucka/f35ae181759c81fa5933b4c025861f54
Chat with ACRE dev: https://i.gyazo.com/5434b3b32687e15e43f8a7f5f0e7a607.png

**Comment by bradon** [comment]
Relevant acre functions:
acre_api_fnc_getBaseRadio
acre_api_fnc_isRadio
are api: http://acre.idi-systems.com/api/api_general.html

Relevant ALiVE file:
master/addons/sys_player/playerData.hpp
