### ISSUE TITLE
War Room stats frozen 48+ Hours

### ISSUE THREAD

**Issue by diveyez** [ALiVEOS/ALiVE.OS#624]
@aliveserver is present, loaded, however the war room has not been updated for 2 days.
I checked my API link, there is no new activity for some reason: http://alivemod.com/api/clanfeed?id=nswdgus

Is this a local or global issue, if local, how do I debug the aliveserver .dll to find out why its not sending to war-room, or the API?

**Comment by marceldev89** [comment]
The last recorded event in that feed is timestamped with `2019-06-17 06:41:45` (UTC probably). Is it still outdated or did it update sometime between you posting and me reading it?

**Comment by diveyez** [comment]
I guess its lagged up, cause that was yesterday and nothing from today posted. Closing issue.
