### ISSUE TITLE
ALIVE Profile Handler - Un-Registering vehicle profiles after player enters!

### ISSUE THREAD

**Issue by AHamburgler** [ALiVEOS/ALiVE.OS#626]
http://alivemod.com/forum/4783-alive-profile-handler-un-registering-vehicle-profiles-after-pla/0#p27090

**Comment by DavisBrown723** [comment]
Fixed via https://github.com/ALiVEOS/ALiVE.OS/commit/e633129b61baffbd1d65d2cb79822092c58f7aff
