### ISSUE TITLE
Kujari index faulty

### ISSUE THREAD

**Issue by diveyez** [ALiVEOS/ALiVE.OS#631]
I spoke with temppa and we can mutually agree the index for kujari is faulty. No civilian placements, have not checked military placements

**Comment by bradon** [comment]
Is it the pre-release index linked on the Kujari steam workshop page you are having issues with, or the current version in ALiVE?

**Comment by bradon** [comment]
Re-tested the [pre-release version](https://github.com/bradon/ALiVE.OS/releases/tag/kujari_reindex_test_0) index in SP and had no issues

**Comment by diveyez** [comment]
I swapped out the index, and started messing with it today, I could not for the life of me get my own index to work with that map neither.
Previously it was your index bro. It is not working at all, and when it does decide to try, the units spawn below seal level? This is the strangest behavior I have seen on ALiVE civ_placement

I rolled back my alive version to the workshop version but I think it just needs a patch from dev branch TBH.

If you have a NON-FAILING packed version of A.OS please send a link and I will try to use it and see if this is resolved.

**Comment by bradon** [comment]
I'm still unable to reproduce the problem unfortunately. We need to find how to reproduce the problem before we can have a crack at fixing it.

Here's how I am testing:
- I run the workshop version of ALiVE, CBA_A3, CUP Terrains Core, Kujari
- I put the pre-release index into a mission on Kujari (here's a [prepared test](https://github.com/bradon/ALiVE.OS/releases/download/kujari_reindex_test_0/kujaritest.tem_kujari.zip))
- I fly around in zues/tp around looking for issues ([here's what i see on my end](https://youtu.be/RPgn0MoCMiM))

I've tested in both single-player and on a dedicated server.

**Comment by HeroesandvillainsOS** [comment]
@Diveyez to test an index when it’s not included in an ALiVE download, all you need to do is put the index’s X folder inside your mission root folder. Have you done that or used @bradon ‘s “prepared test” which I’m assuming already has the index included?

**Comment by HeroesandvillainsOS** [comment]
The test mission above works ok for me.

**Comment by diveyez** [comment]
I am using your index now, a little buggy. Should make them indexes ignore some of the buildings temppa used.

**Comment by bradon** [comment]
I'll note it as needing a full reindex (I did an index without recategorization, which gets it to a playable state but isn't ideal). You mention you gave it a go indexing? If you feel you did a more thorough job, upload the index somewhere and give me a link and we'll use yours :) (alternatively, submit a pull request with your index)

**Comment by diveyez** [comment]
https://github.com/ALiVEOS/ALiVE.OS/pull/644
