### ISSUE TITLE
[Feature Request] Livonia support

### ISSUE THREAD

**Issue by Explodie** [ALiVEOS/ALiVE.OS#633]
The new DLC first contact map "Livonia" is an exceptional map.

I'm ridiculously new to ALiVE and have been working through the tutorials to create a mission. The mission I'm trying to create though is on Livonia, not on Altis and as it's a new map there's no config for it. I see there's some way to index a map but after a few hours of stuffing around have decided to ask for assistance.

Has anyone indexed the map yet?

The error produced when trying to use the map currently (as there's no map data of course) is 

x\alive\addons\main\static\enoch_staticData.sqf not found.

**Comment by LaocheXe** [comment]
http://alivemod.com/wiki/index.php/Map_Indexing

Until they add it

**Comment by bradon** [comment]
Unless BI released contact in a different way to usual, indexing for Livonia will need to be done by someone on our team. Having the maps as ebo's complicates things.

**Comment by DavisBrown723** [comment]
Closing as this is now being tracked in the dedicated map indexing issue thread.
