### ISSUE TITLE
Air Transport Assets can only be set to Faction

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#64]
In the Military Logistics module, underneath Air Transport Assets, "Faction" is set by default. When you change it to "Side and Faction," click ok, and open the module again, it says "Faction." 

I've attempted this with existing Military Logistics modules, as well as placing new ones, and it's 100% reproducible. Probably an Eden bug but will mean almost every modded faction will never use helicopters for resupply/BCR, mainly because most modded factions don't use helicopter assets. Since AI driving is terrible in Arma, I can see this causing issues since the only option available for these faction will be convoys.

**Comment by HeroesandvillainsOS** [comment]
@Tupolov

Closed because it's fixed or closed because you can't repro?

**Comment by tupolov** [comment]
Please understand github, there is a code commit linked to the closing of this ticket, which means it has been fixed.

**Comment by HeroesandvillainsOS** [comment]
I see it now and no I wasn't aware of the links until you mentioned it. Sorry about that.
