### ISSUE TITLE
Feature Request - Add "Reset Player State" Option

### ISSUE THREAD

**Issue by TheNightstalk3r** [ALiVEOS/ALiVE.OS#640]
The AliVE persistent Player State feature has the option to Save player state and Revert to previous player state. However, the option to Reset player state does not exist yet.

**Comment by trapw0w** [comment]
@TheNightstalk3r What are you intending to have reset? Gear, location, health, score etc?

**Comment by TheNightstalk3r** [comment]
Ticket can be closed, I've already implemented my own plugins to take care of this
