### ISSUE TITLE
Suggestion - Replace the current garrison function with CBA_fnc_taskDefend

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#641]
https://cbateam.github.io/CBA_A3/docs/files/ai/fnc_taskDefend-sqf.html

The current garrison script tends to garrison the groups very close together and in a very static manner, even to the point where restarting a mission multiple times will see units occupying the same houses.

Using CBA_fnc_taskDefend however allows you to specify chances for units to move out and patrol, and also more importantly allows you to define a percentage chance they will hold their garrison when in combat.

These options could even be added to the modules to allow mission makers to define patrol and garrison hold percentages. I know that personally I prefer my enemy to react and release from garrison while some prefer them to stay where they are for CQB purposes.

I would also suggest a larger radius  as currently it's not unusual to see a whole squad crammed into 1 building out of a whole compound.

**Comment by diveyez** [comment]
The ALiVE Virtual AI System is persistence focused and minded, it is supposed to work that way.

What we could do, is add func_taskDef... to the list of things ALiVE AI does...

VCOM, ASRAI3 usage improves on the stupidity you speak of as well.

**Comment by NZF-JDWang** [comment]
I do use VCOM religiously. But it doesn't help units garrisoned because their movement is disabled.

The problem as I see it is that ALiVE will garrison troops too close together. Ie you might have a compound with 6 buildings in and the garrison script will put 8 guys in one building, 2 guys in another and leave the rest of the buildings empty, every time.

Then when you clear the compound the AI will hold fast and never leave their building. I've been told this was so people could have a CQB experience, which I totally get.

But then you look at CBA_fnc_taskDefend and it spreads units more evenly, has options for allowing a portion of the units to patrol, options to define the chance units will leave garrison when under attack and a radius for buildings it will try and fill.

I know the virtual AI is persistence focused but it is spawning units when players get within range and then running the garrison function on them. All I'm suggesting is instead of using that garrison function, why not call the CBA version?

Again you could even add options into the modules so mission makers can then tweak the parameters going into that CBA function allowing a lot more flexibility.

**Comment by diveyez** [comment]
I forget what I used to make my units in garrison switch to enableAI "Move"; w/e

But those garrisoned dont stick to their buildings once in combat on my systems.

**Comment by bradon** [comment]
addons/x_lib/functions/behaviour/fnc_groupGarrison.sqf seems like a good starting point

**Comment by NZF-JDWang** [comment]
@bradon that's the function I was hoping to replace with the CBA version.

As far as I can tell the CBA version does everything fnc_groupGarrison.sqf does, but it offers more custom options that could be made available to mission makers, such as the chance for patrol, and the chance to hold garrison when in contact.

Hell you could even give mission makers the radius option as well so those garrisons can be more spread out or condensed depending on mission maker preference. (Failing that set the radius to a random range just to add even more randomness and variation)

**Comment by diveyez** [comment]
@bradon If you help me get this right, I will task myself with this issue to resolve it.
``addons/x_lib/functions/behaviour/fnc_groupGarrison.sqf seems like a good starting point``

**Comment by bradon** [comment]
Marcel left a todo to consider spreading the ai around multiple buildings (https://github.com/ALiVEOS/ALiVE.OS/blob/f330e58008ece6b48c797d9a2c7595e5d047a0df/addons/x_lib/functions/behaviour/fnc_groupGarrison.sqf line 83).

I'm leaning towards just finishing the work of spreading them around first, then comparing to a cba version later

**Comment by NZF-JDWang** [comment]
After further discussion on Discord a simple replacement isn't easy due to blacklisting etc.

But if someone does want to have a look at this in the future the main features I was hoping to achieve were:

- A more even (and random) spread of units across buildings so we don't end up with an empty compound save for the 6 guys all garrisoned in the 1 tin shed.
- The ability for units to break garrison under contact (this is a % chance in the CBA function) and would be a great option for mission makers. 
- The ability for some of the units to go patrol (this again is a % chance and would only be a small radius)

**Comment by MeltedPixel** [comment]
I don't think this is something were going to look into right now. Ill add the label as a Open Archived for tracking.
