### ISSUE TITLE
groups stucks on waiting for regroup

### ISSUE THREAD

**Issue by tbbdudu** [ALiVEOS/ALiVE.OS#65]
A lot of groups get stucks on waiting for regroup.
They are waiting for a group who will never arrive (vehicules bloqued or bug in the ai).

A timer on the action could solve the problem.

**Comment by HeroesandvillainsOS** [comment]
If you're talking about battle casualty replacements, the cycle can take some time. I've seen upwards of 15-30 minutes myself before OPCOM sends the new groups out on objectives. From what I gather, this is perfectly normal.

You can test this in SP by pressing the + key and speeding up the game time by x4.

**Comment by dixon13** [comment]
You can also use the Profile Speed setting to possibly increase the timing for debug purposes
