### ISSUE TITLE
Player persistence failing for first player on dedicated server on missions with lots of data

### ISSUE THREAD

**Issue by 1ncontinentia** [ALiVEOS/ALiVE.OS#66]
[PersistenceTestingIncon2.zip](https://github.com/ALiVEOS/ALiVE.OS/files/379765/PersistenceTestingIncon2.zip)
Here's a repro done with as much detail as I can muster. 

Essentially, the issue is as per the title; in missions with lots of persistent data stored in CouchDB (or in other scenarios where SYS_DATA takes a while to load, for example when people have slow internet connections), player persistence fails for the first player to join a non-auto initialised server. 

Produced the linked mission earlier on and have since run three tests on it. Basically, it's the usual array of modules just with a larger number of objectives and an asymmetric OPCOM with all persistence options set to on. The mission files are included in the dropbox link at the bottom. It has no scripts, was built in a sterile environment with no other mods, and had no previous saved data. Mission entirely produced by me today using latest versions of ALiVE, Arma 3 and CBA.

**Test 1 (fresh mission name, no pre-existing data, no auto-init):** Mission initialised at 12.23.19. Briefing screen appears at 12.24.23. Clicked continue and hint about player data loaded from ALiVE servers appears, everything works perfectly.

_Actions taken:_ moved to new location, dropped primary weapon on ground, placed test marker, moved nearby vehicle, placed second test marker on top of profile e174 in Gravia. Then logged into admin, server saved and exited at 12.28.07, save completes at 12.29.06. Shut down server completely.

_Stats:_

Time between mission init and briefing screen: 1 min, 4 sec. 
Data save duration: 59 sec.

**Test 2 (pre-existing data from Test 1, no auto-init):** Mission initialised at 12.37.44. Goes into loading screen. At roughly 12.39.15 (+/- 4 seconds), during the load screen, environmental sounds begin (including footsteps and some distant shooting). Server RPT suggests this is during data loading and just after Player Options starts loading (although I'd ask a dev to confirm this as I'm no RPT expert). At 12.39.36, the loading screen finishes, map briefing flashes for a millisecond, and the hint about player data loaded from ALiVE servers does not appear.

_Observations:_ Markers are present at correct location, profile e174 is exactly where it should be, weapon left on ground is at correct position, the moved vehicle is at the place it was left at the end of Test 1. Time of day (I think) has persisted too. Player loadout and starting position however have failed and are the default for the character, despite these options being checked in the player options module. Essentially, all persistence has worked except for Player Persistence.

_Actions taken:_ Player save and exit, server shut down. 

_Stats:_

Time between mission initialised and environmental sounds: 1 min, 31 sec.
Time between mission init and loading screen ending: 1 min, 47 sec.

**Test 3 (pre-existing data, "persistent battlefield" and "auto-init" options checked in TADST settings):**

13.04.36: Read mission. 
13.05.45: ALiVE Global Timer Complete. 
13.06.21: Player joins. 
13.06.27: Loading screen finishes.

_Observations:_ Hint about player data loaded from ALiVE servers appears and everything works perfectly. Markers loaded, weapon left on ground, vehicle where it should be, e174 at exact position) however this time, the player has persisted too and is in the correct place and has no primary weapon as per the end of Test 1 (**not** Test 2).

**Conclusions**

I strongly suspect the persistence problem is caused by Player Persistence loading before the player is found in playable units. Previous tests I've run suggest that if player persistence doesn't load at the start, it won't save at the end, even if everything else does. So I could run Test 2 again, save and exit at the end, and then run Test 3, and the player persistence data that loads will be the original data from Test 1.

A further, less clinical test I ran suggests that the longer SYS_DATA takes to load, the more likely this behaviour is to appear. So, for people with slower internet connections (mine is about 2mb/sec) or internet connections that are bottlenecked in some way, this issue is more likely. Furthermore, the more data there is to load and therefore the longer that loading takes place, the more likely this issue is to persist.

**Possible solutions:**
1. Make player persistence wait until the player is found in playableunits before initialising.
2. Find a way to prevent the mission starting while the first player on server is still stuck in the loading screen. The best indicator of this is the first player on the server having to click "Continue" on the map screen before the mission starts.

**Comment by marceldev89** [comment]
Now that's a proper bug report. :+1:

**Comment by friznit** [comment]
Put this in init.sqf

`waituntil {(player getvariable ["alive_sys_player_playerloaded",false])};`

**Comment by 1ncontinentia** [comment]
Thanks for the suggestion, I'll give it a go. Have a feeling it won't work unfortunately though as the issue to me seems to be that SYS_PLAYER is loaded before SYS_DATA completes, making SYS_PLAYER skip player persistence. I'll report back!

**Comment by 1ncontinentia** [comment]
Confirmed that `waituntil {(player getvariable ["alive_sys_player_playerloaded",false])};` doesn't fix the issue. 

One weird thing I've seen in the RPT is that the successful tests have '"ALiVE SYS_PLAYER - PLAYER UNIT FOUND IN PLAYABLEUNITS"' at the beginning and end of the playsession; the failed ones only have it at the end. 

It's probably safe to say that player persistence fails when the player loads before SYS_PLAYER is initialised and ready.

**Comment by dixon13** [comment]
Probably related #36

**Comment by 1ncontinentia** [comment]
Just wondering, is there anything I can do to help out more with this issue?

**Comment by tupolov** [comment]
Great bug report. I will take a look at this further, just short of time atm.

**Comment by tupolov** [comment]
Great bug report. I will take a look at this further, just short of time atm.

**Comment by 1ncontinentia** [comment]
Just to confirm, this issue is still present in the current build.

**Comment by eric963** [comment]
Does the"ready" tag mean it's been fixed and it's waiting for the next release version to be made available?

**Comment by tupolov** [comment]
Negative Ghostrider
Ready means its ready to be worked on.

**Comment by tupolov** [comment]
Can you test this with the new "local" saving function in sys data? let us know. Thanks!

**Comment by eric963** [comment]
Will test tonight and report back

**Comment by eric963** [comment]
Dedicated server, Alive set to local save, Current CBA and Alive, Altis with civ population entire map at high, red and blue commander with 1200 each and player persistence worked correctly. Tested with and without @AliveServer being used.

I had one instance where the player persistence failed so I created missions from minimal forces and no civs all the way up to the above mentioned about 10 total and never had the issue again.

**Comment by tupolov** [comment]
Awesome thank you!

Is it also still reprod with cloud saving?

**Comment by eric963** [comment]
Just ran test using cloud save, 380 profiles, 100+ objectives and same number of civs and troops as listed above.  Also added in logistics.

Entered the mission jumped in a vehicle and moved away from the base.  called in a logistic drop.  Did a server save and exit (took a few minutes).  Disconnected from server, shutdown the dedicated server and restarted it.  Connected back (took a couple minuites to load) and I was correctly placed back outside the base near my vehicle.

Looks like its working correctly now.  Hopefully someone else can verify also.

**Comment by friznit** [comment]
I just tested a heavy mission on dedi server using both local and cloud persistence, and all seemed to be working fine.  Apparently I persisted the mission 3 weeks ago, cos it took me a while remember where I'd left all the bloody vehicles.
