### ISSUE TITLE
Headless client causes autopause to stop working.

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#668]
https://github.com/ALiVEOS/ALiVE.OS/blob/4f7ac35a2cc6b257a795eed8d2fbe52e07913c51/addons/main/fnc_pauseModulesAuto.sqf#L35

The autopause function counts the number of `playableUnits` and I believe HC counts as a playable unit, so if you're running an HC the autopause will never trigger.

Instead of playableUnits something like `allPlayers - entities "HeadlessClient_F"` may work better?

**Comment by diveyez** [comment]
Works fine for me. However, I did turn AutoPause off because of this. Can you produce logs?

**Comment by trapw0w** [comment]
Tested this on a server running 2 headless clients, unable to replicate a fault specifically with `playableUnits`.

Result of `allPlayers`:
`[headless_2,headless_1,player_1]`

Result of `playableUnits`:
`[player_1]`

Will have a further look.
