### ISSUE TITLE
Unable to receive War Room Activation email

### ISSUE THREAD

**Issue by DarkWanderer** [ALiVEOS/ALiVE.OS#670]
(not strictly a ALiVE mod itself, but I don't know any other ways to contact besides Discord)

Activation emails requested via this form: http://alivemod.com/user/resend, never arrive. Another user reported same in Discord chat, but there was no reaciton

**Comment by DavisBrown723** [comment]
The other user was assisted, please post the email you signed up with and we will manually activate your account.

**Comment by DarkWanderer** [comment]
elquentaro (on) gmail dot com

**Comment by DavisBrown723** [comment]
You should be able to sign in now.

**Comment by DarkWanderer** [comment]
Thank you a lot - everything works now
