### ISSUE TITLE
Verification email 

### ISSUE THREAD

**Issue by kiloDeltax** [ALiVEOS/ALiVE.OS#676]
Hello.
I have not gotten my verification email after I signed up about 5 days ago.
I have checked all folders in email and it has not shown up.
Really interested in being able to login a d stuff
Thanks

**Comment by jetelain** [comment]
I've got the same issue

**Comment by marceldev89** [comment]
We're having mail server issues. Send me your email addresses and I'll get it sorted.

**Comment by kiloDeltax** [comment]
Dupontkris@hotmail.com

**Comment by jetelain** [comment]
julien dot etelain at outlook dot com

**Comment by marceldev89** [comment]
@kiloDeltax done and @jetelain done. :)
