### ISSUE TITLE
No activation email sent

### ISSUE THREAD

**Issue by ToKeNeRd** [ALiVEOS/ALiVE.OS#677]
### Prerequisites
Hello I did not receive an activation email
* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [ ] Are you running the latest version of ALiVE ?
* [ ] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by marceldev89** [comment]
Send me your email and I'll get it sorted.

**Comment by ToKeNeRd** [comment]
jnewman12387@gmail.com

**Comment by marceldev89** [comment]
Should be good now. :)
