### ISSUE TITLE
Feature Request - Optional starting IED level

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#678]
As we know when synced to the OPCOM IED take a while to spawn as the insurgency goes about it's business.

We need a "beginning level of IEDs" option which would spawn IED's on mission start.
Essentially you want a option that is equivalent to combining the function of the IED module when sync'd and when not sync'd.

This would make IED's more of a constant threat.

**Comment by svencc** [comment]
this would be awesome

**Comment by johnny0964** [comment]
Would really like to see this become a reality
