### ISSUE TITLE
Allow dump functions to not show messages in player side chats

### ISSUE THREAD

**Issue by alef** [ALiVEOS/ALiVE.OS#68]
For instance from https://github.com/ALiVEOS/ALiVE.OS/blob/a74e01a71126d85771f7ff4b734a798287853336/addons/x_lib/functions/logging/fnc_dumpR.sqf#L50 .

Maybe some global variable or module, thanks.

**Comment by tupolov** [comment]
Just use ALiVE_fnc_dump?

**Comment by alef** [comment]
The problem is with other ALiVE code callling this function.
For instance, when I pause the OPCOM [here,](https://github.com/alef/15BN/blob/ALiVE/MPMissions/15BN_Base.Altis/functions/_15BN_/fn_ALiVE_checkPlayers.sqf#L55) which in turn call dumpR, I get a message on the side chat.

**Comment by SpyderBlack723** [comment]
I've just changed DumpR to Dump in that function.

**Comment by tupolov** [comment]
Yeah we shouldn't be using dumpR unless it's debug?

**Comment by friznit** [comment]
https://github.com/ALiVEOS/ALiVE.OS/commit/b2ccd8e7858a25d661664d33e6f229b8872cf2a4
