### ISSUE TITLE
I am not reviving an activation email. 

### ISSUE THREAD

**Issue by MrChicen** [ALiVEOS/ALiVE.OS#680]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [ ] Are you running the latest version of ALiVE ?
* [ ] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

Its been a few weeks that I've been trying to set up my account for the War Room, and I have seen no activation email; If I could get some help with that, it would be greatly appreciated.

**Comment by marceldev89** [comment]
Send me your email and I'll get it sorted.

**Comment by MrChicen** [comment]
themonsterarmy25@gmail.com Thank you very much!

**Comment by marceldev89** [comment]
Done. :)
