### ISSUE TITLE
Not Getting Validation email

### ISSUE THREAD

**Issue by cigaming** [ALiVEOS/ALiVE.OS#681]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [ ] Are you running the latest version of ALiVE ?
* [ ] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
I seem to be having the same issue as most with not getting the validation email. I did check spam and inbox. Can you take a look in to this please. email-- collin.leck@gmail.com

**Comment by marceldev89** [comment]
Account activated. :smiley:
