### ISSUE TITLE
Not receiving war room activation email

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#682]
Until we fix the mail stuff; reply with your email here and I'll activate your account manually.

**Comment by RepoStudios** [comment]
repettotimothy@gmail.com

**Comment by bradon** [comment]
War room should now be working for new account signups.
Try a password reset if you made an account during the downtime

**Comment by marceldev89** [comment]
@RepoStudios done

**Comment by RepoStudios** [comment]
Thank You!
