### ISSUE TITLE
Captured vehicles seem to get despawned after a little while

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#683]
> Hagrid/ハギル: Quick question with only a little detail [I'm not the server admin and have no access to better info till he comes on]:
> 
> The boys and I attacked an enemy checkpoint which contained a BTR. We managed to steal the BTR but it despawned halfway back to base. We just left it and decided to continue on.
> We attacked a small convoy and managed to steal a GAZ with a ZU on the back which seemed pretty sweet. Unfortunately, halfway back to base, it seemed to virtualize and de-virtualize infinitely. I know that this doesn't happen for every vehicle as we have managed to take some vehicles.
> 
> No problems if no-one has any ideas, we were planning on making a new mission anyway but if anyone has experienced this before, it'd be nice to know how to avoid it. Also, I'll answer any questions I can

related to issue https://github.com/ALiVEOS/ALiVE.OS/issues/626 and commit https://github.com/ALiVEOS/ALiVE.OS/commit/e633129b61baffbd1d65d2cb79822092c58f7aff

**Comment by highhead** [comment]
broken with this: https://github.com/ALiVEOS/ALiVE.OS/commit/e633129b61baffbd1d65d2cb79822092c58f7aff#diff-3165e23ef553e8efdf9ba016293d33c0

Fixed with this (hopefully): https://github.com/ALiVEOS/ALiVE.OS/commit/26beb61d765d1931fef632c396fec9a5e09ab6cd
