### ISSUE TITLE
CfgPatches.hpp ORBATRON Error

### ISSUE THREAD

**Issue by alotofgrey** [ALiVEOS/ALiVE.OS#686]
Iv had this problem for months when using the ORBAT. I keep getting the same error when i try to run the game with the exported faction in the add on section, its extremely frustrating as these factions take nearly 3 days to create, iv had to delete them then remake them multiple times. Could someone please help me as i want to make a RMC faction, RAF, RAF regiment RN and so on.  Asked this question on the ALIVE forum months ago and no one has replied , posted it on reddit and no one replied either, I even uninstalled and reinstalled ARMA twice hopefully someone here could help me out or redo it for me. (sorry for the crap quality) sorry for sounding so petty. Let me know if i should send you the folder or config etc. Please help

![DSC-0001](https://user-images.githubusercontent.com/64854700/81085699-776a3b00-8eef-11ea-94c9-2f755af78b58.jpg)

![DSC-0004](https://user-images.githubusercontent.com/64854700/81085782-92d54600-8eef-11ea-8198-2af77682139b.jpg)

* [yes] Can you reproduce the problem using ALiVE and CBA Only?
* [yes] Are you running the latest version of ALiVE ?
* [yes] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [yes] Have you attached screenshots of the Parameters set on the offending Module?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by DavisBrown723** [comment]
You can only have one

```
class CfgPatches {
.........
}
```

in your config files. My guess is you tried to put multiple factions in a single file, which is not possible without manual work.
