### ISSUE TITLE
Feature Request: Deeper LAMBs_danger.fsm and other AI mod integration

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#696]
Rumour has it that by adding a wrapper around some of the ALiVE functions you can check for other available functions? @marceldev89 ;)
This could be a way to deeper integrate and take advantage of a lot of the AI work done by the likes of LAMBs and VCOM AI mods while not making them a requirement.

Wrapping the garrison function for instance could allow you to instead call the LAMBs garrison function which spread units better, and works with fired, fired near, and hit EH's to really improve how the AI respond when garrisoned.

The LAMBS camp function could also be potentially used at roadblocks and also installations etc, this sees some units of the group sit down at the location while others move off to man static weapons and/or randomly patrol the area.

Being able to integrate these AI mods deeper when available would really increase the immersion you get from an enemy that acts/reacts at a much higher level than it's vanilla counterpart.

**Comment by marceldev89** [comment]
@AUTigerGrad your betrayal of my trust will have consequences! :laughing:

**Comment by AUTigerGrad** [comment]
Bwahahahahahahaha!!!

**Comment by NZF-JDWang** [comment]
https://imgur.com/a75wn18

Perfect example of why this needs to be looked at. 4 guys guarding a military compound, 3 jammed into the one single man tower and the 4th in another tower.

These guys won't move (even though they have waypoints because they're garrisoned 
https://imgur.com/xYujdY6

What makes it even worse though is you can restart the mission multiple times and the exact same scenario happens, there's just not enough randomisation involved.

**Comment by DarrellJMartin** [comment]
AI garrison and patrol options now implemented in modules.
