### ISSUE TITLE
ACE3 compatibility & integration

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#7]
1.  Autodetect ACE3 in the ALiVE (Required).
2.  Persistence for ACE Logistics, Wounds, Weather
3.  Integrate ALiVE options in ACE radial menu (PR to ACE mod)
4. Our weather (and real weather) with ACE weather

See also: https://docs.google.com/document/d/1cr0VQoE_sElN1EnNzHzh8Sf5LvKC5YWkAvIJSJxChtE/edit?usp=sharing

**Comment by Ligthert** [comment]
I've discussed point 1 and 3 with @SpyderBlack723 last night/this morning. My intention is to have it working as much as possible before I go on holiday end May. 

As for the first requirement, I've got that one sorted: https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/admin/init.sqf#L5 :)

**Comment by jonpas** [comment]
> PR to ACE mod

It is better if you either do it directly in your code or provide a compatibility PBO for things that can't be directly in code. Main reason for this being that it is up to you when to release it rather than when ACE3 gets updated.

**Comment by friznit** [comment]
Thanks jonpas - makes sense.  Turns out one of our guys has already done it so hopefully we can include it alongside the "do you got ACE yet?" func (technical term)

**Comment by marceldev89** [comment]
From [BI forums](https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/?do=findComment&comment=3155527)
> Hi lads, I had a peek in the github and noticed in issues that ACE compatibility is obviously still on your list.
>
> I didn't want to go and create another issue related to ACE (never used github before so I don't know if I am able to add onto the existing "to do" list for ACE)
>
> Something i've noticed with vehicle saving and ALiVE is, if the vehicle enters "cook off" with ACE3 and the proceeds to blow up, ALiVE doesn't recognize this and will replace the vehicle on next restart.
>  
> I apologise for posting this here instead of the github, hoping you guys are able to update the original issue as I can't seem to figure it out.
