### ISSUE TITLE
Player Logistics - Towing | Drop action

### ISSUE THREAD

**Issue by LewisSO** [ALiVEOS/ALiVE.OS#708]
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

When towing a vehicle with ALiVE player logistics, the player jumps into the tow vehicle and receives the "Drop Object" addaction. 

### Steps to Reproduce

1. Place two vehicles that can tow or be towed.
2. Tow one of the vehicles to the other vehicle.
3. Once the vehicle is towed jump into the tow vehicle as driver.
4. On the player scroll wheel, the player will now find the "Drop Object" addaction

**Expected behavior:** [What you expected to happen]
Drop object should only be created when the player is carrying an object.
**Actual behavior:** [What actually happened]
Drop object action created as a result of towing on the driver of tow vehicle.

**Comment by trapw0w** [comment]
Fixed in https://github.com/ALiVEOS/ALiVE.OS/pull/709, good to close.
