### ISSUE TITLE
Transport helicopters can not circle/pickup after RTB.

### ISSUE THREAD

**Issue by EasyEB** [ALiVEOS/ALiVE.OS#71]
Greetings!

When a transport helicopter has been used for a task (move/land/circle/so on) and is ordered to RTB it starts acting strange.

When ordered to circle or pickup, instead of slowly transitioning between points in a circle around the ordered position, the helicopter goes in a full speed bank around the point. 

Furthermore the helicopter becomes more prone to overshooting waypoints when in this full speed mode after one RTB.

Only CBA/Alive used.

To replicate in a mission:

1. Get in transport helicopter.
2. Order transport helicopter to land at a point.
3. Get out of the transport helicopter (or stay).
4. Order transport helicopter to RTB.
5. When the transport helicopter is back at base, order it to circle your current location. It will come in at full speed and do a sharp bank turn, and keep that turn in a continous high speed circle.

**Comment by marceldev89** [comment]
Can you try the same thing but without getting in and out of the helicopter? To confirm my theory. :smile:

**Comment by EasyEB** [comment]
Yes, just tried it. Same thing happens.

**Comment by marceldev89** [comment]
Haven't tested it in game yet but there's a (possible) fix waiting to be accepted. :smiley:

**Comment by marceldev89** [comment]
Just tested the fix(es) and things seem to behave as they should again. :smiley:

**Comment by EasyEB** [comment]
Great!

So is there something I can do to apply those fixes now or do I chill untill the next update?

**Comment by marceldev89** [comment]
It's probably best to chill until the next update. If you really want to try it you can follow the steps below but I've got no clue whether that actually works.

1. Download [transport.fsm](https://raw.githubusercontent.com/marceldev89/ALiVE.OS/00eb9bcd1cdf07cf480de8222efba928d62781ee/addons/sup_combatsupport/scripts/NEO_radio/fsms/transport.fsm)
2. Create the following folder structure in your mission folder: `\x\alive\addons\sup_combatSupport\scripts\NEO_radio\fsms\`
3. Place the downloaded transport.fsm in that fsms folder

**Comment by EasyEB** [comment]
Couldn't get it to work so I'll wait for the update.

Big thanks for the help!

**Comment by friznit** [comment]
@marceldev89 Not fixed in dev.  Can still repro with both module and manually placed units.
