### ISSUE TITLE
Feature Request: Ability To Disable Civ Sounds

### ISSUE THREAD

**Issue by Vegas-zzz** [ALiVEOS/ALiVE.OS#722]
A lot of our players are complaining about some of the civilian sounds. Notably the loud screaming and baby crying.

Now, I'm all for immersion, and most of the sounds I really enjoy, however those two in particular are gnarly and they often loop.

Would be great to have some checkboxes in the module to enable or disable certain sounds, or one to enable/disable them all.

Cheers.

**Comment by Brojustuserandomgenerationusername** [comment]
Would be cool too if there was a way to put the baby to sleep permanently.

**Comment by jones140** [comment]
I have to agree the some of sounds are very obnoxious especially baby 
Mabey just some more fitting sounds or higher variety

**Comment by tupolov** [comment]
Ok will try to work something out. Is this ambient sounds or something heard when the shooting starts?

**Comment by tupolov** [comment]
Ok you can try the following script to remove crying and baby sounds from ambient civ house sounds.

waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};
[ALIVE_civilianHouseTracks, "ALiVE_Civpop_Audio_15"] call ALIVE_fnc_hashRem; // Crying
[ALIVE_civilianHouseTracks, "ALiVE_Civpop_Audio_17"] call ALIVE_fnc_hashRem; // Baby
