### ISSUE TITLE
Unexpected Behavior in OPCOM "getobjectivebyid"

### ISSUE THREAD

**Issue by E-Ledere** [ALiVEOS/ALiVE.OS#726]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Running "getobjectivebyid" with the ID of an objective that doesn't exist throws an error.

### Steps to Reproduce

1. Try to get an objective by id with an id that doesn't exist, ie: `[[], "getobjectivebyid", "testObj"] call ALiVE_fnc_OPCOM;`
2. Receive a script error.

**Expected behavior:** Command returns with nil.

**Actual behavior:** Command threw an error.

[Arma3_x64_2021-03-22_21-08-12.rpt.txt](https://github.com/ALiVEOS/ALiVE.OS/files/6186814/Arma3_x64_2021-03-22_21-08-12.rpt.txt)

**Comment by DavisBrown723** [comment]
5ce09ba37e44768a8ea7db1d018f73a438870009
