### ISSUE TITLE
[Feature Request] ACE medical persistence across multiple mission sessions

### ISSUE THREAD

**Issue by MAJThomasASOT** [ALiVEOS/ALiVE.OS#736]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [N] Have you attached an unbinarized SQM?
* [N/A] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N/A] Have you attached screenshots of the Parameters set on the offending Module?

### Description

ACE medical does not persist across multiple mission play throughs. 

### Steps to Reproduce

1. Set up basic ALIVE mission. (Required modules for player and civilian ambiant persistence)
2. Injure player and have them heal themselves. Not fully though. Only to be patched/stitched/in pain etc. 
3. Either; 
              - Have player exit and rejoin. They will be fully healed. 
              - Save and exit server. Relaunch server, all wounded players will be fully healed.

**Expected behavior:** Would like to have players' medical status carry onto future play throughs of the mission. That way it's even more persistent in the sense that players have to consider not only their logistics, but their physical status when exiting a server/mission. 

Could make it an optional setting in a module.

**Actual behavior:** See steps to reproduce.

**Comment by NZF-JDWang** [comment]
Pretty sure the ACE devs are working on a more generic system to save injuries across missions.

**Comment by DarrellJMartin** [comment]
Out of scope for this project.
