### ISSUE TITLE
Chernarus winter potentially needs re index?

### ISSUE THREAD

**Issue by tyl3r99** [ALiVEOS/ALiVE.OS#737]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only? 
* [ ] yes
* [ ] Are you running the latest version of ALiVE ? Yes
* [ ] Are you running the latest version of CBA_A3?
* [ ] yes
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue 
* [ ] couldn't see anything in rpt relates to data
* [ ] Have you attached screenshots of the Parameters set on the offending Module? 
* [ ] I will attach images once at pc

### Description

When using Air component commanders on Chernarus winter the units will spawn at the bottom left of the map (like it doesn't detect airports?)

No error message appears though 

I was using cup Russian faction and USAF RHS 

### Steps to Reproduce

1. [Set up x2 commanders both with mil and civ placements ]
2. [Place x1 air component commander modules at each airport and sync where necessary]
3. [Preview and go into zeus you should... see units at the bottom left of the map like a few pilots and destroyed aircraft.]

**Expected behavior:** [airports to function]

**Actual behavior:** [air commanders don't work on this map]

Will attach more info soon :)

**Comment by jslick007** [comment]
This seems to happen with Chernarus 2020 as well.
