### ISSUE TITLE
"No entry CfgVehicles.Land_vn_hut_05" error in Eden/Zeus if SOG Praire Fire not owned

### ISSUE THREAD

**Issue by heretyk999** [ALiVEOS/ALiVE.OS#738]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [N] Have you attached an unbinarized SQM?
* [N] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Since last ALiVE update that added support for SOG Praire Fire CLDC i get an error when starting Eden or Zeus saying "No entry 'bin\config.bin/CfgCVehicles.Land_vn_hut_05'". I don't have the CDLC, but I assume ALiVE should work regardless. I don't know if this breaks any functionality, so far the only observed symptom was the error message.

### Steps to Reproduce

1. Start Arma 3 with CBA and ALiVE loaded, while not owning SOG Praire Fire CDLC.
2. Start Editor.

**Expected behavior:** No errors should pop up.

**Actual behavior:** Error pops up :)

**Comment by tupolov** [comment]
Thanks for the bug report! Looks like our eager devs left a pbo in the main ALiVE folder that should not have been there. Fixing now and should be up on Steam shortly.

**Comment by heretyk999** [comment]
I just got update from steam around 22:30 CET. I checked and I don't get error anymore. Thx for lightning fast reaction :)

**Comment by tupolov** [comment]
Our pleasure. Enjoy!
