### ISSUE TITLE
Civilian Interaction not possible anymore

### ISSUE THREAD

**Issue by M3MENTOMORIXVII** [ALiVEOS/ALiVE.OS#743]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [N] Have you attached an unbinarized SQM?
* [N] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [N] Have you attached screenshots of the Parameters set on the offending Module?

### Description

After latest Update you are not able to interact with the civ. Population anymore. Basically there is no selection available. 
(e.g. in Insurgency modes/asymmetric Warfare) 
So on the version with Spyder Addon didn't work either, as a alternative. 
### Steps to Reproduce

1. Start a Game with ALiVE Modul based on Insurgencystyle 
2. Try to speak with the local Civs, to gather Information 
3. There is no option available in the drop-down menu. 

**Expected behavior:** Civs are available for interrogation 

**Actual behavior:** no option available for interrogation 

Feel free to contact me, if further information is needed.

**Comment by tupolov** [comment]
Is this every civ or just some civs? SP or Dedi? Did you replace your civ pop modules etc?

**Comment by DavisBrown723** [comment]
9e7aad0723fd3281b7691180f3f449de3082ecdc
