### ISSUE TITLE
FEATURE REQUEST: Assets destroyed while virtualized to be properly simulated.

### ISSUE THREAD

**Issue by hardlycode** [ALiVEOS/ALiVE.OS#744]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only? Y
* [ ] Are you running the latest version of ALiVE ? Y
* [ ] Are you running the latest version of CBA_A3? Y
* [ ] Have you attached an unbinarized SQM? N
* [ ] Have you attached your RPT (If the issue relates to data, also attach Server RPT and ALiVE Plugin Log)? N
* [ ] Have you attached screenshots of the Parameters set on the offending Module? N

### Description

I am working on a single player scouting/scavenging/survival mission which simulates an Altis-wide conflict between BLU/IND/OPFOR with garbage collection turned off.

Any assets that are destroyed while virtualized do not spawn when the player moves nearby. This creates a problem for simulating a scene after a major battle since the area is already clean by the time the player-character moves into it and simply leaves the map feeling empty.

**Comment by DarrellJMartin** [comment]
Out of scope for this project.
