### ISSUE TITLE
FEATURE REQUEST: Allow C2IStar to show only certain types of information on the map.

### ISSUE THREAD

**Issue by hardlycode** [ALiVEOS/ALiVE.OS#745]
This one is pretty simple, I would like options for:

[ ] Show friendly units (no unit numbers, just the symbol).
[ ] Show last known enemy locations (This needs to be made longer so it doesn't fade out instantly).
[ ] Ability to turn off KIA reports.
[ ] Show friendly tactical moves.
[ ] Show friendly opcom installations.

To put it another way: it'd be nice to be able select the kind and variety of info regular players get. Not only to enhance mission security (if a player holding an alive tablet were killed and the enemy could see everything and start ordering units to change patrol routes...that would be bad.) but also because not every player is in a commanding role.

**Comment by kgrosvenor** [comment]
I'd like to be able to disable faction selection in C2IStar @hardlycode, do you know if this is possible?

**Comment by hardlycode** [comment]
I'm not really sure what you are asking but if you need help you should get on the discord.

> I'd like to be able to disable faction selection and use the factions only from the AI enemy commanders in C2IStar @hardlycode, do you know if this is possible?
