### ISSUE TITLE
[Feature req] standalone resupply module 

### ISSUE THREAD

**Issue by tyl3r99** [ALiVEOS/ALiVE.OS#746]
I was wondering if it would be possible to have a module where it wouldn't be reliant on anything else I.e. a OPCOM etc 

So how it would work in my head is that the module is the starting pos for the resupply vehicle and in this module maybe have options where we can dictate what supplies are available.  

So it would be basically the player combat support module but it would work standalone for those who love the aspect of ALiVE logistics (ammo etc) being dropped off or parachuted from a plane 

Hope I'm making a little sense lol 

Thank you for reading!

**Comment by DarrellJMartin** [comment]
Please use the ALiVE Discord for such discussions.
