### ISSUE TITLE
[Feature request] more player task types from MAAC 

### ISSUE THREAD

**Issue by tyl3r99** [ALiVEOS/ALiVE.OS#749]
I'd like if the MAAC could also give you tasks such as: 

Transport units from a base to an objective 
Slingload vehicle to a destination
Slingload ammo to a destination 
Pickup units from an objective and RTB 

More or less some helicopter based missions for logistics :)

**Comment by DarrellJMartin** [comment]
Please use the ALiVE Discord for such discussions.
