### ISSUE TITLE
[Bug]Hard crash when attempting to index G.O.S. Al Rayak

### ISSUE THREAD

**Issue by belcherjy** [ALiVEOS/ALiVE.OS#750]
### Prerequisites

* [NO] Can you reproduce the problem using ALiVE and CBA Only?
 - Require map and dependency to be loaded.
* [YES] Are you running the latest version of ALiVE ?
* [YES] Are you running the latest version of CBA_A3?
* [YES] Have you attached an unbinarized SQM?
 - Added in google drive link.
* [YES] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
 - Added in google drive link.
* [YES] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Create a mission as per the wiki, when I run the indexer module, my game crashed.  RPT shows what looks to be some kind of unhandled exception.

### Steps to Reproduce

1. Start ARMA 3 with ALiVE, CBA, CUP_CORE, and [G.O.S.] Al Rayak loaded.  
2. Open editor and create new mission on Al Rayak.
3. Place down unit (NATO Officer was used) and Map Indexer module.
4. Set attached settings into module parameters.
5. Save mission as "index".
6. Run mission in single player.
7. Open map and zoom all the way out.
8. Use App Key to open ALiVE menu, then run map index module.

== Module Parameters ==
![Parameters](https://user-images.githubusercontent.com/74728434/130498458-a39efeb3-791c-4aa6-931e-f4056a5ae9cb.png)

**Expected behavior:** 
Expect map indexer to call DeWRP and continue on with indexing.

**Actual behavior:** [What actually happened]
ARMA crashes to desktop, RPT reports a fault code.

== RPT, Log, and SQM ==
https://drive.google.com/drive/folders/1HQp7TJYXpqbBgx6y0SAnyAzNYTDMs7Up?usp=sharing

**Comment by Vegas-zzz** [comment]
Hello,

Why are you trying to reindex Al Rayak? I updated the index for this terrain after the last update it received from Makhno... or are you just using it to try and learn the index tools? If you are just trying to learn the tools, experiment with a smaller map like Stratis to see if it works correctly. Otherwise you have a pathing issue to the map file, or an issue with your plugins (dewrp).

Cheers

**Comment by belcherjy** [comment]
I didn't see an index for Al Rayak in the [google sheet](https://docs.google.com/spreadsheets/d/1-wsoODqeeS7N4I6PbKAvcU-vK8t5ZdqA2vZYPyYa2CA/edit#gid=0) linked in the ALiVE discord.  Can you provide a link to where you're hosting the index?

As for my issue, I can index other maps without issue, so it doesn't seem like a plugin or pathing issue.  I'd expect something like that to show a failure on other maps as well.
