### ISSUE TITLE
[Bug] C2ISTAR Wiretap Task is Incompletable

### ISSUE THREAD

**Issue by GE0NE** [ALiVEOS/ALiVE.OS#751]
### Prerequisites

* [YES] Can you reproduce the problem using ALiVE and CBA Only?
* [YES] Are you running the latest version of ALiVE ?
* [YES] Are you running the latest version of CBA_A3?
* [NO] Have you attached an unbinarized SQM?
   Not needed

### Description

The auto-generated 'Intercept Communications/Wiretap communications site' task is unable to be completed. No such 'wiretap device' exists and there is no way to install a wiretap on the target transmitter pole using a regular toolkit.

### Steps to Reproduce

1. Load any ALiVE mission with the C2ISTAR module and generate a 'wiretap communications site' task (either using C2ISTAR or wait for it to auto-generated a wiretap task if that option is enabled).
2. Proceed to the destination with a toolkit on you (as engineer or not).
3. Attempt to complete the task by installing a wiretap on the transmitter pole.

**Expected behavior:** The transmitter pole provides some interaction prompt or option to wiretap.

**Actual behavior:** No such option or prompt exists. The mission is incompletable.
![jniFYbF](https://user-images.githubusercontent.com/25130343/135642007-333c4da6-6f09-4f51-a1a8-be6d6697f24b.png)
![LXra721](https://user-images.githubusercontent.com/25130343/135642012-5dbe593e-5c19-4cb6-a945-1609a33ba221.png)

**Comment by ttrebuchon** [comment]
Just in case anyone stumbles on this while looking for a workaround, you can disable the wiretap task from the types of autogenerated tasks by putting this snippet in your init:

`
[] spawn {
    waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"};
    ALIVE_autoGeneratedTasks deleteAt (ALIVE_autoGeneratedTasks find "Wiretap");
};
`

There may be a better way to handle this, but this is one way to do it.
