### ISSUE TITLE
Disabling HQ's etc is incredibly lackluster 

### ISSUE THREAD

**Issue by NZF-JDWang** [ALiVEOS/ALiVE.OS#754]
Back in the day when you found an IED cache or HQ it was cool, there were objects inside and you'd blow up the building to destroy the cache/HQ.

Now it seems I walk into an empty building and get a popup to hold space for x seconds and the HQ is magically disabled. This seems to fly in the face of the normal ALiVE philosophy of "no magic" eg CAS must be provided by on map units etc.

I get why blowing up the building is a bad idea (eventually you end up with half the map blown up) so how about in order to disable the HQ's etc you have to blow up the items. Eg for an IED factory you have to drag all the crates of IEDs outside and blow THEM up. This still gives the players the option to drop a JDAM on the building, or drag the items out of the building and set up a controlled detonation. 

Much more immersive than simply holding space for 10 seconds.

**Comment by DarrellJMartin** [comment]
Please use the ALiVE Discord for such discussions.
