### ISSUE TITLE
Combat Support (CAS) doesn't work with planes

### ISSUE THREAD

**Issue by EidEchse** [ALiVEOS/ALiVE.OS#76]
I have tried to use a plane (B_Plane_CAS_01_F) instead of an Helicopter in the Combat Support Module the plane gets the signal for CAS, starts his engines but doesn't move.

Contact me if an example Mission is needed.

ARMA3 Version: 1.62.137494
ALIVE Version: v1.1.1.1607201

**Comment by marceldev89** [comment]
That's mostly related to the AI not able to find a path and/or not being able to get to that path. Try to experiment with the location of the module or vehicle.

**Comment by SpyderBlack723** [comment]
Make sure the plane is placed in the proper area on the runway. Arma AI are notoriously bad at taxiing.

**Comment by EidEchse** [comment]
OK, after a few attempts i got a moving plain with the ALiVE module.
But i'am wondering if i place a plane without ALiVE on the runway, it immediately begins to take off. With ALiVE the plane doesn't do anything.

**Comment by friznit** [comment]
ALiVE forces them to wait until told to take off by Combat Support request (though even then some AI mods will override ALiVE).

This issue is just AI being useless.  It's particularly bad on modded maps.
