### ISSUE TITLE
AI are not advancing to objective

### ISSUE THREAD

**Issue by Shizzak** [ALiVEOS/ALiVE.OS#760]
### Prerequisites

* [ Yes] Can you reproduce the problem using ALiVE and CBA Only?
* [ Yes] Are you running the latest version of ALiVE ?
* [Yes ] Are you running the latest version of CBA_A3?
* [I don't know what that is ] Have you attached an unbinarized SQM?
* [I don't know if that applies ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [Yes ] Have you attached screenshots of the Parameters set on the offending Module?

### Description
AI groups will advance to the holding point of an objective then will never advance onto the objective itself. They will only move if OPCOM assigns them a different objective
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step] 
2. [Second Step] 
3. [and so on...]

**Expected behavior:** [What you expected to happen]
AI groups (once all that have been assigned) reach the hold point are then directed to assault the objective
**Actual behavior:** [What actually happened]
AI groups reach the hold point and never advance. 
![Untitled](https://user-images.githubusercontent.com/91353894/156937903-f31c1ce1-ca91-472d-80e7-12d98d61e385.png)

**Comment by Kiskadee-dev** [comment]
@Shizzak Can you still reproduce this behaviour?

**Comment by DarrellJMartin** [comment]
Unable to reproduce without the following:
Please provide a list of additional addons used.
An rpt file with CS modules in debug mode and if possible the mission file.
