### ISSUE TITLE
Internal Server Error upon attempt to view mission playback

### ISSUE THREAD

**Issue by Eagle-Studios** [ALiVEOS/ALiVE.OS#762]
### Prerequisites
N/A // Website Server Bug

### Description
Internal Server Error on all unit operations

### Steps to Reproduce

1. Launched Our Mission File
2. Verified It was on the Home page feed
3. Ended mission file
4. Click on the operation name
5. Error appears

**Expected behavior:** 
Mission playback

**Actual behavior:** 
Internal server Error

![](https://i.gyazo.com/b86f9593075697c1d072ed5639f2ad9c.png)

**Comment by DarrellJMartin** [comment]
The War Room is no longer operative.
