### ISSUE TITLE
Altis Index Error: Galati

### ISSUE THREAD

**Issue by NKrukov** [ALiVEOS/ALiVE.OS#763]
### Prerequisites

* [Y] Can you reproduce the problem using ALiVE and CBA Only?
* [Y] Are you running the latest version of ALiVE ?
* [Y] Are you running the latest version of CBA_A3?
* [N] Have you attached an unbinarized SQM?
* [N] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [Y] Have you attached screenshots of the Parameters set on the offending Module?

### Description

While making a specific mission, I, and other mission makers have run into the same issue where the town of Galati is not populating at all,  At first we were trying to populate it with the Civilians, and it would not, but would populate everything around it.  I have tried populating it with Military forces, and it will still not populate.  I assume it is an index issue for the town of Galati.

### Steps to Reproduce

1. Create Marker over the town of Galati, Name it
2. Create Military Placement, Civ.  Add the Galati marker to the TOAR field, turn on debug
3. Run mission.  Neither Military nor Civilians will populate the town of Galati.

**Expected behavior:** [What you expected to happen]

The town of Galati to be populated with Civilians and/or military forces.

**Actual behavior:** [What actually happened]

The town of Galati did not populate

![1 Marker](https://user-images.githubusercontent.com/13669340/162280072-1b24dc35-869c-4a43-aa7a-058eff2d6d9d.JPG)
![2 Module](https://user-images.githubusercontent.com/13669340/162280078-735f05f4-b9ca-4ad0-b961-1f91a8114db0.JPG)
![3 Map](https://user-images.githubusercontent.com/13669340/162280111-29998139-95f8-4a34-8d72-bd619a78338c.png)
.

**Comment by DarrellJMartin** [comment]
Re-index the map our use an alternative related index.
You could also try placing a custom mil placement over the area.
