### ISSUE TITLE
Feature request: Whitelist or variable for Slingload

### ISSUE THREAD

**Issue by BigPoppaBlunts** [ALiVEOS/ALiVE.OS#77]
Is it a possibility to get a white/blacklist for objects that can be selected for slingloading?
Or a variable : this setvariable ["CS_CANNOTSLING","truck1"];
Maybe even a module. Everything synced to it can be slingloaded.
If this already exists I guess I missed it.
Thanks guys, ALiVE rocks!

**Comment by marceldev89** [comment]
You can do this with the usual A3 commands, see https://community.bistudio.com/wiki/enableRopeAttach. Putting `this enableRopeAttach false` in the init field of an object _should_ disable slingloading.

**Comment by tupolov** [comment]
The items that can be sling loaded by ALiVE transport choppers, are only items that can actually be sling loaded in game.

**Comment by BigPoppaBlunts** [comment]
Thats all I needed to know. Thanks.
