### ISSUE TITLE
Combat Support Transport issue on dedicated server

### ISSUE THREAD

**Issue by emek1501** [ALiVEOS/ALiVE.OS#771]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [ ] Are you running the latest version of ALiVE ?
* [ ] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

When I'm in game on one dedicated server and call for heli transport, trough combat support tablet, the heli won't land. When it arrives it touches the ground and then flying off again.

### Steps to Reproduce

1. Open Combat Support Tablet
2. Choose callsign
3. Choose "land"
4. Mark position on map
5. Order unit to dispatch
6. Wait for heli to arrive

**Expected behavior:** I expect the heli to land on the marked position and wait for me to jump in and give new orders

**Actual behavior:** The heli arrives to marked position, touches the ground and then flying up again

**Comment by DarrellJMartin** [comment]
tested in vanilla (ALiVE and CBA_A3 only) and working fine. 
Helicopter lands and waits.
