### ISSUE TITLE
Player Combat Logistics enhancements

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#8]
Add a cancel option for when AI craps out and refuses to drive over a rock and so never arrives (e.g. dumps the log convoy in current location and lets OPCOM pick up the profile from wherever it is).

Add a filter to disable selected logistics transport types (airdrop, convoy, insertion). E.g. As a user, I want to disable heli insertion for immersion reasons in scenarios that don't have helicopters such as WW2.

Add a LOGSITREP button showing status of logistics delivery (e.g. location, destination, distance) and current forcepool count.

Easier method to blacklist/whitelist classes (point to an external array in an sqf file?)

**Comment by tupolov** [comment]
1. This happens after a certain time limit. Will ensure cancel can be hit at any time.

2. You can enable/disable delivery in the module already.

3. Status button shows distance, click on details and it shows you the current location. Could add Force Pool count in UI if necessary.

4. copy your external array into the module :)
