### ISSUE TITLE
Civ Pop & Civ Settlement Fix

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#80]
And reindex! :8ball:   Civ pop buildings should be added to both civ pop and civ settlement

**Comment by friznit** [comment]
Not sure if related?

Place ALiVE (Req), Virtual AI, Civ Placement, Civ Pop - all settings default - Preview game.

```
11:00:27 Error in expression <issionConfigFile >> "CfgFactionClasses" >> _this;

if !(isClass _path) then {_pa>
11:00:27   Error position: <>> _this;

if !(isClass _path) then {_pa>
11:00:27   Error >>: Type Config entry, expected String
11:00:27 File x\alive\addons\x_lib\functions\config\fnc_configGetFactionClass.sqf, line 32
```

**Comment by SpyderBlack723** [comment]
Above error fixed, need someone who saw behavior before and after today's commits to confirm whether the issue still exists or not

**Comment by friznit** [comment]
Tested Tanoa and Diyala on a dedi server.  Civs everywhere!  No need to reindex.
