### ISSUE TITLE
Can't adjust simulation speed in multiplayer

### ISSUE THREAD

**Issue by drahcirdier** [ALiVEOS/ALiVE.OS#801]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

The function _fnc_profileSimulator.sqf_ computes virtual unit movement steps and attack damages using **accTime**. However the **setAccTime** function does not work in multiplayer, making it impossible for the player to scale the simulation speed in multiplayer scenarios. **setTimeMultiplier** does work in multiplayer, and so **accTime** should be substituted with **timeMultiplier** in _fnc_profileSimulator.sqf_ to allow time scaling to work. 

### Steps to Reproduce

1. Create any single player scenario with Virtual AI debug on
2. Use setAccTime and setTimeMultiplier to change the scenario speed. Observe changes to the unit movement speeds as time is sped up or slowed down. 
3. Repeat the above in Multiplayer and note that setAccTime no longer works.

**Expected behavior:** [What you expected to happen]

AliVE simulation should speed up and slow down with the world simulation speed.

**Actual behavior:** [What actually happened]

It is impossible to change accTime in multiplayer.

**Comment by DarrellJMartin** [comment]
accTime & timeMultiplier are not the same and their correcponding 'set' calls do not except the same values so cannot just be transposed.
setAccTime - accelerates game time (you move faster) only works in single player.
setTimeMultiplier - game times flows same as normal, but clock time moves faster (effecting sunlight/weather).
Game movement cannot be acclerated in multiplayer for performance/data sync issues between server & clients.
