### ISSUE TITLE
No activation email for War Room

### ISSUE THREAD

**Issue by Mercury151** [ALiVEOS/ALiVE.OS#804]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [ ] Are you running the latest version of ALiVE ?
* [ ] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description
Hello,
I am not receiving an activation email for the Alive War Room login.  Any help with this would be awesome!
tpetter795@gmail.com
Thank you!
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by DarrellJMartin** [comment]
The War Room has been closed down.

**Comment by friznit** [comment]
Technically it's still ALiVE....just not had any maint for a few years so it's probably feeling a bit ill.
