### ISSUE TITLE
Using 'rhs_faction_tv' as defined in CustomFactions.hpp

### ISSUE THREAD

**Issue by runedog48** [ALiVEOS/ALiVE.OS#805]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [ ] Have you attached an unbinarized SQM?
* [ ] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

This might be a user error and inappropriate for Github, but the forum looks dead and doesn't send the confirmation email to register (it gives an error on the confirmation page ), so here I am. 

The faction is defined in CustomFactions.hpp; however, when I set it to be used for an objective, it will not work. How do I get the faction to work since, from what I see, it is already defined and should work like the other factions?

### Steps to Reproduce

1. Set the military commander to use rhs_faction_tv
2. Set the civilian/military objective to use rhs_faction_tv 

**Expected behavior:** The faction should work like the msv faction, since it's defined.

**Actual behavior:** Recieve an error about groups not being defined for that faction.

**Comment by DarrellJMartin** [comment]
I would suggest you use the following compatibility addon: <https://steamcommunity.com/sharedfiles/filedetails/?id=2379400196> and set the placement modules to: rhs_faction_vdv.
