### ISSUE TITLE
Mod conflict between ALiVE CQB module and 3CB Factions loadout randomization script

### ISSUE THREAD

**Issue by Drift91** [ALiVEOS/ALiVE.OS#807]
### Prerequisites

* [ ] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3?
* [X] Have you attached an unbinarized SQM?
* [X] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [X] Have you attached screenshots of the Parameters set on the offending Module?

### Description

Hi, there seems to be a mod conflict between 3CB Factions and ALiVE's CQB module. From what I'm reading on the Workshop page for 3CB Factions, there's some kind of loadout randomization script, which I suspect is the cause. Basically the majority of the AI spawned by the CQB module from ALiVE will either be the wrong faction, usually one from 3CB Factions, or they'll be the correct unit (determined via `systemChat str typeOf _unit`) but have a loadout from a 3CB Factions unit.

Mission SQM:
[mission.zip](https://github.com/ALiVEOS/ALiVE.OS/files/12733507/mission.zip)
RPT file:
https://pastebin.com/kKmbwJaf
Module settings:
![20230926220157_1](https://github.com/ALiVEOS/ALiVE.OS/assets/2638764/70e56d6f-7f47-4a58-a008-c4006c932228)

### Steps to Reproduce

1. Load Arma with ALiVE, [3CB Factions](https://steamcommunity.com/sharedfiles/filedetails/?id=1673456286) and their prerequisites.
2. Run the mission above in hosted MP or Eden Editor MP.
3. Go into Zeus.
4. Check the map to see where the AI are, as the module's debug option is on.
5. Move the camera to the AI's locations and wait for them to unvirtualize.
6. If the AI are wearing the correct CSAT loadouts then check another location, as it's not 100% chance.

**Expected behavior:** For the AI to have the loadouts of the faction I've assigned in the CQB module.

**Actual behavior:** 3CB Factions' loadout randomization script is somehow applied to vanilla factions and factions from other mods, but it seems to only happen through the CQB module.

**Comment by DarrellJMartin** [comment]
I suspect this is more an issue with the RHS configs which 3CB Units addon requires. 
RHS don't conform to BI standards. ALiVE requires BI standards.
For example, If you are using RHS with ALiVE I did make a compatibility addon to standardize the RHS configs: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2379400196&searchtext=alive+rhs+comp
