### ISSUE TITLE
ALive menu key only accepts a single key to be pressed

### ISSUE THREAD

**Issue by STyx2909** [ALiVEOS/ALiVE.OS#808]
### Description
Took me time to figure out, my key combination to open ALive menu was not working because it was 2 keys.
Only pressing the second configured key is accepted to open the menu.
Using Custom Configuration keys does the same.

It is interesting to be able to fully handle this the way we want to play.
I am - when possible - using key combinations for special settings and menus (ZEUS: CTRL+Y - HighCommand: ALT+/(NUM)..)

**Comment by DarrellJMartin** [comment]
The ALiVE key can only be defined on one key not multiple.
