### ISSUE TITLE
ORBAT Creator: Initial Tests

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#81]
**Create Unit Dialogue**
~~Trivial: Unit Type list does not show until a Side is selected.~~
~~Minor: Add a Class filter after Side & Faction (Inf, Mech, Armor, Air, Static etc) - this list gets very long with some mods.~~
~~Minor: Consider adding a "Copy Unit" option~~
Minor: Consider adding a "Reset Unit to to Default" option

**Group Editor**
~~**Blocker**: unable to create new groups.  Select Faction, click New, enter details & confirm - no group created.~~
~~**Major**: Selecting a unit and attempting to "Add to Selected Group" when no Group is Selected will cause an error.~~
~~Trivial: Faction drop down should ideally default to the faction I am currently working on.~~
~~Minor: Consider adding a "Copy Group" option~~
Minor: Consider adding a "Reset Group to to Default" option when editing BIS/Addon groups.

**Other**
~~Major: Needs a capability to import an existing config and continue editing.~~
~~Trivial:  ALiVE Logo is slightly misaligned in Group & Unit Editors~~

------------------------------
Fix/New Feature list (relating to this ticket) - SpyderBlack723

- Groups can now be created and edited again
- "Add to Selected Group" button won't error if no group is selected
- Added better button enable/disable/show/hide handling to group editor
- Selected faction persists between all 3 tools
- Units can be imported from config
- Units can now be copied
- UI scaling fixed
- Groups can now be copied

**Comment by SpyderBlack723** [comment]
Awesome, thanks for the feedback :)

> Major: Needs a capability to import an existing config and continue editing.
Planned, needs to be carefully integrated to avoid too much data if user has a lot of mods activated

> Trivial: Faction drop down should ideally default to the faction I am currently working on.
Planning to implement a module-wide faction selection so that your selected faction persists between all 3 parts.

> Minor: Consider adding a "Copy Unit" option
This can be done by creating a new unit and selecting the unit you wish to "copy" (technically you are inheriting the old units). Are you wishing to copy a unit without inheriting? Or are you wanting a copy button so it is much quicker to create a new unit that inherits from the selected unit?

**Comment by friznit** [comment]
Hadn't considered inheritances but quick creation of multiple variations of a single unit is the desired outcome.

i.e. I want to create a single unit in detail and then clone it multiple times and tweak each copy slightly so that I can quickly create a squad with rifleman, machine gunner, AT guy etc...

**Comment by SpyderBlack723** [comment]
Understood, inheritance will definitely that cover that, but I think a copy button has it's place as well.

**Comment by SpyderBlack723** [comment]
Added running changelog to main post

**Comment by friznit** [comment]
New minor issue:  after closing the unit edit loadout, all the drop downs go blank and the screen is unresponsive.  Pressing escape recovers it back to normal.

**Comment by SpyderBlack723** [comment]
Above issue should now be fixed with f2131c5f26da72a095529406ca32e8fa54c1fa2d

**Comment by SpyderBlack723** [comment]
https://github.com/ALiVEOS/ALiVE.OS/issues/103
