### ISSUE TITLE
Quote: "FIX THIS SHIT: ALiVE_fnc_profile was called with 'debug' operation"

### ISSUE THREAD

**Issue by rmjeger80** [ALiVEOS/ALiVE.OS#810]
Hi, I am running a hosted server with Arma 3 including Alive-mod and several other mods together. The game seems to be running fine but I receive the following messages in the server logging. Is this a bug?

### Description

9:34:40 ALiVE 943.091 : 1492.27 - FIX THIS SHIT: ALiVE_fnc_profile was called with 'debug' operation from 'ALiVE_fnc_profile'
 9:34:40 ALiVE 943.091 : 1492.28 - class 'ALiVE_fnc_profile' does not support operation 'debug' - ["#CBA_HASH#",["debug","active","position","side","profileID","type","objectType","vehicleAssignments","vehiclesInCommandOf","vehiclesInCargoOf","leader","unitClasses","unitCount","group","companyID","groupID","waypoints","waypointsCompleted","positions","damages","ranks","units","speedPerSecond","despawnPosition","hasSimulated","isCycling","activeCommands","inactiveCommands","spawnType","faction","isPlayer","_rev","_id","busy","pendingWaypointPaths","isSPE","aiBehaviour","timeLastSim","locked","combat","entitiesInCommandOf","entitiesInCargoOf"],[false,false,[6135.01,19819.5,2.3438],"WEST","BLU_F-entity_330","entity","inf",["#CBA_HASH#",[],[],any],[],[],<NULL-object>,["B_Helipilot_F","B_Helipilot_F"],2,<NULL-object>,"","",[],[],[[6135.01,19819.5,2.3438],[6135.01,19819.5,2.3438]],[0,0],["CAPTAIN","CAPTAIN"],[],[27,55,83],[6135.01,19819.5,2.3438],true,false,[],[],[],"BLU_F",false,"","",true,[],false,"SAFE",1492.27,false,f
 

9:34:41 ALiVE 943.248 : 1492.43 - FIX THIS SHIT: ALiVE_fnc_profile was called with 'debug' operation from 'ALiVE_fnc_profile'
 9:34:41 ALiVE 943.248 : 1492.43 - class 'ALiVE_fnc_profile' does not support operation 'debug' - ["#CBA_HASH#",["debug","active","position","side","profileID","type","objectType","vehicleAssignments","entitiesInCommandOf","entitiesInCargoOf","vehicle","vehicleClass","direction","fuel","ammo","engineOn","damage","canMove","canFire","needReload","despawnPosition","hasSimulated","spawnType","faction","_rev","_id","busy","cargo","slingload","slung","isSPE","aiBehaviour","locked"],[false,false,[6135.01,19819.5,0.205658],"WEST","BLU_F-vehicle_105","vehicle","Helicopter",["#CBA_HASH#",[],[],any],[],[],<NULL-object>,"B_Heli_Transport_01_camo_F",54.7088,0.994106,[["2000Rnd_762x51_Belt_T_Red",2000,2000]],true,[["HitHull",0],["HitFuel",0],["HitAvionics",0],["HitMissiles",0],["HitEngine1",0],["HitEngine2",0],["HitEngine",0],["HitHRotor",0],["HitVRotor",0],["HitGlass1",0],["HitGlass2",0],["HitGlass3",0],["HitGlass4",0],["HitGlass5",0],["HitGlass6",0],["HitGlass7",0],["HitGlass8",0],["HitGlass9",0],["HitGlass10",0],["HitGlass11"

 9:34:41 ALiVE 943.516 : 1492.7 - FIX THIS SHIT: ALiVE_fnc_profile was called with 'debug' operation from 'ALiVE_fnc_profile'
 9:34:41 ALiVE 943.516 : 1492.7 - class 'ALiVE_fnc_profile' does not support operation 'debug' - ["#CBA_HASH#",["debug","active","position","side","profileID","type","objectType","vehicleAssignments","vehiclesInCommandOf","vehiclesInCargoOf","leader","unitClasses","unitCount","group","companyID","groupID","waypoints","waypointsCompleted","positions","damages","ranks","units","speedPerSecond","despawnPosition","hasSimulated","isCycling","activeCommands","inactiveCommands","spawnType","faction","isPlayer","_rev","_id","busy","pendingWaypointPaths","isSPE","aiBehaviour","timeLastSim","locked","combat","entitiesInCommandOf","entitiesInCargoOf"],[false,false,[6428.09,19708.1,2.95326],"WEST","BLU_F-entity_334","entity","inf",["#CBA_HASH#",[],[],any],[],[],<NULL-object>,["B_Helipilot_F","B_Helipilot_F"],2,<NULL-object>,"","",[],[],[[6428.09,19708.1,2.95326],[6428.09,19708.1,2.95326]],[0,0],["CAPTAIN","CAPTAIN"],[],[27,55,83],[6428.09,19708.1,2.95326],true,false,[],[],[],"BLU_F",false,"","",true,[],false,"SAFE",1492.32,fals

 9:34:41 ALiVE 943.609 : 1492.81 - FIX THIS SHIT: ALiVE_fnc_profile was called with 'debug' operation from 'ALiVE_fnc_profile'
 9:34:41 ALiVE 943.609 : 1492.81 - class 'ALiVE_fnc_profile' does not support operation 'debug' - ["#CBA_HASH#",["debug","active","position","side","profileID","type","objectType","vehicleAssignments","entitiesInCommandOf","entitiesInCargoOf","vehicle","vehicleClass","direction","fuel","ammo","engineOn","damage","canMove","canFire","needReload","despawnPosition","hasSimulated","spawnType","faction","_rev","_id","busy","cargo","slingload","slung","isSPE","aiBehaviour","locked"],[false,false,[6428.09,19708.1,0.814087],"WEST","BLU_F-vehicle_107","vehicle","Helicopter",["#CBA_HASH#",[],[],any],[],[],<NULL-object>,"B_Heli_Transport_01_F",56.9481,0.991038,[["2000Rnd_762x51_Belt_T_Red",2000,2000]],true,[["HitHull",0],["HitFuel",0],["HitAvionics",0],["HitMissiles",0],["HitEngine1",0],["HitEngine2",0],["HitEngine",0],["HitHRotor",0],["HitVRotor",0],["HitGlass1",0],["HitGlass2",0],["HitGlass3",0],["HitGlass4",0],["HitGlass5",0],["HitGlass6",0],["HitGlass7",0],["HitGlass8",0],["HitGlass9",0],["HitGlass10",0],["HitGlass11",0],[

**Comment by marceldev89** [comment]
Seems more like a logging thing to find out why the `class 'ALiVE_fnc_profile' does not support operation 'debug'` error log was happening. It's probably fine. It's been in there since 2021 😛

**Comment by DavisBrown723** [comment]
This is 100% a debug log that I added lol. You can ignore it, thanks for logging it.

**Comment by rmjeger80** [comment]
Ok thanks for your answers - closing the issue
