### ISSUE TITLE
Alive asymmetric - roadblocks

### ISSUE THREAD

**Issue by rmjeger80** [ALiVEOS/ALiVE.OS#811]
Just out of curiosity, when asymmetric opcom build roadblocks and with reference to issue #363 https://github.com/ALiVEOS/ALiVE.OS/issues/363

Is there still not any option to blow up the whole roadblock to clear the roads? The compositions that are an issue are the ones with car-wrecks lining up across the road. The only options I find is to disable them but for the sake of immersion shouldn't it be possible to kinda just blow them up? Or will disabling them remove it after some garbage cycle perhaps?

**Comment by DarrellJMartin** [comment]
ALiVE key -> Player Options -> Activate Logistics Actions

Player can then use the actions menu to carry objects and move them.
![move-roadblock](https://github.com/user-attachments/assets/3df29982-73b8-4878-956a-3b07dcdbf97c)
