### ISSUE TITLE
Unable to use War Room Sign Up Email Verification

### ISSUE THREAD

**Issue by BSherb** [ALiVEOS/ALiVE.OS#817]
Not part of ALiVE Mod specifically, unable to sign up for war room like the others. Email not sending.
spazz1219@(gmail).(com)

Obviously adding parentheses to temporarily hinder spam data mining......

This is the screen given (hopefully someone will figure something out based on this?)

|Whoops!
Server Error: 500 (Internal Server Error)
What does this mean?
Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our [home page](http://www.alivemod.com/)?

**Comment by marceldev89** [comment]
I think war room has been offline for a long while now so that's probably why it's not working. :)

**Comment by DarrellJMartin** [comment]
War Room has been decommissioned due to the cost of hosting.
