### ISSUE TITLE
Odd script errors related to profiles

### ISSUE THREAD

**Issue by marceldev89** [ALiVEOS/ALiVE.OS#86]
Over a couple of sessions I saw a few script errors popping up. They seem to be caused by a faulty profile but I'm not sure why.

With session 1 & 2 I didn't notice anything "breaking" but those sessions were quite short (editor preview). During session 3 the profiles didn't seem to update their location anymore with Virtual AI debugging enabled and in the Operations Tablet. I was able to order the profiles around in the Operations Tablet.
## Session 1

~addons/sys_profile/profileSpawner_v2_1.fsm:345~ - (False report, shouldn't happen)
~addons/sys_profile/profileSpawner_v2_1.fsm:649~ - (Fixed in ac4b5833cc70e53ab24eef6afa48cf8264e85d04)

```
20:47:30 Error in expression <then {
_profileType = _profile select 2 select 5;
_profileID = _profile select 2>

20:47:30   Error position: <select 5;
_profileID = _profile select 2>

20:47:30   Error Zero divisor
```

addons/sys_profile/fnc_profileEntity.sqf:1060

```
20:47:31 Error in expression <ashGet) exitwith {};

_unitCount = 0;


if(_active) then {


_despawnPrevented =>

20:47:31   Error position: <if(_active) then {


_despawnPrevented =>

20:47:31   Error if: Type Array, expected Bool
```
## Session 2

~addons/sys_profile/profileSpawner_v2_1.fsm:463~ - (Fixed in 3e0190452f8240ebef046d5e0e399277019b5b25)

```
23:02:18 Error in expression <le") then {
_active = _profile select 2 select 1;

if(_active) then {

_leader =>

23:02:18   Error position: <select 1;

if(_active) then {

_leader =>

23:02:18   Error Zero divisor
```
## Session 3

addons/sys_profile/fnc_profileSimulator.sqf:353

```
23:52:53 Error in expression <n {



_group = _entityProfile select 2 select 13; 




if((!isNull _group) && {>

23:52:53   Error position: <select 13; 




if((!isNull _group) && {>

23:52:53   Error Zero divisor
```

**Comment by SpyderBlack723** [comment]
:(

**Comment by marceldev89** [comment]
Updated issue to reflect above fix. :smile:

**Comment by SpyderBlack723** [comment]
Have fixed one case where profiles have stopped moving. Seems to be another, am working on fixing that as well.

**Comment by SpyderBlack723** [comment]
Any issues with freezing of the profile simulator should now be resolved.

**Comment by friznit** [comment]
@SpyderBlack723 Can this be closed?
