### ISSUE TITLE
Combat support script errors

### ISSUE THREAD

**Issue by Whigital** [ALiVEOS/ALiVE.OS#89]
Possible variable name missmatch causing errors and in turn affecting other calls.

_keepWeapon initialized but _weapon used in code:

https://github.com/ALiVEOS/ALiVE.OS/blob/master/addons/sup_combatsupport/scripts/NEO_radio/functions/misc/fn_disableOtherWeapons.sqf#L7

Excerpt from server log: [ALiVE Combat Support error](http://pastebin.com/kZsT0rKi)

**Comment by SpyderBlack723** [comment]
5da564ffb241b2f52296fff5fbbf578f2df8d3f8
