### ISSUE TITLE
fnc_getCompositions.sqf error

### ISSUE THREAD

**Issue by Opendome** [ALiVEOS/ALiVE.OS#90]
Hello everyone!

I tried to load up a mission with the ALiVE github version (https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.2.0.1608121) and the mission would fail to load properly (would get stuck at the end of the mission loading). In my rpt I noticed it would spam

if (isClass _item && ("any" in _cat || ({tolower(configName _item) find>
17:56:26 Error position: <_cat || ({tolower(configName _item) find>
17:56:26 Error Undefined variable in expression: _cat
17:56:26 File x\alive\addons\x_lib\functions\composition\fnc_getCompositions.sqf, line 134
17:56:26 Error in expression <ct _i;

**Comment by tupolov** [comment]
Hey @Opendome I've added a debug entry for the function. Can you pull from dev, rerun your mission and send me the RPT?

Thanks!

**Comment by tupolov** [comment]
Expired
