### ISSUE TITLE
Version isn't easy to find in log

### ISSUE THREAD

**Issue by dixon13** [ALiVEOS/ALiVE.OS#91]
So today I was looking at someone's log and noticed I couldn't find what version he was running in the log. Maybe the version should be displayed at global init in the RPT no matter what log level.

Also, maybe we should log what log level is implemented for each module? That might be too much but would be nice to know all the details when troubleshooting and going through logs.

**Comment by marceldev89** [comment]
I have this line in my RPTs: `[4981,86.908,0,"CBA_VERSIONING: alive_main=1.0.5.1605051, cba=3.0.0.160713, "]`. The version is off but that's probably related to that it's a dev build.

**Comment by dixon13** [comment]
Also, when building a dev build maybe there should be something there that builds and redefines the VERSION every time it's built.

**Comment by dixon13** [comment]
Ahhh ok found it @marceldev89. I feel like it should be more blunt and there to see when you get the big "ALiVE" splash in the rpt.
