### ISSUE TITLE
Alive Menu Server Exit script error

### ISSUE THREAD

**Issue by rebelvg** [ALiVEOS/ALiVE.OS#92]
When you're pressing alive menu server save and exit or just server exit there's a script error notifying of an undefined variable.
http://imgur.com/a/mja2J

**Comment by SpyderBlack723** [comment]
I'm guessing no ALiVE modules were placed in the mission?

**Comment by rebelvg** [comment]
ALiVE_require, ALiVE_SYS_LOGISTICSDISABLE, ALiVE_SYS_playeroptions were placed.

**Comment by SpyderBlack723** [comment]
Data module needs to be placed, will disable buttons if that is the case.

**Comment by rebelvg** [comment]
Okay, got it.

**Comment by SpyderBlack723** [comment]
037c74e79086684ce897cc48e47c8849e9a87687

**Comment by rebelvg** [comment]
Also, I just tried to add data module and still both server exit produced errors undefined variable.
