### ISSUE TITLE
Add option to disable roadblocks from being placed by asymmetric forces

### ISSUE THREAD

**Issue by VellD16** [ALiVEOS/ALiVE.OS#93]
Hi there I've noticed that when I set the OPCOM to Asymmetric and disable roadblocks I still carry on having roadblocks spawn. Is there a way you could fix this please? 

Thanks,

Dan

**Comment by SpyderBlack723** [comment]
Roadblocks are apart of asymmetric directly. Disabling them from the civilian placement module will only prevent them from being placed at mission start.
