### ISSUE TITLE
Players Pull Out Binoculars When Saving Player Data -  Persitence

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#94]
When player data is set to save to the database (ammo, player position, etc), players pull out their binoculars while saving. If manual save is enabled for players, this happens each time they save their own data.

While this is not a game breaking issue, it is still a strange bug.

**Comment by HeroesandvillainsOS** [comment]
Not seeing this here. Can you repro with ALiVE and CBA only?

**Comment by Vegas** [comment]
Turns out this is a weird issue when combined with ACE3. If you holster your weapon throw ACE3 (0 key), it will make you pull out your binoculars every time you save.... interesting.

**Comment by friznit** [comment]
This is ACE related and not something we can workaround with ALiVE.  ArmA always puts something in hand when you spawn a unit.  Since it can't find a weapon in this instance (ACE has effectively hidden it), it goes for the next thing it can find.
