### ISSUE TITLE
Advanced Markers Do Not Show For JIP Players -  Persitence

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#95]
This is an issue that has been around for a long while. Advanced markers do not show for all players when they JIP to sessions. In most cases, they only show for the first player who joins, or the one who starts the mission.

Perhaps adding a "refresh" to populate the map either as a manual "player option" for them to hit, or perhaps automatically on a time interval to ensure everyone is seeing the same thing.

**Comment by HeroesandvillainsOS** [comment]
This happens to us as well. Sometimes they show, other times they don't. Sometimes logging off and back in works, others times it doesn't.

**Comment by Vegas** [comment]
There has to be a better solution to persisting markers. As I said, maybe adding an auto refresh for JIP players, or some way to manually refresh to keep everyone on the same page.

**Comment by SpyderBlack723** [comment]
From AUTigerGrad

> I'm logged in as the server admin.
> 
> When I first do a server save and exit, then refresh the server and reload the mission...the markers appear and I can see everything.
> 
> However, when I player exit from my session..then return later and load in...the markers are no longer visible. Sometimes...if I player exit out and come back in..they will appear but it is not consistent. The only times I can see the markers is after loading the mission from a server save and exit.

**Comment by friznit** [comment]
Fixed in dev
