### ISSUE TITLE
ALT+Tabbed Players Break Persistence Save Functions

### ISSUE THREAD

**Issue by Vegas** [ALiVEOS/ALiVE.OS#96]
If players in the server are alt+tabbed when the admin hits Server Save and Exit, no data is retained at all and existing saves are corrupted and wiped.

This is a major issue for the persistence functions.

**Comment by SpyderBlack723** [comment]
Is this even something that's fixable?

**Comment by marceldev89** [comment]
Depends on whether the clients runs some code on "Server Save and Exit". Depending on the required data, it could be possible to do the entire save server side.

**Comment by tupolov** [comment]
In the early days we tried just server side persistence, unfortunately to make it reliable we had to run some code on exit on the client. 

Will look at this.

**Comment by friznit** [comment]
Cannot repro.  Have done a thorough test and data seems fine.  If it appears to be a problem, suggest you remove all players before save and exit.
